-- Insert SQL Rules Here 

UPDATE Units
SET ObsoleteTech = 'TECH_COMPASS'
WHERE Class = 'UNITCLASS_SETTLER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='SETTLER_COMMUNITY' AND Value= 1);

UPDATE Units
SET FoundMid = 'true'
WHERE Type = 'UNIT_SPANISH_CONQUISTADOR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='SETTLER_COMMUNITY' AND Value= 1);