----------------------------------------------------------
-- Unique Ability: Manifest Destiny
----------------------------------------------------------
UPDATE Traits
SET
	PlotBuyCostModifier = -25,
	BuyOwnedTiles = 1
WHERE Type = 'TRAIT_RIVER_EXPANSION';

INSERT INTO Trait_YieldFromTilePurchase
	(TraitType, YieldType, Yield)
VALUES
	('TRAIT_RIVER_EXPANSION', 'YIELD_PRODUCTION', 20);

----------------------------------------------------------
-- Unique Unit: Minuteman (Musketman)
----------------------------------------------------------
UPDATE Units
SET
	ObsoleteTech = (
		SELECT ObsoleteTech FROM Units WHERE Type = (
			SELECT DefaultUnit FROM UnitClasses WHERE Type = (
				SELECT UnitClassType FROM Unit_ClassUpgrades WHERE UnitType = 'UNIT_MUSKETMAN'
			)
		)
	),
	Combat = (SELECT Combat FROM Units WHERE Type = 'UNIT_MUSKETMAN') + 1,
	RangedCombat = (SELECT RangedCombat FROM Units WHERE Type = 'UNIT_MUSKETMAN') + 1
WHERE Type = 'UNIT_AMERICAN_MINUTEMAN';

INSERT INTO Unit_FreePromotions
	(UnitType, PromotionType)
VALUES
	('UNIT_AMERICAN_MINUTEMAN', 'PROMOTION_BARRAGE_1'),
	('UNIT_AMERICAN_MINUTEMAN', 'PROMOTION_IGNORE_TERRAIN_COST'),
	('UNIT_AMERICAN_MINUTEMAN', 'PROMOTION_GOLDEN_AGE_POINTS');

INSERT INTO Unit_AITypes
	(UnitType, UnitAIType)
VALUES
	('UNIT_AMERICAN_MINUTEMAN', 'UNITAI_EXPLORE');

----------------------------------------------------------
-- Unique Building: Independence Hall (Royal Collection)
----------------------------------------------------------
INSERT INTO Civilization_BuildingClassOverrides
	(CivilizationType, BuildingClassType, BuildingType)
VALUES
	('CIVILIZATION_AMERICA', 'BUILDINGCLASS_HERMITAGE', 'BUILDING_AMERICA_INDEPENDENCEHALL');

UPDATE Buildings
SET
	PolicyCostModifier = -5,
	GreatWorkCount = 2
WHERE Type = 'BUILDING_AMERICA_INDEPENDENCEHALL';

INSERT INTO Building_ThemingBonuses
	(BuildingType, Description, RequiresOwner, MustBeArt)
VALUES
	('BUILDING_AMERICA_INDEPENDENCEHALL', 'TXT_KEY_THEMING_BONUS_INDEPENDENCEHALL', 1, 1);

----------------------------------------------------------
-- Extra Buildings:
-- The Smithsonian
-- West Point
-- Slater Mill
----------------------------------------------------------
INSERT INTO Building_ClassNeededAnywhere
	(BuildingType, BuildingClassType)
VALUES
	('BUILDING_AMERICA_SMITHSONIAN', 'BUILDINGCLASS_HERMITAGE'),
	('BUILDING_AMERICA_WESTPOINT', 'BUILDINGCLASS_HERMITAGE'),
	('BUILDING_AMERICA_SLATERMILL', 'BUILDINGCLASS_HERMITAGE');

INSERT INTO Building_ClassNeededNowhere
	(BuildingType, BuildingClassType)
VALUES
	('BUILDING_AMERICA_SMITHSONIAN', 'BUILDINGCLASS_AMERICA_WESTPOINT'),
	('BUILDING_AMERICA_SMITHSONIAN', 'BUILDINGCLASS_AMERICA_SLATERMILL'),
	('BUILDING_AMERICA_WESTPOINT', 'BUILDINGCLASS_AMERICA_SMITHSONIAN'),
	('BUILDING_AMERICA_WESTPOINT', 'BUILDINGCLASS_AMERICA_SLATERMILL'),
	('BUILDING_AMERICA_SLATERMILL', 'BUILDINGCLASS_AMERICA_SMITHSONIAN'),
	('BUILDING_AMERICA_SLATERMILL', 'BUILDINGCLASS_AMERICA_WESTPOINT');

INSERT INTO Building_YieldChanges
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_AMERICA_SMITHSONIAN', 'YIELD_SCIENCE', 2),
	('BUILDING_AMERICA_SMITHSONIAN', 'YIELD_CULTURE', 2),
	('BUILDING_AMERICA_WESTPOINT', 'YIELD_PRODUCTION', 2),
	('BUILDING_AMERICA_WESTPOINT', 'YIELD_SCIENCE', 2),
	('BUILDING_AMERICA_WESTPOINT', 'YIELD_GREAT_GENERAL_POINTS', 5),
	('BUILDING_AMERICA_SLATERMILL', 'YIELD_PRODUCTION', 2),
	('BUILDING_AMERICA_SLATERMILL', 'YIELD_GOLD', 2);

INSERT INTO Building_BuildingClassYieldChanges
	(BuildingType, BuildingClassType, YieldType, YieldChange)
VALUES
	('BUILDING_AMERICA_SMITHSONIAN', 'BUILDINGCLASS_MUSEUM', 'YIELD_SCIENCE', 5),
	('BUILDING_AMERICA_SMITHSONIAN', 'BUILDINGCLASS_MUSEUM', 'YIELD_CULTURE', 5),
	('BUILDING_AMERICA_SMITHSONIAN', 'BUILDINGCLASS_LABORATORY', 'YIELD_SCIENCE', 5),
	('BUILDING_AMERICA_SMITHSONIAN', 'BUILDINGCLASS_LABORATORY', 'YIELD_CULTURE', 5),
	('BUILDING_AMERICA_WESTPOINT', 'BUILDINGCLASS_MILITARY_ACADEMY', 'YIELD_PRODUCTION', 5),
	('BUILDING_AMERICA_WESTPOINT', 'BUILDINGCLASS_MILITARY_ACADEMY', 'YIELD_SCIENCE', 5),
	('BUILDING_AMERICA_WESTPOINT', 'BUILDINGCLASS_ARSENAL', 'YIELD_PRODUCTION', 5),
	('BUILDING_AMERICA_WESTPOINT', 'BUILDINGCLASS_ARSENAL', 'YIELD_SCIENCE', 5),
	('BUILDING_AMERICA_SLATERMILL', 'BUILDINGCLASS_FACTORY', 'YIELD_PRODUCTION', 5),
	('BUILDING_AMERICA_SLATERMILL', 'BUILDINGCLASS_FACTORY', 'YIELD_GOLD', 5),
	('BUILDING_AMERICA_SLATERMILL', 'BUILDINGCLASS_STOCK_EXCHANGE', 'YIELD_PRODUCTION', 5),
	('BUILDING_AMERICA_SLATERMILL', 'BUILDINGCLASS_STOCK_EXCHANGE', 'YIELD_GOLD', 5);

INSERT INTO Building_YieldChangeWorldWonderGlobal
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_AMERICA_SMITHSONIAN', 'YIELD_SCIENCE', 2),
	('BUILDING_AMERICA_SMITHSONIAN', 'YIELD_CULTURE', 2),
	('BUILDING_AMERICA_WESTPOINT', 'YIELD_PRODUCTION', 2),
	('BUILDING_AMERICA_WESTPOINT', 'YIELD_SCIENCE', 2),
	('BUILDING_AMERICA_SLATERMILL', 'YIELD_PRODUCTION', 2),
	('BUILDING_AMERICA_SLATERMILL', 'YIELD_GOLD', 2);

INSERT INTO Building_YieldFromYieldPercentGlobal
	(BuildingType, YieldIn, YieldOut, Value)
VALUES
	('BUILDING_AMERICA_SMITHSONIAN', 'YIELD_GOLD', 'YIELD_CULTURE', 10),
	('BUILDING_AMERICA_WESTPOINT', 'YIELD_GOLD', 'YIELD_SCIENCE', 10),
	('BUILDING_AMERICA_SLATERMILL', 'YIELD_GOLD', 'YIELD_PRODUCTION', 10);

INSERT INTO Building_ImprovementYieldChangesGlobal
	(BuildingType, ImprovementType, YieldType, Yield)
VALUES
	('BUILDING_AMERICA_SMITHSONIAN', 'IMPROVEMENT_LANDMARK', 'YIELD_SCIENCE', 5);

INSERT INTO Building_GreatWorkYieldChanges
	(BuildingType, YieldType, Yield)
VALUES
	('BUILDING_AMERICA_SMITHSONIAN', 'YIELD_SCIENCE', 1);
