INSERT INTO Policy_FaithPurchaseUnitClasses
	(PolicyType, UnitClassType)
VALUES
	('POLICY_TRADITION_FINISHER', 'UNITCLASS_ENGINEER'),
	('POLICY_HONOR_FINISHER', 'UNITCLASS_GREAT_GENERAL'),
	('POLICY_AESTHETICS_FINISHER', 'UNITCLASS_WRITER'),
	('POLICY_AESTHETICS_FINISHER', 'UNITCLASS_ARTIST'),
	('POLICY_AESTHETICS_FINISHER', 'UNITCLASS_MUSICIAN'),
	('POLICY_COMMERCE_FINISHER', 'UNITCLASS_MERCHANT'),
	('POLICY_EXPLORATION_FINISHER', 'UNITCLASS_GREAT_ADMIRAL'),
	('POLICY_RATIONALISM_FINISHER', 'UNITCLASS_SCIENTIST');

-- This is now a modifier (stackable) instead of a multiplier
UPDATE Policies SET StrategicResourceMod = StrategicResourceMod - 100 WHERE StrategicResourceMod <> 0;

UPDATE Policies
SET IsFinisher = 1
WHERE Type IN (
	'POLICY_TRADITION_FINISHER',
	'POLICY_LIBERTY_FINISHER',
	'POLICY_HONOR_FINISHER',
	'POLICY_PIETY_FINISHER',
	'POLICY_PATRONAGE_FINISHER',
	'POLICY_COMMERCE_FINISHER',
	'POLICY_RATIONALISM_FINISHER',
	'POLICY_AESTHETICS_FINISHER',
	'POLICY_EXPLORATION_FINISHER'
);

-- Policy Branch Tables
INSERT INTO PolicyBranch_Victories
	(PolicyBranchType, VictoryType)
VALUES
	('POLICY_BRANCH_FREEDOM', 'VICTORY_SPACE_RACE'),
	('POLICY_BRANCH_FREEDOM', 'VICTORY_DIPLOMATIC'),
	('POLICY_BRANCH_FREEDOM', 'VICTORY_CULTURAL'),
	('POLICY_BRANCH_ORDER', 'VICTORY_SPACE_RACE'),
	('POLICY_BRANCH_ORDER', 'VICTORY_DOMINATION'),
	('POLICY_BRANCH_ORDER', 'VICTORY_CULTURAL'),
	('POLICY_BRANCH_AUTOCRACY', 'VICTORY_DIPLOMATIC'),
	('POLICY_BRANCH_AUTOCRACY', 'VICTORY_DOMINATION'),
	('POLICY_BRANCH_AUTOCRACY', 'VICTORY_CULTURAL');
