UPDATE GoodyHuts
SET Experience = '10'
WHERE Type = 'GOODY_EXPERIENCE';

UPDATE GoodyHuts
SET Culture = '15'
WHERE Type = 'GOODY_CULTURE';

UPDATE GoodyHuts
SET MapOffset = '10'
WHERE Type = 'GOODY_MAP';

UPDATE GoodyHuts
SET MapProb = '110'
WHERE Type = 'GOODY_MAP';

-- Goody Hut Payout
UPDATE GoodyHuts
SET GoldRandAmount = '20'
WHERE Type = 'GOODY_GOLD';

UPDATE GoodyHuts
SET GoldRandAmount = '20'
WHERE Type = 'GOODY_LOW_GOLD';

UPDATE GoodyHuts
SET GoldRandAmount = '20'
WHERE Type = 'GOODY_HIGH_GOLD';

UPDATE GoodyHuts
SET Experience = '20'
WHERE Type = 'GOODY_EXPERIENCE';

INSERT INTO Concepts
	(Type, Topic, Description, Summary, AdvisorQuestion, Advisor, CivilopediaHeaderType, InsertBefore, InsertAfter)
VALUES
	('CONCEPT_ANCIENT_RUINS_BENEFITS_GOLDEN_AGE', 'TXT_KEY_TOPIC_BARBARIAN', 'TXT_KEY_BARBARIAN_GOLDEN_AGE_HEADING4_TITLE', 'TXT_KEY_BARBARIAN_GOLDEN_AGE_HEADING4_BODY', 'TXT_KEY_BARBARIAN_GOLDEN_AGE_ADV_QUEST', 'FOREIGN', 'HEADER_RUBARB','CONCEPT_ANCIENT_RUINS_BENEFITS_PRODUCTION','CONCEPT_ANCIENT_RUINS_BENEFITS_SETTLERS_AND_WORKERS'),
	('CONCEPT_ANCIENT_RUINS_BENEFITS_PRODUCTION', 'TXT_KEY_TOPIC_BARBARIAN', 'TXT_KEY_BARBARIAN_PRODUCTION_HEADING4_TITLE', 'TXT_KEY_BARBARIAN_PRODUCTION_HEADING4_BODY', 'TXT_KEY_BARBARIAN_PRODUCTION_ADV_QUEST', 'FOREIGN', 'HEADER_RUBARB','CONCEPT_ANCIENT_RUINS_BENEFITS_TILES','CONCEPT_ANCIENT_RUINS_BENEFITS_GOLDEN_AGE'),
	('CONCEPT_ANCIENT_RUINS_BENEFITS_TILES', 'TXT_KEY_TOPIC_BARBARIAN', 'TXT_KEY_BARBARIAN_TILES_HEADING4_TITLE', 'TXT_KEY_BARBARIAN_TILES_HEADING4_BODY', 'TXT_KEY_BARBARIAN_TILES_ADV_QUEST', 'FOREIGN', 'HEADER_RUBARB','CONCEPT_BARBARIANS','CONCEPT_ANCIENT_RUINS_BENEFITS_PRODUCTION');