@echo off
SETLOCAL

REM --- I have no idea why this does not work ---
REM set STATUS=Clean
REM for /f "usebackq delims=" %%i in (`git status --untracked-files=no --porcelain`) do (
REM	echo Uncommitted change: %%i
REM	if [%%i] NEQ [] set STATUS=Dirty
REM )

REM --- so this is the alternative ---
set STATUS=Unknown
 
for /f "usebackq delims=" %%i in (`git describe`) do set VAR=%%i

echo const char CURRENT_GAMECORE_VERSION[] = "%VAR% %STATUS%"; //autogenerated, do not commit this file! > %~dp0%commit_id.inc
echo Version identifier will be "%VAR% %STATUS%"

ENDLOCAL