INSERT INTO Technologies
	(Type, Cost, Description, Civilopedia, Help, Era, Trade, GridX, GridY, Quote, PortraitIndex, IconAtlas)
VALUES
	('TECH_CORPORATIONS', 4100, 'TXT_KEY_TECH_CORPORATIONS_TITLE', 'TXT_KEY_TECH_CORPORATIONS_DESC', 'TXT_KEY_TECH_CORPORATIONS_HELP', 'ERA_MODERN', 1, 12, 8, 'TXT_KEY_TECH_CORPORATIONS_QUOTE', 0, 'CORP_ATLAS');

INSERT INTO Technology_PrereqTechs
	(PrereqTech, TechType)
VALUES
	('TECH_CORPORATIONS', 'TECH_COMBINED_ARMS'),
	('TECH_RAILROAD', 'TECH_CORPORATIONS');

INSERT INTO Technology_Flavors
	(TechType, FlavorType, Flavor)
VALUES
	('TECH_CORPORATIONS', 'FLAVOR_GOLD', 30),
	('TECH_CORPORATIONS', 'FLAVOR_GROWTH', 30),
	('TECH_CORPORATIONS', 'FLAVOR_PRODUCTION', 30),
	('TECH_CORPORATIONS', 'FLAVOR_SCIENCE', 30),
	('TECH_CORPORATIONS', 'FLAVOR_CULTURE', 30);