-- Great Musicians come from Aesthetics (and only Great Musicians)
DELETE FROM Policy_FaithPurchaseUnitClasses 
WHERE PolicyType = 'POLICY_AESTHETICS_FINISHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

INSERT INTO Policy_FaithPurchaseUnitClasses (PolicyType, UnitClassType)
SELECT 'POLICY_AESTHETICS_FINISHER' , 'UNITCLASS_MUSICIAN'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

-- Unlock Time
UPDATE PolicyBranchTypes
SET EraPrereq = 'ERA_MEDIEVAL'
WHERE Type = 'POLICY_BRANCH_AESTHETICS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

-- Opener
UPDATE Policies
SET GreatWriterRateModifier = '0'
WHERE Type = 'POLICY_AESTHETICS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET GreatArtistRateModifier = '0'
WHERE Type = 'POLICY_AESTHETICS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET GreatMusicianRateModifier = '0'
WHERE Type = 'POLICY_AESTHETICS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET GreatPeopleRateModifier = '25'
WHERE Type = 'POLICY_AESTHETICS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

INSERT INTO Policy_BuildingClassProductionModifiers
	(PolicyType, BuildingClassType, ProductionModifier)
VALUES
	('POLICY_AESTHETICS', 'BUILDINGCLASS_WRITERS_GUILD', 100),
	('POLICY_AESTHETICS', 'BUILDINGCLASS_MUSICIANS_GUILD', 100),
	('POLICY_AESTHETICS', 'BUILDINGCLASS_ARTISTS_GUILD', 100);

-- Cultural Centers (now Humanities)

DELETE FROM Policy_BuildingClassProductionModifiers
WHERE PolicyType = 'POLICY_CULTURAL_CENTERS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

-- GW Changes
INSERT INTO Policy_MusicYieldChanges
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_CULTURAL_CENTERS', 'YIELD_GOLD', 4);

INSERT INTO Policy_LitYieldChanges
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_CULTURAL_CENTERS', 'YIELD_GOLDEN_AGE_POINTS', 3);

INSERT INTO Policy_ArtYieldChanges
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_CULTURAL_CENTERS', 'YIELD_CULTURE', 2);

INSERT INTO Policy_ArtifactYieldChanges
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_CULTURAL_CENTERS', 'YIELD_SCIENCE', 2);

-- Fine Arts

UPDATE Policies
SET HappinessPerXGreatWorks = '3'
WHERE Type = 'POLICY_FINE_ARTS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

INSERT INTO Policy_BuildingClassHappiness
	(PolicyType, BuildingClassType, Happiness)
VALUES
	('POLICY_FINE_ARTS', 'BUILDINGCLASS_WRITERS_GUILD', 1),
	('POLICY_FINE_ARTS', 'BUILDINGCLASS_ARTISTS_GUILD', 1),
	('POLICY_FINE_ARTS', 'BUILDINGCLASS_MUSICIANS_GUILD', 1);

-- Flourishing of the Arts

UPDATE Policies
SET CultureWonderMultiplier = '0'
WHERE Type = 'POLICY_FLOURISHING_OF_ARTS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET GoldenAgeTurns = '0'
WHERE Type = 'POLICY_FLOURISHING_OF_ARTS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET CulturePerWonder = '0'
WHERE Type = 'POLICY_FLOURISHING_OF_ARTS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

INSERT INTO Policy_YieldFromWonderConstruction
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_FLOURISHING_OF_ARTS', 'YIELD_GOLDEN_AGE_POINTS', 100);

INSERT INTO Policy_BuildingClassYieldChanges
	(PolicyType, BuildingClassType, YieldType, YieldChange)
VALUES
	('POLICY_FLOURISHING_OF_ARTS', 'BUILDINGCLASS_UNIVERSITY', 'YIELD_TOURISM', 4),
	('POLICY_FLOURISHING_OF_ARTS', 'BUILDINGCLASS_UNIVERSITY', 'YIELD_GOLDEN_AGE_POINTS', 4);

-- Artistic Genius

UPDATE Policies
SET NumFreeGreatPeople = '1'
WHERE Type = 'POLICY_ARTISTIC_GENIUS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

DELETE FROM Policy_FreeUnitClasses
WHERE PolicyType = 'POLICY_ARTISTIC_GENIUS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

INSERT INTO Policy_YieldGPExpend
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_ARTISTIC_GENIUS', 'YIELD_GOLD', 50);

-- Cultural Exchange

UPDATE Policies
SET SharedReligionTourismModifier = '0'
WHERE Type = 'POLICY_ETHICS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET TradeRouteTourismModifier = '0'
WHERE Type = 'POLICY_ETHICS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET OpenBordersTourismModifier = '10'
WHERE Type = 'POLICY_ETHICS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

-- Building Class Changes
INSERT INTO Policy_BuildingClassYieldChanges
	(PolicyType, BuildingClassType, YieldType, YieldChange)
VALUES
	('POLICY_ETHICS', 'BUILDINGCLASS_AMPHITHEATER', 'YIELD_CULTURE', 2),
	('POLICY_ETHICS', 'BUILDINGCLASS_AMPHITHEATER', 'YIELD_PRODUCTION', 2),
	('POLICY_ETHICS', 'BUILDINGCLASS_OPERA_HOUSE', 'YIELD_CULTURE', 2),
	('POLICY_ETHICS', 'BUILDINGCLASS_OPERA_HOUSE', 'YIELD_PRODUCTION', 2);


INSERT INTO Policy_GoldenAgeYieldMod
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_ETHICS', 'YIELD_CULTURE', 10);

---UPDATE Policies
--SET UnlocksPolicyBranchEra = 'ERA_RENAISSANCE'
--WHERE Type = 'POLICY_AESTHETICS_FINISHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

--UPDATE Policies
--SET IdeologyPoint = '1'
--WHERE Type = 'POLICY_AESTHETICS_FINISHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

-- Finisher

-- Reveals Hidden Sites.

INSERT INTO Policy_ImprovementYieldChanges
	(PolicyType, ImprovementType, YieldType, Yield)
VALUES
	('POLICY_AESTHETICS_FINISHER', 'IMPROVEMENT_LANDMARK', 'YIELD_GOLDEN_AGE_POINTS', 3),
	('POLICY_AESTHETICS_FINISHER', 'IMPROVEMENT_LANDMARK', 'YIELD_SCIENCE', 3);

UPDATE Resources
SET PolicyReveal = 'POLICY_AESTHETICS_FINISHER'
WHERE Type = 'RESOURCE_HIDDEN_ARTIFACTS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET ArchaeologicalDigTourism = '3'
WHERE Type = 'POLICY_AESTHETICS_FINISHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET GoldenAgeTourism = '4'
WHERE Type = 'POLICY_AESTHETICS_FINISHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET ThemingBonusMultiplier = '0'
WHERE Type = 'POLICY_AESTHETICS_FINISHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

INSERT INTO Policy_CityYieldChanges
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_ETHICS', 'YIELD_SCIENCE', 1),
	('POLICY_ETHICS', 'YIELD_GOLDEN_AGE_POINTS', 2),
	('POLICY_ARTISTIC_GENIUS', 'YIELD_SCIENCE', 1),
	('POLICY_ARTISTIC_GENIUS', 'YIELD_GOLDEN_AGE_POINTS', 2),
	('POLICY_FLOURISHING_OF_ARTS', 'YIELD_SCIENCE', 1),
	('POLICY_FLOURISHING_OF_ARTS', 'YIELD_GOLDEN_AGE_POINTS', 2),
	('POLICY_FINE_ARTS', 'YIELD_SCIENCE', 1),
	('POLICY_FINE_ARTS', 'YIELD_GOLDEN_AGE_POINTS', 2),
	('POLICY_CULTURAL_CENTERS', 'YIELD_SCIENCE', 1),
	('POLICY_CULTURAL_CENTERS', 'YIELD_GOLDEN_AGE_POINTS', 2);

INSERT INTO Policy_SpecialistExtraYields
	(PolicyType, YieldType, Yield)
VALUES
	('POLICY_CULTURAL_CENTERS', 'YIELD_CULTURE', 1);