DELETE FROM AICityStrategies
WHERE Type = 'AICITYSTRATEGY_NO_NEED_INTERNATIONAL_LAND_TRADE_ROUTE';

DELETE FROM AICityStrategies
WHERE Type = 'AICITYSTRATEGY_NO_NEED_INTERNATIONAL_SEA_TRADE_ROUTE';

DELETE FROM AICityStrategy_Flavors
WHERE AICityStrategyType = 'AICITYSTRATEGY_NO_NEED_INTERNATIONAL_LAND_TRADE_ROUTE';

DELETE FROM AICityStrategy_Flavors
WHERE AICityStrategyType = 'AICITYSTRATEGY_NO_NEED_INTERNATIONAL_SEA_TRADE_ROUTE';

UPDATE AICityStrategy_Flavors
SET Flavor = '100' WHERE AICityStrategyType = 'AICITYSTRATEGY_NEED_INTERNATIONAL_LAND_TRADE_ROUTE';

UPDATE AICityStrategy_Flavors
SET Flavor = '100' WHERE AICityStrategyType = 'AICITYSTRATEGY_NEED_INTERNATIONAL_SEA_TRADE_ROUTE';