INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
VALUES
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_AMBER'),
	('CORPORATION_FIRAXITE_MATERIALS', 'RESOURCE_JADE'),
	('CORPORATION_GIORGIO_ARMEIER', 'RESOURCE_LAPIS'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_PERFUME'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_GLASS'),
	('CORPORATION_LANDSEA_EXTRACTORS', 'RESOURCE_CORAL'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_TOBACCO'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_OLIVE'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_COFFEE'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_TEA');

INSERT INTO Corporation_ResourceYieldChanges
	(CorporationType, ResourceType, YieldType, Yield)
VALUES
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_AMBER', 'YIELD_GOLDEN_AGE_POINTS', 1),
	('CORPORATION_FIRAXITE_MATERIALS', 'RESOURCE_JADE', 'YIELD_SCIENCE', 1),
	('CORPORATION_GIORGIO_ARMEIER', 'RESOURCE_LAPIS', 'YIELD_CULTURE', 1),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_PERFUME', 'YIELD_PRODUCTION', 1),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_GLASS', 'YIELD_PRODUCTION', 1),
	('CORPORATION_LANDSEA_EXTRACTORS', 'RESOURCE_CORAL', 'YIELD_PRODUCTION', 1),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_TOBACCO', 'YIELD_GOLD', 1),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_OLIVE', 'YIELD_FOOD', 1),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_COFFEE', 'YIELD_FOOD', 1),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_TEA', 'YIELD_FOOD', 1);

INSERT INTO Corporation_SpecialistYieldChanges
	(CorporationType, SpecialistType, YieldType, Yield)
VALUES
	('CORPORATION_GIORGIO_ARMEIER', 'SPECIALIST_CIVIL_SERVANT', 'YIELD_CULTURE', 1);