-- Reduce Gandhi's nuke flavors if the Nuclear Gandhi setting is disabled
UPDATE Leader_Flavors
SET Flavor = 4
WHERE LeaderType = 'LEADER_GANDHI'
AND FlavorType IN ('FLAVOR_NUKE', 'FLAVOR_USE_NUKE')
AND EXISTS (SELECT 1 FROM CustomModOptions WHERE Name = 'DIPLOAI_ENABLE_NUCLEAR_GANDHI' AND Value = 0);

-- Replace leader flavors for Barbarians - many of them are zeroed out
INSERT INTO Leader_Flavors
	(LeaderType, FlavorType, Flavor)
VALUES
	('LEADER_BARBARIAN', 'FLAVOR_OFFENSE', 4),
	('LEADER_BARBARIAN', 'FLAVOR_DEFENSE', 8),
	('LEADER_BARBARIAN', 'FLAVOR_CITY_DEFENSE', 8),
	('LEADER_BARBARIAN', 'FLAVOR_MILITARY_TRAINING', 4),
	('LEADER_BARBARIAN', 'FLAVOR_RECON', 2),
	('LEADER_BARBARIAN', 'FLAVOR_RANGED', 4),
	('LEADER_BARBARIAN', 'FLAVOR_MOBILE', 4),
	('LEADER_BARBARIAN', 'FLAVOR_NAVAL', 4),
	('LEADER_BARBARIAN', 'FLAVOR_NAVAL_RECON', 4),
	('LEADER_BARBARIAN', 'FLAVOR_NAVAL_GROWTH', 4),
	('LEADER_BARBARIAN', 'FLAVOR_NAVAL_TILE_IMPROVEMENT', 4),
	('LEADER_BARBARIAN', 'FLAVOR_AIR', 0),
	('LEADER_BARBARIAN', 'FLAVOR_ANTIAIR', 0),
	('LEADER_BARBARIAN', 'FLAVOR_AIRLIFT', 0),
	('LEADER_BARBARIAN', 'FLAVOR_AIR_CARRIER', 0),
	('LEADER_BARBARIAN', 'FLAVOR_EXPANSION', 0),
	('LEADER_BARBARIAN', 'FLAVOR_GROWTH', 4),
	('LEADER_BARBARIAN', 'FLAVOR_HAPPINESS', 4),
	('LEADER_BARBARIAN', 'FLAVOR_TILE_IMPROVEMENT', 4),
	('LEADER_BARBARIAN', 'FLAVOR_INFRASTRUCTURE', 0),
	('LEADER_BARBARIAN', 'FLAVOR_PRODUCTION', 0),
	('LEADER_BARBARIAN', 'FLAVOR_GOLD', 4),
	('LEADER_BARBARIAN', 'FLAVOR_SCIENCE', 4),
	('LEADER_BARBARIAN', 'FLAVOR_CULTURE', 4),
	('LEADER_BARBARIAN', 'FLAVOR_GREAT_PEOPLE', 4),
	('LEADER_BARBARIAN', 'FLAVOR_WONDER', 0),
	('LEADER_BARBARIAN', 'FLAVOR_RELIGION', 0),
	('LEADER_BARBARIAN', 'FLAVOR_DIPLOMACY', 0),
	('LEADER_BARBARIAN', 'FLAVOR_SPACESHIP', 0),
	('LEADER_BARBARIAN', 'FLAVOR_WATER_CONNECTION', 0),
	('LEADER_BARBARIAN', 'FLAVOR_USE_NUKE', 4),
	('LEADER_BARBARIAN', 'FLAVOR_NUKE', 0),
	('LEADER_BARBARIAN', 'FLAVOR_I_LAND_TRADE_ROUTE', 0),
	('LEADER_BARBARIAN', 'FLAVOR_I_SEA_TRADE_ROUTE', 0),
	('LEADER_BARBARIAN', 'FLAVOR_I_TRADE_ORIGIN', 0),
	('LEADER_BARBARIAN', 'FLAVOR_I_TRADE_DESTINATION', 0),
	('LEADER_BARBARIAN', 'FLAVOR_ARCHAEOLOGY', 0),
	('LEADER_BARBARIAN', 'FLAVOR_ESPIONAGE', 0);
