
-- Settler Stuff

UPDATE Defines
SET Value = '65'
WHERE Name = 'BUILD_ON_RIVER_PERCENT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '65'
WHERE Name = 'SETTLER_BUILD_ON_COAST_PERCENT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '-20'
WHERE Name = 'BUILD_ON_RESOURCE_PERCENT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '2'
WHERE Name = 'SETTLER_STRATEGIC_MULTIPLIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '60'
WHERE Name = 'SETTLER_DISTANCE_DROPOFF_MODIFIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '12'
WHERE Name = 'SETTLER_EVALUATION_DISTANCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

-- Combat Stuff

UPDATE TacticalMoves
SET Priority = '175'
WHERE Type = 'TACTICAL_ESCORT_EMBARKED_UNIT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '15'
WHERE Type = 'TACTICAL_ATTACK_LOW_PRIORITY_CIVILIAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '25'
WHERE Type = 'TACTICAL_ATTACK_MEDIUM_PRIORITY_CIVILIAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '50'
WHERE Type = 'TACTICAL_ATTACK_HIGH_PRIORITY_CIVILIAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '65'
WHERE Type = 'TACTICAL_CLOSE_ON_TARGET' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '100'
WHERE Type = 'TACTICAL_ANCIENT_RUINS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '45'
WHERE Type = 'TACTICAL_DAMAGE_CITY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET OffenseFlavorWeight = '60'
WHERE Type = 'TACTICAL_REPOSITION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET DefenseFlavorWeight = '40'
WHERE Type = 'TACTICAL_REPOSITION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '150'
WHERE Type = 'TACTICAL_OFFENSIVE_POSTURE_MOVES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '2.34'
WHERE Name = 'AI_STRATEGY_DEFEND_MY_LANDS_UNITS_PER_CITY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '7'
WHERE Name = 'AI_STRATEGY_DEFEND_MY_LANDS_BASE_UNITS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '1.75'
WHERE Name = 'AI_STRATEGY_NAVAL_UNITS_PER_CITY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '10'
WHERE Name = 'AI_TACTICAL_RECRUIT_RANGE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '4'
WHERE Name = 'AI_TACTICAL_REPOSITION_RANGE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '1'
WHERE Name = 'AI_MILITARY_BARBARIANS_FOR_MINOR_THREAT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '5'
WHERE Name = 'AI_OPERATIONAL_CITY_ATTACK_DEPLOY_RANGE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '3'
WHERE Name = 'AI_OPERATIONAL_NAVAL_BOMBARDMENT_DEPLOY_RANGE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '50'
WHERE Name = 'AI_OPERATIONAL_PERCENT_DANGER_FOR_FORWARD_MUSTER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '6'
WHERE Name = 'AI_OPERATIONAL_MAX_RECRUIT_TURNS_ENEMY_TERRITORY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '11'
WHERE Name = 'AI_TACTICAL_MAP_UNIT_STRENGTH_MULTIPLIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '20'
WHERE Name = 'AI_TACTICAL_MAP_DOMINANCE_PERCENTAGE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '90'
WHERE Name = 'MILITARY_STRENGTH_RATIO_MULTIPLIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '23'
WHERE Name = 'MILITARY_STRENGTH_CITY_MOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '23'
WHERE Name = 'MILITARY_STRENGTH_BASE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- Policy Decision Stuff

UPDATE Policy_Flavors
SET Flavor = '15'
WHERE PolicyType = 'POLICY_PIETY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICY_TWEAKS' AND Value= 1 );

UPDATE Policy_Flavors
SET Flavor = '20'
WHERE PolicyType = 'POLICY_LIBERTY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICY_TWEAKS' AND Value= 1 );

UPDATE Policy_Flavors
SET Flavor = '15'
WHERE PolicyType = 'POLICY_TRADITION' AND FlavorType = 'FLAVOR_CULTURE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICY_TWEAKS' AND Value= 1 );

UPDATE Policy_Flavors
SET Flavor = '20'
WHERE PolicyType = 'POLICY_TRADITION' AND FlavorType = 'FLAVOR_GROWTH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICY_TWEAKS' AND Value= 1 );

UPDATE Policy_Flavors
SET Flavor = '15'
WHERE PolicyType = 'POLICY_TRADITION' AND FlavorType = 'FLAVOR_WONDER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICY_TWEAKS' AND Value= 1 );

-- City Strategy Flavors

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '35'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_WAR_MOBILIZATION' AND FlavorType = 'FLAVOR_OFFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '20'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_WAR_MOBILIZATION' AND FlavorType = 'FLAVOR_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '25'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_WAR_MOBILIZATION' AND FlavorType = 'FLAVOR_RANGED' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

INSERT INTO AIMilitaryStrategy_Player_Flavors (
AIMilitaryStrategyType, FlavorType, Flavor)
SELECT 'MILITARYAISTRATEGY_WAR_MOBILIZATION', 'FLAVOR_MOBILE' , '30'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '10'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_ANTIAIR' AND FlavorType = 'FLAVOR_ANTIAIR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '15'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_AIR_CARRIER' AND FlavorType = 'FLAVOR_AIR_CARRIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '20'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_AIR' AND FlavorType = 'FLAVOR_AIR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '10'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE' AND FlavorType = 'FLAVOR_OFFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '15'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE' AND FlavorType = 'FLAVOR_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

INSERT INTO AIMilitaryStrategy_Player_Flavors (
AIMilitaryStrategyType, FlavorType, Flavor)
SELECT 'MILITARYAISTRATEGY_EMPIRE_DEFENSE', 'FLAVOR_MOBILE' , '10'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '15'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL' AND FlavorType = 'FLAVOR_OFFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '30'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL' AND FlavorType = 'FLAVOR_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

INSERT INTO AIMilitaryStrategy_Player_Flavors (
AIMilitaryStrategyType, FlavorType, Flavor)
SELECT 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL', 'FLAVOR_MOBILE' , '15'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE AIMilitaryStrategy_City_Flavors
SET Flavor = '15'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE' AND FlavorType = 'FLAVOR_OFFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_City_Flavors
SET Flavor = '25'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE' AND FlavorType = 'FLAVOR_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

INSERT INTO AIMilitaryStrategy_City_Flavors (
AIMilitaryStrategyType, FlavorType, Flavor)
SELECT 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL', 'FLAVOR_MOBILE' , '15'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE AIMilitaryStrategy_City_Flavors
SET Flavor = '20'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL' AND FlavorType = 'FLAVOR_OFFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_City_Flavors
SET Flavor = '30'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL' AND FlavorType = 'FLAVOR_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

INSERT INTO AIMilitaryStrategy_City_Flavors (
AIMilitaryStrategyType, FlavorType, Flavor)
SELECT 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL', 'FLAVOR_MOBILE' , '20'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '15'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_NAVAL_UNITS' AND FlavorType = 'FLAVOR_NAVAL_RECON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '30'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_NAVAL_UNITS_CRITICAL' AND FlavorType = 'FLAVOR_NAVAL_RECON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_City_Flavors
SET Flavor = '20'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_NAVAL_UNITS' AND FlavorType = 'FLAVOR_NAVAL_RECON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_City_Flavors
SET Flavor = '40'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_NAVAL_UNITS_CRITICAL' AND FlavorType = 'FLAVOR_NAVAL_RECON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

