CREATE TEMP TABLE TriggerYieldAmounts (
	EraType text,
	HistoricEventType text,
	YieldType text,
	Amount integer
);

INSERT INTO TriggerYieldAmounts
	(EraType, HistoricEventType, YieldType, Amount)
VALUES
	-- Won a war
	('ERA_ANCIENT', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 228),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 228),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 228),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 228),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 228),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 228),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 228),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 228),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 452),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 452),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 452),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 452),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 1008),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 1008),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 1008),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 1008),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 1202),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 1202),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 1202),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 1202),

	('ERA_MODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 1728),
	('ERA_MODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 1728),
	('ERA_MODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 1728),
	('ERA_MODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 1728),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 2356),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 2356),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 2356),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 2356),

	('ERA_FUTURE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 3084),
	('ERA_FUTURE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 3084),
	('ERA_FUTURE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 3084),
	('ERA_FUTURE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 3084),


	-- Conquered a city
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 171),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 171),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 171),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 171),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 171),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 171),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 171),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 171),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 339),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 339),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 339),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 339),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 756),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 756),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 756),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 756),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 901),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 901),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 901),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 901),

	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 1296),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 1296),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 1296),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 1296),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 1767),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 1767),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 1767),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 1767),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 2313),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 2313),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 2313),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 2313),


	-- Founded a city other than the capital
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 114),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 101),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 114),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 114),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 226),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 226),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 1008),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 1008),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 504),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 504),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 1202),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 1202),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 601),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 601),

	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 1728),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 1728),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 864),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 864),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 2356),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 2356),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 1178),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 1178),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 3084),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 3084),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 1542),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 1542),


	-- Killed a major civ's combat unit
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 22),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 11),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 11),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 22),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 11),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 11),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 45),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 22),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 22),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 100),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 50),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 50),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 120),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 60),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 60),

	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 172),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 86),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 86),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 235),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 117),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 117),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 308),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 154),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 154),


	-- Killed a City-State's combat unit
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 22),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 11),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 11),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 22),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 11),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 11),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 45),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 22),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 22),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 100),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 50),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 50),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 120),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 60),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 60),

	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 172),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 86),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 86),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 235),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 117),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 117),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 308),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 154),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 154),


	-- Killed a Barbarian combat unit
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 11),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 5),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 5),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 11),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 5),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 5),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 22),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 11),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 11),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 50),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 25),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 25),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 60),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 30),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 30),

	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 86),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 43),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 43),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 117),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 58),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 58),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 154),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 77),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 77),


	-- Started a Golden Age
	('ERA_ANCIENT', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 342),
	('ERA_ANCIENT', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 114),
	('ERA_ANCIENT', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 114),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 342),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 114),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 114),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 678),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 226),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 226),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 1512),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 504),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 504),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 1803),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 601),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 601),

	('ERA_MODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 2592),
	('ERA_MODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 864),
	('ERA_MODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 864),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 3534),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 1178),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 1178),

	('ERA_FUTURE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 4626),
	('ERA_FUTURE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 1542),
	('ERA_FUTURE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 1542),


	-- Constructed a World Wonder
	('ERA_ANCIENT', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 342),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 114),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 101),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 342),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 114),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 114),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 678),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 226),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 226),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 1512),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 504),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 504),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 1803),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 601),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 601),

	('ERA_MODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 2592),
	('ERA_MODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 864),
	('ERA_MODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 864),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 3534),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 1178),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 1178),

	('ERA_FUTURE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 4626),
	('ERA_FUTURE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 1542),
	('ERA_FUTURE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 1542),


	-- Researched a Technology
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 22),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 22),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 18),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 22),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 22),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 22),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 45),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 45),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 45),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 100),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 100),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 100),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 120),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 120),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 120),

	('ERA_MODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 172),
	('ERA_MODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 172),
	('ERA_MODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 172),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 235),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 235),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 235),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 308),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 308),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 308),


	-- Adopted a Social Policy
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 37),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 37),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 29),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 37),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 37),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 37),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 74),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 74),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 74),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 166),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 166),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 166),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 198),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 198),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 198),

	('ERA_MODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 285),
	('ERA_MODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 285),
	('ERA_MODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 285),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 388),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 388),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 388),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 508),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 508),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 508),


	-- Completed an Archaeological Dig
	('ERA_ANCIENT', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 114),
	('ERA_ANCIENT', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 114),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 114),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 114),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 226),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 226),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 504),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 504),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 601),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 601),

	('ERA_MODERN', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 864),
	('ERA_MODERN', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 864),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 1178),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 1178),

	('ERA_FUTURE', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 1542),
	('ERA_FUTURE', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 1542),


	-- Birth of a Great Person
	('ERA_ANCIENT', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 114),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 114),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 226),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 504),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 601),

	('ERA_MODERN', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 864),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 1178),

	('ERA_FUTURE', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 1542),


	-- Completed a land Trade Route with a major civ
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 114),
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 114),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 114),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 114),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 226),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 226),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 504),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 504),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 601),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 601),

	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 864),
	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 864),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 1178),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 1178),

	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 1542),
	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 1542),


	-- Completed a sea Trade Route with a major civ
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 114),
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 114),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 114),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 114),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 226),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 226),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 504),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 504),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 601),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 601),

	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 864),
	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 864),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 1178),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 1178),

	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 1542),
	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 1542),


	-- Completed a Trade Route with a City-State
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 114),
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 114),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 114),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 114),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 226),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 226),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 504),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 504),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 601),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 601),

	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 864),
	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 864),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 1178),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 1178),

	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 1542),
	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 1542);

INSERT INTO HandicapInfo_AIDifficultyBonus
	(HandicapType, EraType, HistoricEventType, YieldType, Amount)
SELECT
	'HANDICAP_DEITY', EraType, HistoricEventType, YieldType, Amount
FROM TriggerYieldAmounts;

DROP TABLE TriggerYieldAmounts;