CREATE TEMP TABLE TriggerYieldAmounts (
	EraType text,
	HistoricEventType text,
	YieldType text,
	Amount integer
);

INSERT INTO TriggerYieldAmounts
	(EraType, HistoricEventType, YieldType, Amount)
VALUES
	-- Won a war
	('ERA_ANCIENT', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 92),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 92),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 92),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 92),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 92),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 92),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 92),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 92),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 174),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 174),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 174),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 174),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 378),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 378),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 378),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 378),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 440),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 440),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 440),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 440),

	('ERA_MODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 624),
	('ERA_MODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 624),
	('ERA_MODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 624),
	('ERA_MODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 624),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 842),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 842),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 842),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 842),

	('ERA_FUTURE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 1096),
	('ERA_FUTURE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 1096),
	('ERA_FUTURE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 1096),
	('ERA_FUTURE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 1096),


	-- Conquered a city
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 69),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 69),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 69),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 69),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 69),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 69),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 69),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 69),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 130),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 130),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 130),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 130),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 283),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 283),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 283),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 283),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 330),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 330),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 330),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 330),

	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 468),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 468),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 468),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 468),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 631),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 631),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 631),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 631),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 822),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 822),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 822),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 822),


	-- Founded a city other than the capital
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 46),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 40),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 46),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 46),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 87),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 87),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 378),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 378),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 189),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 189),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 440),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 440),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 220),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 220),

	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 624),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 624),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 312),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 312),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 842),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 842),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 421),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 421),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 1096),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 1096),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 548),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 548),


	-- Killed a major civ's combat unit
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 9),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 4),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 4),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 9),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 4),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 4),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 17),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 8),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 8),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 37),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 18),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 18),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 44),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 22),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 22),

	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 62),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 31),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 31),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 84),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 42),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 42),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 109),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 54),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 54),


	-- Killed a City-State's combat unit
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 9),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 4),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 4),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 9),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 4),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 4),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 17),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 8),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 8),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 37),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 18),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 18),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 44),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 22),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 22),

	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 62),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 31),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 31),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 84),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 42),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 42),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 109),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 54),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 54),


	-- Killed a Barbarian combat unit
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 4),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 2),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 2),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 4),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 2),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 2),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 8),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 4),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 4),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 18),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 9),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 9),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 22),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 11),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 11),

	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 31),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 15),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 15),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 42),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 21),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 21),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 54),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 27),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 27),


	-- Started a Golden Age
	('ERA_ANCIENT', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 138),
	('ERA_ANCIENT', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 46),
	('ERA_ANCIENT', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 46),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 138),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 46),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 46),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 261),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 87),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 87),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 567),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 189),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 189),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 660),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 220),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 220),

	('ERA_MODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 936),
	('ERA_MODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 312),
	('ERA_MODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 312),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 1263),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 421),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 421),

	('ERA_FUTURE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 1644),
	('ERA_FUTURE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 548),
	('ERA_FUTURE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 548),


	-- Constructed a World Wonder
	('ERA_ANCIENT', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 138),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 46),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 40),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 138),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 46),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 46),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 261),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 87),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 87),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 567),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 189),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 189),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 660),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 220),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 220),

	('ERA_MODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 936),
	('ERA_MODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 312),
	('ERA_MODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 312),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 1263),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 421),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 421),

	('ERA_FUTURE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 1644),
	('ERA_FUTURE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 548),
	('ERA_FUTURE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 548),


	-- Researched a Technology
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 9),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 9),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 7),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 9),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 9),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 9),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 17),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 17),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 17),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 37),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 37),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 37),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 44),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 44),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 44),

	('ERA_MODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 62),
	('ERA_MODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 62),
	('ERA_MODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 62),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 84),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 84),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 84),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 109),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 109),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 109),


	-- Adopted a Social Policy
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 15),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 15),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 11),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 15),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 15),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 15),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 28),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 28),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 28),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 62),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 62),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 62),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 72),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 72),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 72),

	('ERA_MODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 102),
	('ERA_MODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 102),
	('ERA_MODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 102),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 138),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 138),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 138),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 180),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 180),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 180),


	-- Completed an Archaeological Dig
	('ERA_ANCIENT', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 46),
	('ERA_ANCIENT', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 46),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 46),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 46),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 87),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 87),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 189),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 189),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 220),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 220),

	('ERA_MODERN', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 312),
	('ERA_MODERN', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 312),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 421),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 421),

	('ERA_FUTURE', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 548),
	('ERA_FUTURE', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 548),


	-- Birth of a Great Person
	('ERA_ANCIENT', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 46),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 46),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 87),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 189),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 220),

	('ERA_MODERN', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 312),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 421),

	('ERA_FUTURE', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 548),


	-- Completed a land Trade Route with a major civ
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 46),
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 46),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 46),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 46),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 87),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 87),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 189),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 189),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 220),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 220),

	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 312),
	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 312),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 421),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 421),

	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 548),
	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 548),


	-- Completed a sea Trade Route with a major civ
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 46),
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 46),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 46),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 46),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 87),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 87),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 189),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 189),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 220),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 220),

	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 312),
	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 312),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 421),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 421),

	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 548),
	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 548),


	-- Completed a Trade Route with a City-State
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 46),
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 46),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 46),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 46),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 87),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 87),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 189),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 189),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 220),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 220),

	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 312),
	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 312),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 421),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 421),

	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 548),
	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 548);

INSERT INTO HandicapInfo_AIDifficultyBonus
	(HandicapType, EraType, HistoricEventType, YieldType, Amount)
SELECT
	'HANDICAP_KING', EraType, HistoricEventType, YieldType, Amount
FROM TriggerYieldAmounts;

DROP TABLE TriggerYieldAmounts;