CREATE TEMP TABLE TriggerYieldAmounts (
	EraType text,
	HistoricEventType text,
	YieldType text,
	Amount integer
);

INSERT INTO TriggerYieldAmounts
	(EraType, HistoricEventType, YieldType, Amount)
VALUES
	-- Won a war
	('ERA_ANCIENT', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 182),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 182),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 182),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 182),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 182),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 182),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 182),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 182),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 354),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 354),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 354),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 354),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 786),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 786),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 786),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 786),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 930),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 930),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 930),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 930),

	('ERA_MODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 1334),
	('ERA_MODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 1334),
	('ERA_MODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 1334),
	('ERA_MODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 1334),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 1814),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 1814),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 1814),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 1814),

	('ERA_FUTURE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_FOOD', 2370),
	('ERA_FUTURE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_GOLD', 2370),
	('ERA_FUTURE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_CULTURE', 2370),
	('ERA_FUTURE', 'HISTORIC_EVENT_WON_WAR', 'YIELD_SCIENCE', 2370),


	-- Conquered a city
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 136),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 136),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 136),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 136),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 136),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 136),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 136),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 136),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 265),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 265),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 265),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 265),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 589),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 589),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 589),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 589),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 697),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 697),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 697),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 697),

	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 1000),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 1000),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 1000),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 1000),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 1360),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 1360),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 1360),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 1360),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_FOOD', 1777),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_GOLD', 1777),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_CULTURE', 1777),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_CONQUEST', 'YIELD_SCIENCE', 1777),


	-- Founded a city other than the capital
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 91),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 80),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 91),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 91),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 177),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 177),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 786),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 786),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 393),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 393),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 930),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 930),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 465),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 465),

	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 1334),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 1334),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 667),
	('ERA_MODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 667),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 1814),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 1814),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 907),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 907),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_FOOD', 2370),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_GOLD', 2370),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_CULTURE', 1185),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_CITY_FOUND', 'YIELD_SCIENCE', 1185),


	-- Killed a major civ's combat unit
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 18),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 9),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 9),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 18),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 9),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 9),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 35),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 17),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 17),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 78),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 39),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 39),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 93),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 46),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 46),

	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 133),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 66),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 66),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 181),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 90),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 90),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_GOLD', 237),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_CULTURE', 118),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_MAJOR_UNIT', 'YIELD_SCIENCE', 118),


	-- Killed a City-State's combat unit
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 18),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 9),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 9),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 18),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 9),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 9),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 35),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 17),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 17),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 78),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 39),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 39),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 93),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 46),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 46),

	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 133),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 66),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 66),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 181),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 90),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 90),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_GOLD', 237),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_CULTURE', 118),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_CITY_STATE_UNIT', 'YIELD_SCIENCE', 118),


	-- Killed a Barbarian combat unit
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 9),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 4),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 4),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 9),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 4),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 4),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 17),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 8),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 8),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 39),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 19),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 19),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 46),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 23),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 23),

	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 66),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 33),
	('ERA_MODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 33),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 90),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 45),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 45),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_GOLD', 118),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_CULTURE', 59),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_KILLED_BARBARIAN_UNIT', 'YIELD_SCIENCE', 59),


	-- Started a Golden Age
	('ERA_ANCIENT', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 273),
	('ERA_ANCIENT', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 91),
	('ERA_ANCIENT', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 91),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 273),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 91),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 91),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 531),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 177),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 177),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 1179),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 393),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 393),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 1395),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 465),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 465),

	('ERA_MODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 2001),
	('ERA_MODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 667),
	('ERA_MODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 667),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 2721),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 907),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 907),

	('ERA_FUTURE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_GOLD', 3555),
	('ERA_FUTURE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_CULTURE', 1185),
	('ERA_FUTURE', 'HISTORIC_EVENT_GOLDEN_AGE', 'YIELD_SCIENCE', 1185),


	-- Constructed a World Wonder
	('ERA_ANCIENT', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 273),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 91),
	('ERA_ANCIENT', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 80),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 273),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 91),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 91),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 531),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 177),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 177),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 1179),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 393),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 393),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 1395),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 465),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 465),

	('ERA_MODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 2001),
	('ERA_MODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 667),
	('ERA_MODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 667),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 2721),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 907),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 907),

	('ERA_FUTURE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_GOLD', 3555),
	('ERA_FUTURE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_CULTURE', 1185),
	('ERA_FUTURE', 'HISTORIC_EVENT_WORLD_WONDER', 'YIELD_SCIENCE', 1185),


	-- Researched a Technology
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 18),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 18),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 14),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 18),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 18),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 18),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 35),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 35),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 35),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 78),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 78),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 78),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 93),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 93),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 93),

	('ERA_MODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 133),
	('ERA_MODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 133),
	('ERA_MODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 133),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 181),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 181),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 181),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_FOOD', 237),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_GOLD', 237),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_RESEARCHED_TECH', 'YIELD_CULTURE', 237),


	-- Adopted a Social Policy
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 30),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 30),
	('ERA_ANCIENT', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 23),

	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 30),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 30),
	('ERA_CLASSICAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 30),

	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 58),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 58),
	('ERA_MEDIEVAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 58),

	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 129),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 129),
	('ERA_RENAISSANCE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 129),

	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 153),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 153),
	('ERA_INDUSTRIAL', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 153),

	('ERA_MODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 220),
	('ERA_MODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 220),
	('ERA_MODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 220),

	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 299),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 299),
	('ERA_POSTMODERN', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 299),

	('ERA_FUTURE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_FOOD', 391),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_GOLD', 391),
	('ERA_FUTURE', 'DIFFICULTY_BONUS_ADOPTED_POLICY', 'YIELD_SCIENCE', 391),


	-- Completed an Archaeological Dig
	('ERA_ANCIENT', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 91),
	('ERA_ANCIENT', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 91),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 91),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 91),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 177),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 177),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 393),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 393),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 465),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 465),

	('ERA_MODERN', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 667),
	('ERA_MODERN', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 667),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 907),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 907),

	('ERA_FUTURE', 'HISTORIC_EVENT_DIG', 'YIELD_FOOD', 1185),
	('ERA_FUTURE', 'HISTORIC_EVENT_DIG', 'YIELD_GOLD', 1185),


	-- Birth of a Great Person
	('ERA_ANCIENT', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 91),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 91),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 177),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 393),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 465),

	('ERA_MODERN', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 667),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 907),

	('ERA_FUTURE', 'HISTORIC_EVENT_GREAT_PERSON', 'YIELD_FOOD', 1185),


	-- Completed a land Trade Route with a major civ
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 91),
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 91),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 91),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 91),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 177),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 177),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 393),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 393),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 465),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 465),

	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 667),
	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 667),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 907),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 907),

	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_FOOD', 1185),
	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_LAND', 'YIELD_GOLD', 1185),


	-- Completed a sea Trade Route with a major civ
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 91),
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 91),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 91),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 91),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 177),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 177),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 393),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 393),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 465),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 465),

	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 667),
	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 667),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 907),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 907),

	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_FOOD', 1185),
	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_SEA', 'YIELD_GOLD', 1185),


	-- Completed a Trade Route with a City-State
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 91),
	('ERA_ANCIENT', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 91),

	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 91),
	('ERA_CLASSICAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 91),

	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 177),
	('ERA_MEDIEVAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 177),

	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 393),
	('ERA_RENAISSANCE', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 393),

	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 465),
	('ERA_INDUSTRIAL', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 465),

	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 667),
	('ERA_MODERN', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 667),

	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 907),
	('ERA_POSTMODERN', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 907),

	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_FOOD', 1185),
	('ERA_FUTURE', 'HISTORIC_EVENT_TRADE_CS', 'YIELD_GOLD', 1185);

INSERT INTO HandicapInfo_AIDifficultyBonus
	(HandicapType, EraType, HistoricEventType, YieldType, Amount)
SELECT
	'HANDICAP_IMMORTAL', EraType, HistoricEventType, YieldType, Amount
FROM TriggerYieldAmounts;

DROP TABLE TriggerYieldAmounts;