-- Arsenal of Democracy

UPDATE Policies
SET MilitaryUnitGiftExtraInfluence = '20'
WHERE Type = 'POLICY_ARSENAL_DEMOCRACY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

-- Capitalism

DELETE FROM Policy_BuildingClassHappiness
WHERE PolicyType = 'POLICY_CAPITALISM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET NoUnhappfromXSpecialists = '5'
WHERE Type = 'POLICY_CAPITALISM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

-- Covert Action
UPDATE Policies
SET FreeSpy = '1'
WHERE Type = 'POLICY_COVERT_ACTION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

-- Open Society
UPDATE Policies
SET GreatPeopleRateModifier = '33'
WHERE Type = 'POLICY_OPEN_SOCIETY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );


-- Creative Expression

-- Economic Union

UPDATE Policies
SET FreeTradeRoute = '1'
WHERE Type = 'POLICY_ECONOMIC_UNION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

-- Media Culture

 -- Their Finest Hour
UPDATE Policies
SET IncludesOneShotFreeUnits = '1'
WHERE Type = 'POLICY_THEIR_FINEST_HOUR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

 -- Universal Suffrage 

UPDATE Policies
SET HalfSpecialistUnhappiness = '0'
WHERE Type = 'POLICY_UNIVERSAL_SUFFRAGE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET HappinessPerXPopulation = '10'
WHERE Type = 'POLICY_UNIVERSAL_SUFFRAGE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

-- Urbanization
DELETE FROM Policy_BuildingClassHappiness
WHERE PolicyType = 'POLICY_URBANIZATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

--POLICY_UNIVERSAL_HEALTHCARE_F

DELETE FROM Policy_BuildingClassHappiness
WHERE PolicyType = 'POLICY_UNIVERSAL_HEALTHCARE_F' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET Help = 'TXT_KEY_POLICY_UNIVERSAL_HEALTHCARE_F_HELP'
WHERE Type = 'POLICY_UNIVERSAL_HEALTHCARE_F' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

UPDATE Policies
SET Description = 'TXT_KEY_POLICY_UNIVERSAL_HEALTHCARE_F'
WHERE Type = 'POLICY_UNIVERSAL_HEALTHCARE_F' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICIES' AND Value= 1 );

