--------------------------------
-- City Strategy
--------------------------------
DELETE FROM AICityStrategies
WHERE Type IN (
	'AICITYSTRATEGY_NO_NEED_INTERNATIONAL_LAND_TRADE_ROUTE',
	'AICITYSTRATEGY_NO_NEED_INTERNATIONAL_SEA_TRADE_ROUTE'
);

DELETE FROM AICityStrategy_Flavors
WHERE AICityStrategyType IN (
	'AICITYSTRATEGY_NO_NEED_INTERNATIONAL_LAND_TRADE_ROUTE',
	'AICITYSTRATEGY_NO_NEED_INTERNATIONAL_SEA_TRADE_ROUTE'
);

-- Shrine has a different prereq
UPDATE AICityStrategies
SET TechPrereq = (
	SELECT PrereqTech FROM Buildings WHERE Type = 'BUILDING_SHRINE'
) WHERE Type = 'AICITYSTRATEGY_FIRST_FAITH_BUILDING';

-- Shut up advisors for some of the strategies
UPDATE AICityStrategies
SET
	Advisor = NULL,
	AdvisorCounsel = NULL
WHERE AdvisorCounsel IN (
	'TXT_KEY_AICITYSTRATEGY_NEED_NAVAL_GROWTH',
	'TXT_KEY_AICITYSTRATEGY_HAVE_TRAINING_FACILITY',
	'TXT_KEY_AICITYSTRATEGY_ENOUGH_TILE_IMPROVERS',
	'TXT_KEY_AICITYSTRATEGY_NEED_TILE_IMPROVERS',
	'TXT_KEY_AICITYSTRATEGY_WANT_TILE_IMPROVERS'
);

-- Flavors
INSERT INTO AICityStrategy_Flavors
	(AICityStrategyType, FlavorType, Flavor)
VALUES
	('AICITYSTRATEGY_NEED_HAPPINESS_CULTURE', 'FLAVOR_CULTURE', 60),
	('AICITYSTRATEGY_NEED_HAPPINESS_SCIENCE', 'FLAVOR_SCIENCE', 60),
	('AICITYSTRATEGY_NEED_HAPPINESS_DEFENSE', 'FLAVOR_PRODUCTION', 40),
	('AICITYSTRATEGY_NEED_HAPPINESS_DEFENSE', 'FLAVOR_GROWTH', 40),
	('AICITYSTRATEGY_NEED_HAPPINESS_DEFENSE', 'FLAVOR_MILITARY_TRAINING', 30),
	('AICITYSTRATEGY_NEED_HAPPINESS_GOLD', 'FLAVOR_GOLD', 60),
	('AICITYSTRATEGY_NEED_HAPPINESS_GOLD', 'FLAVOR_GROWTH', 30),
	('AICITYSTRATEGY_NEED_HAPPINESS_GOLD', 'FLAVOR_I_LAND_TRADE_ROUTE', 30),
	('AICITYSTRATEGY_NEED_HAPPINESS_GOLD', 'FLAVOR_I_SEA_TRADE_ROUTE', 30),
	('AICITYSTRATEGY_NEED_HAPPINESS_CONNECTION', 'FLAVOR_INFRASTRUCTURE', 60),
	('AICITYSTRATEGY_NEED_HAPPINESS_CONNECTION', 'FLAVOR_TILE_IMPROVEMENT', 60),
	('AICITYSTRATEGY_NEED_HAPPINESS_CONNECTION', 'FLAVOR_WATER_CONNECTION', 60),
	('AICITYSTRATEGY_NEED_HAPPINESS_PILLAGE', 'FLAVOR_TILE_IMPROVEMENT', 60),
	('AICITYSTRATEGY_NEED_HAPPINESS_PILLAGE', 'FLAVOR_DEFENSE', 20),
	('AICITYSTRATEGY_NEED_HAPPINESS_PILLAGE', 'FLAVOR_CITY_DEFENSE', 20),
	('AICITYSTRATEGY_NEED_HAPPINESS_RELIGION', 'FLAVOR_RELIGION', 60),
	('AICITYSTRATEGY_NEED_HAPPINESS_STARVE', 'FLAVOR_TILE_IMPROVEMENT', 60),
	('AICITYSTRATEGY_NEED_HAPPINESS_STARVE', 'FLAVOR_NAVAL_GROWTH', 60),
	('AICITYSTRATEGY_NEED_HAPPINESS_STARVE', 'FLAVOR_GROWTH', 60);

UPDATE AICityStrategy_Flavors
SET Flavor = 100
WHERE AICityStrategyType IN (
	'AICITYSTRATEGY_NEED_INTERNATIONAL_LAND_TRADE_ROUTE',
	'AICITYSTRATEGY_NEED_INTERNATIONAL_SEA_TRADE_ROUTE'
);

--------------------------------
-- Grand Strategy
--------------------------------
DELETE FROM AIGrandStrategy_FlavorMods WHERE FlavorType = 'FLAVOR_RELIGION' AND AIGrandStrategyType = 'AIGRANDSTRATEGY_SPACESHIP';

--------------------------------
-- Economic Strategy
--------------------------------
DELETE FROM AIEconomicStrategy_Player_Flavors WHERE FlavorType = 'FLAVOR_NAVAL' AND AIEconomicStrategyType = 'ECONOMICAISTRATEGY_REALLY_NEED_RECON_SEA';

UPDATE AIEconomicStrategy_City_Flavors
SET Flavor = -10
WHERE AIEconomicStrategyType = 'ECONOMICAISTRATEGY_NEED_HAPPINESS_CRITICAL' AND FlavorType = 'FLAVOR_GROWTH';
