-- To be inserted back below
DELETE FROM Resource_YieldChanges;
DELETE FROM Improvement_ResourceType_Yields;
DELETE FROM Resource_QuantityTypes;

-- Resource base yields
INSERT INTO Resource_YieldChanges
	(ResourceType, YieldType, Yield)
VALUES
	-- Bonus
	('RESOURCE_STONE', 'YIELD_PRODUCTION', 1),
	('RESOURCE_WHEAT', 'YIELD_FOOD', 1),
	('RESOURCE_RICE', 'YIELD_FOOD', 1),
	('RESOURCE_MAIZE', 'YIELD_FOOD', 1),
	('RESOURCE_COW', 'YIELD_PRODUCTION', 1),
	('RESOURCE_SHEEP', 'YIELD_FOOD', 1),
	('RESOURCE_DEER', 'YIELD_FOOD', 1),
	('RESOURCE_BISON', 'YIELD_FOOD', 1),
	('RESOURCE_FISH', 'YIELD_FOOD', 2),
	-- Strategics
	('RESOURCE_IRON', 'YIELD_PRODUCTION', 1),
	('RESOURCE_HORSE', 'YIELD_PRODUCTION', 1),
	('RESOURCE_COAL', 'YIELD_PRODUCTION', 1),
	('RESOURCE_OIL', 'YIELD_PRODUCTION', 1),
	('RESOURCE_ALUMINUM', 'YIELD_PRODUCTION', 1),
	('RESOURCE_URANIUM', 'YIELD_PRODUCTION', 1),
	('RESOURCE_URANIUM', 'YIELD_SCIENCE', 1),
	-- Luxuries
	('RESOURCE_AMBER', 'YIELD_PRODUCTION', 1),
	('RESOURCE_AMBER', 'YIELD_GOLD', 1),
	('RESOURCE_CITRUS', 'YIELD_FOOD', 1),
	('RESOURCE_CITRUS', 'YIELD_GOLD', 1),
	('RESOURCE_COCOA', 'YIELD_FOOD', 1),
	('RESOURCE_COCOA', 'YIELD_GOLD', 1),
	('RESOURCE_COFFEE', 'YIELD_FOOD', 1),
	('RESOURCE_COFFEE', 'YIELD_GOLD', 1),
	('RESOURCE_COPPER', 'YIELD_PRODUCTION', 1),
	('RESOURCE_CORAL', 'YIELD_PRODUCTION', 1),
	('RESOURCE_CORAL', 'YIELD_GOLD', 2),
	('RESOURCE_COTTON', 'YIELD_GOLD', 2),
	('RESOURCE_CRAB', 'YIELD_FOOD', 1),
	('RESOURCE_CRAB', 'YIELD_GOLD', 1),
	('RESOURCE_DYE', 'YIELD_GOLD', 1),
	('RESOURCE_FUR', 'YIELD_FOOD', 2),
	('RESOURCE_GEMS', 'YIELD_GOLD', 1),
	('RESOURCE_GLASS', 'YIELD_GOLD', 2),
	('RESOURCE_GOLD', 'YIELD_GOLD', 2),
	('RESOURCE_INCENSE', 'YIELD_GOLD', 2),
	('RESOURCE_IVORY', 'YIELD_PRODUCTION', 1),
	('RESOURCE_JADE', 'YIELD_GOLD', 2),
	('RESOURCE_JEWELRY', 'YIELD_GOLD', 2),
	('RESOURCE_LAPIS', 'YIELD_PRODUCTION', 1),
	('RESOURCE_MARBLE', 'YIELD_PRODUCTION', 1),
	('RESOURCE_OLIVE', 'YIELD_FOOD', 1),
	('RESOURCE_OLIVE', 'YIELD_GOLD', 1),
	('RESOURCE_PEARLS', 'YIELD_GOLD', 2),
	('RESOURCE_PERFUME', 'YIELD_GOLD', 2),
	('RESOURCE_PORCELAIN', 'YIELD_GOLD', 2),
	('RESOURCE_SALT', 'YIELD_FOOD', 1),
	('RESOURCE_SALT', 'YIELD_PRODUCTION', 1),
	('RESOURCE_SILK', 'YIELD_GOLD', 2),
	('RESOURCE_SILVER', 'YIELD_GOLD', 1),
	('RESOURCE_SPICES', 'YIELD_GOLD', 1),
	('RESOURCE_SUGAR', 'YIELD_PRODUCTION', 1),
	('RESOURCE_SUGAR', 'YIELD_GOLD', 1),
	('RESOURCE_TEA', 'YIELD_PRODUCTION', 2),
	('RESOURCE_TOBACCO', 'YIELD_GOLD', 2),
	('RESOURCE_TRUFFLES', 'YIELD_GOLD', 2),
	('RESOURCE_WHALE', 'YIELD_FOOD', 1),
	('RESOURCE_WHALE', 'YIELD_PRODUCTION', 1),
	('RESOURCE_WINE', 'YIELD_FOOD', 1),
	('RESOURCE_WINE', 'YIELD_GOLD', 1),
	-- Uniques
	('RESOURCE_BRAZILWOOD', 'YIELD_GOLD', 1),
	('RESOURCE_CLOVES', 'YIELD_GOLD', 2),
	('RESOURCE_NUTMEG', 'YIELD_PRODUCTION', 1),
	('RESOURCE_NUTMEG', 'YIELD_GOLD', 1),
	('RESOURCE_PEPPER', 'YIELD_FOOD', 1),
	('RESOURCE_PEPPER', 'YIELD_GOLD', 1);

-- Resource improved yields (on top of improvement)
INSERT INTO Improvement_ResourceType_Yields
	(ImprovementType, ResourceType, YieldType, Yield)
VALUES
	-- Bonus
	('IMPROVEMENT_FARM', 'RESOURCE_RICE', 'YIELD_FOOD', -1),
	('IMPROVEMENT_FARM', 'RESOURCE_RICE', 'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_FARM', 'RESOURCE_MAIZE', 'YIELD_FOOD', -1),
	('IMPROVEMENT_FARM', 'RESOURCE_MAIZE', 'YIELD_GOLD', 1),
	('IMPROVEMENT_QUARRY', 'RESOURCE_STONE', 'YIELD_PRODUCTION', 2),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_BANANA', 'YIELD_FOOD', 3),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_BANANA', 'YIELD_GOLD', 1),
	('IMPROVEMENT_CAMP', 'RESOURCE_BISON', 'YIELD_FOOD', 1),
	('IMPROVEMENT_CAMP', 'RESOURCE_BISON', 'YIELD_GOLD', 1),
	('IMPROVEMENT_CAMP', 'RESOURCE_DEER', 'YIELD_FOOD', 1),
	('IMPROVEMENT_PASTURE', 'RESOURCE_COW', 'YIELD_FOOD', 1),
	('IMPROVEMENT_PASTURE', 'RESOURCE_COW', 'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_PASTURE', 'RESOURCE_SHEEP', 'YIELD_FOOD', 1),
	('IMPROVEMENT_PASTURE', 'RESOURCE_SHEEP', 'YIELD_GOLD', 2),
	('IMPROVEMENT_FISHING_BOATS', 'RESOURCE_FISH', 'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_FISHING_BOATS', 'RESOURCE_FISH', 'YIELD_GOLD', 1),
	-- Strategics
	('IMPROVEMENT_MINE', 'RESOURCE_IRON', 'YIELD_SCIENCE', 1),
	('IMPROVEMENT_PASTURE', 'RESOURCE_HORSE', 'YIELD_PRODUCTION', 2),
	('IMPROVEMENT_MINE', 'RESOURCE_COAL', 'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_MINE', 'RESOURCE_ALUMINUM', 'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_WELL', 'RESOURCE_OIL', 'YIELD_PRODUCTION', 5),
	('IMPROVEMENT_OFFSHORE_PLATFORM', 'RESOURCE_OIL', 'YIELD_PRODUCTION', 3),
	('IMPROVEMENT_QUARRY', 'RESOURCE_URANIUM', 'YIELD_SCIENCE', 1),
	-- Luxuries
	('IMPROVEMENT_QUARRY', 'RESOURCE_AMBER', 'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_QUARRY', 'RESOURCE_AMBER', 'YIELD_GOLD', 2),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_CITRUS', 'YIELD_FOOD', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_CITRUS', 'YIELD_GOLD', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_COCOA', 'YIELD_GOLD', 2),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_COFFEE', 'YIELD_SCIENCE', 2),
	('IMPROVEMENT_MINE', 'RESOURCE_COPPER', 'YIELD_GOLD', 1),
	('IMPROVEMENT_FISHING_BOATS', 'RESOURCE_CORAL', 'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_FISHING_BOATS', 'RESOURCE_CORAL', 'YIELD_FOOD', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_COTTON', 'YIELD_GOLD', 2),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_COTTON', 'YIELD_CULTURE', 1),
	('IMPROVEMENT_FISHING_BOATS', 'RESOURCE_CRAB', 'YIELD_PRODUCTION', 2),
	('IMPROVEMENT_FISHING_BOATS', 'RESOURCE_CRAB', 'YIELD_FOOD', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_DYE', 'YIELD_GOLD', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_DYE', 'YIELD_CULTURE', 2),
	('IMPROVEMENT_CAMP', 'RESOURCE_FUR', 'YIELD_GOLD', 1),
	('IMPROVEMENT_CAMP', 'RESOURCE_FUR', 'YIELD_CULTURE', 1),
	('IMPROVEMENT_MINE', 'RESOURCE_GEMS', 'YIELD_GOLD', 1),
	('IMPROVEMENT_MINE', 'RESOURCE_GEMS', 'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_MINE', 'RESOURCE_GOLD', 'YIELD_CULTURE', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_INCENSE', 'YIELD_FAITH', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_INCENSE', 'YIELD_CULTURE', 1),
	('IMPROVEMENT_CAMP', 'RESOURCE_IVORY', 'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_CAMP', 'RESOURCE_IVORY', 'YIELD_GOLD', 1),
	('IMPROVEMENT_QUARRY', 'RESOURCE_JADE', 'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_QUARRY', 'RESOURCE_JADE', 'YIELD_CULTURE', 1),
	('IMPROVEMENT_QUARRY', 'RESOURCE_LAPIS', 'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_QUARRY', 'RESOURCE_LAPIS', 'YIELD_SCIENCE', 2),
	('IMPROVEMENT_QUARRY', 'RESOURCE_MARBLE', 'YIELD_PRODUCTION', 2),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_OLIVE', 'YIELD_GOLD', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_OLIVE', 'YIELD_CULTURE', 1),
	('IMPROVEMENT_FISHING_BOATS', 'RESOURCE_PEARLS', 'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_FISHING_BOATS', 'RESOURCE_PEARLS', 'YIELD_CULTURE', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_PERFUME', 'YIELD_GOLD', 2),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_PERFUME', 'YIELD_CULTURE', 1),
	('IMPROVEMENT_MINE', 'RESOURCE_SALT', 'YIELD_FOOD', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_SILK', 'YIELD_GOLD', 3),
	('IMPROVEMENT_MINE', 'RESOURCE_SILVER', 'YIELD_GOLD', 2),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_SPICES', 'YIELD_FOOD', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_SPICES', 'YIELD_GOLD', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_SUGAR', 'YIELD_FOOD', 2),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_TEA', 'YIELD_PRODUCTION', 2),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_TOBACCO', 'YIELD_GOLD', 3),
	('IMPROVEMENT_CAMP', 'RESOURCE_TRUFFLES', 'YIELD_FOOD', 1),
	('IMPROVEMENT_CAMP', 'RESOURCE_TRUFFLES', 'YIELD_GOLD', 1),
	('IMPROVEMENT_FISHING_BOATS', 'RESOURCE_WHALE', 'YIELD_PRODUCTION', 1),
	('IMPROVEMENT_FISHING_BOATS', 'RESOURCE_WHALE', 'YIELD_SCIENCE', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_WINE', 'YIELD_CULTURE', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_WINE', 'YIELD_GOLD', 1),
	-- Uniques
	('IMPROVEMENT_PLANTATION', 'RESOURCE_CLOVES', 'YIELD_FAITH', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_CLOVES', 'YIELD_GOLD', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_NUTMEG', 'YIELD_CULTURE', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_NUTMEG', 'YIELD_GOLD', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_PEPPER', 'YIELD_GOLD', 1),
	('IMPROVEMENT_PLANTATION', 'RESOURCE_PEPPER', 'YIELD_FAITH', 1);

-- Tech where the resource can be set as "owned"
-- For Strategics, this is the reveal tech
-- For Luxury and Bonus resources, this is the tech for the improvement required to connect it
UPDATE Resources
SET TechImproveable = TechReveal
WHERE ResourceUsage = 1;

UPDATE Resources
SET TechImproveable = (
	SELECT PrereqTech FROM Builds WHERE ImprovementType = (
		SELECT ImprovementType FROM Improvement_ResourceTypes WHERE ResourceType = Resources.Type
	)
)
WHERE ResourceUsage <> 1;

-- Strategics can be sold when they are revealed
-- Luxuries can be sold at game start
UPDATE Resources
SET TechCityTrade = TechReveal
WHERE ResourceUsage = 1;

UPDATE Resources
SET TechCityTrade = NULL
WHERE ResourceUsage <> 1;

-- No need for this anymore, using TechObsolete instead
UPDATE Resources
SET AIStopTradingEra = NULL;

-- Luxuries give 2 happiness each
UPDATE Resources
SET Happiness = 2
WHERE ResourceUsage = 2;

-- Monopoly stuff
UPDATE Resources
SET IsMonopoly = 1;

UPDATE Resources
SET IsMonopoly = 0
WHERE ResourceUsage = 0
OR Type = 'RESOURCE_PAPER';

--------------------------------------------------------------------------------------------
-- Modmod compatibilities
-- Unused columns are either reset to default values or values that make sense
-- Some more checks to make sure Plot:CanHaveResource works as intended
--------------------------------------------------------------------------------------------

-- Set columns back to default
UPDATE Resources
SET
	AITradeModifier = 0,
	AIObjective = 0,
	MinLatitude = 0,
	MaxLatitude = 90,
	MinLandPercent = 0,
	GroupRange = 0,
	GroupRand = 0;

UPDATE Resources
SET MaxLatitude = 40
WHERE Type = 'RESOURCE_RICE';

UPDATE Resources
SET MaxLatitude = 50
WHERE Type = 'RESOURCE_MAIZE';

-- Placement order and resource count for world builder maps
UPDATE Resources
SET
	PlacementOrder = 0,
	ConstAppearance = 50,
	RandApp1 = 25,
	RandApp2 = 25,
	RandApp3 = 0,
	RandApp4 = 0,
	Player = 100,
	TilesPer = 0,
	"Unique" = 0,
	GroupRange = 3,
	GroupRand = 15
WHERE ResourceUsage = 2;

UPDATE Resources
SET
	PlacementOrder = 1,
	ConstAppearance = 100,
	RandApp1 = 10,
	RandApp2 = 10,
	RandApp3 = 0,
	RandApp4 = 0,
	Player = 67,
	TilesPer = 0
	-- Keep vanilla values for Unique
WHERE ResourceUsage = 1;

UPDATE Resources
SET
	PlacementOrder = 2,
	ConstAppearance = 50,
	RandApp1 = 25,
	RandApp2 = 25,
	RandApp3 = 0,
	RandApp4 = 0,
	Player = 0,
	TilesPer = 12,
	"Unique" = 0
WHERE ResourceUsage = 0;

-- Resources that should not be placed on the map
UPDATE Resources
SET
	ConstAppearance = 0,
	RandApp1 = 0,
	RandApp2 = 0,
	RandApp3 = 0,
	RandApp4 = 0,
	Player = 0,
	TilesPer = 0,
	"Unique" = 0,
	GroupRange = 0,
	GroupRand = 0
WHERE Type IN (
	'RESOURCE_BRAZILWOOD',
	'RESOURCE_CLOVES',
	'RESOURCE_NUTMEG',
	'RESOURCE_PEPPER',
	'RESOURCE_GLASS',
	'RESOURCE_JEWELRY',
	'RESOURCE_PORCELAIN',
	'RESOURCE_PAPER'
);

INSERT INTO Resource_QuantityTypes
	(ResourceType, Quantity)
VALUES
	('RESOURCE_IRON', 2),
	('RESOURCE_IRON', 2),
	('RESOURCE_IRON', 3),
	('RESOURCE_IRON', 4),
	('RESOURCE_HORSE', 2),
	('RESOURCE_HORSE', 2),
	('RESOURCE_HORSE', 3),
	('RESOURCE_HORSE', 4),
	('RESOURCE_COAL', 2),
	('RESOURCE_COAL', 2),
	('RESOURCE_COAL', 3),
	('RESOURCE_COAL', 4),
	('RESOURCE_OIL', 2),
	('RESOURCE_OIL', 3),
	('RESOURCE_OIL', 5),
	('RESOURCE_OIL', 6),
	('RESOURCE_ALUMINUM', 2),
	('RESOURCE_ALUMINUM', 3),
	('RESOURCE_ALUMINUM', 6),
	('RESOURCE_ALUMINUM', 7),
	('RESOURCE_URANIUM', 1),
	('RESOURCE_URANIUM', 2);
