
/* Traits */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ART_OF_WAR', 'You get an extra Spy. Great Generals see farther and give more strength.[NEWLINE]Starts with a Warrior and Great General. ', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMPHIB_WARLORD', 'Units move faster along rivers, and start with the Amphibious promotion.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BONUS_AGAINST_TECH', '+50% [ICON_GREAT_PEOPLE] Great People rate from each Alliance, and +20% [ICON_STRENGTH] Combat vs civilizations with more cities.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_BUFFALO_HORNS', 'Melee and vanguard units cost 25% less maintenance. All units require 25% less experience to earn their next promotion.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CARNIVAL', '[ICON_GREAT_PERSON] 200% cultural great person rate during golden ages', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CAPITAL_BUILDINGS_CHEAPER', '25% [ICON_PRODUCTION] Production towards buildings that already exist in the [ICON_CAPITAL] Capital. Starts with [ICON_RES_IRON] Iron in the first 5 cities.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_BONUSES', '25% higher rewards from friendly and allied City-States.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP_SHORT', 'Hellenization', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CITY_STATE_FRIENDSHIP', '+2 [ICON_CULTURE] Culture in every city. City-State [ICON_INFLUENCE] Influence degrades at half and recovers at twice the normal rate.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_SEA_BARBARIANS', 'Internal trade routes provide 10 [ICON_GOLD] Gold to the destination.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CULTURE_FROM_KILLS', 'Gains [ICON_CULTURE] Culture from killing enemy units.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ENHANCED_CULTURE', '[ICON_GREAT_PEOPLE] Gain a cultural Great Person with each culture building constructed in Paris.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_ENHANCED_GOLDEN_AGES', '+50% [ICON_CULTURE] Culture and +1[ICON_MOVES] Movement during [ICON_GOLDEN_AGE] Golden Ages.[NEWLINE]Starts with a unique Spearman.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FAITH_FROM_NATURE', '+1 [ICON_PEACE] Faith from unimproved Forests and Jungle, and 150% yields from Natural Wonders.[NEWLINE]Starts with a unique Spearman.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_FIGHT_WELL_DAMAGED', 'Damaged units fight at full strength. Fishing Boats and Isles give [ICON_CULTURE] Culture.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GREAT_ANDEAN_ROAD', 'Units move faster on Hills. Roads and railroads cost no maintenance on hills; half cost elsewhere.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_GATEWAY_AFRICA', 'Civilians move faster in desert. Your outgoing trade routes with different civilizations earn more [ICON_GOLD] Gold and [ICON_CULTURE] Culture, and incoming trade routes earn more [ICON_GOLD] for the owner of the route.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_IGNORE_TERRAIN_IN_FOREST', 'Faster movement in Forests and Jungle, which count as roads in friendly territory after researching The Wheel.[NEWLINE]Starts with a unique Swordsman.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_INGENIOUS', 'Great Scientists appear 25% faster, and you receive one at Writing.[NEWLINE]Starts with a Bowman.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD_SHORT', 'Desert Caravans', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LAND_TRADE_GOLD', 'Units move faster in desert, caravans reach farther, and trade routes spread religion faster from your cities.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LONG_COUNT', 'After researching Theology, receive a bonus Great Person at the end of every Maya Long Count calendar cycle (every 394 years).[NEWLINE]Starts with a unique Archer.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_LUXURY_RETENTION', 'Each luxury resource increases [ICON_GOLD] Gold income by 5%.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_WONDER_BUILDER', '+20% [ICON_PRODUCTION] Production towards Wonder construction.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_OCEAN_MOVEMENT', 'Military ships move faster.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_EXTRA_BELIEF', 'Choose one more Belief than normal when you found a Religion.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PHOENICIAN_HERITAGE', 'Ports get a free Harbor, and units may cross mountains. Starts with Sailing, a Trireme, and a Warrior.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY_SHORT', 'Planned Economy', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_PLANNED_ECONOMY', 'Units see farther, civilians move faster, and you gain 1 less [ICON_HAPPINESS_4] National Unhappiness per city.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_POPULATION_GROWTH', 'Food buildings add 1 [ICON_CITIZEN] Population when constructed.[NEWLINE]Starts with a Worker.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RAZE_AND_HORSES', 'Barbarian camps surrender when defeated for double [ICON_GOLD] Gold.[NEWLINE]Starts with unique Chariot.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM_SHORT', 'American Dream', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMERICAN_DREAM', 'Immigrants move here from civilizations with low happiness and high American cultural influence. Your citizens migrate along internal [ICON_FOOD] Food trade routes.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL_SHORT', 'Joseon Dynasty', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SCHOLARS_JADE_HALL', '+1 [ICON_RESEARCH] Science from Farms.[NEWLINE]Starts with a Worker.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_SEVEN_CITIES', 'Double yields from Natural Wonders, plus 100 [ICON_GOLD] when discovered.[NEWLINE]Starts with a Scout, and receives a Caravel at Compass.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES_SHORT', 'Hanseatic League', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_STRATEGIC_RICHES', 'Double quantity from Strategic Resources, and 3 extra votes in the World Congress.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY_SHORT', 'Longships', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_VIKING_FURY', 'Faster and stronger embarkation across water, and melee units pillage faster.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR_SHORT', 'Mongol Terror', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TERROR', 'City-states you can bully surrender in fear as puppets. Mounted and skirmish units move faster and their upkeep is discounted 20%. Starts with a Scout.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE_SHORT', 'Tribute', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_TRIBUTE', 'Internal trade routes provide [ICON_GOLD] Gold to the destination city.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA_SHORT', 'Reconquista', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_RECONQUISTA', 'Conquering cities increases your [ICON_PEACE] Faith.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS_SHORT', 'Scourge of God', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_CONVERTS_LAND_BARBARIANS', 'Barbarian camps surrender when defeated, and land units cost less [ICON_GOLD] maintenance.[NEWLINE]Starts with a unique Chariot.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE_SHORT', 'Amsterdam Bourse', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_TRAIT_AMSTERDAM_BOURSE', '+5% [ICON_GOLD] National Income from each type of Luxury Resource you control or import.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_WITHIN', '[ICON_CITIZEN] A citizen migrated from {1_fromCity} to {2_toCity}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_IN', '[ICON_CITIZEN] An immigrant from the {1_fromEmpire} arrived in {2_toCity}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_MIGRATE_OUT', '[ICON_CITIZEN] A citizen emigrated from {1_fromCity} to {2_toEmpire}.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CITY_CAPTURE_YIELD', 'You gained {1_yield} {2_yieldIcon} {3_yieldName} from capturing {4_city}!', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_', '', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_', '', '', '');
/* Units */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS', 'Imperial-Royal Mountain Troops', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_HELP', 'Modern Era unit that only the Austrians may build. It is more powerful and has added promotions that the regular unit doesn''t.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_STRATEGY', 'This unit has powerful advantages in all cold weather terrain. Fighting in Tundra, Snow, Hills and even Mountains.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_AUSTRIAN_MOUNTAIN_TROOPS_TEXT', 'The Imperial-Royal Mountain Troops (German: Kaiserlich-königlich Gebirgstruppe) were founded in 1906 as part of the Austrian Landwehr, the territorial army of the Cisleithanian half of the Austro-Hungarian Empire.[NEWLINE]Proposed in a memorandum by Conrad von Hötzendorf, in February 1906 the War Ministry in Vienna convened a session on Alpine border security. Field Marshal Tunk, agreed with him and put forward a concept, the fundamentals of which were then carried out.[NEWLINE]The existing state rifle regiments were to be trained as mountain troops and, together with the Landsturm border patrol companies and gendarmerie departments were to form the backbone of a territorial defence force with local knowledge on the border of Tyrol.[NEWLINE][NEWLINE]Battalions and companies were given pack animals and were issued with additional equipment adapted to the requirements of mountain warfare; including skis, ropes, crampons and ice axes. Regiments were reinforced by a mountain machine gun section of four machine guns which, to improve mobility, could be carried by pack animals or in manportable packs at the highest altitudes. The same applied to the take-apart mountain guns. Portable field stoves (Schwarmöfen) and heated tents assisted troops to operate in inhospitable conditions.[NEWLINE]When skiing the two-stick approach had replaced the single-stick method. The Bilgeri binding was a touring binding that could be used with the normal hiking boot. The rifle was replaced by the (shorter) 8mm Mannlicher M 95 carbine.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSLIM_CAVALRY', 'Unique Songhai mounted unit. Mandekalu Cavalry starts with the Siege promotion, unlike the Knight it replaces.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_SAMURAI', 'Powerful Medieval soldier unique to the the Japanese. Samurai can attack twice per turn, and are stronger than the Longswordsmen they replace.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_BABYLON_BOWMAN_HELP', 'Unique Babylonian archer unit. The Bowman is stronger than the Archer it replaces, and move faster in deserts.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_DENMARK_BERSERKER_HELP', 'Soldier of the Medieval era unique to Denmark. The Berserker starts with the Charge promotion, unlike the Longswordsman it replaces.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_PANZER', 'Mobile unit unique to Germany. The Panzer has higher strength, speed, and visibility than the Tank it replaces.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_JAGUAR', 'Early-game soldier unique to the Aztecs. The Jaguar heals damage when it kills an enemy, and fights more effectively in Jungle than the Warrior it replaces.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MINUTEMAN', 'Renaissance Vanguard Unit unique to the Americans. It is stronger than the Arquebusier it replaces, sees farther, and moves faster in rough terrain.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_MUSKETEER', 'One of the first gunpowder units of the game, unique to the French. Musketeers have a combat bonus outside of friendly territory, unlike the Arquebusier it replaces.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_IROQUOIAN_MOHAWKWARRIOR_STRATEGY', 'Soldier unique to the Iroquois. The Mohawk Warrior fights stronger in Forest and Jungle than the Swordsman it replaces.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_OTTOMAN_JANISSARY_STRATEGY', 'Soldier unique to the Ottomans. The Janissary is much stronger on the attack and heals after kills, unlike the Arquebusier it replaces.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_GENERAL_HELP', 'Units within 1 tile [COLOR_POSITIVE_TEXT]Heal 4 Additional HP[ENDCOLOR] per turn.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_MONGOLIA_KESHIK_HELP', 'The unique Mongolian replacement for the Knight moves faster, is ranged, and does not share the Knight''s vulnerabilities to Cities or Pikemen. The Keshik also earns experience more quickly.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LEGION', 'Powerful Roman soldier of the Classical Era with a bonus against Cities. The Legion has higher strength than the Swordsman it replaces, extra defense against ranged attacks, and can build roads at twice the speed of Workers.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA', 'Liburna', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_ROMAN_LIBURNA_TEXT', 'A liburna was a type of small galley used for raiding and patrols, particularly by the Roman navy.[NEWLINE][NEWLINE]In its original form, the liburna had one bench with 25 oars on each side, while in the late Roman Republic, it was equipped with two banks of oars (a bireme), remaining faster, lighter, and more agile than triremes. The liburnian design was adopted by the Romans and became a key part of Ancient Rome''s navy by the 2nd half of the 1st century BC. Liburnians played a key role in the battle of Actium in Greece, which saw the establishment of Augustus as the undisputed ruler of the Roman world.[NEWLINE]Liburnians were different from the battle triremes, quadriremes and quinqueremes not because of rowing but rather because of its specific constructional features.[NEWLINE][NEWLINE]Once the Romans had adopted the liburnian, they proceeded to make a few adaptations to improve the ships’ use within the navy. The benefits gained from the addition of rams and protection from missiles more than made-up for the slight loss of speed. Besides the construction, the ships required that the regular Roman military unit be simplified in order to function more smoothly. Each ship operated as an individual entity, so the more complicated organization normally used was not necessary. Within the navy, there were probably liburnian of several varying sizes, all put to specific tasks such as scouting and patrolling Roman waters against piracy. The Romans made use of the liburnian particularly within the provinces of the empire, where the ships formed the bulk of the fleets.[NEWLINE]Gradually liburnians became a general name for the different types of the Roman ships, attached also to cargo ships in Late Antiquity. Tacitus and Suetonius were using it as a synonym for the battle ship. In inscriptions it was mentioned as the last in class of the battle ships: hexeres, penteres, quadrieres, trieres, liburna.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_ROMAN_LIBURNA_STRATEGY', 'The Liburna is Rome''s first naval unit. It is a Melee unit without a Ranged Combat Strength. The Liburna is useful for clearing barbarian ships out of home waters and for limited exploration.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_ROMAN_LIBURNA', 'Rome used these vessels to control the waters and protect their trade routes.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_UNIT_HELP_INDIAN_WAR_ELEPHANT', 'Powerful mobile unit unique to India. Unlike the Horseman it replaces, the War Elephant is ranged, does not require horses, and has no vulnerability to Spearmen.', '', '');
/* Misc */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE', 'Trade Office', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRADE_OFFICE_PEDIA', '(todo)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_TRIBUTE', 'Ottoman Tribute', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILD_MOAI_HELP', '+2 [ICON_CULTURE] Culture.[NEWLINE]+1 [ICON_CULTURE] Culture per adjacent Moai.[NEWLINE][ICON_LOCKED] Must be next to Coast.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CIV5_IMPROVEMENTS_MOAI_HELP', '+2 [ICON_CULTURE] Culture.[NEWLINE]+1 [ICON_CULTURE] Culture per adjacent Moai.[NEWLINE][ICON_LOCKED] Must be next to Coast.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_POLYNESIAN_SCENARIO_BUILD_MOAI_HELP', '+2 [ICON_CULTURE] Culture.[NEWLINE]+1 [ICON_CULTURE] Culture per adjacent Moai.[NEWLINE][ICON_LOCKED] Must be next to Coast.', '', '');
/*  Amsterdam Bourse */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE', 'Amsterdam Bourse', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_AMSTERDAM_BOURSE_PEDIA', 'The Amsterdam Stock Exchange is considered the oldest in the world. It was established in 1602 by the Dutch East India Company for dealings in its printed stocks and bonds. It was subsequently renamed the Amsterdam Bourse and was the first to formally begin trading in securities.', '', '');
/* Forum */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FORUM', 'Forum', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FORUM_PEDIA', 'Forum to do.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FORUM_STRATEGY', 'The Forum is a source of early production [ICON_PRODUCTION] and [ICON_HAPPINESS_1]happiness. Building these improves your city''s productivity and works well with the bonus to buildings from the Glory of Rome.', '', '');

/*  Jelling Stones */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES', 'Jelling Stones', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JELLING_STONES_PEDIA', 'The Jelling stones are massive carved runestones from the 10th century, found at the town of Jelling in Denmark. The older of the two Jelling stones was raised by King Gorm in memory of his wife Thyra. The larger of the two stones was raised by Harald Bluetooth, King Gorm''s son. Harald constructed the second stone in memory of his parents, celebration of his conquest of Denmark and Norway, and his conversion of the Danes to Christianity. The runic inscriptions on these stones are considered the most well known in Denmark.', '', '');
/*  Jade Hall */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL', 'Jade Hall', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_JADE_HALL_PEDIA', 'King Sejong oversaw the development of the Chiphyonjon, the Jade Hall of Scholars, the professional scholars who helped research social and political questions for the King and government. The Jade Hall would be considered a "think tank" by governments today.', '', '');
/*  Indus Sanitation */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION', 'Indus Sanitation', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_INDUS_SANITATION_PEDIA', 'The Harappan civilization of the Indus River Valley designed the world''s first known urban sanitation systems around 2600 BCE. Individual homes or groups of homes obtained water from wells. Waste water was directed from rooms set aside for bathing to covered drains lining the major streets. The massive walls of Harappan cities were speculated to protect from flooding. These Harappan hydraulic engineering systems were even more efficient than those of many areas of Pakistan and India today, achieving large urban cities with relatively little agriculture development.', '', '');
/* Steam Mill */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL', 'Steam Mill', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_STEAM_MILL_PEDIA', 'A transition began towards machine-based factories in Great Britain''s economy in the 1700s, previously reliant on manual labor and draft animals. These precursors to the Industrial Revolution started with the mechanization of the textile industries. Trade expansion was enabled by the introduction of canals, improved roads, and railways. Wider utilization of water wheels and the introduction of steam power pushed dramatic increases in production capacity. The development of all-metal machine tools in the early 1800s facilitated the construction of increasingly refined  production machines for manufacturing in a wide variety of industries.', '', '');
/* Dojo */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO', 'Dojo', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_DOJO_PEDIA', 'A Japanese dojo (''place of the way'') is a gathering place to conduct training, examinations, and other related encounters for the ''do'' arts. Dojos were initially adjunct to temples. In Japan any physical training facility, including professional wrestling schools, may be called dojo because of its close martial arts roots.', '', '');
/* Folkskola */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA', 'Folkskola', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_FOLKSKOLA_PEDIA', 'In 1842, the Swedish parliament introduced a four-year primary school for children in Sweden, "Folkskola" (people''s school). This was one of the earliest public school systems in the world.[NEWLINE][NEWLINE]Swedish children are required to attend grundskola, compulsory school, from age 7 to 16, where grundskola is a combination of primary and secondary school. After grundskola, many Swedes attend the elective gymnasieskolan, upper secondary school, choosing either a university-preparatory program or a vocational program. Students who choose a vocational program normally terminate their education after gymnasieskolan while students who complete a university-preparatory program normally enroll in higher education at a university or university college. Students who complete a vocational program can enroll in higher education, but may need to take additional courses before being eligible to apply.', '', '');
/* Basilica */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA', 'Basilica', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASILICA_PEDIA', 'The Latin word basilica (derived from Greek Stoa, the tribunal chamber of a king) was originally used to describe a Roman public building located in the forum of a Roman town. By extension, it was applied to Christian buildings of the same form.[NEWLINE][NEWLINE]In the 4th century, once the Imperial authorities had decriminalised Christianity with the 313 Edict of Milan, Christians were prepared to build larger and more handsome edifices for worship than the furtive meeting-places they had been using. Traditional architectural formulas for temples were unsuitable because of associations with non-Christian beliefs. Old temple ceremonies occurred outdoors under the open sky in the sight of the gods, with the temple as a backdrop. The model Constantine wanted to memorialise for his imperial piety was the architecture of (previously secular) basilicas, holding ceremonies indoors.', '', '');
/* Cothon */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON', 'Cothon', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_COTHON_PEDIA', 'A cothon (Greek: "drinking vessel") is an artificial, protected inner harbor common in Carthage during the Punic Wars c.200 BCE.[NEWLINE]Cothons were generally found in the Phoenician world. Examples include Motya (Sicily) from the 6th century BC, which performed an uncertain purpose, (measuring 35 metres x 51 metres), although it has been suggested this cothon might even have been closable and drainable to form a dry dock.  Mahdia (Tunisia) from the 7th century BC, (which measured 72 metres x 56 metres) and one from Kition in Cyprus.', '', '');
/* Vedi */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI', 'Vedi', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_VEDI_PEDIA', 'Vedi is the term for “alter” in the Vedic religion, the oldest religion still practiced in modern times. Such altars are an elevated enclosure, generally strewed with Kusha grass, and having receptacles for the sacrificial fire.', '', '');
/* NASA Center */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER', 'NASA Center', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_HELP', 'The NASA Center is Modern Era research center that grants increases in technology. It also provides a resource free Spaceship Factory.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_NASA_CENTER_PEDIA', 'Since its inception in 1958, NASA has accomplished many great scientific and technological feats in air and space. NASA technology also has been adapted for many nonaerospace uses by the private sector. NASA remains a leading force in scientific research and in stimulating public interest in aerospace exploration, as well as science and technology in general. Perhaps more importantly, our exploration of space has taught us to view Earth, ourselves, and the universe in a new way. While the tremendous technical and scientific accomplishments of NASA demonstrate vividly that humans can achieve previously inconceivable feats, we also are humbled by the realization that Earth is just a tiny "blue marble" in the cosmos.', '', '');
/* Abbey */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY', 'Abbey', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_PEDIA', 'The Abbey has at its heart the practice of worship, with the idea to not get everyone to one service, but to provide opportunities for worship that abbey adherents can participate in regularly, if not weekly. Through its services, the arts flourished as an expression of praise to the ''Creator''. In addition abbeys were self-supporting, engaged in cultivating fields, raising livestock, operating public markets, and giving employment opportunities to the community. The Celtic abbeys became the centers of learning, preservation of sacred and literary manuscripts, and schools of instruction.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ABBEY_STRATEGY', 'The Abbey is the Celtic spiritual and cultural hub of each community. It produces +1 [ICON_FOOD]Food,[ICON_RESEARCH]Science,[ICON_CULTURE]Culture,[ICON_GOLD]Gold and [ICON_PRODUCTION]Production.', '', '');
/* Odeon */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON', 'Odeon', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_PEDIA', 'Odeon ,from the Ancient Greek ᾨδεῖον, Ōideion, literally "singing place", or "building for musical competitions".[NEWLINE]The most magnificent odeon was the Odeon of Herodes Atticus on the southwest cliff of the Acropolis at Athens built in about 160 A.D. by the wealthy sophist and rhetorician Herodes Atticus in memory of his wife. It had accommodation for 8000 persons, and the ceiling was constructed of beautifully carved beams of cedar wood, probably with an open space in the centre to admit the light. It was also profusely decorated with pictures and other works of art.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_ODEON_STRATEGY', 'The Odeon is a source of instant [ICON_CULTURE]Culture. Building these helps spread your empire''s boundaries.', '', '');
/* Barbary Port */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT', 'Barbary Port', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BARBARY_PORT_PEDIA', 'The Barbary pirates, sometimes called Barbary corsairs or Ottoman corsairs, were pirates and privateers who operated from North Africa, based primarily in the ports of Tunis, Tripoli and Algiers.[NEWLINE][NEWLINE]This area was known in Europe as the Barbary Coast, a term derived from the name of its Berber inhabitants.[NEWLINE]In addition to seizing ships, they engaged in Razzias, raids on European coastal towns and villages, mainly in Italy, France, Spain, and Portugal, but also in the British Isles, the Netherlands and as far away as Iceland. The main purpose of their attacks was to capture Christian slaves for the Muslim market in North Africa and the Middle East.', '', '');
/* Basin Irrigation */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION', 'Basin Irrigation', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_BUILDING_BASIN_IRRIGATION_PEDIA', 'Ancient Egyptians practiced Basin irrigation using the flooding of the Nile to inundate land plots which had been surrounded by dykes. The flood water was held until the fertile sediment had settled before the surplus was returned to the watercourse.[NEWLINE]There is evidence of the ancient Egyptian pharaoh Amenemhet III in the twelfth dynasty (about 1800 BCE) using the natural lake of the Faiyum Oasis as a reservoir to store surpluses of water for use during the dry seasons, the lake swelled annually from flooding of the Nile.', '', '');






UPDATE LoadedFile SET Value=1, en_US=1 Where Type='Leaders.sql';