/* The sql commands and text below were formulated in the UnitPromotions tab of the Google Spreadsheet 'Cep_Language'.
https://docs.google.com/spreadsheets/d/1ptQRfVsW7UT_8gPexioizS31sM7K_3eBT3tjr4jruTs/edit#gid=410821470
If you make any changes be sure to update the spreadsheet also.*/

/* PROMOTIONS */
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_1_HELP', '[ICON_STRENGTH][ICON_RANGE_STRENGTH] +15% in [COLOR_POSITIVE_TEXT]OPEN[ENDCOLOR] Terrain (NO Hills, Forest or Jungle)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_2_HELP', '[ICON_STRENGTH][ICON_RANGE_STRENGTH] +15% in [COLOR_POSITIVE_TEXT]OPEN[ENDCOLOR] Terrain (NO Hills, Forest or Jungle)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ACCURACY_3_HELP', '[ICON_STRENGTH][ICON_RANGE_STRENGTH] +15% in [COLOR_POSITIVE_TEXT]OPEN[ENDCOLOR] Terrain (NO Hills, Forest or Jungle)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_AMBUSH_1_HELP', '[ICON_STRENGTH] +33% vs [COLOR_POSITIVE_TEXT]Armor[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ARCTIC_POWER', 'Arctic Power', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ARCTIC_POWER_HELP', '[ICON_MOVES] Faster in [COLOR_POSITIVE_TEXT]Snow and Tundra[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_1', 'Bombardment I', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Land[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Sea[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_2', 'Bombardment II', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Land[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Sea[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_3', 'Bombardment III', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_BOMBARDMENT_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Land[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Sea[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_RANGE_HELP', '[ICON_AIR] +6 Range', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_RECON_HELP', '[ICON_AIR] +6 [COLOR_POSITIVE_TEXT]Sight Range[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SIEGE_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_SWEEP_HELP', '[ICON_AIR] Can Air Sweep to clear intercepting Units.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AIR_TARGETING_1_HELP', '[ICON_STRENGTH] +33% vs [COLOR_POSITIVE_TEXT]Naval[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ALLOTMENT', 'Allotment', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ALLOTMENT_HELP', '[ICON_STRENGTH] +10% Strength[NEWLINE][ICON_GOLD] -100% [COLOR_POSITIVE_TEXT]Upgrade Cost[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMPHIBIOUS_HELP', '[ICON_STRENGTH] Full damage attacking across sea or rivers[NEWLINE][ICON_STRENGTH] +100% when [COLOR_POSITIVE_TEXT]Embarked[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMBUSH_1_HELP', '[ICON_STRENGTH] +25% Strength vs [COLOR_POSITIVE_TEXT]Mounted[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Armor[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_AMBUSH_2_HELP', '[ICON_STRENGTH] +25% Strength vs [COLOR_POSITIVE_TEXT]Mounted[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Armor[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR', 'Bonus vs Air (100)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR_HELP', '[ICON_STRENGTH] +100% vs [COLOR_POSITIVE_TEXT]Air[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_AIR_II_HELP', '[ICON_RANGE_STRENGTH] +150% vs [COLOR_POSITIVE_TEXT]Bombers and Helicopters[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_CAVALRY', 'Bonus vs Dragoons (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_CAVALRY_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Dragoons[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_FIGHTER', 'Bonus vs Fighters (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_HELICOPTER', 'Bonus vs Helicopters (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_HELICOPTER_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Helicopters[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_I', 'Bonus vs Mounted (10)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_I_HELP', '[ICON_STRENGTH] +10% vs melee [COLOR_POSITIVE_TEXT]Mounted[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_II', 'Bonus vs Mounted (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_MOUNTED_II_HELP', '[ICON_STRENGTH] +50% vs melee [COLOR_POSITIVE_TEXT]Mounted[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I', 'Attack vs Submarines (25)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_SUBMARINE_I_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT]Attack[ENDCOLOR] vs [COLOR_POSITIVE_TEXT]Submarines[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_TANK', 'Bonus vs Tanks (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ANTI_TANK_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Tanks[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ASTRONOMY', 'Astronomy', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ASTRONOMY_HELP', '[ICON_MOVES] Can traverse [COLOR_POSITIVE_TEXT]Ice[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_I', 'Bonus on Attack (25)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_I_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT]Attack[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_II', 'Bonus on Attack (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ATTACK_BONUS_II_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT]Attack[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_1_HELP', '[ICON_STRENGTH][ICON_RANGE_STRENGTH] +15% in [COLOR_POSITIVE_TEXT]ROUGH[ENDCOLOR] Terrain (Hills, Forest or Jungle)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_2_HELP', '[ICON_STRENGTH][ICON_RANGE_STRENGTH] +15% in [COLOR_POSITIVE_TEXT]ROUGH[ENDCOLOR] Terrain (Hills, Forest or Jungle)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BARRAGE_3_HELP', '[ICON_STRENGTH][ICON_RANGE_STRENGTH] +15% in [COLOR_POSITIVE_TEXT]ROUGH[ENDCOLOR] Terrain (Hills, Forest or Jungle)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BLITZ_HELP', '[ICON_WAR] Can attack twice', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Ships[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Ships[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOARDING_PARTY_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Ships[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Land[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Land[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_BOMBARDMENT_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Land[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAMARADERIE', 'Camaraderie', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAMARADERIE_HELP', '[ICON_STRENGTH] +15% when [COLOR_POSITIVE_TEXT]Adjacent[ENDCOLOR] to a friendly unit', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAN_MOVE_AFTER_ATTACKING_HELP', '[ICON_MOVES] Attacks use [COLOR_POSITIVE_TEXT]1 Move[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAN_MOVE_IMPASSABLE_HELP', '[ICON_MOVES] Can move through [COLOR_POSITIVE_TEXT]Ice[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAPITAL_SHIP_BONUS', 'Bonus vs Capital Ships (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CAPITAL_SHIP_BONUS_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Battleships[ENDCOLOR][NEWLINE][ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Missile Cruisers[ENDCOLOR][NEWLINE][ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Carriers[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_I_HELP', '[ICON_AIR] Can Carry [COLOR_POSITIVE_TEXT]1[ENDCOLOR] Cargo', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_II_HELP', '[ICON_AIR] Can Carry [COLOR_POSITIVE_TEXT]2[ENDCOLOR] Cargo', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_III_HELP', '[ICON_AIR] Can Carry [COLOR_POSITIVE_TEXT]3[ENDCOLOR] Cargo', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CARGO_IV_HELP', '[ICON_AIR] Can Carry [COLOR_POSITIVE_TEXT]4[ENDCOLOR] Cargo', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CHARGE_HELP', '[ICON_MOVES] +1 Movement[NEWLINE][ICON_STRENGTH] +20% vs [COLOR_POSITIVE_TEXT]Wounded[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ASSUALT_HELP', '[ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT]Fortified[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ATTACK_II', 'Attack vs Cities (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_ATTACK_II_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT]Attack[ENDCOLOR] vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_II', 'Bonus vs Cities (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_II_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_III', 'Bonus vs Cities (200)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_BONUS_III_HELP', '[ICON_STRENGTH] +200% vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_SIEGE', 'Bonus vs Cities (25)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_CITY_SIEGE_HELP', '[ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_1', 'Merchant Raider I', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_1_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Port Cities[ENDCOLOR][NEWLINE][ICON_GOLD]Steal gold equal to 33% of damage dealt to ports', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_2', 'Merchant Raider II', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_2_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Port Cities[ENDCOLOR][NEWLINE][ICON_GOLD]Steal gold equal to 33% of damage dealt to ports', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_3', 'Merchant Raider III', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COASTAL_RAIDER_3_HELP', '[ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Port Cities[ENDCOLOR][NEWLINE][ICON_GOLD]Steal gold equal to 34% of damage dealt to ports', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_1_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT]Defense[ENDCOLOR] vs [COLOR_POSITIVE_TEXT]Ranged Attacks[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_2_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT]Defense[ENDCOLOR] vs [COLOR_POSITIVE_TEXT]Ranged Attacks[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY', 'Penalty vs Ranged (10)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY_HELP', '[ICON_STRENGTH] -10% [COLOR_NEGATIVE_TEXT]Defense[ENDCOLOR] against all [COLOR_NEGATIVE_TEXT]Ranged Attacks[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_COVER_PENALTY_PEDIA', '-10% vs [COLOR_NEGATIVE_TEXT]Ranged[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFEND_NEAR_CAPITAL_HELP', '[ICON_STRENGTH] +30% in the [COLOR_POSITIVE_TEXT]Capital[ENDCOLOR]; bonus falls off as the unit gets further away', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_50', 'Penalty on Defense (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_50_HELP', '[ICON_STRENGTH] -50% [COLOR_NEGATIVE_TEXT]Defense[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSIVE_EMBARKATION_HELP', '[ICON_MOVES] Can embark onto [COLOR_POSITIVE_TEXT]Water Tiles[ENDCOLOR][NEWLINE][ICON_STRENGTH] +100% while [COLOR_POSITIVE_TEXT]Embarked[ENDCOLOR].', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_1', 'Bonus on Defense (25)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_1_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT]Defense[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_2', 'Bonus on Defense (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_2_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT]Defense[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY', 'Penalty on Defense (25)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DEFENSE_PENALTY_HELP', '[ICON_STRENGTH] -25% [COLOR_NEGATIVE_TEXT]Defense[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DESERT_POWER', 'Desert Power', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DESERT_POWER_HELP', '[ICON_MOVES] Faster in [COLOR_POSITIVE_TEXT]Deserts[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DISCIPLINE_HELP', '[ICON_STRENGTH] +15% when [COLOR_POSITIVE_TEXT]adjacent[ENDCOLOR] to a friendly Unit', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_1_HELP', '[ICON_RANGE_STRENGTH] +33% [COLOR_POSITIVE_TEXT]Air Sweeps[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_2_HELP', '[ICON_RANGE_STRENGTH] +33% [COLOR_POSITIVE_TEXT]Air Sweeps[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DOGFIGHTING_3_HELP', '[ICON_RANGE_STRENGTH] +34% [COLOR_POSITIVE_TEXT]Air Sweeps[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CONSTRUCT_ROADS_FORTS_HELP', '[ICON_WORKER] Can build roads and forts.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_CONSTRUCT_ROADS_FORTS', 'Can build roads and forts', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_1_HELP', '[ICON_STRENGTH][ICON_RANGE_STRENGTH] +15% in [COLOR_POSITIVE_TEXT]ROUGH[ENDCOLOR] Terrain (Hills, Forest or Jungle)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_2_HELP', '[ICON_STRENGTH][ICON_RANGE_STRENGTH] +15% in [COLOR_POSITIVE_TEXT]ROUGH[ENDCOLOR] Terrain (Hills, Forest or Jungle)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_DRILL_3_HELP', '[ICON_STRENGTH][ICON_RANGE_STRENGTH] +15% in [COLOR_POSITIVE_TEXT]ROUGH[ENDCOLOR] Terrain (Hills, Forest or Jungle)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKATION_HELP', '[ICON_MOVES] Can embark onto [COLOR_POSITIVE_TEXT]Water Tiles[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_DEFENSE', 'Embarked Defense (100)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_DEFENSE_HELP', '[ICON_STRENGTH] +100% when [COLOR_POSITIVE_TEXT]Embarked[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EMBARKED_SIGHT_HELP', '[ICON_DETECT] +1 Sight Range when [COLOR_POSITIVE_TEXT]Embarked[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EVASION_I_HELP', '[ICON_AIR] 50% chance to [COLOR_POSITIVE_TEXT]Evade[ENDCOLOR] interception', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_EVASION_II_HELP', '[ICON_AIR] 100% chance to [COLOR_POSITIVE_TEXT]Evade[ENDCOLOR] interception', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FAST_ADMIRAL_HELP', '[ICON_MOVES] +2 [COLOR_POSITIVE_TEXT]Movement[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FAST_GENERAL_HELP', '[ICON_MOVES] +2 [COLOR_POSITIVE_TEXT]Movement[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FEARED_ELEPHANT_HELP', '[ICON_STRENGTH] -10% for [COLOR_POSITIVE_TEXT]adjacent enemy units[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FIRST_STRIKE', 'First Strike', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FIRST_STRIKE_HELP', '[ICON_WAR] 1 [COLOR_POSITIVE_TEXT]free attack[ENDCOLOR] before combat', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FLANK_ATTACK_BONUS_HELP', '[ICON_STRENGTH] +50% when [COLOR_POSITIVE_TEXT]Flanking[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FLAT_MOVEMENT_COST_HELP', '[ICON_MOVES] All movement uses [COLOR_PLAYER_ORANGE_TEXT]1 Move[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FOREIGN_LANDS', 'Foreign Lands Bonus (20)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_1', 'Formation', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_1_HELP', '[ICON_STRENGTH] +35% vs [COLOR_POSITIVE_TEXT]Mounted[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Armored[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FORMATION_2_HELP', '[ICON_STRENGTH] +33% vs [COLOR_POSITIVE_TEXT]Mounted[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREE_UPGRADES', 'Free Upgrades', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_FREE_UPGRADES_HELP', 'Free Upgrades', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GAIN_EXPERIENCE_HELP', '[ICON_WAR] Earns experience 50% faster', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GENERAL_STACKING_HELP', '[ICON_STRENGTH] +15% with [COLOR_POSITIVE_TEXT]Great General[ENDCOLOR] in same tile', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GOLDEN', 'Golden', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GOLDEN_HELP', '[ICON_GOLDEN_AGE] Golden Age points from combat', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GREAT_ADMIRAL_HELP', '[ICON_STRENGTH] Improves combat effectiveness of nearby [COLOR_POSITIVE_TEXT]Ships[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_GREAT_GENERAL_HELP', '[ICON_STRENGTH] Improves combat effectiveness of nearby [COLOR_POSITIVE_TEXT]Land Units[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP', 'AI Handicap', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_1', 'AI Handicap I', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_1_HELP', '[ICON_DETECT] +1 Visibility[NEWLINE][ICON_WAR] +10% Experience[NEWLINE][ICON_STRENGTH] +10% vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_2', 'AI Handicap II', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_2_HELP', '[ICON_DETECT] +2 Visibility[NEWLINE][ICON_WAR] +25% Experience[NEWLINE][ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HANDICAP_HELP', '[ICON_DETECT] +2 Visibility[NEWLINE][ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HEAL_IF_DESTROY_ENEMY_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT]Heals 50 Damage[ENDCOLOR] when kills a Non-Barbarian unit', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HEAL_INSTANTLY_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT]Heal this Unit[ENDCOLOR] 50 HP Doing so will [COLOR_POSITIVE_TEXT]Consume this Opportunity[ENDCOLOR] to choose a Promotion', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HILL_FIGHTER', 'Hill Fighter', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HILL_FIGHTER_HELP', '[ICON_MOVES] Faster in [COLOR_POSITIVE_TEXT]Hills[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HIMEJI_CASTLE_HELP', '[ICON_STRENGTH] +15% in [COLOR_POSITIVE_TEXT]Friendly Territory[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HOVERING_UNIT', 'All Terrain', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_HOVERING_UNIT_HELP', '[ICON_MOVES] Can traverse [COLOR_POSITIVE_TEXT]Mountains[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_IGNORE_TERRAIN_COST_HELP', '[ICON_MOVES] Ignores Terrain Costs', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INDIRECT_FIRE_HELP', '[ICON_RANGE_STRENGTH] Can attack [COLOR_POSITIVE_TEXT]over obstacles[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_1_HELP', '[ICON_RANGE_STRENGTH] +33% stronger [COLOR_POSITIVE_TEXT]Interceptions[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_2_HELP', '[ICON_RANGE_STRENGTH] +33% stronger [COLOR_POSITIVE_TEXT]Interceptions[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_3_HELP', '[ICON_RANGE_STRENGTH] +34% stronger [COLOR_POSITIVE_TEXT]Interceptions[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_I_HELP', '[ICON_AIR] 20% chance to [COLOR_POSITIVE_TEXT]Intercept[ENDCOLOR] aircraft', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_II_HELP', '[ICON_AIR] 40% chance to [COLOR_POSITIVE_TEXT]Intercept[ENDCOLOR] aircraft', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_III_HELP', '[ICON_AIR] 50% chance to [COLOR_POSITIVE_TEXT]Intercept[ENDCOLOR] aircraft', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_IV_HELP', '[ICON_AIR] 100% chance to [COLOR_POSITIVE_TEXT]Intercept[ENDCOLOR] aircraft', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION', 'Interception', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INTERCEPTION_HELP', '[ICON_AIR] 100% chance to intercept [COLOR_POSITIVE_TEXT]Air Units[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_INVISIBLE_SUBMARINE_HELP', '[ICON_MOVES] Ignores cultural borders[NEWLINE][ICON_DETECT] Can only be seen by units with Sonar or 1 tile away', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_JAGUAR_HELP', '[ICON_STRENGTH] +33% in [COLOR_POSITIVE_TEXT]Forest/Jungle[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_I', 'Bonus vs Land (25)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_I_HELP', '[ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT]Land[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_II', 'Bonus vs Land (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_BONUS_II_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Land[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_PENALTY_II', 'Penalty vs Land (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_LAND_PENALTY_II_HELP', '[ICON_STRENGTH] -50% vs [COLOR_NEGATIVE_TEXT]Land[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPLY_I_HELP', '[ICON_HEAL] Attacking and moving do not prevent healing', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT]+10 Healing[ENDCOLOR] for units within 1 tile', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MEDIC_II_HELP', '[ICON_HEAL] [COLOR_POSITIVE_TEXT]+5 Healing[ENDCOLOR] per turn for units in adjacent tiles[NEWLINE][ICON_HEAL] [COLOR_POSITIVE_TEXT]+5 Healing[ENDCOLOR] per turn for this unit when [COLOR_POSITIVE_TEXT]Outside of Friendly Territory[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCENARY', 'Mercenary', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MERCENARY_HELP', '[ICON_GOLD] -50% [COLOR_POSITIVE_TEXT]Upgrade Cost[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOBILITY_HELP', '[ICON_MOVES] +1 [COLOR_POSITIVE_TEXT]Movement[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOHAWK_HELP', '[ICON_STRENGTH] +33% in [COLOR_POSITIVE_TEXT]Forest/Jungle[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MORALE_HELP', '[ICON_STRENGTH] +20% Strength', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTAINEER', 'Mountaineer', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTAINEER_HELP', '[ICON_MOVES] Can pass over [COLOR_POSITIVE_TEXT]Mountains[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOUNTED_PENALTY', 'Penalty vs Mounted (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MOVEMENT_TO_GENERAL_HELP', '[ICON_MOVES] [COLOR_POSITIVE_TEXT]Great Generals[ENDCOLOR] move at rate of this unit if they start the turn [COLOR_POSITIVE_TEXT]stacked[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_MUST_SET_UP_HELP', '[ICON_RANGE_STRENGTH] Must Set Up to Ranged Attack', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NATIONALISM_HELP', '[ICON_STRENGTH] +15% [COLOR_POSITIVE_TEXT]Attack[ENDCOLOR] in friendly territory', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NATIONAL_PROTECTION', 'National Protection', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_BONUS_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Ships[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_PENALTY', 'Penalty Attacking Ships (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_1', 'Naval Recon I', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_1_HELP', '[ICON_DETECT] +1 Sight[NEWLINE][ICON_HEAL] Can [COLOR_POSITIVE_TEXT]heal[ENDCOLOR] outside friendly territory', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_2', 'Naval Recon II', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_RECON_2_HELP', '[ICON_MOVES] +1 Movement[NEWLINE][ICON_MOVES] Attempts to [COLOR_POSITIVE_TEXT]withdraw[ENDCOLOR] from melee combat', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_SIEGE', 'Naval Siege', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_SIEGE_HELP', '[ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR][NEWLINE][ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT]Fortified Units[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NAVAL_TRADITION_HELP', '[ICON_MOVES] +1 [COLOR_POSITIVE_TEXT]Movement[ENDCOLOR][NEWLINE][ICON_DETECT]+1 [COLOR_POSITIVE_TEXT]Sight Range[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NEW_UNIT', 'New Unit', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NEW_UNIT_HELP', 'New Unit', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_CAPTURE_HELP', '[ICON_PIRATE] Unable to Capture Cities', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_DEFENSIVE_BONUSES', 'No Defensive Terrain Bonuses', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_NO_DEFENSIVE_BONUSES_HELP', '[ICON_PIRATE] No Defensive Terrain Bonuses', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_ASTRO_HELP', '[ICON_MOVES] Cannot enter deep ocean until Astronomy', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OCEAN_IMPASSABLE_HELP', '[ICON_MOVES] Cannot enter deep ocean', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_OLIGARCHY_HELP', '[ICON_STRENGTH] +33% in [COLOR_POSITIVE_TEXT]Friendly Territory[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ONLY_ATTACKS_CITIES_HELP', '[ICON_PIRATE] Unit may not attack [COLOR_NEGATIVE_TEXT]units[ENDCOLOR], only cities', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_ONLY_DEFENSIVE_HELP', '[ICON_PIRATE] May Not Melee Attack', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PANAMA_CANAL', 'Panama Canal', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PANAMA_CANAL_HELP', '[ICON_MOVES] +1 Movement for Ships', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTHENON', 'Parthenon', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTHENON_HELP', '[ICON_STRENGTH] +10% Strength from Great Generals and Admirals', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARADROP_HELP', '[ICON_MOVES] Can [COLOR_POSITIVE_TEXT]Paradrop[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY', '[ICON_HEAL] Heals 25 Damage If Kills a Unit', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PHALANX', 'Phalanx', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PHALANX_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Mounted[ENDCOLOR] and [COLOR_POSITIVE_TEXT]Soldier[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_PRIZE_SHIPS_HELP', '[ICON_WAR] [COLOR_POSITIVE_TEXT]Captures[ENDCOLOR] defeated enemy [COLOR_POSITIVE_TEXT]Ships[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGE_HELP', '[ICON_RANGE_STRENGTH] +1 [COLOR_POSITIVE_TEXT]Range[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_BLITZ_HELP', '[ICON_WAR] Can [COLOR_POSITIVE_TEXT]attack twice[ENDCOLOR] at 90% [ICON_RANGE_STRENGTH] ranged strength', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_I', 'Defense vs Ranged (25)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_I_HELP', '[ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT]Defense[ENDCOLOR] vs [COLOR_POSITIVE_TEXT]Ranged Damage[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_II', 'Defense vs Ranged (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RANGED_DEFENSE_II_HELP', '[ICON_STRENGTH] +50% [COLOR_POSITIVE_TEXT]Defense[ENDCOLOR] vs [COLOR_POSITIVE_TEXT]Ranged Damage[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_RIVAL_TERRITORY_HELP', '[ICON_MOVES] Can enter [COLOR_POSITIVE_TEXT]Rival Territory[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_1', 'Recon I', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_1_HELP', '[ICON_DETECT] +2 Sight', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_2', 'Recon II', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_2_HELP', '[ICON_MOVES] +1 Movement[NEWLINE][ICON_MOVES] Can use enemy roads', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_3', 'Recon III', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SCOUTING_3_HELP', '[ICON_MOVES] Can paradrop 10 tiles.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_I', 'Bonus vs Sea (25)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_I_HELP', '[ICON_STRENGTH] +25% vs [COLOR_POSITIVE_TEXT]Sea[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_II', 'Bonus vs Sea (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEA_BONUS_II_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Sea[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEE_INVISIBLE_SUBMARINE', 'Sonar', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SEE_INVISIBLE_SUBMARINE_HELP', '[ICON_DETECT] Can see [COLOR_POSITIVE_TEXT]Submarines[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SENTRY_HELP', '[ICON_DETECT] +1 [COLOR_POSITIVE_TEXT]Sight Range[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_1_HELP', '[ICON_STRENGTH][ICON_RANGE_STRENGTH] +15% in [COLOR_POSITIVE_TEXT]OPEN[ENDCOLOR] Terrain (NO Hills, Forest or Jungle)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_2_HELP', '[ICON_STRENGTH][ICON_RANGE_STRENGTH] +15% in [COLOR_POSITIVE_TEXT]OPEN[ENDCOLOR] Terrain (NO Hills, Forest or Jungle)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SHOCK_3_HELP', '[ICON_STRENGTH][ICON_RANGE_STRENGTH] +15% in [COLOR_POSITIVE_TEXT]OPEN[ENDCOLOR] Terrain (NO Hills, Forest or Jungle)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SIEGE_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR][NEWLINE][ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT]Fortified Units[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SIGHT_PENALTY_HELP', '[ICON_MINUS] -1 [COLOR_NEGATIVE_TEXT]Sight Range[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SKIRMISH', 'Skirmish', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SKIRMISH_HELP', '[ICON_MOVES] Attempts to withdraw from melee or embarked combat', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SORTIE_HELP', '[ICON_AIR] +1 extra [COLOR_POSITIVE_TEXT]Interception[ENDCOLOR] may be made per turn', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SPAWN_GENERALS_I_HELP', '[ICON_WAR] Combat Likely To Create [COLOR_POSITIVE_TEXT]Great Generals[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SPAWN_GENERALS_II_HELP', '[ICON_WAR] Combat Very Likely To Create [COLOR_POSITIVE_TEXT]Great Generals[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_STATUE_ZEUS_HELP', '[ICON_STRENGTH] +15% attacking [COLOR_POSITIVE_TEXT]Cities[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_STRONGER_VS_DAMAGED_HELP', '[ICON_STRENGTH] +50% vs [COLOR_POSITIVE_TEXT]Wounded[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPLY_I_HELP', '[ICON_HEAL] May heal [COLOR_POSITIVE_TEXT]Outside Friendly Territory[ENDCOLOR][NEWLINE][ICON_HEAL] [COLOR_POSITIVE_TEXT]+20 Healing[ENDCOLOR] per turn', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_2_HELP', '[ICON_HEAL] +5 [COLOR_POSITIVE_TEXT]healing[ENDCOLOR] outside friendly territory[NEWLINE][ICON_STRENGTH] +25% [COLOR_POSITIVE_TEXT]Defense[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_3_HELP', '[ICON_HEAL] Unit will [COLOR_POSITIVE_TEXT]Heal Every Turn[ENDCOLOR], even if it performs an action[NEWLINE][ICON_MOVES] Unit will attempt to withdraw when faced with a melee attack', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPRESSION', 'Suppression', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SUPPRESSION_HELP', '[ICON_STRENGTH] +35% vs [COLOR_POSITIVE_TEXT]Vanguard[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_1', 'Survivalist', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_SURVIVALISM_1_HELP', '[ICON_HEAL] +20 [COLOR_POSITIVE_TEXT]healing[ENDCOLOR] outside friendly territory[NEWLINE][ICON_MOVES] No Movement Cost to Pillage', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_1_HELP', '[ICON_DETECT] +1 Sight[NEWLINE][ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Naval[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_2_HELP', '[ICON_MOVES] +1 Movement[NEWLINE][ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Naval[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_TARGETING_3_HELP', '[ICON_DETECT] +1 Sight[NEWLINE][ICON_STRENGTH] +15% vs [COLOR_POSITIVE_TEXT]Naval[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_UNWELCOME_EVANGELIST_HELP', 'Can enter rival territory without open borders, but loses 25% of original religious strength for each turn they end on such a tile. Unit is eliminated when religious strength is 0.', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_VOLLEY_HELP', '[ICON_STRENGTH] +30% vs [COLOR_POSITIVE_TEXT]Fortified[ENDCOLOR] units', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WAR_CANOES_HELP', '[ICON_STRENGTH] +100% when [COLOR_POSITIVE_TEXT]Embarked[ENDCOLOR][NEWLINE]+1 [COLOR_POSITIVE_TEXT]Sight Range[ENDCOLOR] when [COLOR_POSITIVE_TEXT]Embarked[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WEAK_RANGED', 'Ground Attack Penalty (50)', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WEAK_RANGED_HELP', '[ICON_RANGE_STRENGTH] -50% attack vs [COLOR_NEGATIVE_TEXT]Ground and Ships[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_WOODSMAN_HELP', '[ICON_MOVES] Faster in [COLOR_POSITIVE_TEXT]Forests and Jungle[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_MOVES_I_HELP', '[ICON_MOVES] 1 Movement', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_I_HELP', '[ICON_DETECT] 1 [COLOR_POSITIVE_TEXT]Sight Range[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_II_HELP', '[ICON_DETECT] 2 [COLOR_POSITIVE_TEXT]Sight Range[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_III_HELP', '[ICON_DETECT] 3 [COLOR_POSITIVE_TEXT]Sight Range[ENDCOLOR]', '', '');
REPLACE INTO Language_en_US (Tag, Text, Gender, Plurality) VALUES ('TXT_KEY_PROMOTION_XTRA_SIGHT_IV_HELP', '[ICON_DETECT] 4 [COLOR_POSITIVE_TEXT]Sight Range[ENDCOLOR]', '', '');





UPDATE LoadedFile SET Value=1, en_US=1 Where Type='Promotions.sql';

