UPDATE CustomModOptions SET Value = 1 WHERE Name = 'SQUADS';

INSERT INTO InterfaceModes("Type", "Description", "CursorType")
VALUES
    ("INTERFACEMODE_SQUAD_UNIT_MANAGEMENT", "TXT_KEY_INTERFACEMODE_SQUAD_UNIT_MANAGEMENT", "CURSOR_DEFAULT"),
    ("INTERFACEMODE_SQUAD_BASE_MANAGEMENT", "INTERFACEMODE_SQUAD_BASE_MANAGEMENT", "CURSOR_DEFAULT"),
    ("INTERFACEMODE_SQUAD_MOVEMENT", "TXT_KEY_INTERFACEMODE_SQUAD_MOVEMENT", "CURSOR_GO_TO");

