-----------------------------------------------------------------------------------------------
-- Maritime: Food on capital tile and other city tiles x100 
-----------------------------------------------------------------------------------------------
INSERT INTO MinorCivilizationTraits_FriendCityYieldBonuses
    (MinorCivTraitType, EraType, YieldType, Yield, CapitalOnly)
VALUES
    ('MINOR_TRAIT_MARITIME', 'ERA_ANCIENT', 'YIELD_FOOD', 200, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_CLASSICAL', 'YIELD_FOOD', 300, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_MEDIEVAL', 'YIELD_FOOD', 500, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_RENAISSANCE', 'YIELD_FOOD', 600, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_INDUSTRIAL', 'YIELD_FOOD', 800, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_MODERN', 'YIELD_FOOD', 900, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_POSTMODERN', 'YIELD_FOOD', 1100, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_FUTURE', 'YIELD_FOOD', 1200, 1),
  
    --('MINOR_TRAIT_MARITIME', 'ERA_ANCIENT', 'YIELD_FOOD', 0, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_CLASSICAL', 'YIELD_FOOD', 100, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_MEDIEVAL', 'YIELD_FOOD', 100, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_RENAISSANCE', 'YIELD_FOOD', 200, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_INDUSTRIAL', 'YIELD_FOOD', 200, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_MODERN', 'YIELD_FOOD', 300, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_POSTMODERN', 'YIELD_FOOD', 300, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_FUTURE', 'YIELD_FOOD', 400, 0);

INSERT INTO MinorCivilizationTraits_AllyCityYieldBonuses
    (MinorCivTraitType, EraType, YieldType, Yield, CapitalOnly)
VALUES
    ('MINOR_TRAIT_MARITIME', 'ERA_ANCIENT', 'YIELD_FOOD', 300, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_CLASSICAL', 'YIELD_FOOD', 600, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_MEDIEVAL', 'YIELD_FOOD', 900, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_RENAISSANCE', 'YIELD_FOOD', 1200, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_INDUSTRIAL', 'YIELD_FOOD', 1500, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_MODERN', 'YIELD_FOOD', 1800, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_POSTMODERN', 'YIELD_FOOD', 2100, 1),
    ('MINOR_TRAIT_MARITIME', 'ERA_FUTURE', 'YIELD_FOOD', 2400, 1),
  
    ('MINOR_TRAIT_MARITIME', 'ERA_ANCIENT', 'YIELD_FOOD', 100, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_CLASSICAL', 'YIELD_FOOD', 200, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_MEDIEVAL', 'YIELD_FOOD', 300, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_RENAISSANCE', 'YIELD_FOOD', 400, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_INDUSTRIAL', 'YIELD_FOOD', 500, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_MODERN', 'YIELD_FOOD', 600, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_POSTMODERN', 'YIELD_FOOD', 700, 0),
    ('MINOR_TRAIT_MARITIME', 'ERA_FUTURE', 'YIELD_FOOD', 800, 0);

-----------------------------------------------------------------------------------------------
-- Merchantile: Gold on empire
-- Note also gives Happiness (and CS-only Luxury on Ally)
-----------------------------------------------------------------------------------------------
INSERT INTO MinorCivilizationTraits_FriendYieldBonuses
    (MinorCivTraitType, EraType, YieldType, Yield)
VALUES
    ('MINOR_TRAIT_MERCANTILE', 'ERA_ANCIENT', 'YIELD_GOLD', 200),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_CLASSICAL', 'YIELD_GOLD', 400),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_MEDIEVAL', 'YIELD_GOLD', 800),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_RENAISSANCE', 'YIELD_GOLD', 1200),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_INDUSTRIAL', 'YIELD_GOLD', 1600),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_MODERN', 'YIELD_GOLD', 2000),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_POSTMODERN', 'YIELD_GOLD', 2400),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_FUTURE', 'YIELD_GOLD', 2800);

INSERT INTO MinorCivilizationTraits_AllyYieldBonuses
    (MinorCivTraitType, EraType, YieldType, Yield)
VALUES
    ('MINOR_TRAIT_MERCANTILE', 'ERA_ANCIENT', 'YIELD_GOLD', 400),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_CLASSICAL', 'YIELD_GOLD', 800),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_MEDIEVAL', 'YIELD_GOLD', 1600),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_RENAISSANCE', 'YIELD_GOLD', 2400),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_INDUSTRIAL', 'YIELD_GOLD', 3200),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_MODERN', 'YIELD_GOLD', 4000),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_POSTMODERN', 'YIELD_GOLD', 4800),
    ('MINOR_TRAIT_MERCANTILE', 'ERA_FUTURE', 'YIELD_GOLD', 5600);

-----------------------------------------------------------------------------------------------
-- Militaristic: Science on empire
-- Note also gives Unit Spawn
-----------------------------------------------------------------------------------------------
INSERT INTO MinorCivilizationTraits_FriendYieldBonuses
    (MinorCivTraitType, EraType, YieldType, Yield)
VALUES
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_ANCIENT', 'YIELD_SCIENCE', 100),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_CLASSICAL', 'YIELD_SCIENCE', 100),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_MEDIEVAL', 'YIELD_SCIENCE', 200),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_RENAISSANCE', 'YIELD_SCIENCE', 300),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_INDUSTRIAL', 'YIELD_SCIENCE', 400),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_MODERN', 'YIELD_SCIENCE', 500),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_POSTMODERN', 'YIELD_SCIENCE', 600),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_FUTURE', 'YIELD_SCIENCE', 700);

INSERT INTO MinorCivilizationTraits_AllyYieldBonuses
    (MinorCivTraitType, EraType, YieldType, Yield)
VALUES
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_ANCIENT', 'YIELD_SCIENCE', 200),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_CLASSICAL', 'YIELD_SCIENCE', 300),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_MEDIEVAL', 'YIELD_SCIENCE', 600),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_RENAISSANCE', 'YIELD_SCIENCE', 900),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_INDUSTRIAL', 'YIELD_SCIENCE', 1200),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_MODERN', 'YIELD_SCIENCE', 1500),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_POSTMODERN', 'YIELD_SCIENCE', 1800),
    ('MINOR_TRAIT_MILITARISTIC', 'ERA_FUTURE', 'YIELD_SCIENCE', 2100);

-----------------------------------------------------------------------------------------------
-- Cultured: Culture on empire
-----------------------------------------------------------------------------------------------
INSERT INTO MinorCivilizationTraits_FriendYieldBonuses
    (MinorCivTraitType, EraType, YieldType, Yield)
VALUES
    ('MINOR_TRAIT_CULTURED', 'ERA_ANCIENT', 'YIELD_CULTURE', 100),
    ('MINOR_TRAIT_CULTURED', 'ERA_CLASSICAL', 'YIELD_CULTURE', 300),
    ('MINOR_TRAIT_CULTURED', 'ERA_MEDIEVAL', 'YIELD_CULTURE', 600),
    ('MINOR_TRAIT_CULTURED', 'ERA_RENAISSANCE', 'YIELD_CULTURE', 900),
    ('MINOR_TRAIT_CULTURED', 'ERA_INDUSTRIAL', 'YIELD_CULTURE', 1200),
    ('MINOR_TRAIT_CULTURED', 'ERA_MODERN', 'YIELD_CULTURE', 1500),
    ('MINOR_TRAIT_CULTURED', 'ERA_POSTMODERN', 'YIELD_CULTURE', 1800),
    ('MINOR_TRAIT_CULTURED', 'ERA_FUTURE', 'YIELD_CULTURE', 2100);

INSERT INTO MinorCivilizationTraits_AllyYieldBonuses
    (MinorCivTraitType, EraType, YieldType, Yield)
VALUES
    ('MINOR_TRAIT_CULTURED', 'ERA_ANCIENT', 'YIELD_CULTURE', 300),
    ('MINOR_TRAIT_CULTURED', 'ERA_CLASSICAL', 'YIELD_CULTURE', 600),
    ('MINOR_TRAIT_CULTURED', 'ERA_MEDIEVAL', 'YIELD_CULTURE', 1200),
    ('MINOR_TRAIT_CULTURED', 'ERA_RENAISSANCE', 'YIELD_CULTURE', 1800),
    ('MINOR_TRAIT_CULTURED', 'ERA_INDUSTRIAL', 'YIELD_CULTURE', 2400),
    ('MINOR_TRAIT_CULTURED', 'ERA_MODERN', 'YIELD_CULTURE', 3000),
    ('MINOR_TRAIT_CULTURED', 'ERA_POSTMODERN', 'YIELD_CULTURE', 3600),
    ('MINOR_TRAIT_CULTURED', 'ERA_FUTURE', 'YIELD_CULTURE', 4200);

-----------------------------------------------------------------------------------------------
-- Religious: Faith on empire
-- Different yields per era up to Industrial
-----------------------------------------------------------------------------------------------
INSERT INTO MinorCivilizationTraits_FriendYieldBonuses
    (MinorCivTraitType, EraType, YieldType, Yield)
VALUES
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_ANCIENT', 'YIELD_FAITH', 100),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_CLASSICAL', 'YIELD_FAITH', 300),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_MEDIEVAL', 'YIELD_FAITH', 600),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_RENAISSANCE', 'YIELD_FAITH', 900),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_INDUSTRIAL', 'YIELD_FAITH', 1200),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_MODERN', 'YIELD_FAITH', 1500),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_POSTMODERN', 'YIELD_FAITH', 1800),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_FUTURE', 'YIELD_FAITH', 2100);

INSERT INTO MinorCivilizationTraits_AllyYieldBonuses
    (MinorCivTraitType, EraType, YieldType, Yield)
VALUES
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_ANCIENT', 'YIELD_FAITH', 300),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_CLASSICAL', 'YIELD_FAITH', 600),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_MEDIEVAL', 'YIELD_FAITH', 1200),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_RENAISSANCE', 'YIELD_FAITH', 1800),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_INDUSTRIAL', 'YIELD_FAITH', 2400),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_MODERN', 'YIELD_FAITH', 3000),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_POSTMODERN', 'YIELD_FAITH', 3600),
    ('MINOR_TRAIT_RELIGIOUS', 'ERA_FUTURE', 'YIELD_FAITH', 4200);
