-- Make Kabul's City-State color match the other City-States that are from major civs
UPDATE MinorCivilizations SET DefaultPlayerColor = 'PLAYERCOLOR_MINOR_PERSIA' WHERE Type = 'MINOR_CIV_KABUL';

-- Fix lazy Firaxis overwrite of Civilopedia text keys
UPDATE MinorCivilizations SET Civilopedia = 'TXT_KEY_CIV5_KATHMANDU_TEXT' WHERE Type = 'MINOR_CIV_KATHMANDU';
UPDATE MinorCivilizations SET Civilopedia = 'TXT_KEY_CIV5_QUEBEC_CITY_TEXT' WHERE Type = 'MINOR_CIV_QUEBEC_CITY';
UPDATE MinorCivilizations SET Civilopedia = 'TXT_KEY_CIV5_SYDNEY_TEXT' WHERE Type = 'MINOR_CIV_SYDNEY';

-- Add the capital city name entry for all new City-States
INSERT INTO MinorCivilization_CityNames
	(MinorCivType, CityName)
SELECT a.Type, a.Description
FROM MinorCivilizations a
LEFT JOIN MinorCivilization_CityNames b ON a.Type = b.MinorCivType WHERE b.MinorCivType IS NULL;

-- Block the newly-added City-States from appearing ingame if their associated civilization is present
INSERT INTO MajorBlocksMinor
	(MinorCiv, MajorCiv)
VALUES
	-- Reactivated base game City-States
	('MINOR_CIV_COPENHAGEN', 'CIVILIZATION_DENMARK'),
	('MINOR_CIV_DUBLIN', 'CIVILIZATION_CELTS'),
	('MINOR_CIV_EDINBURGH', 'CIVILIZATION_CELTS'),
	('MINOR_CIV_HELSINKI', 'CIVILIZATION_SWEDEN'),
	('MINOR_CIV_JAKARTA', 'CIVILIZATION_INDONESIA'),
	('MINOR_CIV_LISBON', 'CIVILIZATION_PORTUGAL'),
	('MINOR_CIV_MARRAKECH', 'CIVILIZATION_MOROCCO'),
	('MINOR_CIV_OSLO', 'CIVILIZATION_DENMARK'),
	('MINOR_CIV_RIO_DE_JANEIRO', 'CIVILIZATION_BRAZIL'),
	('MINOR_CIV_SEOUL', 'CIVILIZATION_KOREA'),
	('MINOR_CIV_STOCKHOLM', 'CIVILIZATION_SWEDEN'),
	('MINOR_CIV_VENICE', 'CIVILIZATION_VENICE'),
	('MINOR_CIV_VIENNA', 'CIVILIZATION_AUSTRIA'),
	('MINOR_CIV_WARSAW', 'CIVILIZATION_POLAND'),
	-- Scramble for Africa scenario
	('MINOR_CIV_SEGOU', 'CIVILIZATION_SONGHAI'),
	-- City-States added by VP
	('MINOR_CIV_ABERNETHY', 'CIVILIZATION_CELTS'),
	('MINOR_CIV_AKSUM', 'CIVILIZATION_ETHIOPIA'),
	('MINOR_CIV_ARGOS', 'CIVILIZATION_GREECE'),
	('MINOR_CIV_ASSUR', 'CIVILIZATION_ASSYRIA'),
	('MINOR_CIV_AZTLAN', 'CIVILIZATION_AZTEC'),
	('MINOR_CIV_BAN_CHIANG', 'CIVILIZATION_SIAM'),
	('MINOR_CIV_BRANDENBURG', 'CIVILIZATION_GERMANY'),
	('MINOR_CIV_DJENNE', 'CIVILIZATION_SONGHAI'),
	('MINOR_CIV_DORESTAD', 'CIVILIZATION_NETHERLANDS'),
	('MINOR_CIV_ECBATANA', 'CIVILIZATION_PERSIA'),
	('MINOR_CIV_ENNS', 'CIVILIZATION_AUSTRIA'),
	('MINOR_CIV_ERACLEA', 'CIVILIZATION_VENICE'),
	('MINOR_CIV_HARAPPA', 'CIVILIZATION_INDIA'),
	('MINOR_CIV_HEIDABIR', 'CIVILIZATION_DENMARK'),
	('MINOR_CIV_HOLMUL', 'CIVILIZATION_MAYA'),
	('MINOR_CIV_HUARI', 'CIVILIZATION_INCA'),
	('MINOR_CIV_KWA_BULAWAYO', 'CIVILIZATION_ZULU'),
	('MINOR_CIV_LONGCHENG', 'CIVILIZATION_HUNS'),
	('MINOR_CIV_LUTETIA', 'CIVILIZATION_FRANCE'),
	('MINOR_CIV_MSOURA', 'CIVILIZATION_MOROCCO'),
	('MINOR_CIV_NIPPUR', 'CIVILIZATION_BABYLON'),
	('MINOR_CIV_NOVGOROD', 'CIVILIZATION_RUSSIA'),
	('MINOR_CIV_OKILIS', 'CIVILIZATION_SPAIN'),
	('MINOR_CIV_ONONDAGA', 'CIVILIZATION_IROQUOIS'),
	('MINOR_CIV_OVIEDO', 'CIVILIZATION_SPAIN'),
	('MINOR_CIV_PAGO_PAGO', 'CIVILIZATION_POLYNESIA'),
	('MINOR_CIV_PALATIUM', 'CIVILIZATION_ROME'),
	('MINOR_CIV_PERGE', 'CIVILIZATION_BYZANTIUM'),
	('MINOR_CIV_RAQMU', 'CIVILIZATION_ARABIA'),
	('MINOR_CIV_SALEM', 'CIVILIZATION_AMERICA'),
	('MINOR_CIV_SHANGHAI', 'CIVILIZATION_CHINA'),
	('MINOR_CIV_SHEDET', 'CIVILIZATION_EGYPT'),
	('MINOR_CIV_SIGTUNA', 'CIVILIZATION_SWEDEN'),
	('MINOR_CIV_SOGUT', 'CIVILIZATION_OTTOMAN'),
	('MINOR_CIV_TROWULAN', 'CIVILIZATION_INDONESIA'),
	('MINOR_CIV_UTICA', 'CIVILIZATION_CARTHAGE'),
	('MINOR_CIV_WANGGEOM', 'CIVILIZATION_KOREA'),
	('MINOR_CIV_WINCHESTER', 'CIVILIZATION_ENGLAND'),
	('MINOR_CIV_YAMATAI', 'CIVILIZATION_JAPAN'),
	('MINOR_CIV_ZUUNMOD', 'CIVILIZATION_MONGOL');
