-- For all City-States added to the MajorBlocksMinor table, add a custom color wherein they use their associated major civ's background color instead of the normal CS colors.
-- This is a cool way to highlight that these are special City-States while still keeping it subtle.
CREATE TEMP TABLE NewCityStateColors (
	CityStateColorName text,
	CivBackgroundColor text
);

-- A few civs have a dark background color which needs to be brightened to contrast well against black
-- This is done by taking their original RGB values, converting them to HSV, raising the value to 80%, and then converting back to RGB
INSERT INTO Colors
	(Type, Red, Green, Blue, Alpha)
VALUES
	('COLOR_PLAYER_AMERICA_MINOR_BACKGROUND', 0.2078431373, 0.3411764706, 0.8, 1),		-- RGB = 53/87/204, Original ≈ 31.11/51/120.11
	('COLOR_PLAYER_BABYLON_MINOR_BACKGROUND', 0.3529411765, 0.6627450980, 0.8, 1),		-- RGB = 90/169/204, Original ≈ 43.1/81.09/97.92
	('COLOR_PLAYER_KOREA_MINOR_BACKGROUND', 0.2235294118, 0.2745098039, 0.8, 1),		-- RGB = 57/70/204, Original ≈ 26.98/33/96.01
	('COLOR_PLAYER_PERSIA_MINOR_BACKGROUND', 0.8, 0.0352941176, 0.0156862745, 1),		-- RGB = 204/9/4, Original ≈ 176.97/7.91/3.06
	('COLOR_PLAYER_ROME_MINOR_BACKGROUND', 0.4745098039, 0, 0.8, 1),					-- RGB = 121/0/204, Original ≈ 70.13/0/118.07
	('COLOR_PLAYER_SPAIN_MINOR_BACKGROUND', 0.8, 0.2470588235, 0.2470588235, 1);		-- RGB = 204/63/63, Original ≈ 83.9/26.01/26.01

INSERT INTO NewCityStateColors
	(CityStateColorName, CivBackgroundColor)
VALUES
	('PLAYERCOLOR_MINOR_AMERICA', 'COLOR_PLAYER_AMERICA_MINOR_BACKGROUND'),
	('PLAYERCOLOR_MINOR_ARABIA', 'COLOR_PLAYER_ARABIA_BACKGROUND'),
	('PLAYERCOLOR_MINOR_ASSYRIA', 'COLOR_PLAYER_ASSYRIA_BACKGROUND'),
	('PLAYERCOLOR_MINOR_AUSTRIA', 'COLOR_PLAYER_AUSTRIA_BACKGROUND'),
	('PLAYERCOLOR_MINOR_AZTEC', 'COLOR_PLAYER_AZTEC_BACKGROUND'),
	('PLAYERCOLOR_MINOR_BABYLON', 'COLOR_PLAYER_BABYLON_MINOR_BACKGROUND'),
	('PLAYERCOLOR_MINOR_BRAZIL', 'COLOR_PLAYER_BRAZIL_BACKGROUND'),
	('PLAYERCOLOR_MINOR_BYZANTIUM', 'COLOR_PLAYER_BYZANTIUM_BACKGROUND'),
	('PLAYERCOLOR_MINOR_CARTHAGE', 'COLOR_PLAYER_CARTHAGE_BACKGROUND'),
	('PLAYERCOLOR_MINOR_CELTS', 'COLOR_PLAYER_CELTS_BACKGROUND'),
	('PLAYERCOLOR_MINOR_CHINA', 'COLOR_PLAYER_CHINA_BACKGROUND'),
	('PLAYERCOLOR_MINOR_DENMARK', 'COLOR_PLAYER_DENMARK_BACKGROUND'),
	('PLAYERCOLOR_MINOR_EGYPT', 'COLOR_PLAYER_EGYPT_BACKGROUND'),
	('PLAYERCOLOR_MINOR_ENGLAND', 'COLOR_PLAYER_ENGLAND_BACKGROUND'),
	('PLAYERCOLOR_MINOR_ETHIOPIA', 'COLOR_PLAYER_ETHIOPIA_BACKGROUND'),
	('PLAYERCOLOR_MINOR_FRANCE', 'COLOR_PLAYER_FRANCE_BACKGROUND'),
	('PLAYERCOLOR_MINOR_GERMANY', 'COLOR_PLAYER_GERMANY_BACKGROUND'),
	('PLAYERCOLOR_MINOR_GREECE', 'COLOR_PLAYER_GREECE_BACKGROUND'),
	('PLAYERCOLOR_MINOR_HUNS', 'COLOR_PLAYER_HUNS_BACKGROUND'),
	('PLAYERCOLOR_MINOR_INCA', 'COLOR_PLAYER_INCA_BACKGROUND'),
	('PLAYERCOLOR_MINOR_INDIA', 'COLOR_PLAYER_INDIA_BACKGROUND'),
	('PLAYERCOLOR_MINOR_INDONESIA', 'COLOR_PLAYER_INDONESIA_BACKGROUND'),
	('PLAYERCOLOR_MINOR_IROQUOIS', 'COLOR_PLAYER_IROQUOIS_BACKGROUND'),
	('PLAYERCOLOR_MINOR_JAPAN', 'COLOR_PLAYER_JAPAN_BACKGROUND'),
	('PLAYERCOLOR_MINOR_KOREA', 'COLOR_PLAYER_KOREA_MINOR_BACKGROUND'),
	('PLAYERCOLOR_MINOR_MAYA', 'COLOR_PLAYER_MAYA_BACKGROUND'),
	('PLAYERCOLOR_MINOR_MONGOL', 'COLOR_PLAYER_MONGOL_BACKGROUND'),
	('PLAYERCOLOR_MINOR_MOROCCO', 'COLOR_PLAYER_MOROCCO_BACKGROUND'),
	('PLAYERCOLOR_MINOR_NETHERLANDS', 'COLOR_PLAYER_NETHERLANDS_BACKGROUND'),
	('PLAYERCOLOR_MINOR_OTTOMAN', 'COLOR_PLAYER_OTTOMAN_BACKGROUND'),
	('PLAYERCOLOR_MINOR_PERSIA', 'COLOR_PLAYER_PERSIA_MINOR_BACKGROUND'),
	('PLAYERCOLOR_MINOR_POLAND', 'COLOR_PLAYER_POLAND_BACKGROUND'),
	('PLAYERCOLOR_MINOR_POLYNESIA', 'COLOR_PLAYER_POLYNESIA_BACKGROUND'),
	('PLAYERCOLOR_MINOR_PORTUGAL', 'COLOR_PLAYER_PORTUGAL_BACKGROUND'),
	('PLAYERCOLOR_MINOR_ROME', 'COLOR_PLAYER_ROME_MINOR_BACKGROUND'),
	('PLAYERCOLOR_MINOR_RUSSIA', 'COLOR_PLAYER_RUSSIA_BACKGROUND'),
	--('PLAYERCOLOR_MINOR_SHOSHONE', 'COLOR_PLAYER_SHOSHONE_BACKGROUND'),
	('PLAYERCOLOR_MINOR_SIAM', 'COLOR_PLAYER_SIAM_BACKGROUND'),
	('PLAYERCOLOR_MINOR_SONGHAI', 'COLOR_PLAYER_SONGHAI_BACKGROUND'),
	('PLAYERCOLOR_MINOR_SPAIN', 'COLOR_PLAYER_SPAIN_MINOR_BACKGROUND'),
	('PLAYERCOLOR_MINOR_SWEDEN', 'COLOR_PLAYER_SWEDEN_BACKGROUND'),
	('PLAYERCOLOR_MINOR_VENICE', 'COLOR_PLAYER_VENICE_BACKGROUND'),
	('PLAYERCOLOR_MINOR_ZULU', 'COLOR_PLAYER_ZULU_BACKGROUND');

INSERT INTO PlayerColors
	(Type, PrimaryColor, SecondaryColor, TextColor)
SELECT
	a.CityStateColorName, 'COLOR_PLAYER_MINOR_ICON', a.CivBackgroundColor, 'COLOR_PLAYER_PEACH_TEXT'
FROM NewCityStateColors a;

DROP TABLE NewCityStateColors;