-- Ancient
UPDATE Unit_UniqueNames SET EraType = 'ERA_ANCIENT'
WHERE UniqueName IN (
    'TXT_KEY_GREAT_PERSON_ENHEDUANNA'
);

-- Classical
UPDATE Unit_UniqueNames SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName IN (
    'TXT_KEY_GREAT_PERSON_JI_KANG',
    'TXT_KEY_GREAT_PERSON_MESOMEDES'
);

-- Medieval
UPDATE Unit_UniqueNames SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName IN (
    'TXT_KEY_GREAT_PERSON_ALKINDI',
    'TXT_KEY_GREAT_PERSON_GUIDO_DAREZZO',
    'TXT_KEY_GREAT_PERSON_GUILLAUME_DE_MACHAUT',
    'TXT_KEY_GREAT_PERSON_ZIRYAB'
);

-- Renaissance
UPDATE Unit_UniqueNames SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName IN (
    'TXT_KEY_GREAT_PERSON_CARLO_GESUALDO',
    'TXT_KEY_GREAT_PERSON_FRANZ_JOSEF_HAYDN',
    'TXT_KEY_GREAT_PERSON_GASPAR_FERNANDES',
    'TXT_KEY_GREAT_PERSON_GEORGE_HANDEL',
    'TXT_KEY_GREAT_PERSON_GIOVANNI_GABRIELI',
    'TXT_KEY_GREAT_PERSON_GIOVANNI_PIERLUIGI',
    'TXT_KEY_GREAT_PERSON_GUILLAUME_DUFAY',
    'TXT_KEY_GREAT_PERSON_JACOB_OBRECHT',
    'TXT_KEY_GREAT_PERSON_JOHANNES_OCKEGHEM',
    'TXT_KEY_GREAT_PERSON_JOHANN_SEBASTIAN_BACH',
    'TXT_KEY_GREAT_PERSON_JOSQUIN_DES_PRES',
    'TXT_KEY_GREAT_PERSON_LUDWIG_VON_BEETHOVEN',
    'TXT_KEY_GREAT_PERSON_MEERABAI',
    'TXT_KEY_GREAT_PERSON_NICCOLO_PAGANINI',
    'TXT_KEY_GREAT_PERSON_ORLANDE_DE_LASSUS',
    'TXT_KEY_GREAT_PERSON_THOMAS_TALLIS',
    'TXT_KEY_GREAT_PERSON_WILLIAM_BYRD',
    'TXT_KEY_GREAT_PERSON_WOLFGANG_AMADEUS_MOZART',
    'TXT_KEY_GREAT_PERSON_YAMADA_KENGYO',
    'TXT_KEY_GREAT_PERSON_YATSUHASHI_KENGYO'
);

-- Industrial
UPDATE Unit_UniqueNames SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName IN (
    'TXT_KEY_GREAT_PERSON_EMERICO_LOBO_DE_MESQUITA',
    'TXT_KEY_GREAT_PERSON_ESTABAN_SALAS_Y_CASTRO',
    'TXT_KEY_GREAT_PERSON_FRANCISCO_MANUEL_DA_SILVA',
    'TXT_KEY_GREAT_PERSON_FRANZ_LISZT',
    'TXT_KEY_GREAT_PERSON_FREDERIC_CHOPIN',
    'TXT_KEY_GREAT_PERSON_JOHANN_STRAUSS',
    'TXT_KEY_GREAT_PERSON_MANUEL_SAUMELL'
);

-- Modern
UPDATE Unit_UniqueNames SET EraType = 'ERA_MODERN'
WHERE UniqueName IN (
    'TXT_KEY_GREAT_PERSON_ALBAN_BERG',
    'TXT_KEY_GREAT_PERSON_ANTONIN_DVORAK',
    'TXT_KEY_GREAT_PERSON_CAMILLE_SAINT_SAENS',
    'TXT_KEY_GREAT_PERSON_CHARLES_IVES',
    'TXT_KEY_GREAT_PERSON_CLAUSE_DEBUSSY',
    'TXT_KEY_GREAT_PERSON_ERIK_SATIE',
    'TXT_KEY_GREAT_PERSON_GIUSEPPE_VERDI',
    'TXT_KEY_GREAT_PERSON_GUSTAV_MAHLER',
    'TXT_KEY_GREAT_PERSON_HUGO_WOLF',
    'TXT_KEY_GREAT_PERSON_JOHANNES_BRAHMS',
    'TXT_KEY_GREAT_PERSON_MAURICE_RAVEL',
    'TXT_KEY_GREAT_PERSON_MODEST_MUSSORGSKY',
    'TXT_KEY_GREAT_PERSON_PRINCE_BENBADHANABONGSE',
    'TXT_KEY_GREAT_PERSON_PYOTR_ILYICH_TCHAIKOVSKY',
    'TXT_KEY_GREAT_PERSON_RICHARD_WAGNER',
    'TXT_KEY_GREAT_PERSON_SAYED_DARWISH',
    'TXT_KEY_GREAT_PERSON_SILVESTRE_REVUELTAS',
    'TXT_KEY_GREAT_PERSON_TAIZAN_HIGUCHI'
);

-- Atomic
UPDATE Unit_UniqueNames SET EraType = 'ERA_POSTMODERN'
WHERE UniqueName IN (
    'TXT_KEY_GREAT_PERSON_ALLA_RAKHA',
    'TXT_KEY_GREAT_PERSON_BENJAMIN_BRITTEN',
    'TXT_KEY_GREAT_PERSON_CARLOS_CHAVEZ',
    'TXT_KEY_GREAT_PERSON_DUKE_ELLINGTON',
    'TXT_KEY_GREAT_PERSON_GEORGE_GERSHWIN',
    'TXT_KEY_GREAT_PERSON_GUSTAV_HOLST',
    'TXT_KEY_GREAT_PERSON_HANNA_PETROS',
    'TXT_KEY_GREAT_PERSON_JOHN_CAGE',
    'TXT_KEY_GREAT_PERSON_LOUIS_BALLARD',
    'TXT_KEY_GREAT_PERSON_RICHARD_STRAUSS',
    'TXT_KEY_GREAT_PERSON_SOLOMON_LINDA',
    'TXT_KEY_GREAT_PERSON_ULVI_CEMAL_ERKIN',
    'TXT_KEY_GREAT_PERSON_WASITODININGRAT'
);

-- Information
UPDATE Unit_UniqueNames SET EraType = 'ERA_FUTURE'
WHERE UniqueName IN (
    'TXT_KEY_GREAT_PERSON_CARLOS_NAKAI',
    'TXT_KEY_GREAT_PERSON_CECIL_BUSTAMENTE',
    'TXT_KEY_GREAT_PERSON_DAVID_BLANASI',
    'TXT_KEY_GREAT_PERSON_JOHN_ADAMS',
    'TXT_KEY_GREAT_PERSON_STEVE_REICH'
);
