INSERT INTO Events (Type,EventClass,Description,Help,EventArt,EventAudio,RandomChance,RandomChanceDelta,IsOneShot,IgnoresGlobalCooldown,Global,EraScaling,EventCooldown,NumChoices,MinimumNationalPopulation,MinimumNumberCities,RequiredCiv,RequiredEra,ObsoleteEra,IsUnhappy,IsSuperUnhappy,ImprovementAnywhereRequired,MinimumNumCoastalCities,LessThanMaximumTradeRoutes,RequiredPolicy,RequiredIdeology,RequiresWar,RequiresWarMinor,UnitClassRequired,PrereqTech,ObsoleteTech,RequiresPantheon,RequiredReligion,RequiredStateReligion,RequiresAnyStateReligion,RequiredAnywhereBuildingClass,RequiredNowhereBuildingClass,RequiresHolyCity,RequiresIdeology,HasMetAMajorCiv,InDebt,LosingMoney,IsVassalOfSomeone,IsMasterOfSomeone) VALUES ('PLAYER_EVENT_BATHS_DECISION','EVENT_CLASS_GOOD','TXT_KEY_PLAYER_EVENT_BATHS_DECISION','TXT_KEY_PLAYER_EVENT_BATHS_DECISION_HELP',NULL,'AS2D_INTERFACE_CITY_TILE',20,1,'true','false','false','false',60,3,20,3,NULL,NULL,'ERA_INDUSTRIAL','false','false',NULL,0,'false',NULL,NULL,'false','false',NULL,NULL,NULL,'false',NULL,NULL,'false','BUILDINGCLASS_BATH',NULL,'false','false','false','false','false','false','false');

INSERT INTO Event_ParentEvents (EventChoiceType,EventType) VALUES ('PLAYER_EVENT_BATHS_DECISION_CHOICE_1','PLAYER_EVENT_BATHS_DECISION'),
 ('PLAYER_EVENT_BATHS_DECISION_CHOICE_2','PLAYER_EVENT_BATHS_DECISION'),
 ('PLAYER_EVENT_BATHS_DECISION_CHOICE_3','PLAYER_EVENT_BATHS_DECISION');

INSERT INTO EventChoices (Type,Description,Help,DisabledTooltip,EventChoiceAudio,IsOneShot,EventDuration,EraScaling,EventChance,Expires,MinimumNationalPopulation,MinimumNumberCities,MinimumNumCoastalCities,AffectsCoastalCitiesOnly,LessThanMaximumTradeRoutes,RequiredCiv,RequiredEra,ObsoleteEra,IsUnhappy,IsSuperUnhappy,ImprovementAnywhereRequired,RequiredPolicy,RequiredIdeology,RequiresWar,RequiresWarMinor,UnitClassRequired,PrereqTech,ObsoleteTech,RequiresPantheon,RequiredReligion,RequiredStateReligion,RequiresAnyStateReligion,RequiredAnywhereBuildingClass,RequiredNowhereBuildingClass,RequiresHolyCity,RequiresIdeology,CapitalEffectOnly,EventPolicy,EventPromotion,EventTech,EventBuildingClassGlobal,EventFreePolicies,FreeGreatPeople,GoldenAgeTurns,WLTKDTurns,ResistanceTurns,PlayerHappiness,HappinessPerCity,RandomBarbarianSpawn,FreeUnitsTechAppropriate,HasMetAMajorCiv,InDebt,LosingMoney,IsVassalOfSomeone,IsMasterOfSomeone) VALUES ('PLAYER_EVENT_BATHS_DECISION_CHOICE_1','TXT_KEY_PLAYER_EVENT_BATHS_DECISION_CHOICE_1','TXT_KEY_PLAYER_EVENT_BATHS_DECISION_CHOICE_1_HELP',NULL,'AS2D_EVENT_CHOICE','false',-1,'false',0,'false',0,0,0,'false','false',NULL,NULL,NULL,'false','false',NULL,NULL,NULL,'false','false',NULL,NULL,NULL,'false',NULL,NULL,'false',NULL,NULL,'false','false','false',NULL,NULL,NULL,NULL,0,1,0,0,0,0,0,0,0,'false','false','false','false','false'),
 ('PLAYER_EVENT_BATHS_DECISION_CHOICE_2','TXT_KEY_PLAYER_EVENT_BATHS_DECISION_CHOICE_2','TXT_KEY_PLAYER_EVENT_BATHS_DECISION_CHOICE_2_HELP',NULL,'AS2D_EVENT_CHOICE','false',-1,'false',0,'false',0,0,0,'false','false',NULL,NULL,NULL,'false','false',NULL,NULL,NULL,'false','false',NULL,NULL,NULL,'false',NULL,NULL,'false',NULL,NULL,'false','false','false',NULL,NULL,NULL,NULL,0,0,0,0,0,0,1,0,0,'false','false','false','false','false'),
 ('PLAYER_EVENT_BATHS_DECISION_CHOICE_3','TXT_KEY_PLAYER_EVENT_BATHS_DECISION_CHOICE_3','TXT_KEY_PLAYER_EVENT_BATHS_DECISION_CHOICE_3_HELP',NULL,'AS2D_EVENT_CHOICE','false',-1,'false',0,'false',0,0,0,'false','false',NULL,NULL,NULL,'false','false',NULL,NULL,NULL,'false','false',NULL,NULL,NULL,'false',NULL,NULL,'false',NULL,NULL,'false','false','false',NULL,NULL,NULL,NULL,0,0,0,0,0,0,0,0,0,'false','false','false','false','false');

INSERT INTO EventChoice_BuildingClassYieldChange (EventChoiceType,BuildingClassType,YieldType,YieldChange) VALUES ('PLAYER_EVENT_BATHS_DECISION_CHOICE_2','BUILDINGCLASS_BATH','YIELD_GOLD',-3),
 ('PLAYER_EVENT_BATHS_DECISION_CHOICE_3','BUILDINGCLASS_AQUEDUCT','YIELD_CULTURE',1);

INSERT INTO EventChoiceFlavors (EventChoiceType,FlavorType,Flavor) VALUES ('PLAYER_EVENT_BATHS_DECISION_CHOICE_1','FLAVOR_GREAT_PEOPLE',20),
 ('PLAYER_EVENT_BATHS_DECISION_CHOICE_2','FLAVOR_HAPPINESS',20),
 ('PLAYER_EVENT_BATHS_DECISION_CHOICE_3','FLAVOR_CULTURE',20);

INSERT INTO CityEvents (Type,EventClass,Description,Help,CityEventArt,CityEventAudio,RandomChance,RandomChanceDelta,IsOneShot,EraScaling,IgnoresGlobalCooldown,EventCooldown,NumChoices,MinimumCityPopulation,MaximumCityPopulation,RequiredCiv,RequiredEra,ObsoleteEra,IsUnhappy,IsSuperUnhappy,RequiredPolicy,RequiredIdeology,RequiresWar,RequiresWarMinor,PrereqTech,ObsoleteTech,RequiresPantheon,RequiredReligion,RequiredStateReligion,RequiresAnyStateReligion,RequiredBuildingClass,CannotHaveBuildingClass,RequiresHolyCity,RequiresIdeology,NearbyFeature,NearbyTerrain,LocalResourceRequired,HasTradeConnection,HasCityConnection,RequiresGarrison,CapitalOnly,CoastalOnly,RiverOnly,RequiresResistance,RequiresWLTKD,RequiresOccupied,RequiresRazing,HasAnyReligion,RequiresPuppet,RequiresNearbyNaturalWonder,RequiresNearbyMountain,ImprovementRequired,HasMetAMajorCiv,InDebt,LosingMoney,IsVassalOfSomeone,IsMasterOfSomeone,CityHasPlayerReligion,CityLacksPlayerReligion,CityHasPlayerMajorityReligion,CityLacksPlayerMajorityReligion) VALUES ('CITY_EVENT_PLANTATION_RARE_CROP','EVENT_CLASS_GOOD',NULL,NULL,NULL,'AS2D_INTERFACE_CITY_TILE',10,0,'true','true','false',40,1,5,0,NULL,NULL,NULL,'false','false',NULL,NULL,'false','false',NULL,NULL,'false',NULL,NULL,'false',NULL,NULL,'false','false',NULL,NULL,NULL,'false','false','false','false','false','false','false','false','false','false','false','false','false','false','IMPROVEMENT_PLANTATION','false','false','false','false','false','false','false','false','false');

INSERT INTO CityEvent_ParentEvents (CityEventChoiceType,CityEventType) VALUES ('CITY_EVENT_PLANTATION_RARE_CROP_CHOICE_1','CITY_EVENT_PLANTATION_RARE_CROP');

INSERT INTO CityEventChoices (Type,Description,Help,DisabledTooltip,EventChoiceAudio,EventChance,IsOneShot,EraScaling,EventDuration,Expires,MinimumCityPopulation,MaximumCityPopulation,RequiredCiv,RequiredEra,IsUnhappy,IsSuperUnhappy,ObsoleteEra,RequiredPolicy,RequiredIdeology,RequiresWar,RequiresWarMinor,PrereqTech,ObsoleteTech,RequiresPantheon,RequiredReligion,RequiredStateReligion,RequiresAnyStateReligion,RequiredBuildingClass,CannotHaveBuildingClass,RequiresHolyCity,RequiresIdeology,NearbyFeature,NearbyTerrain,LocalResourceRequired,HasTradeConnection,HasCityConnection,RequiresGarrison,CapitalOnly,CoastalOnly,RiverOnly,RequiresResistance,RequiresWLTKD,RequiresOccupied,RequiresRazing,HasAnyReligion,RequiresPuppet,RequiresNearbyNaturalWonder,RequiresNearbyMountain,EventBuildingClassDestruction,EventBuildingClass,CityWideBuildingDestructionChance,WLTKDTurns,ResistanceTurns,CityHappiness,RandomBarbarianSpawn,ConvertToPlayerReligionPercent,ConvertToPlayerMajorityReligionPercent,ImprovementRequired,FreeUnitsTechAppropriate,HasMetAMajorCiv,InDebt,LosingMoney,IsVassalOfSomeone,IsMasterOfSomeone,CityHasPlayerReligion,CityLacksPlayerReligion,CityHasPlayerMajorityReligion,CityLacksPlayerMajorityReligion) VALUES ('CITY_EVENT_PLANTATION_RARE_CROP_CHOICE_1','TXT_KEY_CITY_EVENT_PLANTATION_RARE_CROP_CHOICE_1','TXT_KEY_CITY_EVENT_PLANTATION_RARE_CROP_CHOICE_1_HELP',NULL,NULL,0,'false','true',-1,'false',0,0,NULL,NULL,'false','false',NULL,NULL,NULL,'false','false',NULL,NULL,'false',NULL,NULL,'false',NULL,NULL,'false','false',NULL,NULL,NULL,'false','false','false','false','false','false','false','false','false','false','false','false','false','false',NULL,NULL,0,0,0,0,0,0,0,NULL,0,'false','false','false','false','false','false','false','false','false');

INSERT INTO CityEventChoice_InstantYield (CityEventChoiceType,YieldType,Yield) VALUES ('CITY_EVENT_PLANTATION_RARE_CROP_CHOICE_1','YIELD_SCIENCE',50);

UPDATE EventChoices
SET EventPromotion = 'PROMOTION_MORALE_EVENT'
WHERE Type = 'PLAYER_EVENT_WAR_FERVOR_CHOICE_1';