--New Beliefs
INSERT INTO Beliefs
		(Type, 						Description, 						ShortDescription, 						Tooltip, 							Pantheon, 	Founder, 	Follower, 	Enhancer, 	Reformation)
VALUES	('BELIEF_GURDWARA', 		'TXT_KEY_BELIEF_GURDWARA',			'TXT_KEY_BELIEF_GURDWARA_SHORT', 		'TXT_KEY_BELIEF_GURDWARA',			0, 			0, 			1, 			0, 			0),
		('BELIEF_TEOCALLI', 		'TXT_KEY_BELIEF_TEOCALLI',			'TXT_KEY_BELIEF_TEOCALLI_SHORT', 		'TXT_KEY_BELIEF_TEOCALLI',			0, 			0, 			1, 			0, 			0),
		('BELIEF_COMMUNALISM', 		'TXT_KEY_BELIEF_COMMUNALISM',		'TXT_KEY_BELIEF_COMMUNALISM_SHORT', 	'TXT_KEY_BELIEF_COMMUNALISM',		0, 			0, 			1, 			0, 			0);



-- Sword into Plowshare (Now Church)
UPDATE Beliefs
SET CityGrowthModifier = '0'
WHERE Type = 'BELIEF_SWORD_PLOWSHARES';

UPDATE Beliefs
SET RequiresPeace = '0'
WHERE Type = 'BELIEF_SWORD_PLOWSHARES';

-- Guruship (Now Mandir)
DELETE FROM Belief_YieldChangeAnySpecialist
WHERE BeliefType = 'BELIEF_GURUSHIP';

-- Holy Warriors (Now Synagogue)
DELETE FROM Belief_EraFaithUnitPurchase
WHERE BeliefType = 'BELIEF_HOLY_WARRIORS';

-- Monasteries (Now Stupa)
UPDATE Belief_BuildingClassFaithPurchase
SET BuildingClassType = 'BUILDINGCLASS_STUPA'
WHERE BeliefType = 'BELIEF_MONASTERIES';

-- Feed the World (Now Thrift)
DELETE FROM Belief_BuildingClassYieldChanges
WHERE BeliefType = 'BELIEF_FEED_WORLD';

-- Peace Gardens (Now Cooperation)
DELETE FROM Belief_BuildingClassHappiness
WHERE BeliefType = 'BELIEF_PEACE_GARDENS';

-- Choral Music (Now Scholarship)
UPDATE Beliefs
SET MinFollowers = '0'
WHERE Type = 'BELIEF_CHORAL_MUSIC';

DELETE FROM Belief_BuildingClassYieldChanges
WHERE BeliefType = 'BELIEF_CHORAL_MUSIC';

-- Religious Art (Now Mastery)
DELETE FROM Belief_BuildingClassYieldChanges
WHERE BeliefType = 'BELIEF_RELIGIOUS_ART';

DELETE FROM Belief_BuildingClassTourism
WHERE BeliefType = 'BELIEF_RELIGIOUS_ART';

-- Liturgical Drama (Now Veneration)
DELETE FROM Belief_BuildingClassYieldChanges
WHERE BeliefType = 'BELIEF_LITURGICAL_DRAMA';

UPDATE Beliefs
SET MinFollowers = '0'
WHERE Type = 'BELIEF_LITURGICAL_DRAMA';

-- Asceticism (Now Asceticism)
UPDATE Beliefs
SET MinFollowers = '0'
WHERE Type = 'BELIEF_ASCETISM';

DELETE FROM Belief_BuildingClassHappiness
WHERE BeliefType = 'BELIEF_ASCETISM';

-- Religious Center (Now Order)
DELETE FROM Belief_BuildingClassHappiness
WHERE BeliefType = 'BELIEF_RELIGIOUS_CENTER';

UPDATE Beliefs
SET MinFollowers = '0'
WHERE Type = 'BELIEF_RELIGIOUS_CENTER';

-- Religious Community (Now Diliegence)

DELETE FROM Belief_MaxYieldModifierPerFollower
WHERE BeliefType = 'BELIEF_RELIGIOUS_COMMUNITY';

-- Divine Inspiration (Now Inspiration)
DELETE FROM Belief_YieldChangeWorldWonder
WHERE BeliefType = 'BELIEF_DIVINE_INSPIRATION';

-- Communalism --
INSERT Into Belief_TradeRouteYieldChange
		(BeliefType, 			DomainType, 		YieldType, 			Yield)
VALUES	('BELIEF_COMMUNALISM', 	'DOMAIN_SEA', 		'YIELD_PRODUCTION', 3),
		('BELIEF_COMMUNALISM', 	'DOMAIN_SEA', 		'YIELD_FOOD', 		3),
		('BELIEF_COMMUNALISM', 	'DOMAIN_LAND', 		'YIELD_PRODUCTION', 3),
		('BELIEF_COMMUNALISM', 	'DOMAIN_LAND', 		'YIELD_FOOD', 		3);

-- NEW

INSERT INTO Belief_SpecialistYieldChanges
	(BeliefType, SpecialistType, YieldType, Yield)
VALUES
	('BELIEF_RELIGIOUS_ART', 'SPECIALIST_MERCHANT', 'YIELD_GOLD', 1),
	('BELIEF_RELIGIOUS_ART', 'SPECIALIST_SCIENTIST', 'YIELD_SCIENCE', 1),
	('BELIEF_RELIGIOUS_ART', 'SPECIALIST_ENGINEER', 'YIELD_PRODUCTION', 1),
	('BELIEF_RELIGIOUS_ART', 'SPECIALIST_ARTIST', 'YIELD_CULTURE', 1),
	('BELIEF_RELIGIOUS_ART', 'SPECIALIST_WRITER', 'YIELD_CULTURE', 1),
	('BELIEF_RELIGIOUS_ART', 'SPECIALIST_MUSICIAN', 'YIELD_CULTURE', 1),
	('BELIEF_RELIGIOUS_ART', 'SPECIALIST_MERCHANT', 'YIELD_GOLDEN_AGE_POINTS', 1),
	('BELIEF_RELIGIOUS_ART', 'SPECIALIST_SCIENTIST', 'YIELD_GOLDEN_AGE_POINTS', 1),
	('BELIEF_RELIGIOUS_ART', 'SPECIALIST_ENGINEER', 'YIELD_GOLDEN_AGE_POINTS', 1),
	('BELIEF_RELIGIOUS_ART', 'SPECIALIST_ARTIST', 'YIELD_GOLDEN_AGE_POINTS', 1),
	('BELIEF_RELIGIOUS_ART', 'SPECIALIST_WRITER', 'YIELD_GOLDEN_AGE_POINTS', 1),
	('BELIEF_RELIGIOUS_ART', 'SPECIALIST_MUSICIAN', 'YIELD_GOLDEN_AGE_POINTS', 1);

INSERT INTO Belief_MaxYieldPerFollowerPercent
	(BeliefType, YieldType, Max)
VALUES
	('BELIEF_FEED_WORLD', 'YIELD_GOLD', 100),
	('BELIEF_ASCETISM', 'YIELD_FOOD', 100),
	('BELIEF_CHORAL_MUSIC', 'YIELD_SCIENCE', 50),
	('BELIEF_DIVINE_INSPIRATION', 'YIELD_CULTURE', 34),
	('BELIEF_RELIGIOUS_COMMUNITY', 'YIELD_PRODUCTION', 50);

INSERT Into Belief_YieldFromFaithPurchase
		(BeliefType, YieldType, Yield)
VALUES	('BELIEF_PEACE_GARDENS', 	'YIELD_PRODUCTION', 10),
		('BELIEF_PEACE_GARDENS', 	'YIELD_GOLD', 		10),
		('BELIEF_LITURGICAL_DRAMA', 'YIELD_CULTURE', 	10),
		('BELIEF_LITURGICAL_DRAMA', 'YIELD_FOOD', 		10);

INSERT INTO Belief_YieldPerScience
		(BeliefType, 				YieldType, 		Yield)
VALUES	('BELIEF_LITURGICAL_DRAMA', 'YIELD_FAITH', 	5);

INSERT Into Belief_YieldPerGPT
		(BeliefType,				YieldType, 		Yield)
VALUES	('BELIEF_PEACE_GARDENS', 	'YIELD_FAITH', 	10);

INSERT Into Belief_YieldChangeAnySpecialist
(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_DIVINE_INSPIRATION', 'YIELD_FAITH', 2),
	('BELIEF_COMMUNALISM', 	'YIELD_PRODUCTION', 2);

INSERT INTO Belief_MaxYieldPerFollower
	(BeliefType, YieldType, Max)
VALUES
	('BELIEF_FEED_WORLD', 'YIELD_GOLD', 10),
	('BELIEF_ASCETISM', 'YIELD_FOOD', 15),
	('BELIEF_CHORAL_MUSIC', 'YIELD_SCIENCE', 15),
	('BELIEF_DIVINE_INSPIRATION', 'YIELD_CULTURE', 6),
	('BELIEF_RELIGIOUS_COMMUNITY', 'YIELD_PRODUCTION', 15);


INSERT INTO Belief_BuildingClassFaithPurchase
	(BeliefType, BuildingClassType)
VALUES
	('BELIEF_SWORD_PLOWSHARES', 'BUILDINGCLASS_CHURCH'),
	('BELIEF_GURUSHIP', 'BUILDINGCLASS_MANDIR'),
	('BELIEF_HOLY_WARRIORS', 'BUILDINGCLASS_SYNAGOGUE'),
	('BELIEF_RELIGIOUS_CENTER', 'BUILDINGCLASS_ORDER'),
	('BELIEF_GURDWARA', 		'BUILDINGCLASS_GURDWARA'),
	('BELIEF_TEOCALLI', 		'BUILDINGCLASS_TEOCALLI');

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BUILDING_CATHEDRAL_TOOLTIP'
WHERE Type = 'BELIEF_CATHEDRALS';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BUILDING_PAGODA_TOOLTIP'
WHERE Type = 'BELIEF_PAGODAS';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BUILDING_MOSQUE_TOOLTIP'
WHERE Type = 'BELIEF_MOSQUES';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BUILDING_STUPA_TOOLTIP'
WHERE Type = 'BELIEF_MONASTERIES';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BUILDING_SYNAGOGUE_TOOLTIP'
WHERE Type = 'BELIEF_HOLY_WARRIORS';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BUILDING_MANDIR_TOOLTIP'
WHERE Type = 'BELIEF_GURUSHIP';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BUILDING_CHURCH_TOOLTIP'
WHERE Type = 'BELIEF_SWORD_PLOWSHARES';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BUILDING_ORDER_TOOLTIP'
WHERE Type = 'BELIEF_RELIGIOUS_CENTER';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BUILDING_GURDWARA_TOOLTIP'
WHERE Type = 'BELIEF_GURDWARA';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BUILDING_TEOCALLI_TOOLTIP'
WHERE Type = 'BELIEF_TEOCALLI';

-- Rest of Tooltips (for LUA)

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_FEED_WORLD'
WHERE Type = 'BELIEF_FEED_WORLD';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_PEACE_GARDENS'
WHERE Type = 'BELIEF_PEACE_GARDENS';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_CHORAL_MUSIC'
WHERE Type = 'BELIEF_CHORAL_MUSIC';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_CHORAL_MUSIC'
WHERE Type = 'BELIEF_CHORAL_MUSIC';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_RELIGIOUS_ART'
WHERE Type = 'BELIEF_RELIGIOUS_ART';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_LITURGICAL_DRAMA'
WHERE Type = 'BELIEF_LITURGICAL_DRAMA';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_ASCETISM'
WHERE Type = 'BELIEF_ASCETISM';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_RELIGIOUS_COMMUNITY'
WHERE Type = 'BELIEF_RELIGIOUS_COMMUNITY';

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_DIVINE_INSPIRATION'
WHERE Type = 'BELIEF_DIVINE_INSPIRATION';
