-- Route
UPDATE SmallAwards SET Influence = '20' WHERE Type = 'MINOR_CIV_QUEST_ROUTE';
UPDATE SmallAwards SET Production = '40' WHERE Type = 'MINOR_CIV_QUEST_ROUTE';
UPDATE SmallAwards SET RandomMod = '25' WHERE Type = 'MINOR_CIV_QUEST_ROUTE';

-- Camp
UPDATE SmallAwards SET Influence = '20' WHERE Type = 'MINOR_CIV_QUEST_KILL_CAMP';
UPDATE SmallAwards SET GeneralPoints = '25' WHERE Type = 'MINOR_CIV_QUEST_KILL_CAMP';
UPDATE SmallAwards SET RandomMod = '30' WHERE Type = 'MINOR_CIV_QUEST_KILL_CAMP';

-- Resource
UPDATE SmallAwards SET Influence = '15' WHERE Type = 'MINOR_CIV_QUEST_CONNECT_RESOURCE';
UPDATE SmallAwards SET Gold = '35' WHERE Type = 'MINOR_CIV_QUEST_CONNECT_RESOURCE';
UPDATE SmallAwards SET RandomMod = '30' WHERE Type = 'MINOR_CIV_QUEST_CONNECT_RESOURCE';

-- Wonder
UPDATE SmallAwards SET Influence = '15' WHERE Type = 'MINOR_CIV_QUEST_CONSTRUCT_WONDER';
UPDATE SmallAwards SET Faith = '30' WHERE Type = 'MINOR_CIV_QUEST_CONSTRUCT_WONDER';
UPDATE SmallAwards SET RandomMod = '45' WHERE Type = 'MINOR_CIV_QUEST_CONSTRUCT_WONDER';

-- GP
UPDATE SmallAwards SET Influence = '15' WHERE Type = 'MINOR_CIV_QUEST_GREAT_PERSON';
UPDATE SmallAwards SET Culture = '45' WHERE Type = 'MINOR_CIV_QUEST_GREAT_PERSON';
UPDATE SmallAwards SET RandomMod = '45' WHERE Type = 'MINOR_CIV_QUEST_GREAT_PERSON';

-- Kill CS
UPDATE Defines SET Value = '0' WHERE Name = 'QUEST_DISABLED_KILL_CITY_STATE';
UPDATE SmallAwards SET Influence = '15' WHERE Type = 'MINOR_CIV_QUEST_KILL_CITY_STATE';
UPDATE SmallAwards SET Gold = '100' WHERE Type = 'MINOR_CIV_QUEST_KILL_CITY_STATE';
UPDATE SmallAwards SET GoldenAgePoints = '100' WHERE Type = 'MINOR_CIV_QUEST_KILL_CITY_STATE';
UPDATE SmallAwards SET RandomMod = '50' WHERE Type = 'MINOR_CIV_QUEST_KILL_CITY_STATE';

-- Find Player
UPDATE SmallAwards SET Influence = '15' WHERE Type = 'MINOR_CIV_QUEST_FIND_PLAYER';
UPDATE SmallAwards SET Science = '30' WHERE Type = 'MINOR_CIV_QUEST_FIND_PLAYER';
UPDATE SmallAwards SET RandomMod = '35' WHERE Type = 'MINOR_CIV_QUEST_FIND_PLAYER';

-- Find NW
UPDATE SmallAwards SET Influence = '20' WHERE Type = 'MINOR_CIV_QUEST_FIND_NATURAL_WONDER';
UPDATE SmallAwards SET GoldenAgePoints = '100' WHERE Type = 'MINOR_CIV_QUEST_FIND_NATURAL_WONDER';
UPDATE SmallAwards SET RandomMod = '35' WHERE Type = 'MINOR_CIV_QUEST_FIND_NATURAL_WONDER';

-- Give Gold
UPDATE SmallAwards SET Influence = '15' WHERE Type = 'MINOR_CIV_QUEST_GIVE_GOLD';
UPDATE SmallAwards SET Food = '30' WHERE Type = 'MINOR_CIV_QUEST_GIVE_GOLD';
UPDATE SmallAwards SET RandomMod = '30' WHERE Type = 'MINOR_CIV_QUEST_GIVE_GOLD';

-- PtP
UPDATE SmallAwards SET Influence = '10' WHERE Type = 'MINOR_CIV_QUEST_PLEDGE_TO_PROTECT';
UPDATE SmallAwards SET CapitalGPPoints = '30' WHERE Type = 'MINOR_CIV_QUEST_PLEDGE_TO_PROTECT';
UPDATE SmallAwards SET RandomMod = '35' WHERE Type = 'MINOR_CIV_QUEST_PLEDGE_TO_PROTECT';

-- Culture Contest
UPDATE SmallAwards SET Influence = '10' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_CULTURE';
UPDATE SmallAwards SET Happiness = '1' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_CULTURE';
UPDATE SmallAwards SET RandomMod = '25' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_CULTURE';

-- Faith Contest
UPDATE SmallAwards SET Influence = '15' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_FAITH';
UPDATE SmallAwards SET GlobalGPPoints = '30' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_FAITH';
UPDATE SmallAwards SET RandomMod = '35' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_FAITH';

-- Tech Contest
UPDATE SmallAwards SET Influence = '10' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_TECHS';
UPDATE SmallAwards SET Tourism = '200' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_TECHS';
UPDATE SmallAwards SET RandomMod = '40' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_TECHS';

-- Bully
UPDATE SmallAwards SET Influence = '15' WHERE Type = 'MINOR_CIV_QUEST_BULLY_CITY_STATE';
UPDATE SmallAwards SET Gold = '60' WHERE Type = 'MINOR_CIV_QUEST_BULLY_CITY_STATE';
UPDATE SmallAwards SET GlobalExperience = '5' WHERE Type = 'MINOR_CIV_QUEST_BULLY_CITY_STATE';
UPDATE SmallAwards SET RandomMod = '20' WHERE Type = 'MINOR_CIV_QUEST_BULLY_CITY_STATE';

-- Denounce
UPDATE SmallAwards SET Influence = '15' WHERE Type = 'MINOR_CIV_QUEST_DENOUNCE_MAJOR';
UPDATE SmallAwards SET GeneralPoints = '50' WHERE Type = 'MINOR_CIV_QUEST_DENOUNCE_MAJOR';
UPDATE SmallAwards SET RandomMod = '30' WHERE Type = 'MINOR_CIV_QUEST_DENOUNCE_MAJOR';

-- Religion
UPDATE SmallAwards SET Influence = '20' WHERE Type = 'MINOR_CIV_QUEST_SPREAD_RELIGION';
UPDATE SmallAwards SET Faith = '30' WHERE Type = 'MINOR_CIV_QUEST_SPREAD_RELIGION';
UPDATE SmallAwards SET RandomMod = '30' WHERE Type = 'MINOR_CIV_QUEST_SPREAD_RELIGION';

-- Trade Route
UPDATE SmallAwards SET Influence = '15' WHERE Type = 'MINOR_CIV_QUEST_TRADE_ROUTE';
UPDATE SmallAwards SET Food = '25' WHERE Type = 'MINOR_CIV_QUEST_TRADE_ROUTE';
UPDATE SmallAwards SET RandomMod = '35' WHERE Type = 'MINOR_CIV_QUEST_TRADE_ROUTE';

-- War
UPDATE SmallAwards SET Influence = '20' WHERE Type = 'MINOR_CIV_QUEST_WAR';
UPDATE SmallAwards SET Happiness = '1' WHERE Type = 'MINOR_CIV_QUEST_WAR';
UPDATE SmallAwards SET RandomMod = '30' WHERE Type = 'MINOR_CIV_QUEST_WAR';

-- Build NW
UPDATE SmallAwards SET Influence = '20' WHERE Type = 'MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER';
UPDATE SmallAwards SET GoldenAgePoints = '100' WHERE Type = 'MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER';
UPDATE SmallAwards SET RandomMod = '35' WHERE Type = 'MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER';

-- Find a CS
UPDATE SmallAwards SET Influence = '10' WHERE Type = 'MINOR_CIV_QUEST_FIND_CITY_STATE';
UPDATE SmallAwards SET Production = '40' WHERE Type = 'MINOR_CIV_QUEST_FIND_CITY_STATE';
UPDATE SmallAwards SET RandomMod = '25' WHERE Type = 'MINOR_CIV_QUEST_FIND_CITY_STATE';

-- Contest Tourism
UPDATE SmallAwards SET Influence = '15' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_TOURISM';
UPDATE SmallAwards SET Culture = '40' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_TOURISM';
UPDATE SmallAwards SET RandomMod = '30' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_TOURISM';

-- Archaeology
UPDATE SmallAwards SET Influence = '5' WHERE Type = 'MINOR_CIV_QUEST_ARCHAEOLOGY';
UPDATE SmallAwards SET Tourism = '200' WHERE Type = 'MINOR_CIV_QUEST_ARCHAEOLOGY';
UPDATE SmallAwards SET RandomMod = '60' WHERE Type = 'MINOR_CIV_QUEST_ARCHAEOLOGY';

-- Circumnavigation
UPDATE SmallAwards SET Influence = '20' WHERE Type = 'MINOR_CIV_QUEST_CIRCUMNAVIGATION';
UPDATE SmallAwards SET AdmiralPoints = '50' WHERE Type = 'MINOR_CIV_QUEST_CIRCUMNAVIGATION';
UPDATE SmallAwards SET RandomMod = '40' WHERE Type = 'MINOR_CIV_QUEST_CIRCUMNAVIGATION';

-- Liberation
UPDATE SmallAwards SET Influence = '20' WHERE Type = 'MINOR_CIV_QUEST_LIBERATION';
UPDATE SmallAwards SET Happiness = '1' WHERE Type = 'MINOR_CIV_QUEST_LIBERATION';
UPDATE SmallAwards SET RandomMod = '40' WHERE Type = 'MINOR_CIV_QUEST_LIBERATION';

-- Discover Plot
UPDATE SmallAwards SET Influence = '25' WHERE Type = 'MINOR_CIV_QUEST_DISCOVER_PLOT';
UPDATE SmallAwards SET Gold = '50' WHERE Type = 'MINOR_CIV_QUEST_DISCOVER_PLOT';
UPDATE SmallAwards SET RandomMod = '50' WHERE Type = 'MINOR_CIV_QUEST_DISCOVER_PLOT';

-- Production
UPDATE SmallAwards SET Influence = '15' WHERE Type = 'MINOR_CIV_QUEST_BUILD_X_BUILDINGS';
UPDATE SmallAwards SET Production = '50' WHERE Type = 'MINOR_CIV_QUEST_BUILD_X_BUILDINGS';
UPDATE SmallAwards SET RandomMod = '60' WHERE Type = 'MINOR_CIV_QUEST_BUILD_X_BUILDINGS';

-- Stealing
UPDATE SmallAwards SET Influence = '20' WHERE Type = 'MINOR_CIV_QUEST_UNIT_STEAL_FROM';
UPDATE SmallAwards SET Science = '50' WHERE Type = 'MINOR_CIV_QUEST_UNIT_STEAL_FROM';
UPDATE SmallAwards SET RandomMod = '60' WHERE Type = 'MINOR_CIV_QUEST_UNIT_STEAL_FROM';

-- Stealing
UPDATE SmallAwards SET Influence = '25' WHERE Type = 'MINOR_CIV_QUEST_UNIT_COUP_CITY';
UPDATE SmallAwards SET CapitalGPPoints = '50' WHERE Type = 'MINOR_CIV_QUEST_UNIT_COUP_CITY';
UPDATE SmallAwards SET RandomMod = '60' WHERE Type = 'MINOR_CIV_QUEST_UNIT_COUP_CITY';

-- Conquest
UPDATE SmallAwards SET Influence = '40' WHERE Type = 'MINOR_CIV_QUEST_UNIT_GET_CITY';
UPDATE SmallAwards SET GlobalExperience = '7' WHERE Type = 'MINOR_CIV_QUEST_UNIT_GET_CITY';
UPDATE SmallAwards SET RandomMod = '15' WHERE Type = 'MINOR_CIV_QUEST_UNIT_GET_CITY';
