INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
VALUES
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_AMBER'),
	('CORPORATION_FIRAXITE_MATERIALS', 'RESOURCE_JADE'),
	('CORPORATION_GIORGIO_ARMEIER', 'RESOURCE_LAPIS'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_PERFUME'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_GLASS'),
	('CORPORATION_LANDSEA_EXTRACTORS', 'RESOURCE_CORAL'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_TOBACCO'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_OLIVE'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_COFFEE'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_TEA');

INSERT INTO Building_ResourceYieldChanges
	(BuildingType, ResourceType, YieldType, Yield)
VALUES
	('BUILDING_CIVILIZED_JEWELERS_FRANCHISE', 'RESOURCE_AMBER', 'YIELD_GOLD', 1),
	('BUILDING_FIRAXITE_MATERIALS_HQ', 'RESOURCE_JADE', 'YIELD_SCIENCE', 3),
	('BUILDING_CIVILIZED_JEWELERS_FRANCHISE', 'RESOURCE_JADE', 'YIELD_GOLD', 1),
	('BUILDING_GIORGIO_ARMEIER_HQ', 'RESOURCE_LAPIS', 'YIELD_CULTURE', 1),
	('BUILDING_GIORGIO_ARMEIER', 'RESOURCE_LAPIS', 'YIELD_CULTURE', 2),
	('BUILDING_GIORGIO_ARMEIER_FRANCHISE', 'RESOURCE_LAPIS', 'YIELD_GOLD', 1),
	('BUILDING_HEXXON_REFINERY_FRANCHISE', 'RESOURCE_PERFUME', 'YIELD_GOLD', 1),
	('BUILDING_HEXXON_REFINERY_FRANCHISE', 'RESOURCE_GLASS', 'YIELD_GOLD', 1),
	('BUILDING_LANDSEA_EXTRACTORS_HQ', 'RESOURCE_CORAL', 'YIELD_PRODUCTION', 2),
	('BUILDING_LANDSEA_EXTRACTORS', 'RESOURCE_CORAL', 'YIELD_PRODUCTION', 2),
	('BUILDING_LANDSEA_EXTRACTORS_FRANCHISE', 'RESOURCE_CORAL', 'YIELD_GOLD', 1),
	('BUILDING_TRADER_SIDS_HQ', 'RESOURCE_TOBACCO', 'YIELD_GOLD', 2),
	('BUILDING_TRADER_SIDS', 'RESOURCE_TOBACCO', 'YIELD_GOLD', 2),
	('BUILDING_TRADER_SIDS_FRANCHISE', 'RESOURCE_TOBACCO', 'YIELD_GOLD', 1),
	('BUILDING_TWOKAY_FOODS_HQ', 'RESOURCE_OLIVE', 'YIELD_FOOD', 2),
	('BUILDING_TWOKAY_FOODS_HQ', 'RESOURCE_COFFEE', 'YIELD_FOOD', 2),
	('BUILDING_TWOKAY_FOODS_HQ', 'RESOURCE_TEA', 'YIELD_FOOD', 2),
	('BUILDING_TWOKAY_FOODS', 'RESOURCE_OLIVE', 'YIELD_FOOD', 2),
	('BUILDING_TWOKAY_FOODS', 'RESOURCE_COFFEE', 'YIELD_FOOD', 2),
	('BUILDING_TWOKAY_FOODS', 'RESOURCE_TEA', 'YIELD_FOOD', 2),
	('BUILDING_TWOKAY_FOODS_FRANCHISE', 'RESOURCE_OLIVE', 'YIELD_GOLD', 1),
	('BUILDING_TWOKAY_FOODS_FRANCHISE', 'RESOURCE_COFFEE', 'YIELD_GOLD', 1),
	('BUILDING_TWOKAY_FOODS_FRANCHISE', 'RESOURCE_TEA', 'YIELD_GOLD', 1);

INSERT INTO Building_SpecialistYieldChanges
	(BuildingType, SpecialistType, YieldType, Yield)
VALUES
	('BUILDING_GIORGIO_ARMEIER_HQ', 'SPECIALIST_CIVIL_SERVANT', 'YIELD_CULTURE', 1);