-- MELEE UNITS
-- LAND

	-- Tech Stuff
	
	UPDATE Units SET PrereqTech = 'TECH_TRAPPING' WHERE Type = 'UNIT_BARBARIAN_ARCHER';
	UPDATE Units SET PrereqTech = 'TECH_MINING' WHERE Type = 'UNIT_CELT_PICTISH_WARRIOR';
	UPDATE Units SET PrereqTech = 'TECH_IRON_WORKING' WHERE Type = 'UNIT_IROQUOIAN_MOHAWKWARRIOR';
	UPDATE Units SET PrereqTech = 'TECH_IRON_WORKING' WHERE Type = 'UNIT_HUN_BATTERING_RAM';
	UPDATE Units SET PrereqTech = 'TECH_OPTICS' WHERE Type = 'UNIT_SCOUT';
	UPDATE Units SET PrereqTech = 'TECH_CHIVALRY' WHERE Type = 'UNIT_POLYNESIAN_MAORI_WARRIOR';
	UPDATE Units SET PrereqTech = 'TECH_STEEL' WHERE Type = 'UNIT_PIKEMAN';
	UPDATE Units SET PrereqTech = 'TECH_GUILDS' WHERE Type = 'UNIT_GERMAN_LANDSKNECHT';
	UPDATE Units SET PrereqTech = 'TECH_GUNPOWDER' WHERE Type = 'UNIT_SPANISH_TERCIO';
	UPDATE Units SET PrereqTech = 'TECH_GUNPOWDER' WHERE Type = 'UNIT_ZULU_IMPI';
--	UPDATE Units SET PrereqTech = 'TECH_RIFLING' WHERE Type = 'UNIT_FRENCH_FOREIGNLEGION'; -- Entry in Honor.sql
	UPDATE Units SET PrereqTech = 'TECH_RIFLING' WHERE Type = 'UNIT_DANISH_SKI_INFANTRY';
	UPDATE Units SET PrereqTech = 'TECH_RIFLING' WHERE Type = 'UNIT_SWEDISH_CAROLEAN';
	UPDATE Units SET PrereqTech = 'TECH_FLIGHT' WHERE Type = 'UNIT_PARATROOPER';
	UPDATE Units SET PrereqTech = 'TECH_COMBINED_ARMS' WHERE Type = 'UNIT_INFANTRY';
	UPDATE Units SET PrereqTech = 'TECH_COMBINED_ARMS' WHERE Type = 'UNIT_BRAZILIAN_PRACINHA';
	UPDATE Units SET PrereqTech = 'TECH_ADVANCED_BALLISTICS' WHERE Type = 'UNIT_MOBILE_SAM';
	UPDATE Units SET PrereqTech = 'TECH_COMPUTERS' WHERE Type = 'UNIT_MARINE';
	UPDATE Units SET PrereqTech = 'TECH_ADVANCED_BALLISTICS' WHERE Type = 'UNIT_MODERN_ARMOR';
	UPDATE Units SET PrereqTech = 'TECH_LASERS' WHERE Type = 'UNIT_XCOM_SQUAD';
	UPDATE Units SET PrereqTech = 'TECH_ROBOTICS' WHERE Type = 'UNIT_MECH';

	UPDATE Units SET ObsoleteTech = 'TECH_BRONZE_WORKING' WHERE Type = 'UNIT_WARRIOR';
	UPDATE Units SET ObsoleteTech = 'TECH_STEEL' WHERE Type = 'UNIT_AZTEC_JAGUAR';
	UPDATE Units SET ObsoleteTech = 'TECH_STEEL' WHERE Type = 'UNIT_BARBARIAN_SPEARMAN';	 
	UPDATE Units SET ObsoleteTech = 'TECH_STEEL' WHERE Type = 'UNIT_SPEARMAN';
	UPDATE Units SET ObsoleteTech = 'TECH_OPTICS' WHERE Type = 'UNIT_SHOSHONE_PATHFINDER';
	UPDATE Units SET ObsoleteTech = 'TECH_COMPASS' WHERE Type = 'UNIT_SCOUT';
	UPDATE Units SET ObsoleteTech = 'TECH_GUNPOWDER' WHERE Type = 'UNIT_HUN_BATTERING_RAM';
	UPDATE Units SET ObsoleteTech = 'TECH_GUNPOWDER' WHERE Type = 'UNIT_KRIS_SWORDSMAN';
	UPDATE Units SET ObsoleteTech = 'TECH_GUNPOWDER' WHERE Type = 'UNIT_PIKEMAN';
	UPDATE Units SET ObsoleteTech = 'TECH_GUNPOWDER' WHERE Type = 'UNIT_CELT_PICTISH_WARRIOR';
	UPDATE Units SET ObsoleteTech = 'TECH_GUNPOWDER' WHERE Type = 'UNIT_GREEK_HOPLITE';
	UPDATE Units SET ObsoleteTech = 'TECH_GUNPOWDER' WHERE Type = 'UNIT_PERSIAN_IMMORTAL';
	UPDATE Units SET ObsoleteTech = 'TECH_RIFLING' WHERE Type = 'UNIT_SPANISH_TERCIO';
	UPDATE Units SET ObsoleteTech = 'TECH_RIFLING' WHERE Type = 'UNIT_POLYNESIAN_MAORI_WARRIOR';
	UPDATE Units SET ObsoleteTech = 'TECH_RIFLING' WHERE Type = 'UNIT_DANISH_BERSERKER';
	UPDATE Units SET ObsoleteTech = 'TECH_REPLACEABLE_PARTS' WHERE Type = 'UNIT_FRENCH_MUSKETEER';
	UPDATE Units SET ObsoleteTech = 'TECH_REPLACEABLE_PARTS' WHERE Type = 'UNIT_AMERICAN_MINUTEMAN';
	UPDATE Units SET ObsoleteTech = 'TECH_COMBINED_ARMS'WHERE Type = 'UNIT_SWEDISH_CAROLEAN';
	UPDATE Units SET ObsoleteTech = 'TECH_COMBINED_ARMS' WHERE Type = 'UNIT_GREAT_WAR_INFANTRY';
--	UPDATE Units SET ObsoleteTech = 'TECH_PENICILIN' WHERE Type = 'UNIT_FRENCH_FOREIGNLEGION'; -- Entry in Honor.sql
	UPDATE Units SET ObsoleteTech = 'TECH_COMBINED_ARMS' WHERE Type = 'UNIT_ETHIOPIAN_MEHAL_SEFARI';
	UPDATE Units SET ObsoleteTech = 'TECH_COMBINED_ARMS' WHERE Type = 'UNIT_DANISH_SKI_INFANTRY';
	UPDATE Units SET ObsoleteTech = 'TECH_REPLACEABLE_PARTS' WHERE Type = 'UNIT_ZULU_IMPI';
	UPDATE Units SET ObsoleteTech = 'TECH_REPLACEABLE_PARTS' WHERE Type = 'UNIT_OTTOMAN_JANISSARY';
	UPDATE Units SET ObsoleteTech = 'TECH_ADVANCED_BALLISTICS' WHERE Type = 'UNIT_ANTI_AIRCRAFT_GUN';
	UPDATE Units SET ObsoleteTech = 'TECH_COMPUTERS' WHERE Type = 'UNIT_PARATROOPER';
	UPDATE Units SET ObsoleteTech = 'TECH_ADVANCED_BALLISTICS' WHERE Type = 'UNIT_TANK';
	UPDATE Units SET ObsoleteTech = 'TECH_LASERS' WHERE Type = 'UNIT_MARINE';
	UPDATE Units SET ObsoleteTech = NULL WHERE Type = 'UNIT_BRAZILIAN_PRACINHA';

	-- Tercio now the Renaissance land unit -- upgrdes into rifleman, medieval melee upgrade into it.
	UPDATE Units SET GoodyHutUpgradeUnitClass = 'UNITCLASS_RIFLEMAN' WHERE Type = 'UNIT_SPANISH_TERCIO';
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_RIFLEMAN' WHERE UnitType = 'UNIT_SPANISH_TERCIO';

	UPDATE Units SET GoodyHutUpgradeUnitClass = 'UNITCLASS_TERCIO' WHERE Type = 'UNIT_PIKEMAN';
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_TERCIO' WHERE UnitType = 'UNIT_PIKEMAN';

	UPDATE Units SET GoodyHutUpgradeUnitClass = 'UNITCLASS_TERCIO' WHERE Type = 'UNIT_LONGSWORDSMAN';
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_TERCIO' WHERE UnitType = 'UNIT_LONGSWORDSMAN';

	-- Recon Unit Classes
	UPDATE Units SET CombatClass = 'UNITCOMBAT_RECON' WHERE Type = 'UNIT_PARATROOPER';	
	UPDATE Units SET GoodyHutUpgradeUnitClass = 'UNITCLASS_MARINE' WHERE Type = 'UNIT_PARATROOPER';
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_MARINE' WHERE UnitType = 'UNIT_PARATROOPER';
	UPDATE Units SET CombatClass = 'UNITCOMBAT_RECON' WHERE Type = 'UNIT_MARINE';
	INSERT INTO Unit_AITypes (UnitType, UnitAIType) VALUES ('UNIT_PARATROOPER', 'UNITAI_EXPLORE');

	INSERT INTO Unit_ClassUpgrades (UnitType, UnitClassType) VALUES ('UNIT_MARINE', 'UNITCLASS_XCOM_SQUAD');
	UPDATE Units  SET DefaultUnitAI = 'UNITAI_PARADROP'  WHERE Type = 'UNIT_MARINE';

	DELETE FROM Unit_AITypes WHERE UnitType = 'UNIT_MARINE' AND UnitAIType = 'UNITAI_ATTACK';
	DELETE FROM Unit_AITypes WHERE UnitType = 'UNIT_MARINE' AND UnitAIType = 'UNITAI_DEFENSE';
	INSERT INTO Unit_AITypes (UnitType, UnitAIType) VALUES ('UNIT_MARINE', 'UNITAI_PARADROP');
	UPDATE Units SET GoodyHutUpgradeUnitClass = 'UNITCLASS_XCOM_SQUAD' WHERE Type = 'UNIT_MARINE';

	UPDATE Units SET CombatClass = 'UNITCOMBAT_RECON' WHERE Type = 'UNIT_XCOM_SQUAD';
	UPDATE Units SET IgnoreBuildingDefense = '1' WHERE Type = 'UNIT_XCOM_SQUAD';
	INSERT INTO Unit_AITypes (UnitType, UnitAIType) VALUES ('UNIT_XCOM_SQUAD', 'UNITAI_EXPLORE');
	-- Recon class base sight +1
	UPDATE Units SET BaseSightRange = '2' WHERE Type = 'UNIT_SHOSHONE_PATHFINDER';
	UPDATE Units SET BaseSightRange = '3' WHERE Type = 'UNIT_SCOUT';
	UPDATE Units SET BaseSightRange = '3' WHERE Type = 'UNIT_EXPLORER';
	UPDATE Units SET BaseSightRange = '3' WHERE Type = 'UNIT_COMMANDO';
	UPDATE Units SET BaseSightRange = '3' WHERE Type = 'UNIT_PARATROOPER';
	UPDATE Units SET BaseSightRange = '3' WHERE Type = 'UNIT_MARINE';
	UPDATE Units SET BaseSightRange = '3' WHERE Type = 'UNIT_XCOM_SQUAD';

	DELETE FROM Unit_AITypes WHERE UnitType = 'UNIT_SHOSHONE_PATHFINDER';
	INSERT INTO Unit_AITypes (UnitType, UnitAIType) VALUES ('UNIT_SHOSHONE_PATHFINDER', 'UNITAI_EXPLORE');
	UPDATE Units SET DefaultUnitAI = 'UNITAI_EXPLORE' WHERE Type = 'UNIT_SHOSHONE_PATHFINDER';

	-- Pathfinder -> Scout -> Explorer
	UPDATE Units SET GoodyHutUpgradeUnitClass = 'UNITCLASS_SCOUT' WHERE Type = 'UNIT_SHOSHONE_PATHFINDER';
	UPDATE Units SET GoodyHutUpgradeUnitClass = 'UNITCLASS_EXPLORER' WHERE Type = 'UNIT_SCOUT';	

	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_SCOUT' WHERE UnitType = 'UNIT_SHOSHONE_PATHFINDER';
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_EXPLORER' WHERE UnitType = 'UNIT_SCOUT';

	-- Change Appearance of Marine and Paratrooper 
	UPDATE Units SET UnitArtInfo = 'ART_DEF_UNIT_PARATROOPER' WHERE Type = 'UNIT_MARINE';
	UPDATE Units SET UnitFlagIconOffset = '59' WHERE Type = 'UNIT_MARINE';
	UPDATE Units SET IconAtlas = 'UNIT_ATLAS_2' WHERE Type = 'UNIT_MARINE';
	UPDATE Units SET PortraitIndex = '14' WHERE Type = 'UNIT_MARINE';
	UPDATE Units SET UnitFlagAtlas = 'UNIT_FLAG_ATLAS' WHERE Type = 'UNIT_MARINE';

	UPDATE Units SET UnitArtInfo = 'ART_DEF_UNIT_MARINE' WHERE Type = 'UNIT_PARATROOPER';
	UPDATE Units SET UnitFlagIconOffset = '19' WHERE Type = 'UNIT_PARATROOPER';
	UPDATE Units SET IconAtlas = 'EXPANSION_UNIT_ATLAS_1' WHERE Type = 'UNIT_PARATROOPER';
	UPDATE Units SET PortraitIndex = '19' WHERE Type = 'UNIT_PARATROOPER';
	UPDATE Units SET UnitFlagAtlas = 'EXPANSION_UNIT_FLAG_ATLAS' WHERE Type = 'UNIT_PARATROOPER';

	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_SPEARMAN' WHERE UnitType = 'UNIT_WARRIOR';
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_SPEARMAN' WHERE UnitType = 'UNIT_BARBARIAN_WARRIOR';
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_TERCIO' WHERE UnitType = 'UNIT_PIKEMAN';

	-- Make Landship cost Coal, not oil:
	UPDATE Unit_ResourceQuantityRequirements SET ResourceType = 'RESOURCE_OIL' WHERE UnitType = 'UNIT_WWI_TANK';

	-- Make Modern Armor cost oil, not aluminum:
	UPDATE Unit_ResourceQuantityRequirements SET ResourceType = 'RESOURCE_OIL' WHERE UnitType = 'UNIT_MODERN_ARMOR';
	
	UPDATE Units SET Range = '4' WHERE Type = 'UNIT_MOBILE_SAM';
	UPDATE Units SET AirInterceptRange = '4' WHERE Type = 'UNIT_MOBILE_SAM';
	UPDATE Units SET Range = '3' WHERE Type = 'UNIT_ANTI_AIRCRAFT_GUN';
	UPDATE Units SET AirInterceptRange = '3' WHERE Type = 'UNIT_ANTI_AIRCRAFT_GUN';

	INSERT INTO Unit_AITypes (UnitType, UnitAIType) VALUES ('UNIT_SPEARMAN' , 'UNITAI_ATTACK');
	INSERT INTO Unit_AITypes (UnitType, UnitAIType) VALUES ('UNIT_SPANISH_TERCIO' , 'UNITAI_ATTACK');
	UPDATE Units SET DefaultUnitAI = 'UNITAI_DEFENSE' WHERE Type = 'UNIT_SPANISH_TERCIO';
	INSERT INTO Unit_AITypes (UnitType, UnitAIType) VALUES ('UNIT_BARBARIAN_SPEARMAN' , 'UNITAI_ATTACK');

	--MECH
	UPDATE Units SET Moves = '8' WHERE Type = 'UNIT_MECH';
	UPDATE Units SET DefaultUnitAI = 'UNITAI_FAST_ATTACK' WHERE Type = 'UNIT_MECH';
	