-- New AIs
INSERT INTO UnitAIInfos	 (ID, Type, Description) VALUES
(44, 'UNITAI_SKIRMISHER','UNITAI_SKIRMISHER'),
(45, 'UNITAI_SUBMARINE', 'UNITAI_SUBMARINE');

UPDATE Units SET DefaultUnitAI = 'UNITAI_SKIRMISHER' WHERE IsMounted = 1;
UPDATE Units SET DefaultUnitAI = 'UNITAI_SUBMARINE' WHERE CombatClass = 'UNITCOMBAT_SUBMARINE';

-- Counter only used by AA
UPDATE Units SET DefaultUnitAI = 'UNITAI_EXPLORE' WHERE DefaultUnitAI = 'UNITAI_FAST_ATTACK' AND CombatClass = 'UNITCOMBAT_RECON';
UPDATE Units SET DefaultUnitAI = 'UNITAI_DEFENSE' WHERE AirInterceptRange == 0 AND DefaultUnitAI = 'UNITAI_COUNTER';
DELETE FROM Unit_AITypes WHERE UnitType IN (SELECT Type From Units Where DefaultUnitAI = 'UNITAI_DEFENSE') AND UnitAIType = 'UNITAI_COUNTER';

UPDATE Unit_AITypes SET UnitAIType = 'UNITAI_SKIRMISHER' WHERE UnitType IN (SELECT Type From Units Where IsMounted) AND UnitAIType = 'UNITAI_COUNTER';
INSERT INTO Unit_AITypes (UnitType, UnitAIType) VALUES
('UNIT_SUBMARINE', 'UNITAI_SUBMARINE'),
('UNIT_NUCLEAR_SUBMARINE', 'UNITAI_SUBMARINE');
