-- RANGED UNITS

	-- Prereq Techs 

	UPDATE Units SET PrereqTech = 'TECH_ANIMAL_HUSBANDRY' WHERE Type = 'UNIT_CHARIOT_ARCHER';
	UPDATE Units SET PrereqTech = 'TECH_TRAPPING' WHERE Type = 'UNIT_ARCHER';
	UPDATE Units SET PrereqTech = 'TECH_TRAPPING' WHERE Type = 'UNIT_ARCHER';
	UPDATE Units SET PrereqTech = 'TECH_TRAPPING' WHERE Type = 'UNIT_INCAN_SLINGER';
	UPDATE Units SET PrereqTech = 'TECH_IRON_WORKING' WHERE Type = 'UNIT_CATAPULT';
	UPDATE Units SET PrereqTech = 'TECH_IRON_WORKING' WHERE Type = 'UNIT_ROMAN_BALLISTA';
	UPDATE Units SET PrereqTech = 'TECH_MATHEMATICS' WHERE Type = 'UNIT_MAYAN_ATLATLIST';
	UPDATE Units SET PrereqTech = 'TECH_MATHEMATICS' WHERE Type = 'UNIT_COMPOSITE_BOWMAN';
	UPDATE Units SET PrereqTech = 'TECH_MATHEMATICS' WHERE Type = 'UNIT_BABYLONIAN_BOWMAN';
	UPDATE Units SET PrereqTech = 'TECH_MACHINERY' WHERE Type = 'UNIT_ENGLISH_LONGBOWMAN';
	UPDATE Units SET PrereqTech = 'TECH_METALLURGY' WHERE Type = 'UNIT_MUSKETMAN';
	UPDATE Units SET PrereqTech = 'TECH_METALLURGY' WHERE Type = 'UNIT_AMERICAN_MINUTEMAN';
	UPDATE Units SET PrereqTech = 'TECH_ADVANCED_BALLISTICS' WHERE Type = 'UNIT_ROCKET_ARTILLERY';
	UPDATE Units SET PrereqTech = 'TECH_DYNAMITE' WHERE Type = 'UNIT_GATLINGGUN';
	UPDATE Units SET PrereqTech = 'TECH_GUNPOWDER' WHERE Type = 'UNIT_CANNON';
	UPDATE Units SET PrereqTech = 'TECH_BALLISTICS' WHERE Type = 'UNIT_ARTILLERY';
	UPDATE Units SET PrereqTech = 'TECH_MOBILE_TACTICS' WHERE Type = 'UNIT_BAZOOKA';


	-- Obsolete Techs
	UPDATE Units SET ObsoleteTech = 'TECH_MATHEMATICS' WHERE Type = 'UNIT_ARCHER';
	UPDATE Units SET ObsoleteTech = 'TECH_MACHINERY' WHERE Type = 'UNIT_INCAN_SLINGER';
	UPDATE Units SET ObsoleteTech = 'TECH_METALLURGY' WHERE Type = 'UNIT_CROSSBOWMAN';
	UPDATE Units SET ObsoleteTech = 'TECH_INDUSTRIALIZATION' WHERE Type = 'UNIT_ENGLISH_LONGBOWMAN';
	UPDATE Units SET ObsoleteTech = 'TECH_DYNAMITE' WHERE Type = 'UNIT_CHINESE_CHUKONU';
	UPDATE Units SET ObsoleteTech = 'TECH_METALLURGY' WHERE Type = 'UNIT_BABYLONIAN_BOWMAN';
	UPDATE Units SET ObsoleteTech = 'TECH_METALLURGY' WHERE Type = 'UNIT_MAYAN_ATLATLIST';
	UPDATE Units SET ObsoleteTech = 'TECH_PHYSICS' WHERE Type = 'UNIT_ROMAN_BALLISTA';
	UPDATE Units SET ObsoleteTech = 'TECH_ADVANCED_BALLISTICS' WHERE Type = 'UNIT_ARTILLERY';
	UPDATE Units SET ObsoleteTech = 'TECH_GUNPOWDER' WHERE Type = 'UNIT_TREBUCHET';
	UPDATE Units SET ObsoleteTech = 'TECH_RIFLING' WHERE Type = 'UNIT_KOREAN_HWACHA';
	UPDATE Units SET ObsoleteTech = 'TECH_DYNAMITE' WHERE Type = 'UNIT_MUSKETMAN';
	UPDATE Units SET ObsoleteTech = 'TECH_BALLISTICS' WHERE Type = 'UNIT_AMERICAN_MINUTEMAN';
	UPDATE Units SET ObsoleteTech = 'TECH_BALLISTICS' WHERE Type = 'UNIT_OTTOMAN_JANISSARY';
	UPDATE Units SET ObsoleteTech = 'TECH_RIFLING' WHERE Type = 'UNIT_CANNON';
	UPDATE Units SET ObsoleteTech = 'TECH_MOBILE_TACTICS' WHERE Type = 'UNIT_MACHINE_GUN';

	-- AI
	DELETE FROM Unit_AITypes WHERE UnitType = 'UNIT_AMERICAN_MINUTEMAN';
	DELETE FROM Unit_AITypes WHERE UnitType = 'UNIT_OTTOMAN_JANISSARY';
	DELETE FROM Unit_AITypes WHERE UnitType = 'UNIT_MUSKETMAN';

	INSERT INTO Unit_AITypes (UnitType, UnitAIType) VALUES 
	('UNIT_AMERICAN_MINUTEMAN', 'UNITAI_RANGED'),
	('UNIT_OTTOMAN_JANISSARY', 'UNITAI_RANGED'),
	('UNIT_MUSKETMAN', 'UNITAI_RANGED');

	UPDATE Units SET DefaultUnitAI = 'UNITAI_RANGED' WHERE Type = 'UNIT_AMERICAN_MINUTEMAN';
	UPDATE Units SET DefaultUnitAI = 'UNITAI_RANGED' WHERE Type = 'UNIT_OTTOMAN_JANISSARY';
	UPDATE Units SET DefaultUnitAI = 'UNITAI_RANGED' WHERE Type = 'UNIT_MUSKETMAN';

	-- Ancient Era Ranged now all Range 1
	--UPDATE Units SET Range = '1' WHERE Type = 'UNIT_ARCHER';
	--UPDATE Units SET Range = '1' WHERE Type = 'UNIT_BARBARIAN_ARCHER';
	--UPDATE Units SET Range = '1' WHERE Type = 'UNIT_INCAN_SLINGER';

	-- Musketman now ranged (Tercio Melee) - UUs splitting down middle
	UPDATE Units SET Range = '2' WHERE Type = 'UNIT_AMERICAN_MINUTEMAN';
	UPDATE Units SET Range = '2' WHERE Type = 'UNIT_MUSKETMAN';
	UPDATE Units SET Range = '2' WHERE Type = 'UNIT_OTTOMAN_JANISSARY';
	UPDATE Units SET CombatClass = 'UNITCOMBAT_ARCHER' WHERE Type = 'UNIT_AMERICAN_MINUTEMAN';
	UPDATE Units SET CombatClass = 'UNITCOMBAT_ARCHER' WHERE Type = 'UNIT_MUSKETMAN';
	UPDATE Units SET CombatClass = 'UNITCOMBAT_ARCHER' WHERE Type = 'UNIT_OTTOMAN_JANISSARY';
	
	-- Hand Axe
	UPDATE Units SET GoodyHutUpgradeUnitClass = 'UNITCLASS_COMPOSITE_BOWMAN' WHERE Type = 'UNIT_BARBARIAN_AXMAN';
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_COMPOSITE_BOWMAN' WHERE UnitType = 'UNIT_BARBARIAN_AXMAN';

	-- Upgrades	
	UPDATE Units SET GoodyHutUpgradeUnitClass = 'UNITCLASS_GATLINGGUN' WHERE Type = 'UNIT_MUSKETMAN';
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_GATLINGGUN' WHERE UnitType = 'UNIT_MUSKETMAN';

	UPDATE Units SET GoodyHutUpgradeUnitClass = 'UNITCLASS_MUSKETMAN' WHERE Type = 'UNIT_CROSSBOWMAN';
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_MUSKETMAN' WHERE UnitType = 'UNIT_CROSSBOWMAN';
	UPDATE Units SET IgnoreBuildingDefense = '1' WHERE Type = 'UNIT_GATLINGGUN';
	
	-- Gatling Gun, Machine Gun, Bazooka - make Range 2 (instead of 1) to help AI

	UPDATE Units SET Range = '2' WHERE Type = 'UNIT_GATLINGGUN';
	UPDATE Units SET Range = '2' WHERE Type = 'UNIT_MACHINE_GUN';
	UPDATE Units SET Range = '2' WHERE Type = 'UNIT_BAZOOKA';

	-- Make Rocket Artillery cost oil, not aluminum:
	UPDATE Unit_ResourceQuantityRequirements SET ResourceType = 'RESOURCE_IRON' WHERE UnitType = 'UNIT_ROCKET_ARTILLERY';

	-- Cannons and Artillery should cost Iron
	INSERT INTO Unit_ResourceQuantityRequirements (UnitType, ResourceType, Cost) VALUES ('UNIT_CANNON', 'RESOURCE_IRON', '1');
	INSERT INTO Unit_ResourceQuantityRequirements (UnitType, ResourceType, Cost) VALUES ('UNIT_ARTILLERY', 'RESOURCE_IRON', '1');

	-- Cannon should also transition into new field gun class
	UPDATE Units SET GoodyHutUpgradeUnitClass = 'UNITCLASS_FIELD_GUN' WHERE Type = 'UNIT_CANNON';
	UPDATE Unit_ClassUpgrades SET UnitClassType = 'UNITCLASS_FIELD_GUN' WHERE UnitType = 'UNIT_CANNON';
	
	--DefaultUnitAI fixes
	UPDATE Units SET DefaultUnitAI = 'UNITAI_RANGED' WHERE Type = 'UNIT_MACHINE_GUN';
	UPDATE Units SET DefaultUnitAI = 'UNITAI_RANGED' WHERE Type = 'UNIT_BAZOOKA';



	
