-- Move Coal to Steampower

	UPDATE Resources
	SET TechReveal = 'TECH_STEAM_POWER'
	WHERE Type = 'RESOURCE_COAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_UNITS' AND Value= 1 );
