-- Terrain 

UPDATE Terrains
SET Movement = '2'
WHERE Type = 'TERRAIN_DESERT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_TERRAIN' AND Value= 1 );

UPDATE Terrains
SET Movement = '2'
WHERE Type = 'TERRAIN_SNOW' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_TERRAIN' AND Value= 1 );




