--DO NOT MODIFY THIS--
CREATE TABLE IF NOT EXISTS CSD (
Type text,
Value variant default 0
);
--DO NOT MODIFY ABOVE--

-- CSD

UPDATE CustomModOptions
SET Value = '1'
WHERE Name = 'DIPLOMACY_CITYSTATES';

UPDATE CustomModOptions
SET Value = '1'
WHERE Name = 'DIPLOMACY_CITYSTATES_QUESTS';

UPDATE CustomModOptions
SET Value = '1'
WHERE Name = 'DIPLOMACY_CITYSTATES_RESOLUTIONS';

UPDATE CustomModOptions
SET Value = '1'
WHERE Name = 'DIPLOMACY_CITYSTATES_HURRY';