-- Sets default WorkWithWillingness and WorkAgainstWillingness values for all base game leaders
-- These are unused base game columns that are being repurposed
UPDATE Leaders SET WorkWithWillingness = DoFWillingness;
UPDATE Leaders SET WorkAgainstWillingness = DenounceWillingness;

-- Sets default victory pursuits for all base game leaders
CREATE TEMP TABLE Leader_VictoryPursuits (
	TempLeaderType text,
	PrimaryVictoryPursuit text,
	SecondaryVictoryPursuit text
);

INSERT INTO Leader_VictoryPursuits
VALUES
	('LEADER_AHMAD_ALMANSUR', 'VICTORY_PURSUIT_DIPLOMACY', 'VICTORY_PURSUIT_CULTURE'),
	('LEADER_ALEXANDER', 'VICTORY_PURSUIT_DIPLOMACY', 'VICTORY_PURSUIT_DOMINATION'),
	('LEADER_ASHURBANIPAL', 'VICTORY_PURSUIT_DOMINATION', 'VICTORY_PURSUIT_SCIENCE'),
	('LEADER_ASKIA', 'VICTORY_PURSUIT_DOMINATION', NULL),
	('LEADER_ATTILA', 'VICTORY_PURSUIT_DOMINATION', NULL),
	('LEADER_AUGUSTUS', 'VICTORY_PURSUIT_DOMINATION', NULL),
	('LEADER_BISMARCK', 'VICTORY_PURSUIT_DOMINATION', 'VICTORY_PURSUIT_DIPLOMACY'),
	('LEADER_BOUDICCA', NULL, NULL),
	('LEADER_CASIMIR', NULL, NULL),
	('LEADER_CATHERINE', 'VICTORY_PURSUIT_DOMINATION', 'VICTORY_PURSUIT_SCIENCE'),
	('LEADER_DARIUS', 'VICTORY_PURSUIT_CULTURE', 'VICTORY_PURSUIT_DOMINATION'),
	('LEADER_DIDO', 'VICTORY_PURSUIT_DOMINATION', 'VICTORY_PURSUIT_DIPLOMACY'),
	('LEADER_ELIZABETH', 'VICTORY_PURSUIT_DOMINATION', 'VICTORY_PURSUIT_SCIENCE'),
	('LEADER_ENRICO_DANDOLO', 'VICTORY_PURSUIT_DIPLOMACY', NULL),
	('LEADER_GAJAH_MADA', NULL, NULL),
	('LEADER_GANDHI', 'VICTORY_PURSUIT_SCIENCE', 'VICTORY_PURSUIT_CULTURE'),
	('LEADER_GENGHIS_KHAN', 'VICTORY_PURSUIT_DOMINATION', NULL),
	('LEADER_GUSTAVUS_ADOLPHUS', 'VICTORY_PURSUIT_DIPLOMACY', NULL),
	('LEADER_HARALD', 'VICTORY_PURSUIT_DOMINATION', NULL),
	('LEADER_HARUN_AL_RASHID', 'VICTORY_PURSUIT_DOMINATION', 'VICTORY_PURSUIT_DIPLOMACY'),
	('LEADER_HIAWATHA', NULL, NULL),
	('LEADER_ISABELLA', 'VICTORY_PURSUIT_DOMINATION', 'VICTORY_PURSUIT_CULTURE'),
	('LEADER_KAMEHAMEHA', 'VICTORY_PURSUIT_CULTURE', NULL),
	('LEADER_MARIA', 'VICTORY_PURSUIT_DIPLOMACY', NULL),
	('LEADER_MARIA_I', 'VICTORY_PURSUIT_DIPLOMACY', NULL),
	('LEADER_MONTEZUMA', 'VICTORY_PURSUIT_DOMINATION', 'VICTORY_PURSUIT_SCIENCE'),
	('LEADER_NAPOLEON', NULL, NULL),
	('LEADER_NEBUCHADNEZZAR', 'VICTORY_PURSUIT_SCIENCE', NULL),
	('LEADER_ODA_NOBUNAGA', 'VICTORY_PURSUIT_DOMINATION', NULL),
	('LEADER_PACAL', 'VICTORY_PURSUIT_SCIENCE', NULL),
	('LEADER_PACHACUTI', 'VICTORY_PURSUIT_SCIENCE', 'VICTORY_PURSUIT_DOMINATION'),
	('LEADER_PEDRO', 'VICTORY_PURSUIT_CULTURE', NULL),
	('LEADER_POCATELLO', NULL, NULL),
	('LEADER_RAMESSES', 'VICTORY_PURSUIT_CULTURE', NULL),
	('LEADER_RAMKHAMHAENG', 'VICTORY_PURSUIT_DIPLOMACY', NULL),
	('LEADER_SEJONG', 'VICTORY_PURSUIT_SCIENCE', NULL),
	('LEADER_SELASSIE', 'VICTORY_PURSUIT_CULTURE', NULL),
	('LEADER_SHAKA', 'VICTORY_PURSUIT_DOMINATION', NULL),
	('LEADER_SULEIMAN', 'VICTORY_PURSUIT_DOMINATION', NULL),
	('LEADER_THEODORA', 'VICTORY_PURSUIT_CULTURE', 'VICTORY_PURSUIT_DOMINATION'),
	('LEADER_WASHINGTON', 'VICTORY_PURSUIT_DOMINATION', 'VICTORY_PURSUIT_SCIENCE'),
	('LEADER_WILLIAM', 'VICTORY_PURSUIT_DIPLOMACY', NULL),
	('LEADER_WU_ZETIAN', 'VICTORY_PURSUIT_DOMINATION', 'VICTORY_PURSUIT_SCIENCE');

UPDATE Leaders
SET
	PrimaryVictoryPursuit = (SELECT PrimaryVictoryPursuit FROM Leader_VictoryPursuits WHERE TempLeaderType = Type),
	SecondaryVictoryPursuit = (SELECT SecondaryVictoryPursuit FROM Leader_VictoryPursuits WHERE TempLeaderType = Type)
WHERE EXISTS (SELECT 1 FROM Leader_VictoryPursuits WHERE TempLeaderType = Type);

DROP TABLE Leader_VictoryPursuits;
