-- PANTHEONS

-- Goddess of the Hunt
DELETE FROM Belief_ImprovementYieldChanges
WHERE BeliefType = 'BELIEF_GODDESS_HUNT';

UPDATE Beliefs
SET RequiresResource = '1'
WHERE Type = 'BELIEF_GODDESS_HUNT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- Fertility Rites
UPDATE Beliefs
SET CityGrowthModifier = '25'
WHERE Type = 'BELIEF_FERTILITY_RITES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

INSERT INTO Belief_YieldPerConstruction
	(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_FERTILITY_RITES', 'YIELD_FAITH', 8),
	('BELIEF_FERTILITY_RITES', 'YIELD_FOOD', 8);

-- God of Craftsmen
DELETE FROM Beliefs
WHERE Type = 'BELIEF_GOD_CRAFTSMEN';

DELETE FROM Belief_CityYieldChanges
WHERE BeliefType = 'BELIEF_GOD_CRAFTSMEN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- God of the Sea
UPDATE Belief_ImprovementYieldChanges
SET YieldType = 'YIELD_FAITH'
WHERE BeliefType = 'BELIEF_GOD_SEA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Belief_ImprovementYieldChanges
SET Yield = '1'
WHERE BeliefType = 'BELIEF_GOD_SEA' AND YieldType = 'YIELD_FAITH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- God of the Open Sky

UPDATE Belief_ImprovementYieldChanges
SET YieldType = 'YIELD_FAITH'
WHERE BeliefType = 'BELIEF_OPEN_SKY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Belief_ImprovementYieldChanges
SET Yield = '1'
WHERE BeliefType = 'BELIEF_OPEN_SKY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET RequiresNoImprovementFeature = '1'
WHERE Type = 'BELIEF_OPEN_SKY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- Messenger of the Gods
UPDATE Belief_YieldChangeTradeRoute
SET YieldType = 'YIELD_GOLD'
WHERE BeliefType = 'BELIEF_MESSENGER_GODS' AND YieldType = 'YIELD_SCIENCE';

-- One With Nature
UPDATE Belief_YieldChangeNaturalWonder
SET Yield = '3'
WHERE YieldType = 'YIELD_FAITH' AND BeliefType = 'BELIEF_ONE_WITH_NATURE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- Liturgy (Now Goddess of Wisdom)

DELETE FROM Belief_ResourceYieldChanges
WHERE BeliefType = 'BELIEF_FORMAL_LITURGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- Stone Circles
DELETE FROM Belief_ImprovementYieldChanges
WHERE BeliefType = 'BELIEF_STONE_CIRCLES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- God of War
UPDATE Beliefs
SET MaxDistance = '0'
WHERE Type = 'BELIEF_GOD_WAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET FaithFromKills = '225'
WHERE Type = 'BELIEF_GOD_WAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET UnitProductionModifier = '10'
WHERE Type = 'BELIEF_GOD_WAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET CityRangeStrikeModifier = '10'
WHERE Type = 'BELIEF_GOD_WAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- Sacred Waters

-- Goddess of Love
UPDATE Beliefs
SET MinPopulation = '3'
WHERE Type = 'BELIEF_GODDESS_LOVE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET HappinessPerCity = '0'
WHERE Type = 'BELIEF_GODDESS_LOVE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

INSERT INTO Belief_CityYieldChanges
	(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_GODDESS_LOVE', 'YIELD_FAITH', 1),
	('BELIEF_GODDESS_LOVE', 'YIELD_GOLD', 2),
	('BELIEF_GODDESS_LOVE', 'YIELD_PRODUCTION', 3);

INSERT INTO Belief_SpecialistYieldChanges
	(BeliefType, SpecialistType, YieldType, Yield)
VALUES
	('BELIEF_GODDESS_LOVE', 'SPECIALIST_ENGINEER', 'YIELD_FAITH', 1),
	('BELIEF_GODDESS_LOVE', 'SPECIALIST_ENGINEER', 'YIELD_PRODUCTION', 1);

-- Religious Settlements

UPDATE Beliefs
SET PlotCultureCostModifier = '-25'
WHERE Type = 'BELIEF_RELIGIOUS_SETTLEMENTS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- God of Festivals
DELETE FROM Belief_ResourceYieldChanges
WHERE BeliefType = 'BELIEF_GOD_FESTIVALS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- Oral Tradition

UPDATE Belief_ImprovementYieldChanges
SET YieldType = 'YIELD_GOLD'
WHERE BeliefType = 'BELIEF_ORAL_TRADITION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Belief_ImprovementYieldChanges
SET Yield = '1'
WHERE BeliefType = 'BELIEF_ORAL_TRADITION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- Ancestor Worship
DELETE FROM Belief_BuildingClassYieldChanges
WHERE BeliefType = 'BELIEF_ANCESTOR_WORSHIP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

--Desert Folklore
UPDATE Belief_TerrainYieldChanges
SET Yield = '1'
WHERE YieldType = 'YIELD_FAITH' AND BeliefType = 'BELIEF_DESERT_FOLKLORE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET RequiresResource = '1'
WHERE Type = 'BELIEF_DESERT_FOLKLORE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- Sacred Path

DELETE FROM Belief_FeatureYieldChanges
WHERE BeliefType = 'BELIEF_SACRED_PATH' AND FeatureType = 'FEATURE_JUNGLE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- Goddess of Protection
UPDATE Beliefs
SET FriendlyHealChange = '10'
WHERE Type = 'BELIEF_GODDESS_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET CityRangeStrikeModifier = '0'
WHERE Type = 'BELIEF_GODDESS_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- Faith Healers
DELETE FROM Beliefs
WHERE Type = 'BELIEF_FAITH_HEALERS';

-- Monuments to the Gods
UPDATE Beliefs
SET WonderProductionModifier = '0'
WHERE Type = 'BELIEF_MONUMENT_GODS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

INSERT INTO Belief_GreatWorkYieldChanges(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_MONUMENT_GODS', 'YIELD_FAITH', '1');

INSERT INTO Belief_GreatPersonPoints
	(BeliefType, GreatPersonType, Value)
VALUES
	('BELIEF_MONUMENT_GODS', 'GREATPERSON_ARTIST', 2),
	('BELIEF_MONUMENT_GODS', 'GREATPERSON_ENGINEER', 2);

-- Dance of the Aurora
UPDATE Belief_TerrainYieldChanges
SET Yield = '1'
WHERE YieldType = 'YIELD_FAITH' AND BeliefType = 'BELIEF_DANCE_AURORA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET RequiresResource = '1'
WHERE Type = 'BELIEF_DANCE_AURORA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

--  Tears of the Gods (Now Polytheism)

DELETE FROM Belief_ResourceYieldChanges
WHERE BeliefType = 'BELIEF_TEARS_OF_GODS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- Earth Mother
DELETE FROM Belief_ResourceYieldChanges
WHERE BeliefType = 'BELIEF_EARTH_MOTHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET RequiresResource = '1'
WHERE Type = 'BELIEF_EARTH_MOTHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- God-King
DELETE FROM Belief_BuildingClassYieldChanges
WHERE BeliefType = 'BELIEF_GOD_KING' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

-- Sun God

DELETE FROM Belief_ResourceYieldChanges
WHERE BeliefType = 'BELIEF_SUN_GOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET RequiresResource = '1'
WHERE Type = 'BELIEF_SUN_GOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET RequiresImprovement = '1'
WHERE Type = 'BELIEF_SUN_GOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );


INSERT INTO Belief_ImprovementYieldChanges
	(BeliefType, ImprovementType, YieldType, Yield)
VALUES
	('BELIEF_GODDESS_HUNT', 'IMPROVEMENT_CAMP', 'YIELD_FAITH', 1),
	('BELIEF_GODDESS_HUNT', 'IMPROVEMENT_CAMP', 'YIELD_FOOD', 1),
	('BELIEF_GODDESS_HUNT', 'IMPROVEMENT_CAMP', 'YIELD_CULTURE', 1),
	('BELIEF_EARTH_MOTHER', 'IMPROVEMENT_MINE', 'YIELD_FAITH', 1),
	('BELIEF_EARTH_MOTHER', 'IMPROVEMENT_MINE', 'YIELD_CULTURE', 1),
	('BELIEF_OPEN_SKY', 'IMPROVEMENT_PASTURE', 'YIELD_GOLD', 3),
	('BELIEF_SUN_GOD', 'IMPROVEMENT_FARM', 'YIELD_FOOD', 3),
	('BELIEF_ORAL_TRADITION', 'IMPROVEMENT_PLANTATION', 'YIELD_FOOD', 1),
	('BELIEF_ORAL_TRADITION', 'IMPROVEMENT_PLANTATION', 'YIELD_FAITH', 1),
	('BELIEF_GOD_SEA', 'IMPROVEMENT_FISHING_BOATS', 'YIELD_PRODUCTION', 1),
	('BELIEF_STONE_CIRCLES', 'IMPROVEMENT_QUARRY', 'YIELD_FAITH', 1),
	('BELIEF_STONE_CIRCLES', 'IMPROVEMENT_QUARRY', 'YIELD_PRODUCTION', 1);

INSERT INTO Belief_CoastalCityYieldChanges
	(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_GOD_SEA', 'YIELD_FOOD', 2),
	('BELIEF_GOD_SEA', 'YIELD_FAITH', 1);

INSERT INTO Belief_BuildingClassYieldChanges
	(BeliefType, BuildingClassType, YieldType, YieldChange)
VALUES
	('BELIEF_TEARS_OF_GODS', 'BUILDINGCLASS_MONUMENT', 'YIELD_FAITH', 1),
	('BELIEF_TEARS_OF_GODS', 'BUILDINGCLASS_PALACE', 'YIELD_CULTURE', 1),
	('BELIEF_MONUMENT_GODS', 'BUILDINGCLASS_PALACE', 'YIELD_FAITH', 2),
	('BELIEF_GOD_KING', 'BUILDINGCLASS_PALACE', 'YIELD_FAITH', 1),
	('BELIEF_FERTILITY_RITES', 'BUILDINGCLASS_SHRINE', 'YIELD_FOOD', 1),
	('BELIEF_FERTILITY_RITES', 'BUILDINGCLASS_SHRINE', 'YIELD_FAITH', 1),
	('BELIEF_EARTH_MOTHER', 'BUILDINGCLASS_MONUMENT', 'YIELD_FAITH', 1),
	('BELIEF_EARTH_MOTHER', 'BUILDINGCLASS_MONUMENT', 'YIELD_PRODUCTION', 1),
	('BELIEF_GOD_FESTIVALS', 'BUILDINGCLASS_PALACE', 'YIELD_FAITH', 1),
	('BELIEF_GODDESS_STRATEGY', 'BUILDINGCLASS_PALACE', 'YIELD_FAITH', 2),
	('BELIEF_GODDESS_STRATEGY', 'BUILDINGCLASS_PALACE', 'YIELD_CULTURE', 1),
	('BELIEF_GODDESS_STRATEGY', 'BUILDINGCLASS_BARRACKS', 'YIELD_FAITH', 2),
	('BELIEF_GODDESS_STRATEGY', 'BUILDINGCLASS_BARRACKS', 'YIELD_CULTURE', 1),
	('BELIEF_GODDESS_STRATEGY', 'BUILDINGCLASS_WALLS', 'YIELD_FAITH', 2),
	('BELIEF_GODDESS_STRATEGY', 'BUILDINGCLASS_WALLS', 'YIELD_CULTURE', 1),
	('BELIEF_STONE_CIRCLES', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_FAITH', 1),
	('BELIEF_STONE_CIRCLES', 'BUILDINGCLASS_STONE_WORKS', 'YIELD_PRODUCTION', 1),
	('BELIEF_STONE_CIRCLES', 'BUILDINGCLASS_PALACE', 'YIELD_FAITH', 2),
	('BELIEF_STONE_CIRCLES', 'BUILDINGCLASS_PALACE', 'YIELD_SCIENCE', 1),
	('BELIEF_STONE_CIRCLES', 'BUILDINGCLASS_PALACE', 'YIELD_CULTURE', 1),
	('BELIEF_SACRED_PATH', 'BUILDINGCLASS_MARKET', 'YIELD_SCIENCE', 2),
	('BELIEF_SACRED_PATH', 'BUILDINGCLASS_MARKET', 'YIELD_FOOD', 2),
	('BELIEF_SUN_GOD', 'BUILDINGCLASS_GRANARY', 'YIELD_FAITH', 3),
	('BELIEF_SUN_GOD', 'BUILDINGCLASS_GRANARY', 'YIELD_GOLD', 2),
	('BELIEF_ORAL_TRADITION', 'BUILDINGCLASS_HERBALIST', 'YIELD_SCIENCE', 1),
	('BELIEF_ORAL_TRADITION', 'BUILDINGCLASS_HERBALIST', 'YIELD_FAITH', 2),
	('BELIEF_ANCESTOR_WORSHIP', 'BUILDINGCLASS_GROVE', 'YIELD_FAITH', 1),
	('BELIEF_ANCESTOR_WORSHIP', 'BUILDINGCLASS_GROVE', 'YIELD_CULTURE', 1);

INSERT INTO Belief_YieldFromKnownPantheons
	(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_TEARS_OF_GODS', 'YIELD_FOOD', 50),
	('BELIEF_TEARS_OF_GODS', 'YIELD_GOLD', 50),
	('BELIEF_TEARS_OF_GODS', 'YIELD_PRODUCTION', 50),
	('BELIEF_TEARS_OF_GODS', 'YIELD_SCIENCE', 50);

INSERT INTO Belief_YieldPerPop
	(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_ANCESTOR_WORSHIP', 'YIELD_FAITH', 3);

INSERT INTO Belief_YieldPerLux
	(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_GOD_FESTIVALS', 'YIELD_FAITH', 1),
	('BELIEF_GOD_FESTIVALS', 'YIELD_CULTURE', 1),
	('BELIEF_GOD_FESTIVALS', 'YIELD_GOLD', 3);


INSERT INTO Belief_YieldChangeTradeRoute
	(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_MESSENGER_GODS', 'YIELD_FAITH', 2);

INSERT INTO Belief_YieldPerActiveTR
	(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_MESSENGER_GODS', 'YIELD_GOLD', 2),
	('BELIEF_MESSENGER_GODS', 'YIELD_FAITH', 2);

INSERT INTO Belief_GreatPersonPoints
	(BeliefType, GreatPersonType, Value)
VALUES
	('BELIEF_MESSENGER_GODS', 'GREATPERSON_MERCHANT', 2);

INSERT INTO Belief_YieldChangeWorldWonder
	(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_MONUMENT_GODS', 'YIELD_FAITH', 2);

INSERT INTO Belief_YieldChangeNaturalWonder
	(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_ONE_WITH_NATURE', 'YIELD_CULTURE', 2);

INSERT INTO Belief_YieldPerBorderGrowth
	(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_RELIGIOUS_SETTLEMENTS', 'YIELD_FAITH', 20),
	('BELIEF_RELIGIOUS_SETTLEMENTS', 'YIELD_PRODUCTION', 10);

INSERT INTO Belief_FeatureYieldChanges
	(BeliefType, FeatureType, YieldType, Yield)
VALUES
	('BELIEF_SACRED_WATERS', 'FEATURE_MARSH', 'YIELD_FOOD', 1),
	('BELIEF_SACRED_WATERS', 'FEATURE_MARSH', 'YIELD_FAITH', 1),
	('BELIEF_SACRED_WATERS', 'FEATURE_MARSH', 'YIELD_PRODUCTION', 1),
	('BELIEF_GOD_SEA', 'FEATURE_ATOLL', 'YIELD_FAITH', 1),
	('BELIEF_GOD_SEA', 'FEATURE_ATOLL', 'YIELD_PRODUCTION', 1),
	('BELIEF_DESERT_FOLKLORE', 'FEATURE_OASIS', 'YIELD_FOOD', 3);

INSERT INTO Belief_LakePlotYield
	(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_SACRED_WATERS', 'YIELD_FAITH', 1),
	('BELIEF_SACRED_WATERS', 'YIELD_FOOD', 1);

INSERT INTO Belief_CityYieldChanges
	(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_FORMAL_LITURGY', 'YIELD_FAITH', 1),
	('BELIEF_FORMAL_LITURGY', 'YIELD_SCIENCE', 1);

INSERT Into Belief_YieldChangeAnySpecialist
(BeliefType, YieldType, Yield)
VALUES
	('BELIEF_FORMAL_LITURGY', 'YIELD_FAITH', 2),
	('BELIEF_FORMAL_LITURGY', 'YIELD_SCIENCE', 2);

INSERT INTO Belief_GreatPersonPoints
	(BeliefType, GreatPersonType, Value)
VALUES
	('BELIEF_FORMAL_LITURGY', 'GREATPERSON_SCIENTIST', 2);

INSERT INTO Belief_TerrainYieldChanges
	(BeliefType, TerrainType, YieldType, Yield)
VALUES
	('BELIEF_DESERT_FOLKLORE', 'TERRAIN_DESERT', 'YIELD_PRODUCTION', 1),
	('BELIEF_DESERT_FOLKLORE', 'TERRAIN_DESERT', 'YIELD_GOLD', 1),
	('BELIEF_DANCE_AURORA', 'TERRAIN_TUNDRA', 'YIELD_GOLD', 1),
	('BELIEF_DANCE_AURORA', 'TERRAIN_TUNDRA', 'YIELD_CULTURE', 1),
	('BELIEF_GODDESS_HUNT', 'TERRAIN_TUNDRA', 'YIELD_FOOD', 1);

INSERT INTO Belief_YieldPerXFollowers
	(BeliefType, YieldType, PerXFollowers)
VALUES
	('BELIEF_GOD_KING', 'YIELD_FAITH', 5),
	('BELIEF_GOD_KING', 'YIELD_GOLD', 5),
	('BELIEF_GOD_KING', 'YIELD_CULTURE', 5),
	('BELIEF_GOD_KING', 'YIELD_GOLDEN_AGE_POINTS', 5),
	('BELIEF_GOD_KING', 'YIELD_SCIENCE', 5);

INSERT INTO Belief_CityYieldPerXTerrainTimes100
	(BeliefType, TerrainType, YieldType, Yield)
VALUES
	('BELIEF_OPEN_SKY', 'TERRAIN_PLAINS', 'YIELD_CULTURE', 50),
	('BELIEF_OPEN_SKY', 'TERRAIN_GRASS', 'YIELD_CULTURE', 50),
	('BELIEF_OPEN_SKY', 'TERRAIN_PLAINS', 'YIELD_FAITH', 50),
	('BELIEF_OPEN_SKY', 'TERRAIN_GRASS', 'YIELD_FAITH', 50),
	('BELIEF_ONE_WITH_NATURE', 'TERRAIN_MOUNTAIN', 'YIELD_FAITH', 50),
	('BELIEF_ONE_WITH_NATURE', 'TERRAIN_MOUNTAIN', 'YIELD_GOLD', 50),
	('BELIEF_ONE_WITH_NATURE', 'TERRAIN_MOUNTAIN', 'YIELD_FOOD', 50);

INSERT INTO Belief_CityYieldPerXFeatureTimes100
	(BeliefType, FeatureType, YieldType, Yield)
VALUES
	('BELIEF_SACRED_PATH', 'FEATURE_FOREST', 'YIELD_CULTURE', 50),
	('BELIEF_SACRED_PATH', 'FEATURE_JUNGLE', 'YIELD_CULTURE', 50),
	('BELIEF_SACRED_PATH', 'FEATURE_FOREST', 'YIELD_SCIENCE', 50),
	('BELIEF_SACRED_PATH', 'FEATURE_JUNGLE', 'YIELD_SCIENCE', 50),
	('BELIEF_SACRED_PATH', 'FEATURE_JUNGLE', 'YIELD_FAITH', 50),
	('BELIEF_SACRED_PATH', 'FEATURE_FOREST', 'YIELD_FAITH', 50);


UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_SUN_GOD'
WHERE Type = 'BELIEF_SUN_GOD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_GOD_KING'
WHERE Type = 'BELIEF_GOD_KING' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_EARTH_MOTHER'
WHERE Type = 'BELIEF_EARTH_MOTHER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_TEARS_OF_GODS'
WHERE Type = 'BELIEF_TEARS_OF_GODS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_DANCE_AURORA'
WHERE Type = 'BELIEF_DANCE_AURORA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_MONUMENT_GODS'
WHERE Type = 'BELIEF_MONUMENT_GODS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_GODDESS_STRATEGY'
WHERE Type = 'BELIEF_GODDESS_STRATEGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_SACRED_PATH'
WHERE Type = 'BELIEF_SACRED_PATH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_DESERT_FOLKLORE'
WHERE Type = 'BELIEF_DESERT_FOLKLORE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_ANCESTOR_WORSHIP'
WHERE Type = 'BELIEF_ANCESTOR_WORSHIP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_ORAL_TRADITION'
WHERE Type = 'BELIEF_ORAL_TRADITION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_GOD_FESTIVALS'
WHERE Type = 'BELIEF_GOD_FESTIVALS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_RELIGIOUS_SETTLEMENTS'
WHERE Type = 'BELIEF_RELIGIOUS_SETTLEMENTS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_GODDESS_LOVE'
WHERE Type = 'BELIEF_GODDESS_LOVE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_SACRED_WATERS'
WHERE Type = 'BELIEF_SACRED_WATERS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_GOD_WAR'
WHERE Type = 'BELIEF_GOD_WAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_STONE_CIRCLES'
WHERE Type = 'BELIEF_STONE_CIRCLES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_FORMAL_LITURGY'
WHERE Type = 'BELIEF_FORMAL_LITURGY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_ONE_WITH_NATURE'
WHERE Type = 'BELIEF_ONE_WITH_NATURE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_MESSENGER_GODS'
WHERE Type = 'BELIEF_MESSENGER_GODS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_OPEN_SKY'
WHERE Type = 'BELIEF_OPEN_SKY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_GOD_SEA'
WHERE Type = 'BELIEF_GOD_SEA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_FERTILITY_RITES'
WHERE Type = 'BELIEF_FERTILITY_RITES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

UPDATE Beliefs
SET Tooltip = 'TXT_KEY_BELIEF_GODDESS_HUNT'
WHERE Type = 'BELIEF_GODDESS_HUNT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_RELIGION' AND Value= 1 );

