-- Common properties
UPDATE Corporations
SET
	BaseFranchises = 3,
	NumFreeTradeRoutes = 1,
	RandomSpreadChance = 5,
	TourismModNumFranchises = 2;

-- Update non-standard TR numbers
UPDATE Corporations SET NumFreeTradeRoutes = 2 WHERE Type IN ('CORPORATION_CIVILIZED_JEWELERS', 'CORPORATION_POPULI_MEDICINE');

UPDATE Corporations SET NumFreeTradeRoutes = 3 WHERE Type = 'CORPORATION_TRADER_SIDS';

-- Required monopolies for corporations
INSERT INTO Corporation_ResourceMonopolyOrs
	(CorporationType, ResourceType)
VALUES
	('CORPORATION_TRADER_SIDS', 'RESOURCE_COCOA'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_SALT'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_SPICES'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_SUGAR'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_CLOVES'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_NUTMEG'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_PEPPER'),
	('CORPORATION_TRADER_SIDS', 'RESOURCE_COFFEE'),
	('CORPORATION_CENTAURUS_EXTRACTORS', 'RESOURCE_WHALE'),
	('CORPORATION_CENTAURUS_EXTRACTORS', 'RESOURCE_CRAB'),
	('CORPORATION_CENTAURUS_EXTRACTORS', 'RESOURCE_CORAL'),
	('CORPORATION_CENTAURUS_EXTRACTORS', 'RESOURCE_PEARLS'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_COAL'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_OIL'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_URANIUM'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_GLASS'),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_BRAZILWOOD'),
	('CORPORATION_GIORGIO_ARMEIER', 'RESOURCE_SILK'),
	('CORPORATION_GIORGIO_ARMEIER', 'RESOURCE_COTTON'),
	('CORPORATION_GIORGIO_ARMEIER', 'RESOURCE_DYE'),
	('CORPORATION_GIORGIO_ARMEIER', 'RESOURCE_FUR'),
	('CORPORATION_GIORGIO_ARMEIER', 'RESOURCE_PERFUME'),
	('CORPORATION_FIRAXITE_MATERIALS', 'RESOURCE_IRON'),
	('CORPORATION_FIRAXITE_MATERIALS', 'RESOURCE_ALUMINUM'),
	('CORPORATION_FIRAXITE_MATERIALS', 'RESOURCE_MARBLE'),
	('CORPORATION_FIRAXITE_MATERIALS', 'RESOURCE_COPPER'),
	('CORPORATION_FIRAXITE_MATERIALS', 'RESOURCE_PORCELAIN'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_HORSE'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_WINE'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_TRUFFLES'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_CITRUS'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_OLIVE'),
	('CORPORATION_TWOKAY_FOODS', 'RESOURCE_COFFEE'),
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_GOLD'),
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_SILVER'),
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_GEMS'),
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_AMBER'),
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_JEWELRY'),
	('CORPORATION_CIVILIZED_JEWELERS', 'RESOURCE_LAPIS'),
	('CORPORATION_POPULI_MEDICINE', 'RESOURCE_IVORY'),
	('CORPORATION_POPULI_MEDICINE', 'RESOURCE_TOBACCO'),
	('CORPORATION_POPULI_MEDICINE', 'RESOURCE_INCENSE'),
	('CORPORATION_POPULI_MEDICINE', 'RESOURCE_JADE'),
	('CORPORATION_POPULI_MEDICINE', 'RESOURCE_TEA');

-- Corporation boosts buildings
INSERT INTO Corporation_BuildingClassYieldChanges
	(CorporationType, BuildingClassType, YieldType, YieldChange)
VALUES
	('CORPORATION_TRADER_SIDS', 'BUILDINGCLASS_BROADCAST_TOWER', 'YIELD_GOLD', 4),
	('CORPORATION_CENTAURUS_EXTRACTORS', 'BUILDINGCLASS_MINEFIELD', 'YIELD_PRODUCTION', 8),
	('CORPORATION_HEXXON_REFINERY', 'BUILDINGCLASS_REFINERY', 'YIELD_PRODUCTION', 5),
	('CORPORATION_HEXXON_REFINERY', 'BUILDINGCLASS_REFINERY', 'YIELD_SCIENCE', 5),
	('CORPORATION_HEXXON_REFINERY', 'BUILDINGCLASS_REFINERY', 'YIELD_CULTURE_LOCAL', 5),
	('CORPORATION_GIORGIO_ARMEIER', 'BUILDINGCLASS_SHOPPING_MALL', 'YIELD_CULTURE', 4),
	('CORPORATION_FIRAXITE_MATERIALS', 'BUILDINGCLASS_STOCK_EXCHANGE', 'YIELD_SCIENCE', 3),
	('CORPORATION_TWOKAY_FOODS', 'BUILDINGCLASS_AGRIBUSINESS', 'YIELD_FOOD', 5),
	('CORPORATION_CIVILIZED_JEWELERS', 'BUILDINGCLASS_AIRPORT', 'YIELD_TOURISM', 5),
	('CORPORATION_POPULI_MEDICINE', 'BUILDINGCLASS_HOSPITAL', 'YIELD_FAITH', 3);

-- Corporation boosts specialist yields
INSERT INTO Corporation_SpecialistYieldChanges
	(CorporationType, SpecialistType, YieldType, Yield)
VALUES
	('CORPORATION_TRADER_SIDS', 'SPECIALIST_MERCHANT', 'YIELD_FOOD', 3),
	-- centaurus all specialists below
	('CORPORATION_HEXXON_REFINERY', 'SPECIALIST_ENGINEER', 'YIELD_SCIENCE', 2),
	('CORPORATION_GIORGIO_ARMEIER', 'SPECIALIST_ARTIST', 'YIELD_CULTURE', 2),
	('CORPORATION_GIORGIO_ARMEIER', 'SPECIALIST_ARTIST', 'YIELD_GOLD', 2),
	('CORPORATION_GIORGIO_ARMEIER', 'SPECIALIST_ARTIST', 'YIELD_TOURISM', 2),
	('CORPORATION_FIRAXITE_MATERIALS', 'SPECIALIST_SCIENTIST', 'YIELD_PRODUCTION', 2),
	-- no twokay bonus
	-- jewellers all specialists below
	('CORPORATION_POPULI_MEDICINE', 'SPECIALIST_CIVIL_SERVANT', 'YIELD_GOLD', 3);

INSERT INTO Corporation_SpecialistYieldChanges
	(CorporationType, SpecialistType, YieldType, Yield)
SELECT
	'CORPORATION_CENTAURUS_EXTRACTORS', Type, 'YIELD_TOURISM', 1
FROM Specialists WHERE GreatPeopleUnitClass IS NOT NULL;

INSERT INTO Corporation_SpecialistYieldChanges
	(CorporationType, SpecialistType, YieldType, Yield)
SELECT
	'CORPORATION_CIVILIZED_JEWELERS', Type, 'YIELD_GOLD', 1
FROM Specialists WHERE GreatPeopleUnitClass IS NOT NULL;
	
-- Corporation gives a flat number of free resources
INSERT INTO Corporation_NumFreeResource
	(CorporationType, ResourceType, NumResource)
VALUES
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_OIL', 5),
	('CORPORATION_HEXXON_REFINERY', 'RESOURCE_COAL', 5);

-- Office boosts yields of international trade routes targeting cities with franchise
INSERT INTO Corporation_TradeRouteMod
	(CorporationType, YieldType, Yield)
VALUES
	('CORPORATION_TRADER_SIDS', 'YIELD_GOLD', 25),
	('CORPORATION_HEXXON_REFINERY', 'YIELD_SCIENCE', 50);

-- Office boosts city yields for each trade route targeting a city with franchise (works with nationalized corporations)
INSERT INTO Corporation_TradeRouteCityYield
	(CorporationType, YieldType, Yield)
VALUES
	('CORPORATION_CENTAURUS_EXTRACTORS', 'YIELD_PRODUCTION', 3),
	('CORPORATION_GIORGIO_ARMEIER', 'YIELD_CULTURE', 3),
	('CORPORATION_FIRAXITE_MATERIALS', 'YIELD_SCIENCE', 3),
	('CORPORATION_TWOKAY_FOODS', 'YIELD_FOOD', 3),
	('CORPORATION_CIVILIZED_JEWELERS', 'YIELD_GOLD', 3),
	('CORPORATION_POPULI_MEDICINE', 'YIELD_FAITH', 3);

-- Franchise boosts resources
-- and so do Offices (this must load before BuildingChanges2.sql)
INSERT INTO Corporation_ResourceYieldChanges
	(CorporationType, ResourceType, YieldType, Yield)
SELECT DISTINCT
	a.CorporationType, a.ResourceType, b.YieldType, 3
FROM Corporation_ResourceMonopolyOrs a
INNER JOIN Corporation_BuildingClassYieldChanges b
ON a.CorporationType = b.CorporationType
WHERE b.YieldType IN ('YIELD_CULTURE', 'YIELD_FAITH', 'YIELD_SCIENCE', 'YIELD_TOURISM');

INSERT INTO Corporation_ResourceYieldChanges
	(CorporationType, ResourceType, YieldType, Yield)
SELECT DISTINCT
	a.CorporationType, a.ResourceType, b.YieldType, 5
FROM Corporation_ResourceMonopolyOrs a
INNER JOIN Corporation_BuildingClassYieldChanges b
ON a.CorporationType = b.CorporationType
WHERE b.YieldType IN ('YIELD_FOOD', 'YIELD_PRODUCTION', 'YIELD_GOLD');

INSERT INTO Corporation_ResourceYieldChanges
	(CorporationType, ResourceType, YieldType, Yield)
SELECT DISTINCT
	a.CorporationType, a.ResourceType, b.YieldType, 8
FROM Corporation_ResourceMonopolyOrs a
INNER JOIN Corporation_BuildingClassYieldChanges b
ON a.CorporationType = b.CorporationType
WHERE b.YieldType IN ('YIELD_CULTURE_LOCAL');
