// Auto-generated file - DO NOT EDIT
// Generated by generate-event-hpp.js from TypeScript event schemas
// Compatible with MSVC 2008

#pragma once

#include <map>
#include <string>

// Get event schemas map: event name -> NULL-terminated property array
std::map<std::string, const char**> GetEventSchemas();
