-- 150
UPDATE Defines
SET Value = '800'
WHERE Name = 'AI_GOLD_PRIORITY_UPGRADE_BASE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1 );

-- 75
UPDATE Defines
SET Value = '200'
WHERE Name = 'AI_GOLD_PRIORITY_UPGRADE_PER_FLAVOR_POINT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1 );

-- 25
UPDATE Defines
SET Value = '500'
WHERE Name = 'AI_HOMELAND_MOVE_PRIORITY_UPGRADE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_LEADERS' AND Value= 1 );
