---------------------------------------------------------------------------------------------------------------
-- Unit Panel promotions
---------------------------------------------------------------------------------------------------------------

-- Default
UPDATE UnitPromotions SET OrderPriority = 9999, ShowInUnitPanel = 1;

CREATE TEMP TABLE PromotionClass_Orders (
	PromotionClass TEXT,
	OrderNumber INTEGER
);

INSERT INTO PromotionClass_Orders
VALUES
	-- Plagues (should be always shown)
	('BOARDED', 1),
	-- Trunk promotions
	('SHOCK', 101),
	('DRILL', 102),
	('INTERCEPTOR', 104), -- reserve slot for Buffalo
	('BARRAGE', 101),
	('ACCURACY', 102),
	('TANK_HUNTER', 103),
	('HELI_MOBILITY', 104),
	('SIEGE', 101),
	('FIELD', 105), -- Oromo Cavalry gets this
	('TRAILBLAZER', 101),
	('SURVIVALISM', 105), -- Otomi gets this
	('HULL', 101), -- Treasure Ship gets this
	('BOARDING_PARTY', 102),
	('TARGETING', 102),
	('BOMBARDMENT', 103),
	('TORPEDO', 101),
	('FLIGHT_DECK', 101),
	('ARMOR_PLATING', 109), -- also given to other units
	('ACE_PILOT', 101),
	('DOGFIGHTING', 102),
	('AIR_SUPREMACY', 103),
	('AIR_TARGETING', 101),
	('AIR_SIEGE', 102),
	('AIR_AMBUSH', 103),
	-- Unique unit free promotions
	('BUFFALO', 103),
	('BUSHIDO', 111),
	('MYSTIC_BLADE', 112), -- technically a unit can have both Bushido and Mystic Blade
	-- Building free promotions
	('DIPLO_BOOST', 201),
	-- Leaf promotions
	('FORMATION', 301),
	('COVER', 302),
	('AMBUSH', 303),
	('CHARGE', 304), -- Pancerny gets this
	('MEDIC', 305),
	('MARCH', 306),
	('AIR_DEFENSE', 307),
	('SENTRY', 308),
	('SPLASH', 301), -- Camel Archer gets this
	('SCOUTING', 301), -- Cacador gets this
	('NAVIGATOR', 301),
	('AIR_PENETRATION', 301),
	-- Unit free promotions (stays on upgrade)
	('GENERAL_MOVEMENT', 401),
	('WITHDRAW', 402),
	('GENERAL_RATE', 403),
	-- Policy promotions
	('AUTHORITY', 603),
	('IMPERIALISM', 608),
	-- Tech promotions
	('EMBARKATION', 701),
	('FALLOUT_RESISTANCE', 703),
	-- Unit free promotions (lost on upgrade)
	('FIELD_WORKS', 801),
	('COVERING_FIRE', 801),
	('SIEGE_ENGINE', 801),
	('PARADROP', 801),
	('DEPTH_CHARGES', 801),
	('AIR_RECON', 801),
	('SUBMARINE_BASE', 801),
	('DIPLO_BASE', 801),
	('CARGO', 802);

UPDATE UnitPromotions
SET OrderPriority = (SELECT OrderNumber FROM PromotionClass_Orders WHERE PromotionClass = RankList)
WHERE EXISTS (SELECT 1 FROM PromotionClass_Orders WHERE PromotionClass = RankList);

DROP TABLE PromotionClass_Orders;

CREATE TEMP TABLE UnitPromotion_Orders (
	PromotionType TEXT,
	OrderNumber INTEGER
);

INSERT INTO UnitPromotion_Orders
VALUES
	-- Plagues
	('PROMOTION_DAZED', 2),
	('PROMOTION_ON_FIRE', 3),
	('PROMOTION_MAIMED', 4),
	('PROMOTION_PRISONERS_OF_WAR', 5),
	-- Really important promotions
	('PROMOTION_JUGGERNAUT', 10),
	-- Unique unit free promotions (stays on upgrade)
	('PROMOTION_ADJACENT_BONUS', 113),
	('PROMOTION_IGNORE_TERRAIN_COST', 114),
	('PROMOTION_SPAWN_GENERALS_I', 115),
	('PROMOTION_SPAWN_GENERALS_II', 116),
	('PROMOTION_FASIMBA', 118),
	('PROMOTION_OPEN_TERRAIN', 119),
	('PROMOTION_MOVEMENT_TO_GENERAL', 120),
	('PROMOTION_GENERAL_STACKING', 121),
	('PROMOTION_PARTIAL_HEAL_IF_DESTROY_ENEMY', 122),
	('PROMOTION_HAKKAA_PAALLE', 123),
	('PROMOTION_FOREIGN_LANDS', 125),
	('PROMOTION_FASTER_HEAL', 126),
	('PROMOTION_STRONGER_VS_DAMAGED', 127),
	('PROMOTION_WITHERING_FIRE', 128),
	('PROMOTION_SKI_INFANTRY', 129),
	('PROMOTION_WITHDRAW_BEFORE_MELEE', 130),
	('PROMOTION_HAKA_WAR_DANCE', 131),
	('PROMOTION_MEDIC_GENERAL', 132),
	('PROMOTION_GAIN_EXPERIENCE', 133),
	('PROMOTION_TRADE_MISSION_BONUS', 134),
	('PROMOTION_HEAVY_CHARGE', 135),
	('PROMOTION_SAPPER', 136),
	('PROMOTION_GOLDEN_AGE_POINTS', 137),
	('PROMOTION_PRIDE_OF_THE_NATION', 138),
	('PROMOTION_HOMELAND_GUARDIAN', 139),
	('PROMOTION_DEFEND_NEAR_CAPITAL', 140),
	('PROMOTION_MOON_STRIKER', 141),
	('PROMOTION_LIGHTNING_WARFARE', 142),
	('PROMOTION_DOUBLE_PLUNDER', 143),
	('PROMOTION_FLANK_ATTACK_BONUS', 144),
	('PROMOTION_HEAVY_FLANKING', 145),
	('PROMOTION_PRIZE_SHIPS', 146),
	('PROMOTION_GIFT_OF_THE_PHARAOH', 147),
	('PROMOTION_RAIDER', 148),
	('PROMOTION_FLAG_BEARER', 149),
	('PROMOTION_ASSIZE_OF_ARMS', 150),
	('PROMOTION_FOCUS_FIRE', 151),
	('PROMOTION_GRENADIER', 152),
	('PROMOTION_PILUM', 153),
	('PROMOTION_DOPPELSOLDNER', 154),
	('PROMOTION_CONCUSSIVE_HIT', 155),
	('PROMOTION_SIEGE_VOLLEY', 156),
	('PROMOTION_HEAVY_ASSAULT', 157),
	('PROMOTION_MOHAWK', 158),
	('PROMOTION_MYSTIC_BLADE', 159),
	('PROMOTION_HARDENED', 160),
	('PROMOTION_HARBOR_DEFENSE', 161),
	('PROMOTION_GARLAND_MINE', 162),
	('PROMOTION_DESERT_RAIDER', 163),
	('PROMOTION_SHOCK_CAVALRY', 164),
	('PROMOTION_FRONTIERSMAN', 165),
	('PROMOTION_BRUTE_STRENGTH', 166),
	('PROMOTION_LEGACY', 167),
	('PROMOTION_RIACHUELO', 168),
	('PROMOTION_GREEK_FIRE', 169),
	('PROMOTION_ELISHAS_GUILE', 170),
	('PROMOTION_AT_THE_GATES', 171),
	('PROMOTION_CARNYX', 172),
	('PROMOTION_VUR_HA', 173),
	('PROMOTION_MAIM', 174),
	('PROMOTION_ZEMENE_MESAFINT', 175),
	('PROMOTION_MINENWERFER', 176),
	('PROMOTION_TROMMELFEUER', 177),
	('PROMOTION_PHILHELLENISM', 178),
	('PROMOTION_BELLUM_ALET', 179),
	('PROMOTION_SENTINEL_OF_THE_SUN', 180),
	('PROMOTION_DHANURVIDYA', 181),
	('PROMOTION_CETBANG', 182),
	('PROMOTION_TAIKAN_KYOHO', 183),
	('PROMOTION_DECK_SPIKES', 184),
	('PROMOTION_LOST_CODEX', 185),
	('PROMOTION_MINGGHAN', 186),
	('PROMOTION_RAZZIA', 187),
	('PROMOTION_BURGHER', 188),
	('PROMOTION_GOEDENDAG', 189),
	('PROMOTION_SAFAVI_AGITATOR', 190),
	('PROMOTION_FIGHTING_COCK', 191),
	('PROMOTION_LEGATUS_LEGIONIS', 192),
	('PROMOTION_GRAPESHOT', 193),
	('PROMOTION_BIG_HORSE_DANCE', 194),
	('PROMOTION_FATHER_OF_THE_HORSE', 195),
	('PROMOTION_SANTA_MARIA', 196),
	('PROMOTION_INVINCIBLE', 197),
	('PROMOTION_AGINCOURT', 198),
	-- Building free promotions
	('PROMOTION_MORALE', 201),
	('PROMOTION_BUSHIDO', 202),
	('PROMOTION_SCHUTZENKONIG', 203),
	('PROMOTION_AGE_OF_DISCOVERY', 204),
	('PROMOTION_HIMEJI_CASTLE', 205),
	('PROMOTION_STATUE_ZEUS', 206),
	('PROMOTION_JINETE', 207),
	('PROMOTION_TREASURE_FLEET', 208),
	('PROMOTION_VENETIAN_CRAFTSMANSHIP', 209),
	('PROMOTION_PROXENOS', 210),
	-- Leaf promotions
	('PROMOTION_SIEGE', 311),
	('PROMOTION_PARTHIAN_TACTICS', 311),
	('PROMOTION_COUP_DE_GRACE', 312), -- Jaguar gets this
	('PROMOTION_ENVELOPMENT', 313),
	('PROMOTION_VOLLEY', 311),
	('PROMOTION_COASTAL_ARTILLERY', 312),
	('PROMOTION_FROGMAN', 311),
	('PROMOTION_SCREENING', 312),
	('PROMOTION_BREACHER', 311),
	('PROMOTION_NAVAL_SIEGE', 312),
	('PROMOTION_COMMERCE_RAIDER', 313),
	('PROMOTION_PIRACY', 314),
	('PROMOTION_ENCIRCLEMENT', 315),
	('PROMOTION_MINELAYER', 316),
	('PROMOTION_SEE_INVISIBLE_SUBMARINE', 317),
	('PROMOTION_DAUNTLESS', 318),
	('PROMOTION_SHRAPNEL_ROUNDS', 311),
	('PROMOTION_ANTI_FIGHTER', 311),
	('PROMOTION_AERIAL_TORPEDO', 312),
	('PROMOTION_BOMB_RACK', 313),
	('PROMOTION_EVASION', 314),
	('PROMOTION_OVERRUN', 321),
	('PROMOTION_STALWART', 322),
	('PROMOTION_FIRING_DOCTRINE', 321),
	('PROMOTION_INFILTRATORS', 322),
	('PROMOTION_BLOCKADE', 321),
	('PROMOTION_PINCER', 322),
	('PROMOTION_INDOMITABLE', 323),
	('PROMOTION_BROADSIDE', 324),
	('PROMOTION_VANGUARD', 325), -- Conquistador gets this
	('PROMOTION_VP_WOLFPACK', 321),
	('PROMOTION_HUNTER_KILLER', 324),
	('PROMOTION_PREDATOR', 325),
	('PROMOTION_PERISCOPE_DEPTH', 326),
	('PROMOTION_RANGE', 331),
	('PROMOTION_AIR_RANGE', 331),
	('PROMOTION_AMPHIBIOUS', 332),
	('PROMOTION_WOODSMAN', 333),
	('PROMOTION_BLITZ', 334),
	('PROMOTION_LOGISTICS', 334),
	('PROMOTION_AIR_LOGISTICS', 334),
	('PROMOTION_MOBILITY', 335),
	('PROMOTION_SUPPLY', 336),
	-- Unit free promotions (stays on upgrade)
	('PROMOTION_RECONNAISSANCE', 413),
	('PROMOTION_OCEAN_EXPLORER', 414),
	('PROMOTION_EMBARKED_SIGHT', 415),
	('PROMOTION_SCAVENGER', 416),
	('PROMOTION_ATTACK_BONUS', 417),
	('PROMOTION_FREE_PILLAGE_MOVES', 418),
	('PROMOTION_RIVAL_TERRITORY', 422),
	-- Event/Natural Wonder promotions
	('PROMOTION_FERVOR', 496),
	('PROMOTION_ALTITUDE_TRAINING', 497),
	('PROMOTION_SACRED_STEPS', 498),
	('PROMOTION_EVERLASTING_YOUTH', 499),
	-- Barbarian promotions
	('PROMOTION_HILL_WALKER', 501),
	('PROMOTION_DESERT_WALKER', 502),
	('PROMOTION_WOODS_WALKER', 503),
	('PROMOTION_WHITE_WALKER', 504),
	('PROMOTION_MARSH_WALKER', 505),
	-- Policy promotions
	('PROMOTION_FASTER_WORKER', 602),
	('PROMOTION_NATIONALISM', 611),
	('PROMOTION_FAST_GENERAL', 612),
	('PROMOTION_LIGHTNING_WARFARE_GUNPOWDER', 612),
	('PROMOTION_LIGHTNING_WARFARE_ARMORED', 612),
	('PROMOTION_MARE_NOSTRUM', 612),
	-- Tech promotions
	('PROMOTION_ENGINEERING_CORP', 702),
	-- Trait promotions
	('PROMOTION_SUN_NEVER_SETS', 793),
	('PROMOTION_MONGOL_TERROR', 794),
	('PROMOTION_VIKING', 795),
	('PROMOTION_LONGBOAT', 795),
	('PROMOTION_COERCION', 796),
	('PROMOTION_ATTACK_BONUS_SWEDEN', 797),
	('PROMOTION_SEWN_CANOES', 798),
	('PROMOTION_GOODY_HUT_PICKER', 799),
	-- Unit free promotions (lost on upgrade)
	('PROMOTION_CAN_MOVE_AFTER_ATTACKING', 803),
	('PROMOTION_CITY_ASSAULT', 804),
	('PROMOTION_RANGED_SUPPORT_FIRE', 805),
	('PROMOTION_FEARED_ELEPHANT', 806),
	('PROMOTION_BRUTE_FORCE', 807),
	('PROMOTION_SKIRMISHER_DOCTRINE', 808),
	('PROMOTION_HOVERING_UNIT', 809),
	('PROMOTION_FLAT_MOVEMENT_COST', 810),
	('PROMOTION_INDIRECT_FIRE', 811),
	('PROMOTION_COMMANDO', 812),
	('PROMOTION_AIR_SWEEP', 814),
	('PROMOTION_STRAFING_RUNS', 815),
	('PROMOTION_ANTI_HELICOPTER', 816),
	('PROMOTION_STEALTH', 817),
	('PROMOTION_GREAT_GENERAL', 818),
	('PROMOTION_GREAT_ADMIRAL', 818),
	('PROMOTION_GREAT_DIPLOMAT', 818),
	('PROMOTION_MILITARY_TRADITION', 819),
	('PROMOTION_SHIELDED_SILO', 820),
	('PROMOTION_TITANIC', 821),
	('PROMOTION_SELL_EXOTIC_GOODS', 822),
	('PROMOTION_CONSCRIPT', 823),
	('PROMOTION_ANTI_MOUNTED_I', 824),
	('PROMOTION_REND', 825),
	('PROMOTION_KOWTOW', 826),
	('PROMOTION_RULE_BRITANNIA', 827),
	('PROMOTION_HOOKED_WEAPON', 828),
	('PROMOTION_EPIC', 829),
	('PROMOTION_UNWIELDY', 830),
	('PROMOTION_PRAEFECTUS_CASTRORUM', 831),
	('PROMOTION_CROUCHING_TIGER', 832),
	-- Penalties
	('PROMOTION_ONLY_ATTACKS_CITIES', 901),
	('PROMOTION_UNWELCOME_EVANGELIST', 901),
	('PROMOTION_CITY_PENALTY', 902),
	('PROMOTION_SMALL_CITY_PENALTY', 902),
	('PROMOTION_SHALLOW_DRAFT', 903),
	('PROMOTION_OCEAN_IMPASSABLE_UNTIL_ASTRONOMY', 903),
	('PROMOTION_MUST_SET_UP', 904),
	('PROMOTION_BEAM_AXLE', 905),
	('PROMOTION_NAVAL_TARGET_PENALTY', 906),
	('PROMOTION_NAVAL_INACCURACY', 906),
	('PROMOTION_NO_DEFENSIVE_BONUSES', 998);

UPDATE UnitPromotions
SET OrderPriority = (SELECT OrderNumber FROM UnitPromotion_Orders WHERE PromotionType = Type)
WHERE EXISTS (SELECT 1 FROM UnitPromotion_Orders WHERE PromotionType = Type);

DROP TABLE UnitPromotion_Orders;

-- don't show these on the unit panel
UPDATE UnitPromotions SET ShowInUnitPanel = 0 WHERE Type IN (
	'PROMOTION_ONLY_DEFENSIVE'
);

---------------------------------------------------------------------------------------------------------------
-- Unit Flag promotions
-- Promotions with the same RankList will be grouped together
---------------------------------------------------------------------------------------------------------------
UPDATE UnitPromotions SET FlagPromoOrder = OrderPriority;

-- There shouldn't be any here, but just in case, put these promotions at the end.
UPDATE UnitPromotions SET FlagPromoOrder = 999 WHERE OrderPriority = 0;

---------------------------------------------------------------------------------------------------------------
-- Promotions which should not be displayed above the Unit Flag
-- Trait- and unit-specific free promotions are already automatically excluded with the respective settings
---------------------------------------------------------------------------------------------------------------

-- Default
UPDATE UnitPromotions SET IsVisibleAboveFlag = 1;

UPDATE UnitPromotions
SET IsVisibleAboveFlag = 0
WHERE Type IN (
	'PROMOTION_EMBARKATION',
	'PROMOTION_FASTER_GENERAL',
	'PROMOTION_FAST_GENERAL',
	'PROMOTION_ROYAL_SIGNET',
	'PROMOTION_WIRE_SERVICE',
	'PROMOTION_LITERACY',
	'PROMOTION_DIPLOMATIC_IMMUNITY',
	'PROMOTION_IMPERIAL_SEAL',
	'PROMOTION_NOBILITY',
	'PROMOTION_PROXENOS',
	'PROMOTION_FALLOUT_RESISTANCE',
	'PROMOTION_FALLOUT_IMMUNITY',
	'PROMOTION_ENGINEERING_CORP',
	'PROMOTION_INSTA_HEAL'
);

---------------------------------------------------------------------------------------------------------------
-- Misc.
---------------------------------------------------------------------------------------------------------------

-- For promos where the title is the same as the Help text
UPDATE UnitPromotions SET SimpleHelpText = 1 WHERE Description = Help;
