
-- Settler Stuff

UPDATE Defines
SET Value = '35'
WHERE Name = 'BUILD_ON_RIVER_PERCENT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '35'
WHERE Name = 'SETTLER_BUILD_ON_COAST_PERCENT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '-10'
WHERE Name = 'BUILD_ON_RESOURCE_PERCENT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '2'
WHERE Name = 'SETTLER_STRATEGIC_MULTIPLIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '5'
WHERE Name = 'SETTLER_DISTANCE_DROPOFF_MODIFIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '8'
WHERE Name = 'SETTLER_EVALUATION_DISTANCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_SETTLER_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '5000'
WHERE Name = 'AI_STRATEGY_MINIMUM_SETTLE_FERTILITY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE Defines
SET Value = '12'
WHERE Name = 'CITY_RING_1_MULTIPLIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE Defines
SET Value = '10'
WHERE Name = 'CITY_RING_2_MULTIPLIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE Defines
SET Value = '6'
WHERE Name = 'CITY_RING_3_MULTIPLIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE Defines
SET Value = '12'
WHERE Name = 'SETTLER_FOOD_MULTIPLIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE Defines
SET Value = '5'
WHERE Name = 'SETTLER_PRODUCTION_MULTIPLIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

-- Combat Stuff

UPDATE Defines
SET Value = '1'
WHERE Name = 'AI_MILITARY_BARBARIANS_FOR_MINOR_THREAT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '500'
WHERE Type = 'TACTICAL_ESCORT_EMBARKED_UNIT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '40'
WHERE Type = 'TACTICAL_ATTACK_LOW_PRIORITY_CIVILIAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '60'
WHERE Type = 'TACTICAL_ATTACK_MEDIUM_PRIORITY_CIVILIAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '90'
WHERE Type = 'TACTICAL_ATTACK_HIGH_PRIORITY_CIVILIAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '100'
WHERE Type = 'TACTICAL_MOVE_OPERATIONS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '20'
WHERE Type = 'TACTICAL_DAMAGE_CITY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '60'
WHERE Type = 'TACTICAL_CLOSE_ON_TARGET' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '40'
WHERE Type = 'TACTICAL_POSTURE_HEDGEHOG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '10'
WHERE Type = 'TACTICAL_GARRISON_ALREADY_THERE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '5'
WHERE Type = 'TACTICAL_GUARD_IMPROVEMENT_ALREADY_THERE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '125'
WHERE Type = 'TACTICAL_OFFENSIVE_POSTURE_MOVES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '3'
WHERE Type = 'TACTICAL_REPOSITION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '80'
WHERE Type = 'TACTICAL_SAFE_BOMBARDS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

UPDATE TacticalMoves
SET Priority = '100'
WHERE Type = 'TACTICAL_ANCIENT_RUINS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- Policy Decision Stuff

UPDATE Policy_Flavors
SET Flavor = '15'
WHERE PolicyType = 'POLICY_PIETY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICY_TWEAKS' AND Value= 1 );

UPDATE Policy_Flavors
SET Flavor = '15'
WHERE PolicyType = 'POLICY_LIBERTY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICY_TWEAKS' AND Value= 1 );

UPDATE Policy_Flavors
SET Flavor = '15'
WHERE PolicyType = 'POLICY_TRADITION' AND FlavorType = 'FLAVOR_CULTURE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICY_TWEAKS' AND Value= 1 );

UPDATE Policy_Flavors
SET Flavor = '15'
WHERE PolicyType = 'POLICY_TRADITION' AND FlavorType = 'FLAVOR_GROWTH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICY_TWEAKS' AND Value= 1 );

UPDATE Policy_Flavors
SET Flavor = '0'
WHERE PolicyType = 'POLICY_TRADITION' AND FlavorType = 'FLAVOR_WONDER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '80'
WHERE Name = 'POLICY_WEIGHT_PERCENT_DROP_NEW_BRANCH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '40'
WHERE Name = 'IDEOLOGY_SCORE_PER_FREE_TENET' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '15'
WHERE Name = 'IDEOLOGY_SCORE_HAPPINESS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_POLICY_TWEAKS' AND Value= 1 );

-- Military Strategy Flavors

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '60'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_AT_WAR' AND FlavorType = 'FLAVOR_OFFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '40'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_AT_WAR' AND FlavorType = 'FLAVOR_MOBILE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '45'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_AT_WAR' AND FlavorType = 'FLAVOR_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '50'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_AT_WAR' AND FlavorType = 'FLAVOR_RANGED' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '35'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_AT_WAR' AND FlavorType = 'FLAVOR_NAVAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '40'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_AT_WAR' AND FlavorType = 'FLAVOR_AIR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

-- City Strategy Flavors

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '60'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_WAR_MOBILIZATION' AND FlavorType = 'FLAVOR_OFFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '40'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_WAR_MOBILIZATION' AND FlavorType = 'FLAVOR_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '50'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_WAR_MOBILIZATION' AND FlavorType = 'FLAVOR_RANGED' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

INSERT INTO AIMilitaryStrategy_Player_Flavors (
AIMilitaryStrategyType, FlavorType, Flavor)
SELECT 'MILITARYAISTRATEGY_WAR_MOBILIZATION', 'FLAVOR_MOBILE' , '35'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '10'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_ANTIAIR' AND FlavorType = 'FLAVOR_ANTIAIR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '10'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_AIR_CARRIER' AND FlavorType = 'FLAVOR_AIR_CARRIER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '30'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_AIR' AND FlavorType = 'FLAVOR_AIR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '30'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE' AND FlavorType = 'FLAVOR_OFFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '40'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE' AND FlavorType = 'FLAVOR_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

INSERT INTO AIMilitaryStrategy_Player_Flavors (
AIMilitaryStrategyType, FlavorType, Flavor)
SELECT 'MILITARYAISTRATEGY_EMPIRE_DEFENSE', 'FLAVOR_MOBILE' , '20'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '30'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL' AND FlavorType = 'FLAVOR_OFFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '50'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL' AND FlavorType = 'FLAVOR_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

INSERT INTO AIMilitaryStrategy_Player_Flavors (
AIMilitaryStrategyType, FlavorType, Flavor)
SELECT 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL', 'FLAVOR_MOBILE' , '25'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

INSERT INTO AIMilitaryStrategy_Player_Flavors (
AIMilitaryStrategyType, FlavorType, Flavor)
SELECT 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL', 'FLAVOR_AIR' , '15'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE AIMilitaryStrategy_City_Flavors
SET Flavor = '25'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE' AND FlavorType = 'FLAVOR_OFFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_City_Flavors
SET Flavor = '40'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE' AND FlavorType = 'FLAVOR_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

INSERT INTO AIMilitaryStrategy_City_Flavors (
AIMilitaryStrategyType, FlavorType, Flavor)
SELECT 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL', 'FLAVOR_MOBILE' , '20'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

INSERT INTO AIMilitaryStrategy_City_Flavors (
AIMilitaryStrategyType, FlavorType, Flavor)
SELECT 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL', 'FLAVOR_AIR' , '10'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE AIMilitaryStrategy_City_Flavors
SET Flavor = '40'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL' AND FlavorType = 'FLAVOR_OFFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_City_Flavors
SET Flavor = '50'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL' AND FlavorType = 'FLAVOR_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

INSERT INTO AIMilitaryStrategy_City_Flavors (
AIMilitaryStrategyType, FlavorType, Flavor)
SELECT 'MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL', 'FLAVOR_MOBILE' , '25'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='MILITARYAISTRATEGY_EMPIRE_DEFENSE_CRITICAL' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '25'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_NAVAL_UNITS' AND FlavorType = 'FLAVOR_NAVAL_RECON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_Player_Flavors
SET Flavor = '40'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_NAVAL_UNITS_CRITICAL' AND FlavorType = 'FLAVOR_NAVAL_RECON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_City_Flavors
SET Flavor = '35'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_NAVAL_UNITS' AND FlavorType = 'FLAVOR_NAVAL_RECON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIMilitaryStrategy_City_Flavors
SET Flavor = '50'
WHERE AIMilitaryStrategyType = 'MILITARYAISTRATEGY_NEED_NAVAL_UNITS_CRITICAL' AND FlavorType = 'FLAVOR_NAVAL_RECON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

-- Economic Strategies
UPDATE AIEconomicStrategy_City_Flavors
SET Flavor = '-100'
WHERE AIEconomicStrategyType = 'ECONOMICAISTRATEGY_TOO_MANY_UNITS' AND FlavorType = 'FLAVOR_OFFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIEconomicStrategy_City_Flavors
SET Flavor = '-100'
WHERE AIEconomicStrategyType = 'ECONOMICAISTRATEGY_TOO_MANY_UNITS' AND FlavorType = 'FLAVOR_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIEconomicStrategy_City_Flavors
SET Flavor = '-100'
WHERE AIEconomicStrategyType = 'ECONOMICAISTRATEGY_TOO_MANY_UNITS' AND FlavorType = 'FLAVOR_NAVAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIEconomicStrategy_City_Flavors
SET Flavor = '-100'
WHERE AIEconomicStrategyType = 'ECONOMICAISTRATEGY_TOO_MANY_UNITS' AND FlavorType = 'FLAVOR_RANGED' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIEconomicStrategy_City_Flavors
SET Flavor = '-100'
WHERE AIEconomicStrategyType = 'ECONOMICAISTRATEGY_TOO_MANY_UNITS' AND FlavorType = 'FLAVOR_MOBILE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE AIEconomicStrategy_City_Flavors
SET Flavor = '-100'
WHERE AIEconomicStrategyType = 'ECONOMICAISTRATEGY_TOO_MANY_UNITS' AND FlavorType = 'FLAVOR_RECON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

-- AI Diplomacy Values
--100
UPDATE Defines
SET Value = '90'
WHERE Name = 'EACH_GOLD_VALUE_PERCENT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

--100
UPDATE Defines
SET Value = '110'
WHERE Name = 'EACH_GOLD_PER_TURN_VALUE_PERCENT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

--150
UPDATE Defines
SET Value = '250'
WHERE Name = 'PEACE_WILLINGNESS_ACCEPT_THRESHOLD_UN_SURRENDER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

--115
UPDATE Defines
SET Value = '200'
WHERE Name = 'PEACE_WILLINGNESS_ACCEPT_THRESHOLD_CAPITULATION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

--80
UPDATE Defines
SET Value = '150'
WHERE Name = 'PEACE_WILLINGNESS_ACCEPT_THRESHOLD_CESSION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

--65
UPDATE Defines
SET Value = '120'
WHERE Name = 'PEACE_WILLINGNESS_ACCEPT_THRESHOLD_SURRENDER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

--50
UPDATE Defines
SET Value = '100'
WHERE Name = 'PEACE_WILLINGNESS_ACCEPT_THRESHOLD_SUBMISSION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

--35
UPDATE Defines
SET Value = '70'
WHERE Name = 'PEACE_WILLINGNESS_ACCEPT_THRESHOLD_BACKDOWN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

--20
UPDATE Defines
SET Value = '40'
WHERE Name = 'PEACE_WILLINGNESS_ACCEPT_THRESHOLD_SETTLEMENT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

--10
UPDATE Defines
SET Value = '5'
WHERE Name = 'PEACE_WILLINGNESS_ACCEPT_THRESHOLD_ARMISTICE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

--2
UPDATE Defines
SET Value = '8'
WHERE Name = 'APPROACH_WAR_CURRENTLY_DECEPTIVE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

--5
UPDATE Defines
SET Value = '8'
WHERE Name = 'APPROACH_HOSTILE_CURRENTLY_HOSTILE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

--3
UPDATE Defines
SET Value = '4'
WHERE Name = 'APPROACH_WAR_CURRENTLY_WAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

--100
UPDATE Defines
SET Value = '125'
WHERE Name = 'MILITARY_THREAT_NEIGHBORS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 20
UPDATE Defines
SET Value = '30'
WHERE Name = 'OPINION_WEIGHT_IGNORED_NO_DIG_PROMISE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 30
UPDATE Defines
SET Value = '40'
WHERE Name = 'OPINION_WEIGHT_BROKEN_NO_DIG_PROMISE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 4
UPDATE Defines
SET Value = '8'
WHERE Name = 'APPROACH_OPINION_COMPETITOR_WAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- Other

--7
UPDATE Defines
SET Value = '8'
WHERE Name = 'AI_CITIZEN_VALUE_SCIENCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '2'
WHERE Name = 'AI_DIPLO_PLOT_RANGE_FROM_CITY_HOME_FRONT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '2'
WHERE Name = 'RELIGION_MAX_MISSIONARIES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );

UPDATE Defines
SET Value = '8'
WHERE Name = 'RELIGION_MISSIONARY_RANGE_IN_TURNS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_CITYSTRATEGY_TWEAKS' AND Value= 1 );


-- Diplomacy and War Likelihood

-- 1.0
UPDATE Defines
SET Value = '1.20'
WHERE Name = 'AI_DANGER_MAJOR_APPROACH_WAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 0.2
UPDATE Defines
SET Value = '0.4'
WHERE Name = 'AI_DANGER_MAJOR_APPROACH_HOSTILE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 0.1
UPDATE Defines
SET Value = '0.3'
WHERE Name = 'AI_DANGER_MAJOR_APPROACH_DECEPTIVE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 0.5
UPDATE Defines
SET Value = '0.70'
WHERE Name = 'AI_DANGER_MAJOR_APPROACH_GUARDED' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 0.9
UPDATE Defines
SET Value = '1.25'
WHERE Name = 'AI_DANGER_MAJOR_APPROACH_AFRAID' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 0.1
UPDATE Defines
SET Value = '0.20'
WHERE Name = 'AI_DANGER_MAJOR_APPROACH_NEUTRAL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 30
UPDATE Defines
SET Value = '45'
WHERE Name = 'OPINION_WEIGHT_LAND_FIERCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 20
UPDATE Defines
SET Value = '35'
WHERE Name = 'OPINION_WEIGHT_LAND_STRONG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 10
UPDATE Defines
SET Value = '15'
WHERE Name = 'OPINION_WEIGHT_LAND_WEAK' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- -6
UPDATE Defines
SET Value = '-4'
WHERE Name = 'OPINION_WEIGHT_LAND_NONE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 30
UPDATE Defines
SET Value = '75'
WHERE Name = 'OPINION_WEIGHT_VICTORY_FIERCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 20 
UPDATE Defines
SET Value = '50'
WHERE Name = 'OPINION_WEIGHT_VICTORY_STRONG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- -5 
UPDATE Defines
SET Value = '-10'
WHERE Name = 'OPINION_WEIGHT_ADOPTING_HIS_RELIGION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- -3
UPDATE Defines
SET Value = '-8'
WHERE Name = 'OPINION_WEIGHT_ADOPTING_MY_RELIGION' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 5
UPDATE Defines
SET Value = '-15'
WHERE Name = 'OPINION_WEIGHT_SAME_LATE_POLICIES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 5
UPDATE Defines
SET Value = '15'
WHERE Name = 'OPINION_WEIGHT_DIFFERENT_LATE_POLICIES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 15
UPDATE Defines
SET Value = '30'
WHERE Name = 'OPINION_WEIGHT_DOF_WITH_ENEMY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 50
UPDATE Defines
SET Value = '75'
WHERE Name = 'OPINION_WEIGHT_WAR_FRIEND_EACH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 60
UPDATE Defines
SET Value = '80'
WHERE Name = 'OPINION_WEIGHT_WAR_ME_FRIENDS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 25
UPDATE Defines
SET Value = '75'
WHERE Name = 'WAR_PROJECTION_THEIR_MILITARY_STRENGTH_POOR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 60
UPDATE Defines
SET Value = '100'
WHERE Name = 'WAR_PROJECTION_THEIR_MILITARY_STRENGTH_WEAK' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 100
UPDATE Defines
SET Value = '150'
WHERE Name = 'WAR_PROJECTION_THEIR_MILITARY_STRENGTH_PATHETIC' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- -12
UPDATE Defines
SET Value = '-5'
WHERE Name = 'WAR_PROJECTION_THEIR_ECONOMIC_STRENGTH_STRONG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- -30
UPDATE Defines
SET Value = '-15'
WHERE Name = 'WAR_PROJECTION_THEIR_ECONOMIC_STRENGTH_POWERFUL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- -50
UPDATE Defines
SET Value = '-25'
WHERE Name = 'WAR_PROJECTION_THEIR_ECONOMIC_STRENGTH_IMMENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 5
UPDATE Defines
SET Value = '10'
WHERE Name = 'WAR_PROJECTION_WAR_DAMAGE_THEM_MINOR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 10
UPDATE Defines
SET Value = '15'
WHERE Name = 'WAR_PROJECTION_WAR_DAMAGE_THEM_MAJOR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 15
UPDATE Defines
SET Value = '20'
WHERE Name = 'WAR_PROJECTION_WAR_DAMAGE_THEM_SERIOUS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );

-- 20
UPDATE Defines
SET Value = '30'
WHERE Name = 'WAR_PROJECTION_WAR_DAMAGE_THEM_CRIPPLED' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );


-- 50
UPDATE Defines
SET Value = '40'
WHERE Name = 'TARGET_FAVORABLE_THRESHOLD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );
		
-- -10
UPDATE Defines
SET Value = '-15'
WHERE Name = 'TARGET_NEIGHBORS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );
		
-- 0
UPDATE Defines
SET Value = '-5'
WHERE Name = 'TARGET_CLOSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );
		
-- 30
UPDATE Defines
SET Value = '20'
WHERE Name = 'TARGET_FAR' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );
		
-- 80
UPDATE Defines
SET Value = '70'
WHERE Name = 'TARGET_DISTANT' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );
		
-- 14
UPDATE Defines
SET Value = '30'
WHERE Name = 'VICTORY_DISPUTE_GRAND_STRATEGY_MATCH_POSITIVE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );
		
-- 10
UPDATE Defines
SET Value = '20'
WHERE Name = 'VICTORY_DISPUTE_GRAND_STRATEGY_MATCH_LIKELY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );
		
-- 6
UPDATE Defines
SET Value = '5'
WHERE Name = 'VICTORY_DISPUTE_GRAND_STRATEGY_MATCH_UNSURE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_MILITARY_TWEAKS' AND Value= 1 );


-- 3 
-- Makes trade partnersips and trade deals last a bit longer

UPDATE Defines
SET Value = '2'
WHERE Name = 'DEAL_VALUE_PER_TURN_DECAY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

-- -30 
-- Makes trade partnersips and trade deals last a bit longer

UPDATE Defines
SET Value = '-50'
WHERE Name = 'OPINION_WEIGHT_TRADE_MAX' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

-- Protection of Minors
UPDATE Defines
SET Value = '30'
WHERE Name = 'MINOR_APPROACH_PROTECTIVE_CURRENTLY_PROTECTIVE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );
