-- Ancient
UPDATE Unit_UniqueNames
SET EraType = 'ERA_ANCIENT'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HOMER';

-- Classical

-- Medieval
UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_WANG_XIMENG';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HUANG_GONGWANG';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ZHANG_ZUDUAN';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_YAN_LIBEN';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_QIAN_XUAN';

-- Renaissance
UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JAN_VERMEER';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HANS_HOLBEIN';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_PIETER_BRUEGEL';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_LEONARDO_DA_VINCI' AND UnitType = 'UNIT_ARTIST';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_EL_GRECO';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_SANDRO_BOTTICELLI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_RAFFAELLO_SANZO';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_PAOLO_UCCELLO';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MICHELANGELO_BUONARROTI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JIAO_BINGZHEN';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_QIU_YING';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HIRANAND';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_KAMALEDDIN_BEHZAD';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_SULTAN_MUHAMMAD';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ANTONELLO_DA_MESSINA';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_REMBRANDT';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JEAN_FOUQUET';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ZURBARAN';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_PETER_BRUEGHEL';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_PETRUS_CHRISTUS';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_KANO_MASANOBU';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_TITIAN';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_GEORGE_GOWER';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JEAN_CLOUET';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_BARTHOLOMEUM_SPRANGER';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_GIUSEPPE_ARCIMBOLDO';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_TINTORETTO';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JAN_VAN_EYCK';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_GIOVANNI_BELLINI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_GIOTTO_DI_BONDONE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_PETER_PAUL_RUBENS';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_BERNARDO_MARTORELL';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_CARAVAGGIO';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_FRANS_POST';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_WILLEM_THE_YOUNGER';

-- Industrial

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_GEORGE_SEURAT';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_CLAUDE_MONET';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_SAMUEL_MORSE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_EMANUAL_LEUTZE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JAMES_WHISTLER';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_KATSUSHIKA_HOKUSAI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_UTAGAWA_HIROSHIGE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_EUGENE_DELACROIX';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JACQUES_DAVID';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_YANAGAWA';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_PAUL_DELAROCHE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_CASPAR_DAVID_FRIEDRICH';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ASHER_DURAND';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_THOMAS_GAINSBOROUGH';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_FRANCISCO_DE_GOYA';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ALPHONSE_MARIE_ADOLPHE_DE_NEUVILLE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JEAN_HONORE_FRAGONARD';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MARTIN_JOHNSON_HEADE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_GILBERT_STUART';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_TOYOKUNI_UTAGAWA';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JOZEF_BORSOS';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_WILLIAM_SIMPSON';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_GEORGE_HEALY';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_UTAGAWA_KUNIYOSHI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ADRIEN_CARPENTIERS';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_BAHRAM_KIRMANSHAHI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_FRANCESCO_HAYEZ';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HORACE_VERNET';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_KARL_BRIULLOV';

-- Modern

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_PABLO_PICASSO';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_PIERRE_AUGUSTE_ENOIR';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VINCENT_VAN_GOGH';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_WINSLOW_HOMER';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_EDGAR_DEGAS';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_PAUL_GAUDUIN';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_EDOUARD_MANET';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HENRI_DE_TOULOUSE_LAUTREC';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_GUSTAV_KLIMPT';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_GRANT_DEVOLSON_WOOD';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_RAJA_RAVI_VARMA';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_GUSTAVE_CAILLEBOTTE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MARY_CASSATT';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_PAUL_CEZANNE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_AMEDEO_MODIGLIANI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_FREDERIC_REMINGTON';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_TORAJIRO_KASAI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HENRI_ROUSSEAU';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ILYA_REPIN';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_AUGUST_HAAKE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_WILLIAM_BOUGUEREAU';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VIKTOR_VASNETSOV';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_EDMUND_LEIGHTON';

-- Atomic
UPDATE Unit_UniqueNames
SET EraType = 'ERA_POSTMODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_SERGEY_IVANOV';

-- Information