-- Ancient

-- Classical
UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HOMER';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_AESOP';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_SOPHOCLES';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ARISTOPHANES';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VIRGIL';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_OVID';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_LUCIAN_SAMOSATA';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VALMIKI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VYASA';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_BHASA';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_QU_YUAN';

-- Medieval
UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_OMAR_KHAYYAM';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_RUMI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_LANLING_XIAOXIAO_SHENG';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_KALIDASA';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_SHI_NAIAN';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_KI_NO_TSURAYUKI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MURASAKI_SHIKIBU';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_BERTRAND_DE_BAR_SUR_AUBE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_DANTE_ALIGHIERI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_GEOFFREY_CHAUCER';

-- Renaissance
UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_CAO_XUEQIN';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_YOSHIDA_KENKO';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_CHIKAMATSU_MONZAEMON';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MIGUEL_DE_CERVANTES';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_FRANCOIS_RABELAIS';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VOLTAIRE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_PETRARCH';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_LUDOVICO_ARIOSTO';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VITTORIO_ALFIERI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JOHANN_FRIEDRICH_VON_SCHILLER';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_THOMAS_MALORY';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_EDMUND_SPENSER';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_WILLIAM_SHAKESPEARE';

-- Industrial
UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_UEDA_AKINARI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_NATSUME_SOSEKI';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JORGE_ISAACS';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JOSE_HERNANDEZ';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_RUBEN_DARIO';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ALEXANDRE_DUMAS';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VICTOR_HUGO';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JULES_VERNE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JOHANN_WOLFGANG_VON_GOETHE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_NIKOLAI_GOGOL';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JANE_AUSTIN';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MARY_SHELLEY';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_CHARLES_DICKENS';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_LEWIS_CARROLL';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_RUDYARD_KIPLING';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_H_G_WELLS';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_WASHINGTON_IRVING';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_EDGAR_ALLEN_POE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_NATHANIEL_HAWTHORNE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HARRIET_BEECHER_STOWE';

-- Modern
UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MARCUS_PROUST';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_FYODOR_DOSTOYEVSKY';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_LEO_TOLSTOY';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ANTON_CHEKHOV';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MAXIM_GORKY';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ARTHUR_CONAN_DOYLE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_D_H_LAWRENCE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JAMES_FENIMORE_COOPER';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HERMAN_MELVILLE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HENRY_DAVID_THOREAU';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_WALT_WHITMAN';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MARK_TWAIN';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_EMILY_DICKENSON';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_STEPHEN_CRANE';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_L_FRANK_BAUM';

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_F_SCOTT_FITZGERALD';

-- Atomic

-- Information