-- Ancient

-- Classical
UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HOMER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_AESOP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_SOPHOCLES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ARISTOPHANES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VIRGIL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_OVID' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_LUCIAN_SAMOSATA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VALMIKI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VYASA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_BHASA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_CLASSICAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_QU_YUAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

-- Medieval
UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_OMAR_KHAYYAM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_RUMI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_LANLING_XIAOXIAO_SHENG' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_KALIDASA' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_SHI_NAIAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_KI_NO_TSURAYUKI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MURASAKI_SHIKIBU' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_BERTRAND_DE_BAR_SUR_AUBE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_DANTE_ALIGHIERI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MEDIEVAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_GEOFFREY_CHAUCER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

-- Renaissance
UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_CAO_XUEQIN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_YOSHIDA_KENKO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_CHIKAMATSU_MONZAEMON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MIGUEL_DE_CERVANTES' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_FRANCOIS_RABELAIS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VOLTAIRE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_PETRARCH' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_LUDOVICO_ARIOSTO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VITTORIO_ALFIERI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JOHANN_FRIEDRICH_VON_SCHILLER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_THOMAS_MALORY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_EDMUND_SPENSER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_RENAISSANCE'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_WILLIAM_SHAKESPEARE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

-- Industrial
UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_UEDA_AKINARI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_NATSUME_SOSEKI' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JORGE_ISAACS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JOSE_HERNANDEZ' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_RUBEN_DARIO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ALEXANDRE_DUMAS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_VICTOR_HUGO' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JULES_VERNE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JOHANN_WOLFGANG_VON_GOETHE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_NIKOLAI_GOGOL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JANE_AUSTIN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MARY_SHELLEY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_CHARLES_DICKENS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_LEWIS_CARROLL' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_RUDYARD_KIPLING' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_H_G_WELLS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_WASHINGTON_IRVING' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_EDGAR_ALLEN_POE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_NATHANIEL_HAWTHORNE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_INDUSTRIAL'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HARRIET_BEECHER_STOWE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

-- Modern
UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MARCUS_PROUST' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_FYODOR_DOSTOYEVSKY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_LEO_TOLSTOY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ANTON_CHEKHOV' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MAXIM_GORKY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_ARTHUR_CONAN_DOYLE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_D_H_LAWRENCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_JAMES_FENIMORE_COOPER' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HERMAN_MELVILLE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_HENRY_DAVID_THOREAU' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_WALT_WHITMAN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_MARK_TWAIN' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_EMILY_DICKENSON' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_STEPHEN_CRANE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_L_FRANK_BAUM' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

UPDATE Unit_UniqueNames
SET EraType = 'ERA_MODERN'
WHERE UniqueName = 'TXT_KEY_GREAT_PERSON_F_SCOTT_FITZGERALD' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE_ERA_GREAT_WORKS' AND Value= 1 );

-- Atomic

-- Information