-- Unit entries follow the historical order. UnitClass names are for reference only and may not reflect the actual UNITCLASS in the database.

DELETE FROM Unit_AITypes;
INSERT INTO Unit_AITypes (UnitType, UnitAIType) VALUES

-- Settlers
('UNIT_SETTLER','UNITAI_SETTLE'),
('UNIT_PIONEER','UNITAI_SETTLE'),
('UNIT_COLONIST','UNITAI_SETTLE'),

-- Worker&Workboat
('UNIT_WORKER','UNITAI_WORKER'),
('UNIT_WORKBOAT','UNITAI_WORKER_SEA'),

/*
-- CSD
('UNIT_EMISSARY','UNITAI_MESSENGER'),
('UNIT_ENVOY','UNITAI_MESSENGER'),
('UNIT_DIPLOMAT','UNITAI_MESSENGER'),
('UNIT_AMBASSADOR','UNITAI_MESSENGER'),
('UNIT_GREAT_DIPLOMAT','UNITAI_DIPLOMAT'),
*/

-- Great People
('UNIT_ARTIST','UNITAI_ARTIST'),
('UNIT_WRITER','UNITAI_WRITER'),
('UNIT_MUSICIAN','UNITAI_MUSICIAN'),

('UNIT_ENGINEER','UNITAI_ENGINEER'),
('UNIT_SCIENTIST','UNITAI_SCIENTIST'),
('UNIT_PROPHET','UNITAI_PROPHET'),
('UNIT_MERCHANT','UNITAI_MERCHANT'),

('UNIT_GREAT_ADMIRAL','UNITAI_ADMIRAL'),
('UNIT_GREAT_GENERAL','UNITAI_GENERAL'),
('UNIT_MONGOLIAN_KHAN','UNITAI_GENERAL'),

('UNIT_VENETIAN_MERCHANT','UNITAI_MERCHANT'),

-- Other Civilians
('UNIT_CARAVAN','UNITAI_TRADE_UNIT'),
('UNIT_CARGO_SHIP','UNITAI_TRADE_UNIT'),

('UNIT_MISSIONARY','UNITAI_MISSIONARY'),

('UNIT_INQUISITOR','UNITAI_INQUISITOR'),
('UNIT_SPAIN_INQUISITOR','UNITAI_INQUISITOR'),

('UNIT_ARCHAEOLOGIST','UNITAI_ARCHAEOLOGIST'),

('UNIT_ASSYRIAN_SIEGE_TOWER','UNITAI_CITY_SPECIAL'),

-- Spaceship
('UNIT_SS_STASIS_CHAMBER','UNITAI_SPACESHIP_PART'),
('UNIT_SS_ENGINE','UNITAI_SPACESHIP_PART'),
('UNIT_SS_COCKPIT','UNITAI_SPACESHIP_PART'),
('UNIT_SS_BOOSTER','UNITAI_SPACESHIP_PART'),

---------------------------
-- Combat Units
-- Spear Melee
-- UNITCLASS_WARRIOR
('UNIT_WARRIOR', 'UNITAI_ATTACK'),
('UNIT_WARRIOR', 'UNITAI_DEFENSE'),
('UNIT_WARRIOR', 'UNITAI_EXPLORE'),

('UNIT_AZTEC_JAGUAR', 'UNITAI_ATTACK'),
('UNIT_AZTEC_JAGUAR', 'UNITAI_DEFENSE'),
('UNIT_AZTEC_JAGUAR', 'UNITAI_EXPLORE'),

('UNIT_BARBARIAN_WARRIOR','UNITAI_ATTACK'),
('UNIT_BARBARIAN_WARRIOR','UNITAI_DEFENSE'),
('UNIT_BARBARIAN_WARRIOR','UNITAI_EXPLORE'),

-- UNITCLASS_SPEARMAN
('UNIT_SPEARMAN', 'UNITAI_ATTACK'),
('UNIT_SPEARMAN', 'UNITAI_COUNTER'),
('UNIT_SPEARMAN', 'UNITAI_DEFENSE'),
('UNIT_SPEARMAN', 'UNITAI_EXPLORE'),

('UNIT_GREEK_HOPLITE', 'UNITAI_COUNTER'),
('UNIT_GREEK_HOPLITE', 'UNITAI_ATTACK'),
('UNIT_GREEK_HOPLITE', 'UNITAI_DEFENSE'),
('UNIT_GREEK_HOPLITE', 'UNITAI_EXPLORE'),

('UNIT_PERSIAN_IMMORTAL', 'UNITAI_ATTACK'),
('UNIT_PERSIAN_IMMORTAL', 'UNITAI_COUNTER'),
('UNIT_PERSIAN_IMMORTAL', 'UNITAI_DEFENSE'),
('UNIT_PERSIAN_IMMORTAL', 'UNITAI_EXPLORE'),

('UNIT_CELT_PICTISH_WARRIOR', 'UNITAI_ATTACK'),
('UNIT_CELT_PICTISH_WARRIOR', 'UNITAI_DEFENSE'),
('UNIT_CELT_PICTISH_WARRIOR', 'UNITAI_EXPLORE'),

('UNIT_BARBARIAN_SPEARMAN', 'UNITAI_ATTACK'),
('UNIT_BARBARIAN_SPEARMAN', 'UNITAI_COUNTER'),
('UNIT_BARBARIAN_SPEARMAN', 'UNITAI_DEFENSE'),
('UNIT_BARBARIAN_SPEARMAN', 'UNITAI_EXPLORE'),

-- UNITCLASS_PIKEMAN
('UNIT_PIKEMAN', 'UNITAI_ATTACK'),
('UNIT_PIKEMAN', 'UNITAI_DEFENSE'),
('UNIT_PIKEMAN', 'UNITAI_COUNTER'),
('UNIT_PIKEMAN', 'UNITAI_EXPLORE'),

('UNIT_DANISH_BERSERKER', 'UNITAI_ATTACK'),
('UNIT_DANISH_BERSERKER', 'UNITAI_DEFENSE'),
('UNIT_DANISH_BERSERKER', 'UNITAI_EXPLORE'),

('UNIT_FCOMPANY', 'UNITAI_ATTACK'),
('UNIT_FCOMPANY', 'UNITAI_DEFENSE'),
('UNIT_FCOMPANY', 'UNITAI_EXPLORE'),
('UNIT_FCOMPANY', 'UNITAI_COUNTER'),

-- UNITCLASS_SWORDSMAN
('UNIT_SWORDSMAN', 'UNITAI_ATTACK'),
('UNIT_SWORDSMAN', 'UNITAI_DEFENSE'),
('UNIT_SWORDSMAN', 'UNITAI_EXPLORE'),

('UNIT_IROQUOIAN_MOHAWKWARRIOR', 'UNITAI_ATTACK'),
('UNIT_IROQUOIAN_MOHAWKWARRIOR', 'UNITAI_DEFENSE'),
('UNIT_IROQUOIAN_MOHAWKWARRIOR', 'UNITAI_EXPLORE'),

('UNIT_ROMAN_LEGION', 'UNITAI_ATTACK'),
('UNIT_ROMAN_LEGION', 'UNITAI_DEFENSE'),
('UNIT_ROMAN_LEGION', 'UNITAI_EXPLORE'),
('UNIT_ROMAN_LEGION', 'UNITAI_WORKER'),

('UNIT_KRIS_SWORDSMAN', 'UNITAI_ATTACK'),
('UNIT_KRIS_SWORDSMAN', 'UNITAI_DEFENSE'),
('UNIT_KRIS_SWORDSMAN', 'UNITAI_EXPLORE'),

('UNIT_BARBARIAN_SWORDSMAN', 'UNITAI_ATTACK'),
('UNIT_BARBARIAN_SWORDSMAN', 'UNITAI_DEFENSE'),
('UNIT_BARBARIAN_SWORDSMAN', 'UNITAI_EXPLORE'),

-- UNITCLASS_LONGSWORDSMAN
('UNIT_LONGSWORDSMAN', 'UNITAI_ATTACK'),
('UNIT_LONGSWORDSMAN', 'UNITAI_DEFENSE'),
('UNIT_LONGSWORDSMAN', 'UNITAI_EXPLORE'),

('UNIT_POLYNESIAN_MAORI_WARRIOR', 'UNITAI_ATTACK'),
('UNIT_POLYNESIAN_MAORI_WARRIOR', 'UNITAI_DEFENSE'),
('UNIT_POLYNESIAN_MAORI_WARRIOR', 'UNITAI_EXPLORE'),

('UNIT_JAPANESE_SAMURAI', 'UNITAI_ATTACK'),
('UNIT_JAPANESE_SAMURAI', 'UNITAI_DEFENSE'),
('UNIT_JAPANESE_SAMURAI', 'UNITAI_EXPLORE'),

-- Gun Infantry
-- UNITCLASS_TERCIO
('UNIT_SPANISH_TERCIO', 'UNITAI_ATTACK'),
('UNIT_SPANISH_TERCIO', 'UNITAI_DEFENSE'),
('UNIT_SPANISH_TERCIO', 'UNITAI_COUNTER'),
('UNIT_SPANISH_TERCIO', 'UNITAI_EXPLORE'),

('UNIT_ZULU_IMPI', 'UNITAI_ATTACK'),
('UNIT_ZULU_IMPI', 'UNITAI_DEFENSE'),
('UNIT_ZULU_IMPI', 'UNITAI_COUNTER'),
('UNIT_ZULU_IMPI', 'UNITAI_EXPLORE'),

('UNIT_FRENCH_MUSKETEER', 'UNITAI_ATTACK'),
('UNIT_FRENCH_MUSKETEER', 'UNITAI_DEFENSE'),
('UNIT_FRENCH_MUSKETEER', 'UNITAI_EXPLORE'),

('UNIT_GERMAN_LANDSKNECHT', 'UNITAI_ATTACK'),
('UNIT_GERMAN_LANDSKNECHT', 'UNITAI_DEFENSE'),
('UNIT_GERMAN_LANDSKNECHT', 'UNITAI_COUNTER'),
('UNIT_GERMAN_LANDSKNECHT', 'UNITAI_EXPLORE'),

-- UNITCLASS_FUSILIER
('UNIT_RIFLEMAN', 'UNITAI_ATTACK'),
('UNIT_RIFLEMAN', 'UNITAI_DEFENSE'),
('UNIT_RIFLEMAN', 'UNITAI_EXPLORE'),

('UNIT_SWEDISH_CAROLEAN', 'UNITAI_ATTACK'),
('UNIT_SWEDISH_CAROLEAN', 'UNITAI_DEFENSE'),
('UNIT_SWEDISH_CAROLEAN', 'UNITAI_EXPLORE'),

('UNIT_ETHIOPIAN_MEHAL_SEFARI', 'UNITAI_ATTACK'),
('UNIT_ETHIOPIAN_MEHAL_SEFARI', 'UNITAI_DEFENSE'),
('UNIT_ETHIOPIAN_MEHAL_SEFARI', 'UNITAI_EXPLORE'),

('UNIT_FRENCH_FOREIGNLEGION', 'UNITAI_ATTACK'),
('UNIT_FRENCH_FOREIGNLEGION', 'UNITAI_DEFENSE'),
('UNIT_FRENCH_FOREIGNLEGION', 'UNITAI_EXPLORE'),

-- UNITCLASS_RIFLEMAN
('UNIT_GREAT_WAR_INFANTRY', 'UNITAI_ATTACK'),
('UNIT_GREAT_WAR_INFANTRY', 'UNITAI_DEFENSE'),
('UNIT_GREAT_WAR_INFANTRY', 'UNITAI_EXPLORE'),

-- UNITCLASS_INFANTRY
('UNIT_INFANTRY', 'UNITAI_ATTACK'),
('UNIT_INFANTRY', 'UNITAI_DEFENSE'),
('UNIT_INFANTRY', 'UNITAI_EXPLORE'),

('UNIT_BRAZILIAN_PRACINHA', 'UNITAI_ATTACK'),
('UNIT_BRAZILIAN_PRACINHA', 'UNITAI_DEFENSE'),
('UNIT_BRAZILIAN_PRACINHA', 'UNITAI_EXPLORE'),

('UNIT_GUERILLA', 'UNITAI_ATTACK'),
('UNIT_GUERILLA', 'UNITAI_DEFENSE'),
('UNIT_GUERILLA', 'UNITAI_EXPLORE'),

('UNIT_DANISH_SKI_INFANTRY', 'UNITAI_ATTACK'),
('UNIT_DANISH_SKI_INFANTRY', 'UNITAI_DEFENSE'),
('UNIT_DANISH_SKI_INFANTRY', 'UNITAI_EXPLORE'),

-- UNITCLASS_MECHANIZED_INFANTRY
('UNIT_MECHANIZED_INFANTRY', 'UNITAI_ATTACK'),
('UNIT_MECHANIZED_INFANTRY', 'UNITAI_DEFENSE'),
('UNIT_MECHANIZED_INFANTRY', 'UNITAI_EXPLORE'),

---------------------------

-- Mounted Melee & Armor
-- UNITCLASS_HORSEMAN
('UNIT_HORSEMAN', 'UNITAI_DEFENSE'),
('UNIT_HORSEMAN', 'UNITAI_FAST_ATTACK'),

('UNIT_GREEK_COMPANIONCAVALRY', 'UNITAI_DEFENSE'),
('UNIT_GREEK_COMPANIONCAVALRY', 'UNITAI_FAST_ATTACK'),

('UNIT_CARTHAGINIAN_FOREST_ELEPHANT', 'UNITAI_DEFENSE'),
('UNIT_CARTHAGINIAN_FOREST_ELEPHANT', 'UNITAI_FAST_ATTACK'),

('UNIT_BARBARIAN_HORSEMAN', 'UNITAI_DEFENSE'),
('UNIT_BARBARIAN_HORSEMAN', 'UNITAI_FAST_ATTACK'),

-- UNITCLASS_KNIGHT
('UNIT_KNIGHT', 'UNITAI_DEFENSE'),
('UNIT_KNIGHT', 'UNITAI_FAST_ATTACK'),

('UNIT_BYZANTINE_CATAPHRACT', 'UNITAI_DEFENSE'),
('UNIT_BYZANTINE_CATAPHRACT', 'UNITAI_FAST_ATTACK'),

('UNIT_SPANISH_CONQUISTADOR', 'UNITAI_DEFENSE'),
('UNIT_SPANISH_CONQUISTADOR', 'UNITAI_FAST_ATTACK'),

('UNIT_SONGHAI_MUSLIMCAVALRY', 'UNITAI_DEFENSE'),
('UNIT_SONGHAI_MUSLIMCAVALRY', 'UNITAI_FAST_ATTACK'),

('UNIT_SIAMESE_WARELEPHANT', 'UNITAI_DEFENSE'),
('UNIT_SIAMESE_WARELEPHANT', 'UNITAI_FAST_ATTACK'),

-- UNITCLASS_LANCER
('UNIT_LANCER', 'UNITAI_DEFENSE'),
('UNIT_LANCER', 'UNITAI_FAST_ATTACK'),

('UNIT_OTTOMAN_SIPAHI', 'UNITAI_DEFENSE'),
('UNIT_OTTOMAN_SIPAHI', 'UNITAI_FAST_ATTACK'),

('UNIT_SWEDISH_HAKKAPELIITTA', 'UNITAI_DEFENSE'),
('UNIT_SWEDISH_HAKKAPELIITTA', 'UNITAI_FAST_ATTACK'),

('UNIT_POLISH_WINGED_HUSSAR', 'UNITAI_DEFENSE'),
('UNIT_POLISH_WINGED_HUSSAR', 'UNITAI_FAST_ATTACK'),

-- UNITCLASS_LANDSHIP
('UNIT_WWI_TANK', 'UNITAI_DEFENSE'),
('UNIT_WWI_TANK', 'UNITAI_ATTACK'),
('UNIT_WWI_TANK', 'UNITAI_FAST_ATTACK'),

-- UNITCLASS_TANK
('UNIT_TANK', 'UNITAI_DEFENSE'),
('UNIT_TANK', 'UNITAI_ATTACK'),
('UNIT_TANK', 'UNITAI_FAST_ATTACK'),

('UNIT_GERMAN_PANZER', 'UNITAI_DEFENSE'),
('UNIT_GERMAN_PANZER', 'UNITAI_ATTACK'),
('UNIT_GERMAN_PANZER', 'UNITAI_FAST_ATTACK'),

-- UNITCLASS_MODERN_ARMOR
('UNIT_MODERN_ARMOR', 'UNITAI_DEFENSE'),
('UNIT_MODERN_ARMOR', 'UNITAI_ATTACK'),
('UNIT_MODERN_ARMOR', 'UNITAI_FAST_ATTACK'),

-- UNITCLASS_MECH
('UNIT_MECH', 'UNITAI_DEFENSE'),
('UNIT_MECH', 'UNITAI_ATTACK'),
('UNIT_MECH', 'UNITAI_FAST_ATTACK'),

---------------------------

-- Ranged
-- UNITCLASS_ARCHER 
('UNIT_ARCHER', 'UNITAI_RANGED'),

('UNIT_INCAN_SLINGER','UNITAI_RANGED'),

('UNIT_BARBARIAN_ARCHER','UNITAI_RANGED'),

-- UNITCLASS_COMPOSITE_BOWMAN
('UNIT_COMPOSITE_BOWMAN','UNITAI_RANGED'),

('UNIT_MAYAN_ATLATLIST','UNITAI_RANGED'),

('UNIT_BABYLONIAN_BOWMAN','UNITAI_RANGED'),

-- UNITCLASS_CROSSBOWMAN
('UNIT_CROSSBOWMAN','UNITAI_RANGED'),

('UNIT_CHINESE_CHUKONU','UNITAI_RANGED'),

('UNIT_ENGLISH_LONGBOWMAN','UNITAI_RANGED'),

-- UNITCLASS_MUSKETMAN
('UNIT_MUSKETMAN','UNITAI_RANGED'),

('UNIT_OTTOMAN_JANISSARY','UNITAI_RANGED'),

('UNIT_AMERICAN_MINUTEMAN','UNITAI_RANGED'),
('UNIT_AMERICAN_MINUTEMAN','UNITAI_EXPLORE'),

-- UNITCLASS_GATLINGGUN
('UNIT_GATLINGGUN','UNITAI_RANGED'),

-- UNITCLASS_MACHINE_GUN
('UNIT_MACHINE_GUN','UNITAI_RANGED'),

-- infantry doesn't have a ranged pair

-- UNITCLASS_BAZOOKA
('UNIT_BAZOOKA','UNITAI_RANGED'),

---------------------------

-- Skirmishers
-- UNITCLASS_CHARIOT_ARCHER
('UNIT_CHARIOT_ARCHER','UNITAI_RANGED'),
('UNIT_CHARIOT_ARCHER','UNITAI_COUNTER'),

('UNIT_EGYPTIAN_WARCHARIOT','UNITAI_RANGED'),
('UNIT_EGYPTIAN_WARCHARIOT','UNITAI_COUNTER'),

('UNIT_BARBARIAN_AXMAN','UNITAI_RANGED'),

-- UNITCLASS_SKIRMISHER
('UNIT_MONGOLIAN_KESHIK','UNITAI_RANGED'),
('UNIT_MONGOLIAN_KESHIK','UNITAI_COUNTER'),

('UNIT_HUN_HORSE_ARCHER','UNITAI_RANGED'),
('UNIT_HUN_HORSE_ARCHER','UNITAI_COUNTER'),

-- UNITCLASS_HEAVY_SKIRMISHER
('UNIT_MOUNTED_BOWMAN','UNITAI_RANGED'),
('UNIT_MOUNTED_BOWMAN','UNITAI_COUNTER'),

('UNIT_ARABIAN_CAMELARCHER','UNITAI_RANGED'),
('UNIT_ARABIAN_CAMELARCHER','UNITAI_COUNTER'),

-- UNITCLASS_CUIRASSIER
('UNIT_CUIRASSIER','UNITAI_RANGED'),
('UNIT_CUIRASSIER','UNITAI_COUNTER'),

('UNIT_AUSTRIAN_HUSSAR','UNITAI_RANGED'),
('UNIT_AUSTRIAN_HUSSAR','UNITAI_COUNTER'),

('UNIT_INDIAN_WARELEPHANT','UNITAI_RANGED'),
('UNIT_INDIAN_WARELEPHANT','UNITAI_COUNTER'),

-- UNITCLASS_CAVALRY
('UNIT_CAVALRY','UNITAI_RANGED'),
('UNIT_CAVALRY','UNITAI_COUNTER'),

('UNIT_BERBER_CAVALRY','UNITAI_RANGED'),
('UNIT_BERBER_CAVALRY','UNITAI_COUNTER'),

('UNIT_SHOSHONE_COMANCHE_RIDERS','UNITAI_RANGED'),
('UNIT_SHOSHONE_COMANCHE_RIDERS','UNITAI_COUNTER'),

('UNIT_RUSSIAN_COSSACK','UNITAI_RANGED'),
('UNIT_RUSSIAN_COSSACK','UNITAI_COUNTER'),

-- UNITCLASS_LIGHT_TANK
('UNIT_ANTI_TANK_GUN','UNITAI_RANGED'),
('UNIT_ANTI_TANK_GUN','UNITAI_COUNTER'),

-- UNITCLASS_HELICOPTER_GUNSHIP
('UNIT_HELICOPTER_GUNSHIP','UNITAI_RANGED'),
('UNIT_HELICOPTER_GUNSHIP','UNITAI_COUNTER'),

-- Siege
-- UNITCLASS_CATAPULT
('UNIT_CATAPULT','UNITAI_CITY_BOMBARD'),
('UNIT_CATAPULT','UNITAI_RANGED'),

('UNIT_ROMAN_BALLISTA','UNITAI_CITY_BOMBARD'),
('UNIT_ROMAN_BALLISTA','UNITAI_RANGED'),

('UNIT_HUN_BATTERING_RAM', 'UNITAI_CITY_BOMBARD'),

-- UNITCLASS_TREBUCHET
('UNIT_TREBUCHET','UNITAI_CITY_BOMBARD'),
('UNIT_TREBUCHET','UNITAI_RANGED'),

('UNIT_KOREAN_HWACHA','UNITAI_CITY_BOMBARD'),
('UNIT_KOREAN_HWACHA','UNITAI_RANGED'),

-- UNITCLASS_CANNON
('UNIT_CANNON','UNITAI_CITY_BOMBARD'),
('UNIT_CANNON','UNITAI_RANGED'),

-- UNITCLASS_FIELD_GUN
('UNIT_FIELD_GUN','UNITAI_CITY_BOMBARD'),
('UNIT_FIELD_GUN','UNITAI_RANGED'),

-- UNITCLASS_ARTILLERY
('UNIT_ARTILLERY','UNITAI_CITY_BOMBARD'),
('UNIT_ARTILLERY','UNITAI_RANGED'),

-- UNITCLASS_ROCKET_ARTILLERY
('UNIT_ROCKET_ARTILLERY','UNITAI_CITY_BOMBARD'),
('UNIT_ROCKET_ARTILLERY','UNITAI_RANGED'),

---------------------------

-- Recon
-- UNITCLASS_PATHFINDER
('UNIT_SHOSHONE_PATHFINDER','UNITAI_EXPLORE'),

-- UNITCLASS_SCOUT
('UNIT_SCOUT','UNITAI_EXPLORE'),

-- UNITCLASS_EXPLORER
('UNIT_EXPLORER','UNITAI_EXPLORE'),

('UNIT_BANDEIRANTES','UNITAI_EXPLORE'),
('UNIT_BANDEIRANTES','UNITAI_WORKER'),

-- UNITCLASS_COMMANDO
('UNIT_COMMANDO','UNITAI_EXPLORE'),

-- UNITCLASS_PARATROOPER
('UNIT_PARATROOPER','UNITAI_EXPLORE'),
('UNIT_PARATROOPER','UNITAI_PARADROP'),

-- UNITCLASS_SPECIAL_FORCES
('UNIT_MARINE','UNITAI_EXPLORE'),
('UNIT_MARINE','UNITAI_PARADROP'),

-- UNITCLASS_XCOM_SQUAD
('UNIT_XCOM_SQUAD','UNITAI_EXPLORE'),
('UNIT_XCOM_SQUAD','UNITAI_PARADROP'),

---------------------------

-- Naval Melee
('UNIT_GALLEY', 'UNITAI_ATTACK_SEA'),
('UNIT_GALLEY', 'UNITAI_RESERVE_SEA'),
('UNIT_GALLEY', 'UNITAI_ESCORT_SEA'),
('UNIT_GALLEY', 'UNITAI_EXPLORE_SEA'),

-- UNITCLASS_TRIREME
('UNIT_TRIREME', 'UNITAI_ATTACK_SEA'),
('UNIT_TRIREME', 'UNITAI_RESERVE_SEA'),
('UNIT_TRIREME', 'UNITAI_ESCORT_SEA'),
('UNIT_TRIREME', 'UNITAI_EXPLORE_SEA'),

('UNIT_CARTHAGINIAN_QUINQUEREME', 'UNITAI_ATTACK_SEA'),
('UNIT_CARTHAGINIAN_QUINQUEREME', 'UNITAI_RESERVE_SEA'),
('UNIT_CARTHAGINIAN_QUINQUEREME', 'UNITAI_ESCORT_SEA'),
('UNIT_CARTHAGINIAN_QUINQUEREME', 'UNITAI_EXPLORE_SEA'),

-- UNITCLASS_CARAVEL
('UNIT_CARAVEL', 'UNITAI_ATTACK_SEA'),
('UNIT_CARAVEL', 'UNITAI_RESERVE_SEA'),
('UNIT_CARAVEL', 'UNITAI_ESCORT_SEA'),
('UNIT_CARAVEL', 'UNITAI_EXPLORE_SEA'),

('UNIT_PORTUGUESE_NAU', 'UNITAI_ATTACK_SEA'),
('UNIT_PORTUGUESE_NAU', 'UNITAI_RESERVE_SEA'),
('UNIT_PORTUGUESE_NAU', 'UNITAI_ESCORT_SEA'),
('UNIT_PORTUGUESE_NAU', 'UNITAI_EXPLORE_SEA'),

('UNIT_KOREAN_TURTLE_SHIP', 'UNITAI_ATTACK_SEA'),
('UNIT_KOREAN_TURTLE_SHIP', 'UNITAI_RESERVE_SEA'),
('UNIT_KOREAN_TURTLE_SHIP', 'UNITAI_ESCORT_SEA'),
('UNIT_KOREAN_TURTLE_SHIP', 'UNITAI_EXPLORE_SEA'),

-- UNITCLASS_CORVETTE
('UNIT_PRIVATEER', 'UNITAI_ATTACK_SEA'),
('UNIT_PRIVATEER', 'UNITAI_RESERVE_SEA'),
('UNIT_PRIVATEER', 'UNITAI_ESCORT_SEA'),
('UNIT_PRIVATEER', 'UNITAI_EXPLORE_SEA'),

('UNIT_DUTCH_SEA_BEGGAR', 'UNITAI_ATTACK_SEA'),
('UNIT_DUTCH_SEA_BEGGAR', 'UNITAI_RESERVE_SEA'),
('UNIT_DUTCH_SEA_BEGGAR', 'UNITAI_ESCORT_SEA'),
('UNIT_DUTCH_SEA_BEGGAR', 'UNITAI_EXPLORE_SEA'),

-- UNITCLASS_IRONCLAD
('UNIT_IRONCLAD', 'UNITAI_ATTACK_SEA'),
('UNIT_IRONCLAD', 'UNITAI_RESERVE_SEA'),
('UNIT_IRONCLAD', 'UNITAI_ESCORT_SEA'),
('UNIT_IRONCLAD', 'UNITAI_EXPLORE_SEA'),

-- UNITCLASS_DESTROYER
('UNIT_DESTROYER', 'UNITAI_ATTACK_SEA'),
('UNIT_DESTROYER', 'UNITAI_RESERVE_SEA'),
('UNIT_DESTROYER', 'UNITAI_ESCORT_SEA'),
('UNIT_DESTROYER', 'UNITAI_EXPLORE_SEA'),

-- UNITCLASS_MISSILE_CRUISER
('UNIT_MISSILE_CRUISER', 'UNITAI_ATTACK_SEA'),
('UNIT_MISSILE_CRUISER', 'UNITAI_RESERVE_SEA'),
('UNIT_MISSILE_CRUISER', 'UNITAI_ESCORT_SEA'),
('UNIT_MISSILE_CRUISER', 'UNITAI_MISSILE_CARRIER_SEA'),
('UNIT_MISSILE_CRUISER', 'UNITAI_EXPLORE_SEA'),

---------------------------

-- Naval Ranged
-- UNITCLASS_DROMON
('UNIT_BYZANTINE_DROMON', 'UNITAI_ASSAULT_SEA'),
('UNIT_BYZANTINE_DROMON', 'UNITAI_RESERVE_SEA'),
('UNIT_BYZANTINE_DROMON', 'UNITAI_ESCORT_SEA'),

-- UNITCLASS_GALLEASS
('UNIT_GALLEASS', 'UNITAI_ASSAULT_SEA'),
('UNIT_GALLEASS', 'UNITAI_RESERVE_SEA'),
('UNIT_GALLEASS', 'UNITAI_ESCORT_SEA'),

('UNIT_VENETIAN_GALLEASS', 'UNITAI_ASSAULT_SEA'),
('UNIT_VENETIAN_GALLEASS', 'UNITAI_RESERVE_SEA'),
('UNIT_VENETIAN_GALLEASS', 'UNITAI_ESCORT_SEA'),

-- UNITCLASS_FRIGATE
('UNIT_FRIGATE', 'UNITAI_ASSAULT_SEA'),
('UNIT_FRIGATE', 'UNITAI_RESERVE_SEA'),
('UNIT_FRIGATE', 'UNITAI_ESCORT_SEA'),

('UNIT_ENGLISH_SHIPOFTHELINE', 'UNITAI_ASSAULT_SEA'),
('UNIT_ENGLISH_SHIPOFTHELINE', 'UNITAI_RESERVE_SEA'),
('UNIT_ENGLISH_SHIPOFTHELINE', 'UNITAI_ESCORT_SEA'),

-- UNITCLASS_CRUISER
('UNIT_CRUISER', 'UNITAI_ASSAULT_SEA'),
('UNIT_CRUISER', 'UNITAI_RESERVE_SEA'),
('UNIT_CRUISER', 'UNITAI_ESCORT_SEA'),

-- UNITCLASS_BATTLESHIP
('UNIT_BATTLESHIP', 'UNITAI_ASSAULT_SEA'),
('UNIT_BATTLESHIP', 'UNITAI_RESERVE_SEA'),
('UNIT_BATTLESHIP', 'UNITAI_ESCORT_SEA'),

---------------------------

-- Submarines & Carrier
-- UNITCLASS_SUBMARINE
('UNIT_SUBMARINE', 'UNITAI_ASSAULT_SEA'),
('UNIT_SUBMARINE', 'UNITAI_RESERVE_SEA'),
('UNIT_SUBMARINE', 'UNITAI_EXPLORE_SEA'),

-- UNITCLASS_NUCLEAR_SUBMARINE
('UNIT_NUCLEAR_SUBMARINE', 'UNITAI_ASSAULT_SEA'),
('UNIT_NUCLEAR_SUBMARINE', 'UNITAI_RESERVE_SEA'),
('UNIT_NUCLEAR_SUBMARINE', 'UNITAI_EXPLORE_SEA'),
('UNIT_NUCLEAR_SUBMARINE', 'UNITAI_MISSILE_CARRIER_SEA'),

-- UNITCLASS_CARRIER
('UNIT_CARRIER','UNITAI_CARRIER_SEA'),

---------------------------
-- AntiAir
-- UNITCLASS_ANTI_AIRCRAFT_GUN
('UNIT_ANTI_AIRCRAFT_GUN', 'UNITAI_COUNTER'),

-- UNITCLASS_MOBILE_SAM
('UNIT_MOBILE_SAM', 'UNITAI_COUNTER'),

---------------------------

-- Bombers
-- UNITCLASS_BOMBER
('UNIT_WWI_BOMBER','UNITAI_ATTACK_AIR'),

-- UNITCLASS_HEAVY_BOMBER
('UNIT_BOMBER','UNITAI_ATTACK_AIR'),

('UNIT_AMERICAN_B17','UNITAI_ATTACK_AIR'),

-- UNITCLASS_STEALTH_BOMBER
('UNIT_STEALTH_BOMBER','UNITAI_ATTACK_AIR'),

---------------------------

-- Fighters
-- UNITCLASS_TRIPLANE
('UNIT_TRIPLANE','UNITAI_DEFENSE_AIR'),
('UNIT_TRIPLANE','UNITAI_CARRIER_AIR'),

-- UNITCLASS_FIGHTER
('UNIT_FIGHTER','UNITAI_DEFENSE_AIR'),
('UNIT_FIGHTER','UNITAI_CARRIER_AIR'),

('UNIT_JAPANESE_ZERO','UNITAI_DEFENSE_AIR'),
('UNIT_JAPANESE_ZERO','UNITAI_CARRIER_AIR'),

-- UNITCLASS_JET_FIGHTER
('UNIT_JET_FIGHTER','UNITAI_DEFENSE_AIR'),

---------------------------

-- Guided Missile & Nukes
-- UNITCLASS_GUIDED_MISSILE
('UNIT_GUIDED_MISSILE','UNITAI_MISSILE_AIR'),

-- UNITCLASS_ATOMIC_BOMB
('UNIT_ATOMIC_BOMB','UNITAI_ICBM'),

-- UNITCLASS_NUCLEAR_MISSILE
('UNIT_NUCLEAR_MISSILE','UNITAI_ICBM');

---------------------------
