
-- Cooldowns

UPDATE Units SET PurchaseCooldown = 1;

UPDATE Units
SET PurchaseCooldown = '0'
WHERE Type IN 
('UNIT_FRENCH_FOREIGNLEGION',
'UNIT_GERMAN_LANDSKNECHT',
'UNIT_FCOMPANY',
'UNIT_GUERILLA');

UPDATE Units SET PurchaseCooldown = 5  
WHERE Type IN 
('UNIT_CARAVAN',
'UNIT_CARGO_SHIP',
'UNIT_WORKER',
'UNIT_SETTLER',
'UNIT_PIONEER',
'UNIT_COLONIST',
'UNIT_WORKBOAT');

UPDATE Units SET PurchaseCooldown =	15  
WHERE Type IN 
('UNIT_ATOMIC_BOMB', 
'UNIT_NUCLEAR_MISSILE'); 

UPDATE Units SET GlobalFaithPurchaseCooldown =	5  
WHERE Type IN 
('UNIT_ARTIST',
'UNIT_SCIENTIST',
'UNIT_MERCHANT',
'UNIT_ENGINEER',
'UNIT_GREAT_GENERAL',
'UNIT_MONGOLIAN_KHAN',
'UNIT_PROPHET',
'UNIT_GREAT_ADMIRAL',
'UNIT_WRITER', 
'UNIT_MUSICIAN', 
'UNIT_VENETIAN_MERCHANT', 

'UNIT_SS_STASIS_CHAMBER', 
'UNIT_SS_ENGINE', 
'UNIT_SS_COCKPIT', 
'UNIT_SS_BOOSTER'); 

UPDATE Units SET HurryCostModifier = 25 
WHERE Type IN 
('UNIT_SS_STASIS_CHAMBER',
'UNIT_SS_ENGINE', 
'UNIT_SS_COCKPIT', 
'UNIT_SS_BOOSTER'); 

 