-- Keystone Options
UPDATE CustomModOptions SET Value = 1 WHERE Name = 'BALANCE_VP';


-- Enabled Pick'N'Mix Mods
UPDATE CustomModOptions
SET Value = 1
WHERE Name IN (
	'GLOBAL_SEPARATE_GP_COUNTERS',
	'GLOBAL_PASSABLE_FORTS',
	'GLOBAL_PARATROOPS_AA_DAMAGE',
	'GLOBAL_CS_GIFTS',
	'GLOBAL_CS_GIFT_SHIPS',
	'GLOBAL_CS_GIFTS_LOCAL_XP',
	'GLOBAL_CITY_FOREST_BONUS',
	'GLOBAL_CITY_JUNGLE_BONUS'
);


-- VP Balance Changes
UPDATE CustomModOptions
SET Value = 1
WHERE Name IN (
	'BALANCE_ALTERNATE_INDONESIA_TRAIT',
	'BALANCE_ALTERNATE_MAYA_TRAIT',
	'BALANCE_ALTERNATE_SIAM_TRAIT',
	'BALANCE_UNIQUE_BELIEFS_ONLY_FOR_CIV',
	'BALANCE_CULTURE_VICTORY_CHANGES',
	'BALANCE_BUILDING_INVESTMENTS',
	'BALANCE_RESOURCE_MONOPOLIES',
	'BALANCE_STRATEGIC_RESOURCE_MONOPOLIES',
	'BALANCE_HEAVY_TRIBUTE',
	'BALANCE_MINOR_PROTECTION_REQUIREMENTS',
	'BALANCE_CITY_STRENGTH_SWITCH',
	'BALANCE_RIVER_CITY_CONNECTIONS',
	'BALANCE_SPY_POINTS',
	'BALANCE_AIR_UNIT_CHANGES',
	'BALANCE_RANGED_DEFENSE_UNIT_HEALTH',
	'BALANCE_LAND_UNITS_ADJACENT_BLOCKADE',
	'BALANCE_RECON_ONLY_ANCIENT_RUINS',
	'BALANCE_INQUISITOR_NERF',
	'BALANCE_RESOURCE_SHORTAGE_UNIT_HEALING',
	'BALANCE_RESOURCE_SHORTAGE_BUILDING_REFUND',
	'BALANCE_RETROACTIVE_PROMOTIONS',
	'BALANCE_PUPPET_CHANGES',
	'BALANCE_RAZING_CREATES_PARTISANS',
	'BALANCE_HALF_XP_GOLD_PURCHASES',
	'BALANCE_PURCHASED_UNIT_DAMAGE',
	'BALANCE_SETTLERS_CONSUME_POPULATION',
	'BALANCE_ENCAMPMENTS_SPAWN_ON_VISIBLE_TILES',
	'BALANCE_BARBARIAN_THEFT',
	'BALANCE_WORLD_WONDER_COST_INCREASE',
	'BALANCE_TRADE_ROUTE_PROXIMITY_PENALTY',
	'BALANCE_TRADE_ROUTE_DESTINATION_RESTRICTION',
	'BALANCE_FLIPPED_OPEN_BORDERS_TOURISM',
	'BALANCE_NO_WARTIME_CONCERT_TOURS',
	'BALANCE_PRISONERS_OF_WAR',
	'BALANCE_PURCHASE_COST_ADJUSTMENTS',
	'BALANCE_PERMANENT_VOTE_COMMITMENTS',
	'BALANCE_QUEST_CHANGES',
	'BALANCE_RESILIENT_PANTHEONS',
	'BALANCE_XP_ON_FIRST_ATTACK'
);

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'BALANCE_WONDERS_VARIABLE_CONSOLATION' AND EXISTS (SELECT 1 FROM Community WHERE Type = 'COMMUNITY_CORE_BALANCE_WONDER_CONSOLATION_TWEAK' AND Value <> 0);


-- API Extensions
UPDATE CustomModOptions SET Value = 1 WHERE Name = 'RESOURCES_PRODUCTION_COST_MODIFIERS';


-- Slated for Deletion
UPDATE CustomModOptions SET Value = 1 WHERE Name = 'BALANCE_BOMBARD_RANGE_BUILDINGS';
UPDATE CustomModOptions SET Value = 1 WHERE Name = 'BALANCE_NEW_GREAT_PERSON_ATTRIBUTES';
UPDATE CustomModOptions SET Value = 0 WHERE Name = 'PROMOTIONS_DEEP_WATER_EMBARKATION';
