-- Keystone Options
UPDATE CustomModOptions SET Value = 1 WHERE Name = 'BALANCE_VP';

-- Enabled Pick'N'Mix Mods
UPDATE CustomModOptions
SET Value = 1
WHERE Name IN (
	'GLOBAL_CS_GIFTS',
	'GLOBAL_CS_GIFT_SHIPS',
	'GLOBAL_SEPARATE_GP_COUNTERS',
	'GLOBAL_CITY_FOREST_BONUS',
	'GLOBAL_CITY_JUNGLE_BONUS',
	'GLOBAL_PASSABLE_FORTS',
	'GLOBAL_PARATROOPS_AA_DAMAGE'
);

-- VP Balance Changes
UPDATE CustomModOptions
SET Value = 1
WHERE Name IN (
	'BALANCE_ALTERNATE_SIAM_TRAIT',
	'BALANCE_ENCAMPMENTS_SPAWN_ON_VISIBLE_TILES',
	'BALANCE_PERMANENT_VOTE_COMMITMENTS',
	'BALANCE_RIVER_CITY_CONNECTIONS',
	'BALANCE_SETTLERS_CONSUME_POPULATION',
	'BALANCE_CORE_SPIES',
	'BALANCE_BARBARIAN_THEFT',
	'BALANCE_PRISONERS_OF_WAR',
	'TRADE_ROUTE_SCALING',
	'BALANCE_ALTERNATE_INDONESIA_TRAIT',
	'BALANCE_LAND_UNITS_ADJACENT_BLOCKADE',
	'BALANCE_PURCHASED_UNIT_DAMAGE',
	'BALANCE_CORE_RESOURCE_MONOPOLIES',
	'BALANCE_CORE_RESOURCE_MONOPOLIES_STRATEGIC',
	'BALANCE_MINOR_PROTECTION_REQUIREMENTS',
	'BALANCE_CORE_VICTORY_GAME_CHANGES',
	'BALANCE_CORE_MINOR_VARIABLE_BULLYING',
	'BALANCE_CORE_MAYA_CHANGE',
	'BALANCE_CORE_PORTUGAL_CHANGE',
	'BALANCE_CORE_BUILDING_INVESTMENTS',
	'BALANCE_CORE_MILITARY_RESISTANCE',
	'BALANCE_CORE_MILITARY_RESOURCES',
	'BALANCE_RETROACTIVE_PROMOS',
	'BALANCE_DEFENSIVE_PACTS_AGGRESSION_ONLY',
	'BALANCE_CORE_SCALING_TRADE_DISTANCE',
	'BALANCE_CORE_HALF_XP_PURCHASE',
	'BALANCE_FLIPPED_TOURISM_MODIFIER_OPEN_BORDERS',
	'BALANCE_CORE_RANGED_ATTACK_PENALTY',
	'BALANCE_CORE_INQUISITOR_TWEAKS',
	'BALANCE_CORE_GOODY_RECON_ONLY',
	'BALANCE_CORE_ARCHAEOLOGY_FROM_GP',
	'BALANCE_CORE_CITY_DEFENSE_SWITCH',
	'BALANCE_WORLD_WONDER_COST_INCREASE',
	'BALANCE_PURCHASE_COST_ADJUSTMENTS',
	'BALANCE_AIR_UNIT_CHANGES',
	'BALANCE_RAZING_CREATES_PARTISANS',
	'BALANCE_QUEST_CHANGES',
	'BALANCE_PUPPET_CHANGES',
	'BALANCE_UNIQUE_BELIEFS_ONLY_FOR_CIV'
);

-- API Extensions
UPDATE CustomModOptions
SET Value = 1
WHERE Name IN (
	'RESOURCE_PRODUCTION_COST_MODIFIERS'
);

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'BALANCE_CORE_WONDERS_VARIABLE_REWARD' AND EXISTS (SELECT 1 FROM Community WHERE Type = 'COMMUNITY_CORE_BALANCE_WONDER_CONSOLATION_TWEAK' AND Value <> 0);

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'BALANCE_CORE_AFRAID_ANNEX';

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'BALANCE_CORE_RESOURCE_FLAVORS';

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'BALANCE_CORE_NEW_GP_ATTRIBUTES';

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'BALANCE_CORE_BUILDING_RESOURCE_MAINTENANCE';

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'BALANCE_CORE_BOMBARD_RANGE_BUILDINGS';

UPDATE CustomModOptions
SET Value = 1
WHERE Name = 'BALANCE_CORE_TOURISM_HUNDREDS';

-- No longer needed now that Helicopter Gunship doesn't embark anywhere
UPDATE CustomModOptions SET Value = 0 WHERE Name = 'PROMOTIONS_DEEP_WATER_EMBARKATION';

UPDATE CustomModOptions SET Value = 1 WHERE Name = 'CORE_RESILIENT_PANTHEONS';