UPDATE GameOptions
SET Visible = 1
WHERE Type IN (
	'GAMEOPTION_DISABLE_RESEARCH_AGREEMENTS',
	'GAMEOPTION_ENABLE_TECH_TRADING',
	'GAMEOPTION_NO_TECH_BROKERING',
	'GAMEOPTION_BAD_EVENTS',
	'GAMEOPTION_CIV_SPECIFIC_EVENTS',
	'GAMEOPTION_GOOD_EVENTS',
	'GAMEOPTION_NEUTRAL_EVENTS',
	'GAMEOPTION_TRADE_EVENTS'
);

UPDATE GameOptions
SET Default = 1
WHERE Type IN (
	'GAMEOPTION_DISABLE_RESEARCH_AGREEMENTS',
	'GAMEOPTION_ENABLE_TECH_TRADING',
	'GAMEOPTION_NO_TECH_BROKERING'
);
