-- Barbarian Stuff

INSERT INTO Defines (
Name, Value)
SELECT 'BALANCE_BARBARIAN_HEAL_RATE', '0'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='BARBARIAN_HEAL' AND Value= 0 );

INSERT INTO Defines (
Name, Value)
SELECT 'BALANCE_BARBARIAN_HEAL_RATE', '7'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='BARBARIAN_HEAL' AND Value= 1 );

INSERT INTO Defines (
Name, Value)
SELECT 'BALANCE_BARBARIAN_HEAL_RATE', '14'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='BARBARIAN_HEAL' AND Value= 2 );