-- General Data
UPDATE Defines SET Value = '20' WHERE Name = 'MINOR_CIV_CONTACT_GOLD_OTHER';
UPDATE Defines SET Value = '-3000' WHERE Name = 'MINOR_FRIENDSHIP_DROP_BULLY_GOLD_SUCCESS';
UPDATE Defines SET Value = '-6000' WHERE Name = 'MINOR_FRIENDSHIP_DROP_BULLY_WORKER_SUCCESS';
UPDATE Defines SET Value = '-5' WHERE Name = 'FRIENDSHIP_PER_UNIT_INTRUDING';
UPDATE Defines SET Value = '15' WHERE Name = 'FRIENDSHIP_PER_BARB_KILLED';
UPDATE Defines SET Value = '15' WHERE Name = 'FRIENDSHIP_PER_UNIT_GIFTED';
UPDATE Defines SET Value = '50' WHERE Name = 'RETURN_CIVILIAN_FRIENDSHIP';
UPDATE Defines SET Value = '35' WHERE Name = 'MINOR_CIV_QUEST_FIRST_POSSIBLE_TURN';
UPDATE Defines SET Value = '20' WHERE Name = 'MINOR_CIV_QUEST_FIRST_POSSIBLE_TURN_RAND';
UPDATE Defines SET Value = '10' WHERE Name = 'MINOR_CIV_QUEST_MIN_TURNS_BETWEEN';
UPDATE Defines SET Value = '20' WHERE Name = 'MINOR_CIV_QUEST_RAND_TURNS_BETWEEN';
UPDATE Defines SET Value = '200' WHERE Name = 'MINOR_CIV_QUEST_RAND_TURNS_BETWEEN_HOSTILE_MULTIPLIER';

-- Route
UPDATE SmallAwards SET Influence = '40' WHERE Type = 'MINOR_CIV_QUEST_ROUTE';
UPDATE SmallAwards SET Production = '70' WHERE Type = 'MINOR_CIV_QUEST_ROUTE';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_ROUTE';

-- Camp
UPDATE SmallAwards SET Influence = '25' WHERE Type = 'MINOR_CIV_QUEST_KILL_CAMP';
UPDATE SmallAwards SET GeneralPoints = '30' WHERE Type = 'MINOR_CIV_QUEST_KILL_CAMP';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_KILL_CAMP';

-- Resource
UPDATE SmallAwards SET Influence = '25' WHERE Type = 'MINOR_CIV_QUEST_CONNECT_RESOURCE';
UPDATE SmallAwards SET Gold = '90' WHERE Type = 'MINOR_CIV_QUEST_CONNECT_RESOURCE';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_CONNECT_RESOURCE';

-- Wonder
UPDATE SmallAwards SET Influence = '30' WHERE Type = 'MINOR_CIV_QUEST_CONSTRUCT_WONDER';
UPDATE SmallAwards SET Faith = '65' WHERE Type = 'MINOR_CIV_QUEST_CONSTRUCT_WONDER';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_CONSTRUCT_WONDER';

-- GP
UPDATE SmallAwards SET Influence = '25' WHERE Type = 'MINOR_CIV_QUEST_GREAT_PERSON';
UPDATE SmallAwards SET Culture = '65' WHERE Type = 'MINOR_CIV_QUEST_GREAT_PERSON';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_GREAT_PERSON';

-- Kill CS
UPDATE Defines SET Value = '0' WHERE Name = 'QUEST_DISABLED_KILL_CITY_STATE';
UPDATE SmallAwards SET Influence = '50' WHERE Type = 'MINOR_CIV_QUEST_KILL_CITY_STATE';
UPDATE SmallAwards SET Gold = '200' WHERE Type = 'MINOR_CIV_QUEST_KILL_CITY_STATE';
UPDATE SmallAwards SET GoldenAgePoints = '200' WHERE Type = 'MINOR_CIV_QUEST_KILL_CITY_STATE';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_KILL_CITY_STATE';

-- Find Player
UPDATE SmallAwards SET Influence = '30' WHERE Type = 'MINOR_CIV_QUEST_FIND_PLAYER';
UPDATE SmallAwards SET Science = '50' WHERE Type = 'MINOR_CIV_QUEST_FIND_PLAYER';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_FIND_PLAYER';

-- Find NW
UPDATE SmallAwards SET Influence = '30' WHERE Type = 'MINOR_CIV_QUEST_FIND_NATURAL_WONDER';
UPDATE SmallAwards SET GoldenAgePoints = '150' WHERE Type = 'MINOR_CIV_QUEST_FIND_NATURAL_WONDER';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_FIND_NATURAL_WONDER';

-- Give Gold
UPDATE SmallAwards SET Influence = '25' WHERE Type = 'MINOR_CIV_QUEST_GIVE_GOLD';
UPDATE SmallAwards SET Food = '100' WHERE Type = 'MINOR_CIV_QUEST_GIVE_GOLD';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_GIVE_GOLD';

-- PtP
UPDATE SmallAwards SET Influence = '30' WHERE Type = 'MINOR_CIV_QUEST_PLEDGE_TO_PROTECT';
UPDATE SmallAwards SET CapitalGPPoints = '20' WHERE Type = 'MINOR_CIV_QUEST_PLEDGE_TO_PROTECT';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_PLEDGE_TO_PROTECT';

-- Culture Contest
UPDATE SmallAwards SET Influence = '50' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_CULTURE';
UPDATE SmallAwards SET Happiness = '1' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_CULTURE';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_CULTURE';

-- Faith Contest
UPDATE SmallAwards SET Influence = '30' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_FAITH';
UPDATE SmallAwards SET GlobalGPPoints = '20' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_FAITH';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_FAITH';

-- Tech Contest
UPDATE SmallAwards SET Influence = '25' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_TECHS';
UPDATE SmallAwards SET Tourism = '300' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_TECHS';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_TECHS';

-- Bully
UPDATE SmallAwards SET Influence = '20' WHERE Type = 'MINOR_CIV_QUEST_BULLY_CITY_STATE';
UPDATE SmallAwards SET Gold = '60' WHERE Type = 'MINOR_CIV_QUEST_BULLY_CITY_STATE';
UPDATE SmallAwards SET RandomMod = '5' WHERE Type = 'MINOR_CIV_QUEST_BULLY_CITY_STATE';

-- Denounce
UPDATE SmallAwards SET Influence = '30' WHERE Type = 'MINOR_CIV_QUEST_DENOUNCE_MAJOR';
UPDATE SmallAwards SET GeneralPoints = '50' WHERE Type = 'MINOR_CIV_QUEST_DENOUNCE_MAJOR';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_DENOUNCE_MAJOR';

-- Religion
UPDATE SmallAwards SET Influence = '30' WHERE Type = 'MINOR_CIV_QUEST_SPREAD_RELIGION';
UPDATE SmallAwards SET Faith = '70' WHERE Type = 'MINOR_CIV_QUEST_SPREAD_RELIGION';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_SPREAD_RELIGION';

-- Trade Route
UPDATE SmallAwards SET Influence = '30' WHERE Type = 'MINOR_CIV_QUEST_TRADE_ROUTE';
UPDATE SmallAwards SET Food = '50' WHERE Type = 'MINOR_CIV_QUEST_TRADE_ROUTE';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_TRADE_ROUTE';

-- War
UPDATE SmallAwards SET Influence = '75' WHERE Type = 'MINOR_CIV_QUEST_WAR';
UPDATE SmallAwards SET Happiness = '1' WHERE Type = 'MINOR_CIV_QUEST_WAR';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_WAR';

-- Build NW
UPDATE SmallAwards SET Influence = '30' WHERE Type = 'MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER';
UPDATE SmallAwards SET GoldenAgePoints = '125' WHERE Type = 'MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER';

-- Find a CS
UPDATE SmallAwards SET Influence = '15' WHERE Type = 'MINOR_CIV_QUEST_FIND_CITY_STATE';
UPDATE SmallAwards SET Production = '60' WHERE Type = 'MINOR_CIV_QUEST_FIND_CITY_STATE';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_FIND_CITY_STATE';

-- Contest Tourism
UPDATE SmallAwards SET Influence = '50' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_TOURISM';
UPDATE SmallAwards SET Culture = '80' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_TOURISM';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_CONTEST_TOURISM';

-- Archaeology
UPDATE SmallAwards SET Influence = '25' WHERE Type = 'MINOR_CIV_QUEST_ARCHAEOLOGY';
UPDATE SmallAwards SET Tourism = '200' WHERE Type = 'MINOR_CIV_QUEST_ARCHAEOLOGY';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_ARCHAEOLOGY';

-- Circumnavigation
UPDATE SmallAwards SET Influence = '30' WHERE Type = 'MINOR_CIV_QUEST_CIRCUMNAVIGATION';
UPDATE SmallAwards SET AdmiralPoints = '25' WHERE Type = 'MINOR_CIV_QUEST_CIRCUMNAVIGATION';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_CIRCUMNAVIGATION';

-- Liberation
UPDATE SmallAwards SET Influence = '40' WHERE Type = 'MINOR_CIV_QUEST_LIBERATION';
UPDATE SmallAwards SET Happiness = '1' WHERE Type = 'MINOR_CIV_QUEST_LIBERATION';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_LIBERATION';

-- Discover Plot
UPDATE SmallAwards SET Influence = '30' WHERE Type = 'MINOR_CIV_QUEST_DISCOVER_PLOT';
UPDATE SmallAwards SET Gold = '100' WHERE Type = 'MINOR_CIV_QUEST_DISCOVER_PLOT';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_DISCOVER_PLOT';

-- Production
UPDATE SmallAwards SET Influence = '40' WHERE Type = 'MINOR_CIV_QUEST_BUILD_X_BUILDINGS';
UPDATE SmallAwards SET Production = '75' WHERE Type = 'MINOR_CIV_QUEST_BUILD_X_BUILDINGS';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_BUILD_X_BUILDINGS';

-- Stealing
UPDATE SmallAwards SET Influence = '60' WHERE Type = 'MINOR_CIV_QUEST_UNIT_STEAL_FROM';
UPDATE SmallAwards SET Science = '150' WHERE Type = 'MINOR_CIV_QUEST_UNIT_STEAL_FROM';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_UNIT_STEAL_FROM';

-- Coup
UPDATE SmallAwards SET Influence = '40' WHERE Type = 'MINOR_CIV_QUEST_UNIT_COUP_CITY';
UPDATE SmallAwards SET CapitalGPPoints = '150' WHERE Type = 'MINOR_CIV_QUEST_UNIT_COUP_CITY';
UPDATE SmallAwards SET RandomMod = '10' WHERE Type = 'MINOR_CIV_QUEST_UNIT_COUP_CITY';

-- Conquest
UPDATE SmallAwards SET Influence = '80' WHERE Type = 'MINOR_CIV_QUEST_UNIT_GET_CITY';
UPDATE SmallAwards SET GlobalExperience = '15' WHERE Type = 'MINOR_CIV_QUEST_UNIT_GET_CITY';
UPDATE SmallAwards SET RandomMod = '5' WHERE Type = 'MINOR_CIV_QUEST_UNIT_GET_CITY';

-- Quest Weights
UPDATE Defines SET Value = '150' WHERE Name = 'MINOR_CIV_QUEST_WEIGHT_MULTIPLIER_MILITARISTIC_KILL_CITY_STATE';
UPDATE Defines SET Value = '150' WHERE Name = 'MINOR_CIV_QUEST_WEIGHT_MULTIPLIER_HOSTILE_KILL_CITY_STATE';
UPDATE Defines SET Value = '33' WHERE Name = 'MINOR_CIV_QUEST_WEIGHT_MULTIPLIER_NEUTRAL_KILL_CITY_STATE';