-- BUILDINGS_CITY_AUTOMATON_WORKERS, TRAITS_CITY_AUTOMATON_WORKERS, POLICIES_CITY_AUTOMATON_WORKERS and TECHS_CITY_AUTOMATON_WORKERS
ALTER TABLE Traits ADD 'CityAutomatonWorkersChange' INTEGER DEFAULT 0;
ALTER TABLE Policies ADD 'CityAutomatonWorkersChange' INTEGER DEFAULT 0;
ALTER TABLE Technologies ADD 'CityAutomatonWorkersChange' INTEGER DEFAULT 0;
ALTER TABLE Buildings ADD 'CityAutomatonWorkersChange' INTEGER DEFAULT 0;
ALTER TABLE Buildings ADD 'GlobalCityAutomatonWorkersChange' INTEGER DEFAULT 0;

INSERT INTO CustomModDbUpdates(Name, Value) VALUES('GLOBAL_CITY_AUTOMATON_WORKERS', 1);