--- @meta

--- @enum ActionSubType
ActionSubTypes = {
	 ACTIONSUBTYPE_INTERFACEMODE = 0,
	 ACTIONSUBTYPE_COMMAND = 1,
	 ACTIONSUBTYPE_BUILD = 2,
	 ACTIONSUBTYPE_PROMOTION = 3,
	 ACTIONSUBTYPE_SPECIALIST = 4,
	 ACTIONSUBTYPE_CONTROL = 5,
	 ACTIONSUBTYPE_AUTOMATE = 6,
	 ACTIONSUBTYPE_MISSION = 7,

	 NUM_ACTIONSUBTYPES = 8
}
