--- @meta

--- @enum AggressivePostureType
AggressivePostureTypes = {
	AGGRESSIVE_POSTURE_NONE = 0,
	AGGRESSIVE_POSTURE_LOW = 1,
	AGGRESSIVE_POSTURE_MEDIUM = 2,
	AGGRESSIVE_POSTURE_HIGH = 3,
	AGGRESSIVE_POSTURE_INCREDIBLE = 4,
	NUM_AGGRESSIVE_POSTURE_TYPES = 5,
}
