--- @meta

--- @enum CombatPredictionType
CombatPredictionTypes = {
	NO_COMBAT_PREDICTION = -1,
	COMBAT_PREDICTION_RANGED = 0,
	COMBAT_PREDICTION_STALEMATE = 1,
	COMBAT_PREDICTION_TOTAL_DEFEAT = 2,
	COMBAT_PREDICTION_TOTAL_VICTORY = 3,
	COMBAT_PREDICTION_MAJOR_VICTORY = 4,
	COMBAT_PREDICTION_SMALL_VICTORY = 5,
	COMBAT_PREDICTION_MAJOR_DEFEAT = 6,
	COMBAT_PREDICTION_SMALL_DEFEAT = 7,
	NUM_COMBAT_PREDICTIONS = 8,
}
