--- @meta

--- @enum CommandType
CommandTypes = {
	COMMAND_PROMOTION = 0,
	COMMAND_UPGRADE = 1,
	COMMAND_AUTOMATE = 2,
	COMMAND_WAKE = 3,
	COMMAND_CANCEL = 4,
	COMMAND_CANCEL_ALL = 5,
	COMMAND_STOP_AUTOMATION = 6,
	COMMAND_DELETE = 7,
	COMMAND_GIFT = 8,
	COMMAND_HOTKEY = 9,
	NUM_COMMAND_TYPES = 10,
}
