--- @meta

--- @enum LeaderheadAnimationType
LeaderheadAnimationTypes = {
	NO_LEADERHEAD_ANIM = -1,
	LEADERHEAD_ANIM_INTRO = 1,
	LEADERHEAD_ANIM_NEUTRAL_HELLO = 2,
	LEADERHEAD_ANIM_PEACEFUL = 3,
	LEADERHEAD_ANIM_OPENING_GLOAT = 4,
	LEADERHEAD_ANIM_DECLARE_WAR = 5,
	LEADERHEAD_ANIM_ATTACKED = 6,
	LEADERHEAD_ANIM_HATE_HELLO = 7,
	LEADERHEAD_ANIM_DEFEATED = 8,
	LEADERHEAD_ANIM_REQUEST = 9,
	LEADERHEAD_ANIM_DEMAND = 10,
	LEADERHEAD_ANIM_NEUTRAL_IDLE = 11,
	LEADERHEAD_ANIM_HATE_IDLE = 12,
	LEADERHEAD_ANIM_LETS_HEAR_IT = 15,
	LEADERHEAD_ANIM_YES = 16,
	LEADERHEAD_ANIM_NO = 17,
}
