--- @meta

--- @enum MajorCivApproachType
MajorCivApproachTypes = {
	NO_MAJOR_CIV_APPROACH = -1,
	MAJOR_CIV_APPROACH_WAR = 0,
	MAJOR_CIV_APPROACH_HOSTILE = 1,
	MAJOR_CIV_APPROACH_DECEPTIVE = 2,
	MAJOR_CIV_APPROACH_GUARDED = 3,
	MAJOR_CIV_APPROACH_AFRAID = 4,
	MAJOR_CIV_APPROACH_NEUTRAL = 5,
	MAJOR_CIV_APPROACH_FRIENDLY = 6,
	NUM_MAJOR_CIV_APPROACHES = 7,
}
