--- @meta

--- @enum PeaceTreatyType
PeaceTreatyTypes = {
	NO_PEACE_TREATY_TYPE = -1,
	PEACE_TREATY_WHITE_PEACE = 0,
	PEACE_TREATY_ARMISTICE = 1,
	PEACE_TREATY_SETTLEMENT = 2,
	PEACE_TREATY_BACKDOWN = 3,
	PEACE_TREATY_SUBMISSION = 4,
	PEACE_TREATY_SURRENDER = 5,
	PEACE_TREATY_CESSION = 6,
	PEACE_TREATY_CAPITULATION = 7,
	PEACE_TREATY_UNCONDITIONAL_SURRENDER = 8,
}
