--- @meta

--- @enum TradeConnectionType
TradeConnectionTypes = {
	TRADE_CONNECTION_INTERNATIONAL = 0,
	TRADE_CONNECTION_FOOD = 1,
	TRADE_CONNECTION_PRODUCTION = 2,
	TRADE_CONNECTION_WONDER_RESOURCE = 3,
	TRADE_CONNECTION_GOLD_INTERNAL = 4,
	NUM_TRADE_CONNECTION_TYPES = 5,
}
