--- @meta

--- @type table<string, YieldType>
YieldTypes = {
	NO_YIELD = -1,
	YIELD_FOOD = 0,
	YIELD_PRODUCTION = 1,
	YIELD_GOLD = 2,
	YIELD_SCIENCE = 3,
	YIELD_CULTURE = 4,
	YIELD_FAITH = 5,
	YIELD_TOURISM = 6,
	YIELD_GOLDEN_AGE_POINTS = 7,
	YIELD_GREAT_ADMIRAL_POINTS = 9,
	YIELD_GREAT_GENERAL_POINTS = 8,
	YIELD_POPULATION = 10,
	YIELD_CULTURE_LOCAL = 11,
	NUM_YIELD_TYPES = 17,
}
