-- Gold Changes

UPDATE Units
SET HurryCostModifier= 40
WHERE Type = 'UNIT_EMISSARY' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 1 );

UPDATE Units
SET HurryCostModifier= 40
WHERE Type = 'UNIT_ENVOY' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 1 );

UPDATE Units
SET HurryCostModifier= 40
WHERE Type = 'UNIT_DIPLOMAT' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 1 );

UPDATE Units
SET HurryCostModifier= 40
WHERE Type = 'UNIT_AMBASSADOR' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 1 );

UPDATE Units
SET HurryCostModifier= 60
WHERE Type = 'UNIT_EMISSARY' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 2 );

UPDATE Units
SET HurryCostModifier= 60
WHERE Type = 'UNIT_ENVOY' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 2 );

UPDATE Units
SET HurryCostModifier= 60
WHERE Type = 'UNIT_DIPLOMAT' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 2 );

UPDATE Units
SET HurryCostModifier= 60
WHERE Type = 'UNIT_AMBASSADOR' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 2 );

UPDATE Units
SET HurryCostModifier= 80
WHERE Type = 'UNIT_EMISSARY' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 3 );

UPDATE Units
SET HurryCostModifier= 80
WHERE Type = 'UNIT_ENVOY' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 3 );

UPDATE Units
SET HurryCostModifier= 80
WHERE Type = 'UNIT_DIPLOMAT' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 3 );

UPDATE Units
SET HurryCostModifier= 80
WHERE Type = 'UNIT_AMBASSADOR' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 3 );

UPDATE Units
SET HurryCostModifier= -1
WHERE Type = 'UNIT_EMISSARY' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 4 );

UPDATE Units
SET HurryCostModifier= -1
WHERE Type = 'UNIT_ENVOY' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 4 );

UPDATE Units
SET HurryCostModifier= -1
WHERE Type = 'UNIT_DIPLOMAT' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 4 );

UPDATE Units
SET HurryCostModifier= -1
WHERE Type = 'UNIT_AMBASSADOR' AND EXISTS (SELECT * FROM CSD WHERE Type='CSD_GOLDHURRY' AND Value= 4 );