-- NOTE: Many of these are unused in CP and only have a default value.

-- Use replace instead of insert/update
REPLACE INTO Defines
	(Name, Value)
VALUES
-- These two entries control whether AI major civs and City-States are able to move their starting Settler(s) from their starting plot - set to 0 to disable the ability
-- NOTE: They can always move their starting Settler(s) if they're not able to found a city in their starting location
	('MAJORS_CAN_MOVE_STARTING_SETTLER', 1),
	('CS_CAN_MOVE_STARTING_SETTLER', 0),
-- Can units that ignore ALL terrain costs cross rivers without expending additional movement? Doesn't affect trait abilities.
	('IGNORE_GLOBAL_TERRAIN_COSTS_INCLUDES_RIVERS', 1),
-- Can units that ignore SPECIFIC terrain costs via UnitPromotions_Features or UnitPromotions_Terrains cross rivers without expending additional movement? Doesn't affect trait abilities.
	('IGNORE_SPECIFIC_TERRAIN_COSTS_INCLUDES_RIVERS', 0),
-- If > -1, a player with no cities but who is still alive (Complete Kills) will be granted a free Settler after this many turns
	('COMPLETE_KILLS_TURN_TIMER', -1),
-- Maximum number of Ideology Tenets of each Level that a Player can have (should correspond to the limitations put on human players by the Ideology Selection UI)
	('MAX_NUM_TENETS_LEVEL_1', 7),
	('MAX_NUM_TENETS_LEVEL_2', 4),
	('MAX_NUM_TENETS_LEVEL_3', 3),
-- Victory conditions
	('VICTORY_DOMINATION_CONTROL_PERCENT', 100),
-- Number of units allowed in a city
	('CITY_UNIT_LIMIT', 1),
	('HISTORY_LOCAL_NUM_BEST_CITIES', 1),
	('HISTORY_NUM_TURNS_TO_AVERAGE', 10), -- number of turns considered for yield history calculation
-- Defines used only in modmods
	('POLICY_BRANCH_HERITAGE', -1),
	('PROMOTION_DEFENSIVE_DEEPWATER_EMBARKATION', -1),
	('PROMOTION_FLAGSHIP', -1),
-- Number of rings a new city starts with
	('CITY_STARTING_RINGS', 1),
	('MAXIMUM_WORK_PLOT_DISTANCE', 3),
-- Minimum war duration for AI players
	('WAR_MAJOR_MINIMUM_TURNS', 10),
	('WAR_MINOR_MINIMUM_TURNS', 1),
-- Religion
	('INQUISITION_EFFECTIVENESS', 100), -- expected value between 1 and 100. percentage of heretics' pressure to be removed by inquisitors. does not affect prophets.
	('INQUISITOR_CONVERSION_REDUCTION_FACTOR', 2), -- Only relevant if BALANCE_CORE_INQUISITOR_TWEAKS is active. Divides missionary and prophet conversion strength by this number if an inquisitor is defending the target city.
	('RELIGION_MAXIMUM_FIXED_AMOUNT', 1), -- this number is added to the religion maximum (VP only)
	('RELIGION_MAXIMUM_PER_PLAYER_DIVISOR', 200), -- the number of majors in the game * 100 / this number is added to the religion maximum (VP only)
	('RELIGION_MAXIMUM_CAP', 8), -- cap on religion maximum (VP only)
-- Tourism
	('TOURISM_MODIFIER_SHARED_RELIGION', 25), -- percentage
	('TOURISM_MODIFIER_SHARED_RELIGION_MAX', 0), -- maximum base percentage allowed (0 is no max)
	('TOURISM_MODIFIER_SHARED_RELIGION_TYPE', 0), -- 0 = no scaling, 1 = scaling per city, 2 = scaling per population
	('MINIMUM_TOURISM_MODIFIER', -100), -- minimum total % modifier allowed (must be >= -100)
-- Golden age
	('GOLDEN_AGE_BASE_THRESHOLD_INITIAL', 500),
	('GOLDEN_AGE_THRESHOLD_CITY_MULTIPLIER', 1),
-- Minimum war duration for aggressively attacked City-States (scales with game speed)
	('WAR_MINOR_PEACE_BLOCKED_TURNS', 2),
-- City strength threshold used for Policy_YieldPerCityOverStrengthThreshold
	('CITY_STRENGTH_THRESHOLD_FOR_BONUSES', 10),
-- Number of turns a pledge of protection is blocked for after breaking it (scales with game speed)
	('PLEDGE_BROKEN_MINIMUM_TURNS', 20),
	('PLEDGE_BROKEN_MINIMUM_TURNS_BULLYING', 0), -- After bullying
-- Defensive Pact limits
	('DEFENSIVE_PACT_LIMIT_BASE', 99), -- The base number of Defensive Pacts that a civilization can form. If set to -1 or lower, Defensive Pacts cannot be formed. Each player on a team counts as 1 Defensive Pact.
	('DEFENSIVE_PACT_LIMIT_SCALER', 0), -- Additional number of Defensive Pacts permitted for each X other major civilizations ingame. 0 disables the scaler.
	('AI_DEFENSIVE_PACT_LIMIT_BASE', 2), -- Limit for AI players. Only does anything if lower than the base limit.
	('AI_DEFENSIVE_PACT_LIMIT_SCALER', 10), -- Limit for AI players. Only does anything if lower than the base limit.
-- Wonder consolation yields
	('BALANCE_WONDER_BEATEN_CONSOLATION_PRIZE', 2), -- Consolation prize of Culture (default)
	('BALANCE_CULTURE_PERCENTAGE_VALUE', 33), -- % of Production awarded as Culture if consolation prize is Culture
	('BALANCE_GA_PERCENTAGE_VALUE', 25), -- % of Production awarded as GAP if consolation prize is GAP
	('BALANCE_SCIENCE_PERCENTAGE_VALUE', 10), -- % of Production awarded as Science if consolation prize is Science
	('BALANCE_FAITH_PERCENTAGE_VALUE', 10), -- % of Production awarded as Faith if consolation prize is Faith
-- Advanced settlers
	('PIONEER_POPULATION_CHANGE', 3),
	('PIONEER_EXTRA_PLOTS', 3),
	('PIONEER_FOOD_PERCENT', 25),
	('COLONIST_POPULATION_CHANGE', 5),
	('COLONIST_EXTRA_PLOTS', 5),
	('COLONIST_FOOD_PERCENT', 50),
-- Trade routes
	('OPEN_BORDERS_MODIFIER_TRADE_GOLD', 20), -- Open Borders trade gold modifier (halved if not mutual)
-- Ideology unlock via policies
	('BALANCE_MOD_POLICY_BRANCHES_NEEDED_IDEOLOGY', 3),
	('BALANCE_MOD_POLICIES_NEEDED_IDEOLOGY', 18),
-- Resource monopolies
	('GLOBAL_RESOURCE_MONOPOLY_THRESHOLD', 50),
	('STRATEGIC_RESOURCE_MONOPOLY_THRESHOLD', 25),
-- Corporations
	('BALANCE_CORE_CORP_OFFICE_FRANCHISE_CONVERSION', 0.5),
	('BALANCE_CORE_CORP_OFFICE_TR_CONVERSION', 1.0),
-- Recon
	('BALANCE_SCOUT_XP_RANDOM_VALUE', 12),
	('BALANCE_SCOUT_XP_BASE', 1),
-- "Too early for agreement" turn buffers
	('JUST_MET_TURN_BUFFER', 10), -- Hard floor for below two
	('SHARE_OPINION_TURN_BUFFER', 20), -- How many turns after we meet a civilization must we wait before they'll share their opinion?
	('DOF_TURN_BUFFER', 50), -- How many turns after we meet a civilization must we wait before they'll accept friendship?
	('DOF_TURN_BUFFER_REDUCTION_PER_ERA', -5),
-- Help requests
	('HELP_REQUEST_TURN_LIMIT_MIN', 20), -- Base turns before Help Request can be accepted again.
	('HELP_REQUEST_TURN_LIMIT_RAND', 10), -- Randomized number of turns before Help Request can be accepted again. Added to base turns.
-- Vassalage
	('VASSAL_HAPPINESS_PERCENT', 20), -- What % of the vassal's Happiness does the master get? (NOTE: Halved in VP)
	('VASSAL_PRESSURE_PERCENT', 100), -- What % of the master's majority pressure is applied to Vassal's cities?
	('VASSALAGE_FREE_YIELD_FROM_VASSAL_PERCENT', 20), -- What % of the vassal's Science/Culture/Faith does the master get?
	('VASSAL_TOURISM_MODIFIER', 33), -- What % bonus does the master get to Tourism against the vassal?
	('VASSAL_SCORE_PERCENT', 50), -- What % of the vassal's Land/Population score does the master get?
	('VASSALAGE_VASSAL_TAX_PERCENT_MINIMUM', 0), -- Minimum percent we can tax a vassal's income. Negative values may cause undefined behavior.
	('VASSALAGE_VASSAL_TAX_PERCENT_MAXIMUM', 25), -- Maximum percent we can tax a vassal's income. Values greater than 100% will do nothing. Make sure this is a multiple of 5 please!
	('VASSALAGE_VASSAL_CITY_POP_EXPONENT', 0.8), -- How much does each vassal citizen affect the master's maintenance costs?
	('VASSALAGE_VASSAL_UNIT_MAINT_COST_PERCENT', 10), -- How much does the master pay for the vassal's units?
	('VASSALAGE_VASSAL_LOST_CITIES_THRESHOLD', 75), -- Percentage of vassal cities that must be lost before Vassalage can be ended.
	('VASSALAGE_VASSAL_POPULATION_THRESHOLD', 300), -- Percentage of population over what the vassal started with before Vassalage can be ended.
	('VASSALAGE_VASSAL_MASTER_CITY_PERCENT_THRESHOLD', 60),
	('VASSALAGE_VASSAL_MASTER_POP_PERCENT_THRESHOLD', 60),
	('VASSALAGE_CAPITULATE_BASE_THRESHOLD', 100), -- How likely is a vassal to voluntarily capitulate?
	('VASSALAGE_LIBERATE_BASE_THRESHOLD', 100), -- How likely is a master to voluntarily liberate a vassal?
-- Tech trading
	('TECH_COST_ERA_EXPONENT', 0.7), -- Exponent for era multiplier.
-- Border growth tile selection
	('PLOT_INFLUENCE_RING_COST', 200),
	('PLOT_INFLUENCE_WATER_COST', 20),
	('PLOT_INFLUENCE_YIELD_POINT_COST', -40), -- 3 yield tops 1 distance
	('PLOT_INFLUENCE_RESOURCE_COST', -180), -- should be more than 100 to be able to skip one ring
	('PLOT_INFLUENCE_NW_COST', -500),
-- World Congress
	('LEAGUE_PROPOSERS_PER_SESSION', 2),
	('LEAGUE_NUM_LEADERS_FOR_EXTRA_VOTES', 2),
	('LEAGUE_PROJECT_PROGRESS_PERCENT_WARNING', 33),
	('LEAGUE_AID_MAX', 30), -- Max Arts/Sciences % Boost - 1/3 of this is minimum % boost.
	('SCHOLAR_MINOR_ALLY_MULTIPLIER', 2),
	('SCIENCE_LEAGUE_GREAT_WORK_MODIFIER', 1),
-- Unit supply
	('MAX_UNIT_SUPPLY_GROWTH_MOD', 70),
	('PRODUCTION_PENALTY_PER_UNIT_OVER_SUPPLY', 10),
	('GROWTH_PENALTY_PER_UNIT_OVER_SUPPLY', 0),
	('UNIT_SUPPLY_BASE_TECH_REDUCTION_PER_ERA', 0),
	('UNIT_SUPPLY_CITIES_TECH_REDUCTION_MULTIPLIER', 0),
	('UNIT_SUPPLY_POPULATION_TECH_REDUCTION_MULTIPLIER', 0),
	('UNIT_SUPPLY_WAR_WEARINESS_PERCENT_REDUCTION', 34),
	('UNIT_SUPPLY_POPULATION_PUPPET_PERCENT', 100),
	('MINOR_CIV_UNIT_SUPPLY_MODIFIER_CULTURED', 0),
	('MINOR_CIV_UNIT_SUPPLY_MODIFIER_MILITARISTIC', 0),
	('MINOR_CIV_UNIT_SUPPLY_MODIFIER_MARITIME', 0),
	('MINOR_CIV_UNIT_SUPPLY_MODIFIER_MERCANTILE', 0),
	('MINOR_CIV_UNIT_SUPPLY_MODIFIER_RELIGIOUS', 0),
	('MINOR_CIV_UNIT_SUPPLY_MODIFIER_FRIENDLY', 0),
	('MINOR_CIV_UNIT_SUPPLY_MODIFIER_NEUTRAL', 0),
	('MINOR_CIV_UNIT_SUPPLY_MODIFIER_HOSTILE', 0),
	('MINOR_CIV_UNIT_SUPPLY_MODIFIER_IRRATIONAL', 0),
	('MINOR_CIV_UNIT_SUPPLY_MULTIPLIER_PER_EXTRA_CITY', 0),
	('UNIT_COST_WAR_WEARINESS_PERCENT_INCREASE', 75),
-- Traits.PopulationBoostReligion
	('BALANCE_FOLLOWER_GROWTH_BONUS', 0), -- Growth% per follower
	('BALANCE_FOLLOWER_FOOD_BONUS', 0), -- Food% per follower
	('RELIGION_FOUND_AUTO_SPREAD_PRESSURE', 0), -- Pressure to all cities on found
-- Great Musician
	('MINIMUM_TOURISM_BLAST_STRENGTH', 100),
	('GREAT_MUSICIAN_BLAST_HAPPINESS_CAPITAL', 0),
	('GREAT_MUSICIAN_BLAST_HAPPINESS_GLOBAL', 0),
-- Chance of CS to be wary of the player (or declare permanent war, if a DLL flag is enabled) in different scenarios
	('PERMANENT_WAR_AGGRESSOR_CHANCE', 40),
	('PERMANENT_WAR_OTHER_WARMONGER_CHANCE_DISTANT', 20),
	('PERMANENT_WAR_OTHER_WARMONGER_CHANCE_FAR', 30),
	('PERMANENT_WAR_OTHER_WARMONGER_CHANCE_CLOSE', 50),
	('PERMANENT_WAR_OTHER_WARMONGER_CHANCE_NEIGHBORS', 60),
	('PERMANENT_WAR_OTHER_CHANCE_DISTANT', 10),
	('PERMANENT_WAR_OTHER_CHANCE_FAR', 15),
	('PERMANENT_WAR_OTHER_CHANCE_CLOSE', 20),
	('PERMANENT_WAR_OTHER_CHANCE_NEIGHBORS', 25),
	('PERMANENT_WAR_OTHER_AT_WAR', 20),
-- Player proximity
	('PROXIMITY_NEIGHBORS_CLOSEST_CITY_REQUIREMENT', 8),
	('PROXIMITY_CLOSE_CLOSEST_CITY_POSSIBILITY', 16),
	('PROXIMITY_FAR_DISTANCE_MAX', 24),
	('AI_DIPLO_PLOT_RANGE_FROM_CITY_HOME_FRONT', 5), -- this determines whether a city is close to AI
-- Grand strategy AI
	('AI_GRAND_STRATEGY_NUM_TURNS_STRATEGY_MUST_BE_ACTIVE', 10),
	('AI_GRAND_STRATEGY_CURRENT_STRATEGY_WEIGHT', 50),
	('AI_GRAND_STRATEGY_CONQUEST_NOBODY_MET_WEIGHT', -100),
	('AI_GS_SS_TECH_PROGRESS_MOD', 600),
	('AI_GS_CULTURE_RATIO_MULTIPLIER', 60),
	('AI_GS_TOURISM_RATIO_MULTIPLIER', 80),
	('AI_GRAND_STRATEGY_OTHER_PLAYERS_GS_MULTIPLIER', 33),
	('AI_GRAND_STRATEGY_GUESS_POSITIVE_THRESHOLD', 150),
	('AI_GRAND_STRATEGY_GUESS_LIKELY_THRESHOLD', 80),
-- Homeland AI
	('AI_HOMELAND_GREAT_PERSON_TURNS_TO_WAIT', 5),
-- Economic AI
	('MAX_PLOTS_PER_EXPLORER', 20), -- Recon unit calculations
	('NEED_DIPLOMAT_THRESHOLD_MODIFIER', 125), -- Higher Threshold = Lower diplomacy desire.
	('NEED_DIPLOMAT_DESIRE_MODIFIER', 2), -- Higher Desire = Higher diplomacy desire.
	('NEED_DIPLOMAT_DISTASTE_MODIFIER', 6), -- Lower distaste = More sensitive to other player's diplomatic actions and/or city-state abuse.
-- Policy AI
	('POLICY_WEIGHT_PERCENT_DROP_NEW_BRANCH', 90), -- Negative modifier to adopting a new policy branch
	('IDEOLOGY_SCORE_PER_FREE_TENET', 45),
	('IDEOLOGY_SCORE_HAPPINESS', 10),
	('IDEOLOGY_SCORE_GRAND_STRATS', 1000),
	('IDEOLOGY_SCORE_HOSTILE', 500),
	('IDEOLOGY_SCORE_GUARDED', 250),
	('IDEOLOGY_SCORE_AFRAID', 150),
	('IDEOLOGY_SCORE_FRIENDLY', 25),
-- Tech AI
	('AI_RESEARCH_WEIGHT_MOD_PER_TURN_LEFT', 0.035),
	('AI_RESEARCH_WEIGHT_BASE_MOD', 0.2),
	('TECH_PRIORITY_UNIQUE_ITEM', 25), -- emphasis on uniques - changed formula
-- Religion AI
	('RELIGION_MAX_MISSIONARIES', 2),
	('RELIGION_MISSIONARY_RANGE_IN_TURNS', 20),
	('RELIGION_BELIEF_SCORE_CITY_MULTIPLIER', 6),
-- Deal AI
	('EACH_GOLD_PER_TURN_VALUE_PERCENT', 25), -- interest rate reduction to Gold Per Turn Value for Trade Valuation
	('DEMAND_LIMIT_MAX_VALUE', 200), -- maximum amount of gold that can be asked from the AI / that the AI can ask for when making demands
	('DEMAND_LIMIT_GAMEPROGRESS_SCALING', 20), -- scaling factor of DEMAND_LIMIT_MAX_VALUE over the course of the game (the max demand value is DEMAND_LIMIT_MAX_VALUE * (1 + GameProgress * DEMAND_LIMIT_GAMEPROGRESS_SCALING), with GameProgress the percentage of researched techs)
-- City specialization AI
	('AI_CITY_SPECIALIZATION_REEVALUATION_INTERVAL', 35),
	('AI_CITY_SPECIALIZATION_PRODUCTION_WEIGHT_OPERATIONAL_UNITS_REQUESTED', 20),
	('AI_CITY_SPECIALIZATION_PRODUCTION_WEIGHT_CIVS_AT_WAR_WITH', 150),
	('AI_CITY_SPECIALIZATION_PRODUCTION_WEIGHT_WAR_MOBILIZATION', 250),
	('AI_CITY_SPECIALIZATION_PRODUCTION_WEIGHT_EMPIRE_DEFENSE', 250),
	('AI_CITY_SPECIALIZATION_PRODUCTION_WEIGHT_EMPIRE_DEFENSE_CRITICAL', 1250),
	('AI_CITY_SPECIALIZATION_PRODUCTION_WEIGHT_FLAVOR_WONDER', 250),
-- City strategy AI
	('AI_CITYSTRATEGY_MEDIUM_CITY_POP_THRESHOLD', 7),
	('AI_CITYSTRATEGY_LARGE_CITY_POP_THRESHOLD', 15),
	('AI_CITYSTRATEGY_OPERATION_UNIT_BASE_WEIGHT', 5000),
	('AI_CITYSTRATEGY_YIELD_DEFICIENT_FOOD', 0.5), -- food is different because we include consumption.
	('AI_CITYSTRATEGY_YIELD_DEFICIENT_PRODUCTION', 1.0),
	('AI_CITYSTRATEGY_YIELD_DEFICIENT_GOLD', 1.5),
	('AI_CITYSTRATEGY_YIELD_DEFICIENT_SCIENCE', 2.5),
	('AI_CITYSTRATEGY_YIELD_DEFICIENT_CULTURE', 2.5),
	('AI_CITYSTRATEGY_YIELD_DEFICIENT_FAITH', 2.5),
	('AI_CITYSTRATEGY_WANT_TILE_IMPROVERS_MINIMUM_SIZE', 3),
-- Builder tasking AI
	('BUILDER_TASKING_PLOT_EVAL_MULTIPLIER_FOOD', 3),
	('BUILDER_TASKING_PLOT_EVAL_MULTIPLIER_PRODUCTION', 2),
	('BUILDER_TASKING_PLOT_EVAL_MULTIPLIER_GOLD', 2),
	('BUILDER_TASKING_PLOT_EVAL_MULTIPLIER_SCIENCE', 2),
	('BUILDER_TASKING_PLOT_EVAL_MULTIPLIER_CULTURE', 3),
	('BUILDER_TASKING_BASELINE_REPAIR', 1000),
	('BUILDER_TASKING_BASELINE_BUILD_ROUTES', 750),
	('BUILDER_TASKING_BASELINE_BUILD_RESOURCE_IMPROVEMENTS', 300),
	('BUILDER_TASKING_BASELINE_BUILD_IMPROVEMENTS', 100),
	('BUILDER_TASKING_BASELINE_ADDS_FOOD', 180),
	('BUILDER_TASKING_BASELINE_ADDS_GOLD', 90),
	('BUILDER_TASKING_BASELINE_ADDS_PRODUCTION', 180),
	('BUILDER_TASKING_BASELINE_ADDS_SCIENCE', 240),
	('BUILDER_TASKING_BASELINE_ADDS_CULTURE', 240),
	('BUILDER_TASKING_BASELINE_ADDS_FAITH', 240),
	('BUILDER_TASKING_BASELINE_ADDS_TOURISM', 240),
	('BUILDER_TASKING_BASELINE_ADDS_GOLDEN_AGE_POINTS', 200),
	('BUILDER_TASKING_BASELINE_ADDS_CULTURE_LOCAL', 80),
-- Military AI
	('AI_MILITARY_RECAPTURING_CITY_STATE', 200),
	('BALANCE_BASIC_ATTACK_ARMY_SIZE', 6),
	('BALANCE_ARMY_NAVY_START_SIZE', 3),
	('AI_CONFIG_MILITARY_MELEE_PER_AA', 2), -- Number of melee units per AA unit before the AI considers that they have enough
	('AI_CONFIG_MILITARY_TILES_PER_SHIP', 6), -- Number of water tiles per ship for (small?) bodies of water
-- Tactical/Operation AI
	('AI_TACTICAL_MAP_TEMP_ZONE_TURNS', 5),
	('AI_OPERATIONAL_PERCENT_HEALTH_FOR_OPERATION', 70),
	('AI_TACTICAL_MAP_DOMINANCE_PERCENTAGE', 70),
	('COMBAT_AI_OFFENSE_DAMAGEWEIGHT', 100), -- This controls how much damage an attack needs to inflict to be considered worthwhile. Default value 100. Higher -> more aggressive
	('COMBAT_AI_OFFENSE_DANGERWEIGHT', 100), -- This controls whether ending the turn on a certain plot is acceptable (defense and offense). Default value 100. Higher -> more timid
-- City governor
-- Should all be in the same ballpark, specialization decides which yield to maximize; food is always highly valued when needed
	('AI_CITIZEN_VALUE_FOOD', 8),
	('AI_CITIZEN_VALUE_PRODUCTION', 12),
	('AI_CITIZEN_VALUE_GOLD', 12),
	('AI_CITIZEN_VALUE_SCIENCE', 20),
	('AI_CITIZEN_VALUE_CULTURE', 20),
	('AI_CITIZEN_VALUE_FAITH', 20),
	('AI_CITIZEN_VALUE_GPP', 8),
	('AI_CITIZEN_VALUE_FOOD_NEED_GROWTH', 32),
	('AI_CITIZEN_VALUE_FOOD_STARVING', 500),
	('AI_CITIZEN_VALUE_GOLD_IN_DEBT', 24),
	('AI_CITIZEN_SPECIALIST_COMBO_BONUS', 1000),
	('AI_CITIZEN_UNHAPPINESS_VALUE_EMPIRE_VERY_UNHAPPY', -50000),
	('AI_CITIZEN_UNHAPPINESS_VALUE_EMPIRE_UNHAPPY', -15000),
	('AI_CITIZEN_UNHAPPINESS_VALUE_CITY_UNHAPPY', -5000),
	('AI_CITIZEN_UNHAPPINESS_VALUE_EMPIRE_HAPPY', -2000),
-- Site evaluation
	('SETTLER_DISTANCE_DROPOFF_MODIFIER', 5), -- Start of settle plot devaluation (prefer close settling)
	('SETTLER_EVALUATION_DISTANCE', 10), -- Max range for settling (unless offshore; time offset will be added)
	('CITY_RING_1_MULTIPLIER', 6), -- there are 6 ring1 plots but don't overemphasize the very short term
	('CITY_RING_2_MULTIPLIER', 6), -- there are 12 ring2 plots, workable soon
	('CITY_RING_3_MULTIPLIER', 3), -- there are 18 ring3 plots, workable late and often conflicted
	('SETTLER_FOOD_MULTIPLIER', 12),
	('SETTLER_PRODUCTION_MULTIPLIER', 8),
	('SETTLER_GOLD_MULTIPLIER', 8),
	('SETTLER_SCIENCE_MULTIPLIER', 5),
	('SETTLER_FAITH_MULTIPLIER', 4),
	('BUILD_ON_RIVER_PERCENT', 35),
	('SETTLER_BUILD_ON_COAST_PERCENT', 40),
	('BUILD_ON_RESOURCE_PERCENT', -10),
	('SETTLER_STRATEGIC_MULTIPLIER', 3),
	('CHOKEPOINT_STRATEGIC_VALUE', 10),
	('BALANCE_BAD_TILES_STRATEGIC_VALUE', -34),
	('BALANCE_FRESH_WATER_STRATEGIC_VALUE', 5),
	('BALANCE_COAST_STRATEGIC_VALUE', 3),
	('BALANCE_EMPIRE_BORDERLAND_STRATEGIC_VALUE', 30),
-- Number of cities the AI considers as core production cities for spaceship building
	('AI_NUM_CORE_CITIES_FOR_SPACESHIP', 4),
-- AI City Conquest logic: used when AI conquers a city and is deciding what to do with it
	('AI_CITY_VALUE_MULTIPLIER', 100),
	('AI_CAPITAL_VALUE_MULTIPLIER', 150),
	('AI_MOSTLY_HAPPY_THRESHOLD', 40),
	('AI_CITY_HIGH_VALUE_THRESHOLD', 80),
	('AI_CITY_SOME_VALUE_THRESHOLD', 40),
	('AI_CITY_PUPPET_BONUS_THRESHOLD', 25),
-- AI World Congress logic
	('AI_WORLD_LEADER_BASE_WEIGHT_SELF', 1000),
-- AI purchase logic
	('AI_GOLD_TREASURY_BUFFER', 50),
	('AI_GOLD_PRIORITY_DEFENSIVE_BUILDING', 250), -- No idea why this was so high by default, spending gold on defensive buildings seems like a waste unless it's an emergency
	('AI_GOLD_PRIORITY_UPGRADE_BASE', 500),
	('AI_GOLD_PRIORITY_UPGRADE_PER_FLAVOR_POINT', 100),
	('AI_PLOT_VALUE_STRATEGIC_RESOURCE', 80), -- Now equal to the luxury resource plot bonus (for luxuries we don't have yet)
	('AI_GOLD_PRIORITY_MINIMUM_PLOT_BUY_VALUE', 150),
-- City State related
	('MINOR_FRIENDSHIP_DROP_PER_TURN_DAMAGED_CAPITAL_MULTIPLIER', 100), -- Multiplier for influence loss while pledged CS is damaged
	('MINOR_INFLUENCE_SCALING_DECAY_EXPONENT', 1.5), -- Per turn influence loss exponent (VP only)
	('MINOR_QUEST_REBELLION_TIMER', 20), -- Duration of horde/rebellion quests
	('INFLUENCE_MINOR_QUEST_BOOST', 20), -- Modifier for influence from diplo missions during forum quest
	('BALANCE_CS_WAR_COOLDOWN_RATE', 50), -- How long till a City-State forgets that a major aggressively attacked it?
	('BALANCE_MINOR_PROTECTION_MINIMUM_DURATION', 10), -- How long before a major can revoke a PtP to a CS?
	('BALANCE_CS_PLEDGE_TO_PROTECT_DEFENSE_BONUS', 5), -- Bonus to CS capital's CS for each PtP
	('BALANCE_CS_PLEDGE_TO_PROTECT_DEFENSE_BONUS_MAX', 25), -- Max bonus to CS capital's CS from PtPs
	('BALANCE_CS_ALLIANCE_DEFENSE_BONUS', 25), -- Bonus to CS capital's CS for having an ally
	('BALANCE_MAX_CS_ALLY_STRENGTH', 5), -- Max number of CS calc'd for bonus for Greek UA (VP)
	('CSD_GOLD_GIFT_DISABLED', 0), -- Set to a positive value to disable gold gifts
	('MINOR_BULLY_GOLD_GROWTH_FACTOR', 400), -- Gold tribute amount increasing with game progress
	('MINOR_CIV_GOLD_PERCENT', 120), -- CS buff to keep up with AI
	('MINOR_REMOVE_SPHERE_FRIENDSHIP', 0),
	('MINOR_LIBERATION_RESTING_INFLUENCE', 0),
	('MINOR_LANDMARK_RESTING_INFLUENCE', 0), -- scales with era; set to 0 to disable all effects
	('MINOR_QUEST_ACQUIRE_CITY_BONUS_XP', 100), -- Amount of extra XP given to Juggernaut unit rewards
	('MINOR_CIV_QUEST_ROUTE_MAXIMUM_DISTANCE', 7), -- Maximum distance from nearest city to offer the city connection quest
	('MINOR_CIV_QUEST_WONDER_COMPLETION_MAX_TURNS', 30), -- Maximum turns the player is able to complete the wonder to receive this quest
	('MINOR_CIV_QUEST_FIND_CITY_MIN_DISTANCE', 16), -- Minimum distance from target city to nearest owned city to receive the find city quest
	('MINOR_CIV_QUEST_ARCHAEOLOGY_RANGE', 12), -- Maximum distance from archaeological site to offer the dig quest
	('MINOR_CIV_QUEST_ACQUIRE_CITY_MINIMUM_POP', 6),
	('MINOR_CIV_QUEST_ACQUIRE_CITY_MINIMUM_TURNS', 10),
-- City State friend/ally yields (gold, science)
-- TODO: add a table for this
	('FRIENDS_GOLD_FLAT_BONUS_AMOUNT_ANCIENT', 0),
	('FRIENDS_GOLD_FLAT_BONUS_AMOUNT_CLASSICAL', 0),
	('FRIENDS_GOLD_FLAT_BONUS_AMOUNT_MEDIEVAL', 0),
	('FRIENDS_GOLD_FLAT_BONUS_AMOUNT_RENAISSANCE', 0),
	('FRIENDS_GOLD_FLAT_BONUS_AMOUNT_INDUSTRIAL', 0),
	('ALLIES_GOLD_FLAT_BONUS_AMOUNT_ANCIENT', 0),
	('ALLIES_GOLD_FLAT_BONUS_AMOUNT_CLASSICAL', 0),
	('ALLIES_GOLD_FLAT_BONUS_AMOUNT_MEDIEVAL', 0),
	('ALLIES_GOLD_FLAT_BONUS_AMOUNT_RENAISSANCE', 0),
	('ALLIES_GOLD_FLAT_BONUS_AMOUNT_INDUSTRIAL', 0),
	('FRIENDS_SCIENCE_FLAT_BONUS_AMOUNT_ANCIENT', 0),
	('FRIENDS_SCIENCE_FLAT_BONUS_AMOUNT_CLASSICAL', 0),
	('FRIENDS_SCIENCE_FLAT_BONUS_AMOUNT_MEDIEVAL', 0),
	('FRIENDS_SCIENCE_FLAT_BONUS_AMOUNT_RENAISSANCE', 0),
	('FRIENDS_SCIENCE_FLAT_BONUS_AMOUNT_INDUSTRIAL', 0),
	('ALLIES_SCIENCE_FLAT_BONUS_AMOUNT_ANCIENT', 0),
	('ALLIES_SCIENCE_FLAT_BONUS_AMOUNT_CLASSICAL', 0),
	('ALLIES_SCIENCE_FLAT_BONUS_AMOUNT_MEDIEVAL', 0),
	('ALLIES_SCIENCE_FLAT_BONUS_AMOUNT_RENAISSANCE', 0),
	('ALLIES_SCIENCE_FLAT_BONUS_AMOUNT_INDUSTRIAL', 0),
-- City State quest reward
	('BALANCE_INFLUENCE_BOOST_PROTECTION_MINOR', 0), -- modifier to all quest rewards from PTP
	('MINOR_CIV_QUEST_REWARD_FRIENDLY', 0), -- modifier to all quest rewards if CS is Friendly
	('MINOR_CIV_QUEST_REWARD_HOSTILE', 0), -- modifier to all quest rewards is CS is Hostile
	('MINOR_CIV_QUEST_REWARD_GOLD_MERCANTILE', 100),
	('MINOR_CIV_QUEST_REWARD_GOLD_MARITIME', 100),
	('MINOR_CIV_QUEST_REWARD_SCIENCE_RELIGIOUS', 100),
	('MINOR_CIV_QUEST_REWARD_CULTURE_CULTURED', 100),
	('MINOR_CIV_QUEST_REWARD_CULTURE_NEUTRAL', 100),
	('MINOR_CIV_QUEST_REWARD_CULTURE_IRRATIONAL', 100),
	('MINOR_CIV_QUEST_REWARD_FAITH_RELIGIOUS', 100),
	('MINOR_CIV_QUEST_REWARD_FAITH_NEUTRAL', 100),
	('MINOR_CIV_QUEST_REWARD_GAP_CULTURED', 100),
	('MINOR_CIV_QUEST_REWARD_GAP_RELIGIOUS', 100),
	('MINOR_CIV_QUEST_REWARD_GAP_IRRATIONAL', 100),
	('MINOR_CIV_QUEST_REWARD_FOOD_MARITIME', 100),
	('MINOR_CIV_QUEST_REWARD_FOOD_MERCANTILE', 100),
	('MINOR_CIV_QUEST_REWARD_FOOD_NEUTRAL', 100),
	('MINOR_CIV_QUEST_REWARD_PRODUCTION_MILITARISTIC', 100),
	('MINOR_CIV_QUEST_REWARD_TOURISM_MILITARISTIC', 100),
	('MINOR_CIV_QUEST_REWARD_TOURISM_CULTURED', 100),
	('MINOR_CIV_QUEST_REWARD_TOURISM_NEUTRAL', 100),
	('MINOR_CIV_QUEST_REWARD_TOURISM_IRRATIONAL', 100),
	('MINOR_CIV_QUEST_REWARD_GPP_CULTURED', 100),
	('MINOR_CIV_QUEST_REWARD_GPP_NEUTRAL', 100),
	('MINOR_CIV_QUEST_REWARD_GPP_IRRATIONAL', 100),
	('MINOR_CIV_QUEST_REWARD_GPP_GLOBAL_RELIGIOUS', 100),
	('MINOR_CIV_QUEST_REWARD_GPP_GLOBAL_CULTURED', 100),
	('MINOR_CIV_QUEST_REWARD_GPP_GLOBAL_NEUTRAL', 100),
	('MINOR_CIV_QUEST_REWARD_GENERAL_POINTS_MILITARISTIC', 100),
	('MINOR_CIV_QUEST_REWARD_GENERAL_POINTS_CULTURED', 100),
	('MINOR_CIV_QUEST_REWARD_ADMIRAL_POINTS_MARITIME', 100),
	('MINOR_CIV_QUEST_REWARD_ADMIRAL_POINTS_CULTURED', 100),
	('MINOR_CIV_QUEST_REWARD_EXPERIENCE_MILITARISTIC', 100),
	('MINOR_CIV_QUEST_REWARD_EXPERIENCE_RELIGIOUS', 100),
-- Thresholds for demanding tribute
	('MINOR_CIV_GOLD_TRIBUTE_THRESHOLD', 0),
	('MINOR_CIV_HEAVY_TRIBUTE_THRESHOLD', 0),
-- Marriage
	('BALANCE_GPP_RATE_IN_CAPITAL_PER_MARRIAGE', 15),
	('BALANCE_MARRIAGE_RESTING_POINT_INCREASE', 75),
	('BALANCE_MARRIAGE_COST_BASE', 200),
	('BALANCE_MARRIAGE_COST_INCREASE_PER_PREVIOUS_MARRIAGE', 200),
-- Additional yield modifiers for puppets
	('PUPPET_GROWTH_MODIFIER', 0),
	('PUPPET_PRODUCTION_MODIFIER', 0),
	('PUPPET_GOLDEN_AGE_MODIFIER', 0),
	('PUPPET_TOURISM_MODIFIER', 0),
-- If set to a positive value, observer mode will stop automatically after this many turns
	('MAX_TURNS_OBSERVER_MODE', 0),
-- Misc.
	('MIN_CITY_RANGE', 3), -- Backup min city range (if MinDistanceCities or MinDistanceCityStates are 0 in the Worlds table)
	('UNHAPPINESS_PER_POPULATION_FLOAT', 0.0),
	('POLICY_COST_EXTRA_VALUE', 0.0),
	('BLOCKADE_GOLD_PENALTY', 0),
	('MINOR_MAX_XP_VALUE', -1),
	('PERSONALITY_FLAVOR_MIN_VALUE', 1),
	('INFLUENCE_TARGET_DISTANCE_WEIGHT_VALUE', 3),
	('UNIT_AUTO_EXTRA_AUTOMATIONS_DISABLED', 0),
	('MAX_CITY_ATTACK_RANGE', 2), -- For EVENTS_CITY_BOMBARD: base city attack range
	('UNIT_SPAWN_NUM_CHOICES', 5), -- Number of top choices considered when spawning a random free unit. Also used for militaristic city states' unique unit choice.
	('BLOCKADED_CITY_ATTACK_MODIFIER', 0), -- Attack bonus against blockaded cities
	('GWAM_THRESHOLD_DECREASE', 0), -- Flat GPP cost reduction for GWAM
	('BALANCE_BUILDING_INVESTMENT_BASELINE', -50), -- Cost modifier for building investment
	('BALANCE_UNIT_INVESTMENT_BASELINE', -50), -- Cost modifier for unit investment
	('BALANCE_CORE_PRODUCTION_DESERT_IMPROVEMENT', 0), -- Production yield change on featureless flat desert with improved resource
	('BALANCE_CONQUEST_REDUCTION_BOOST', 0), -- Reduce resistance turns when annexing cities. Base is hardcoded per level of influence, this adds to it.
	('EMBARKED_VISIBILITY_RANGE', 1), -- Base vision when embarked
	('CITY_RANGED_ATTACK_STRENGTH_MULTIPLIER', -40), -- Modifier of city strike strength from city defense strength
	('BONUS_PER_ADJACENT_FRIEND', 10), -- Base flanking modifier
	('AIR_SWEEP_INTERCEPTION_DAMAGE_MOD', -50), -- Modifier to damage taken when performing air sweep
	('REVOLT_COUNTER_MIN', 10), -- Number of turns in super unhappy before a city revolts
	('RELIGION_ADJACENT_CITY_DISTANCE', 9), -- Base trade route distance affected by religious pressure
	('WOUNDED_DAMAGE_MULTIPLIER', 34), -- CP changed the wounded penalty from damage penalty to CS penalty. Adjust accordingly so it's actually 1% per 3HP lost.
	('WLTKD_RESOURCE_RESET_TURNS', 0), -- WLTKD Reset Timer (<= 0 means disabled); scales with game speed
-- These will be replaced by PostDefines in VP
	('EMBASSY_IMPROVEMENT', -1),
	('JUGGERNAUT_PROMOTION', -1),
	('MARCH_SKIRMISHER_PROMOTION', -1);

--------------------------------
-- City State quest disables
-- TODO: add a table for this
--------------------------------
REPLACE INTO Defines
	(Name, Value)
VALUES
	('QUEST_DISABLED_KILL_CITY_STATE_FRIENDLY', 1), -- If enabled, Friendly CS can't give out Kill City-State quests
	('QUEST_DISABLED_FIND_CITY', 1),
	('QUEST_DISABLED_WAR', 1),
	('QUEST_DISABLED_CONSTRUCT_NATIONAL_WONDER', 1),
	('QUEST_DISABLED_GIFT_SPECIFIC_UNIT', 1),
	('QUEST_DISABLED_FIND_CITY_STATE', 1),
	('QUEST_DISABLED_INFLUENCE', 1),
	('QUEST_DISABLED_CONTEST_TOURISM', 1),
	('QUEST_DISABLED_ARCHAEOLOGY', 1),
	('QUEST_DISABLED_CIRCUMNAVIGATION', 1),
	('QUEST_DISABLED_LIBERATION', 1),
	('QUEST_DISABLED_HORDE', 1),
	('QUEST_DISABLED_REBELLION', 1),
	('QUEST_DISABLED_EXPLORE_AREA', 1),
	('QUEST_DISABLED_BUILD_X_BUILDINGS', 1),
	('QUEST_DISABLED_SPY_ON_MAJOR', 1),
	('QUEST_DISABLED_COUP', 1),
	('QUEST_DISABLED_ACQUIRE_CITY', 1),
	('QUEST_DISABLED_ACQUIRE_CITY_MILITARISTIC_ONLY', 1), -- If enabled, non-Militaristic CS can't give out Acquire City quests

--------------------------------
-- City State quest weights
-- TODO: add a table for this
--------------------------------

-- Number of copies of each City-State Quest for random selection
-- Each valid quest has X base copies - trait and personality can add or subtract copies
-- Minimum of 1 copy for each valid quest
-- The more copies of a quest, the greater the chance it is selected
-- "Hyperlink" values are specific trait + personality combinations which, if non-zero, override the normal number of copies.

-- Personal Quests
	('MINOR_CIV_QUEST_ROUTE_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_ROUTE_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_ROUTE_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_ROUTE_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_ROUTE_COPIES_MERCANTILE', 5),
	('MINOR_CIV_QUEST_ROUTE_COPIES_RELIGIOUS', 2),
	('MINOR_CIV_QUEST_ROUTE_COPIES_FRIENDLY', 10),
	('MINOR_CIV_QUEST_ROUTE_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_ROUTE_COPIES_HOSTILE', -8),
	('MINOR_CIV_QUEST_ROUTE_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_CONNECT_RESOURCE_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_CONNECT_RESOURCE_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_CONNECT_RESOURCE_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_CONNECT_RESOURCE_COPIES_MARITIME', 10),
	('MINOR_CIV_QUEST_CONNECT_RESOURCE_COPIES_MERCANTILE', 20),
	('MINOR_CIV_QUEST_CONNECT_RESOURCE_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_CONNECT_RESOURCE_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_CONNECT_RESOURCE_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_CONNECT_RESOURCE_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_CONNECT_RESOURCE_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_CONNECT_RESOURCE_COPIES_HYPERLINK', 0), -- Mercantile + Friendly

	('MINOR_CIV_QUEST_CONSTRUCT_WONDER_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_CONSTRUCT_WONDER_COPIES_CULTURED', 20),
	('MINOR_CIV_QUEST_CONSTRUCT_WONDER_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_WONDER_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_WONDER_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_WONDER_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_WONDER_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_WONDER_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_WONDER_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_WONDER_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_WONDER_COPIES_HYPERLINK', 0), -- Religious + Hostile

	('MINOR_CIV_QUEST_GREAT_PERSON_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_GREAT_PERSON_COPIES_CULTURED', 20),
	('MINOR_CIV_QUEST_GREAT_PERSON_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_GREAT_PERSON_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_GREAT_PERSON_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_GREAT_PERSON_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_GREAT_PERSON_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_GREAT_PERSON_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_GREAT_PERSON_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_GREAT_PERSON_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_GREAT_PERSON_COPIES_HYPERLINK', 0), -- Cultured + Friendly

	('MINOR_CIV_QUEST_FIND_PLAYER_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_FIND_PLAYER_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_FIND_PLAYER_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_FIND_PLAYER_COPIES_MARITIME', 20),
	('MINOR_CIV_QUEST_FIND_PLAYER_COPIES_MERCANTILE', 10),
	('MINOR_CIV_QUEST_FIND_PLAYER_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_FIND_PLAYER_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_FIND_PLAYER_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_FIND_PLAYER_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_FIND_PLAYER_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_FIND_NATURAL_WONDER_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_FIND_NATURAL_WONDER_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_FIND_NATURAL_WONDER_COPIES_MILITARISTIC', -5),
	('MINOR_CIV_QUEST_FIND_NATURAL_WONDER_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_FIND_NATURAL_WONDER_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_FIND_NATURAL_WONDER_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_FIND_NATURAL_WONDER_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_FIND_NATURAL_WONDER_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_FIND_NATURAL_WONDER_COPIES_HOSTILE', -7),
	('MINOR_CIV_QUEST_FIND_NATURAL_WONDER_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_GIVE_GOLD_COPIES_BASE', 30),
	('MINOR_CIV_QUEST_GIVE_GOLD_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_GIVE_GOLD_COPIES_MILITARISTIC', -10),
	('MINOR_CIV_QUEST_GIVE_GOLD_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_GIVE_GOLD_COPIES_MERCANTILE', 5),
	('MINOR_CIV_QUEST_GIVE_GOLD_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_GIVE_GOLD_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_GIVE_GOLD_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_GIVE_GOLD_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_GIVE_GOLD_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_PLEDGE_TO_PROTECT_COPIES_BASE', 30),
	('MINOR_CIV_QUEST_PLEDGE_TO_PROTECT_COPIES_CULTURED', 5),
	('MINOR_CIV_QUEST_PLEDGE_TO_PROTECT_COPIES_MILITARISTIC', -10),
	('MINOR_CIV_QUEST_PLEDGE_TO_PROTECT_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_PLEDGE_TO_PROTECT_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_PLEDGE_TO_PROTECT_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_PLEDGE_TO_PROTECT_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_PLEDGE_TO_PROTECT_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_PLEDGE_TO_PROTECT_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_PLEDGE_TO_PROTECT_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_BULLY_CITY_STATE_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_BULLY_CITY_STATE_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_BULLY_CITY_STATE_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_BULLY_CITY_STATE_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_BULLY_CITY_STATE_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_BULLY_CITY_STATE_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_BULLY_CITY_STATE_COPIES_FRIENDLY', -7),
	('MINOR_CIV_QUEST_BULLY_CITY_STATE_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_BULLY_CITY_STATE_COPIES_HOSTILE', 10),
	('MINOR_CIV_QUEST_BULLY_CITY_STATE_COPIES_IRRATIONAL', 5),

	('MINOR_CIV_QUEST_DENOUNCE_MAJOR_COPIES_BASE', 15),
	('MINOR_CIV_QUEST_DENOUNCE_MAJOR_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_DENOUNCE_MAJOR_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_DENOUNCE_MAJOR_COPIES_MARITIME', 5),
	('MINOR_CIV_QUEST_DENOUNCE_MAJOR_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_DENOUNCE_MAJOR_COPIES_RELIGIOUS', 10),
	('MINOR_CIV_QUEST_DENOUNCE_MAJOR_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_DENOUNCE_MAJOR_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_DENOUNCE_MAJOR_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_DENOUNCE_MAJOR_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_DENOUNCE_MAJOR_COPIES_HYPERLINK', 0), -- Mercantile + Hostile

	('MINOR_CIV_QUEST_SPREAD_RELIGION_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_SPREAD_RELIGION_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_SPREAD_RELIGION_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_SPREAD_RELIGION_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_SPREAD_RELIGION_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_SPREAD_RELIGION_COPIES_RELIGIOUS', 20),
	('MINOR_CIV_QUEST_SPREAD_RELIGION_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_SPREAD_RELIGION_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_SPREAD_RELIGION_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_SPREAD_RELIGION_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_SPREAD_RELIGION_COPIES_HYPERLINK', 0), -- Religious + Friendly

	('MINOR_CIV_QUEST_TRADE_ROUTE_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_TRADE_ROUTE_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_TRADE_ROUTE_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_TRADE_ROUTE_COPIES_MARITIME', 10),
	('MINOR_CIV_QUEST_TRADE_ROUTE_COPIES_MERCANTILE', 10),
	('MINOR_CIV_QUEST_TRADE_ROUTE_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_TRADE_ROUTE_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_TRADE_ROUTE_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_TRADE_ROUTE_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_TRADE_ROUTE_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_TRADE_ROUTE_COPIES_HYPERLINK', 0), -- Mercantile + Neutral

	('MINOR_CIV_QUEST_FIND_CITY_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_FIND_CITY_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_FIND_CITY_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_FIND_CITY_COPIES_MARITIME', 20),
	('MINOR_CIV_QUEST_FIND_CITY_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_FIND_CITY_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_FIND_CITY_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_FIND_CITY_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_FIND_CITY_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_FIND_CITY_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_WAR_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_WAR_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_WAR_COPIES_MILITARISTIC', 20),
	('MINOR_CIV_QUEST_WAR_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_WAR_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_WAR_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_WAR_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_WAR_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_WAR_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_WAR_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_WAR_COPIES_HYPERLINK', 80), -- Militaristic + Friendly

	('MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER_COPIES_CULTURED', 20),
	('MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_CONSTRUCT_NATIONAL_WONDER_COPIES_HYPERLINK', 80), -- Cultured + Hostile

	('MINOR_CIV_QUEST_GIFT_SPECIFIC_UNIT_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_GIFT_SPECIFIC_UNIT_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_GIFT_SPECIFIC_UNIT_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_GIFT_SPECIFIC_UNIT_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_GIFT_SPECIFIC_UNIT_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_GIFT_SPECIFIC_UNIT_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_GIFT_SPECIFIC_UNIT_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_GIFT_SPECIFIC_UNIT_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_GIFT_SPECIFIC_UNIT_COPIES_HOSTILE', 20),
	('MINOR_CIV_QUEST_GIFT_SPECIFIC_UNIT_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_GIFT_SPECIFIC_UNIT_COPIES_HYPERLINK', 80), -- Militaristic + Hostile

	('MINOR_CIV_QUEST_FIND_CITY_STATE_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_FIND_CITY_STATE_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_FIND_CITY_STATE_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_FIND_CITY_STATE_COPIES_MARITIME', 20),
	('MINOR_CIV_QUEST_FIND_CITY_STATE_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_FIND_CITY_STATE_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_FIND_CITY_STATE_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_FIND_CITY_STATE_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_FIND_CITY_STATE_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_FIND_CITY_STATE_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_LIBERATION_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_LIBERATION_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_LIBERATION_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_LIBERATION_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_LIBERATION_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_LIBERATION_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_LIBERATION_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_LIBERATION_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_LIBERATION_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_LIBERATION_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_LIBERATION_COPIES_HYPERLINK', 80), -- Militaristic + Friendly / Mercantile + Hostile

	('MINOR_CIV_QUEST_EXPLORE_AREA_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_EXPLORE_AREA_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_EXPLORE_AREA_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_EXPLORE_AREA_COPIES_MARITIME', 20),
	('MINOR_CIV_QUEST_EXPLORE_AREA_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_EXPLORE_AREA_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_EXPLORE_AREA_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_EXPLORE_AREA_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_EXPLORE_AREA_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_EXPLORE_AREA_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_EXPLORE_AREA_COPIES_HYPERLINK', 80), -- Maritime + Friendly / Maritime + Neutral

	('MINOR_CIV_QUEST_BUILD_X_BUILDINGS_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_BUILD_X_BUILDINGS_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_BUILD_X_BUILDINGS_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_BUILD_X_BUILDINGS_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_BUILD_X_BUILDINGS_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_BUILD_X_BUILDINGS_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_BUILD_X_BUILDINGS_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_BUILD_X_BUILDINGS_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_BUILD_X_BUILDINGS_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_BUILD_X_BUILDINGS_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_SPY_ON_MAJOR_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_SPY_ON_MAJOR_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_SPY_ON_MAJOR_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_SPY_ON_MAJOR_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_SPY_ON_MAJOR_COPIES_MERCANTILE', 20),
	('MINOR_CIV_QUEST_SPY_ON_MAJOR_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_SPY_ON_MAJOR_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_SPY_ON_MAJOR_COPIES_NEUTRAL', 20),
	('MINOR_CIV_QUEST_SPY_ON_MAJOR_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_SPY_ON_MAJOR_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_COUP_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_COUP_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_COUP_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_COUP_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_COUP_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_COUP_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_COUP_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_COUP_COPIES_NEUTRAL', 20),
	('MINOR_CIV_QUEST_COUP_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_COUP_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_ACQUIRE_CITY_COPIES_BASE', 0), -- Non-Militaristic CS will not give out this quest at all
	('MINOR_CIV_QUEST_ACQUIRE_CITY_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_ACQUIRE_CITY_COPIES_MILITARISTIC', 30),
	('MINOR_CIV_QUEST_ACQUIRE_CITY_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_ACQUIRE_CITY_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_ACQUIRE_CITY_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_ACQUIRE_CITY_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_ACQUIRE_CITY_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_ACQUIRE_CITY_COPIES_HOSTILE', 20),
	('MINOR_CIV_QUEST_ACQUIRE_CITY_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_ACQUIRE_CITY_COPIES_HYPERLINK', 80), -- Militaristic + Neutral

-- Global Quests
	('MINOR_CIV_QUEST_KILL_CAMP_COPIES_BASE', 30),
	('MINOR_CIV_QUEST_KILL_CAMP_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_KILL_CAMP_COPIES_MILITARISTIC', 60),
	('MINOR_CIV_QUEST_KILL_CAMP_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_KILL_CAMP_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_KILL_CAMP_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_KILL_CAMP_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_KILL_CAMP_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_KILL_CAMP_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_KILL_CAMP_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_KILL_CITY_STATE_COPIES_BASE', 10), -- NOTE: This is a personal quest in Community Patch Only
	('MINOR_CIV_QUEST_KILL_CITY_STATE_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_KILL_CITY_STATE_COPIES_MILITARISTIC', 10),
	('MINOR_CIV_QUEST_KILL_CITY_STATE_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_KILL_CITY_STATE_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_KILL_CITY_STATE_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_KILL_CITY_STATE_COPIES_FRIENDLY', 0), -- In Community Patch Only, friendly CS will not give this quest out at all
	('MINOR_CIV_QUEST_KILL_CITY_STATE_COPIES_NEUTRAL', -6),
	('MINOR_CIV_QUEST_KILL_CITY_STATE_COPIES_HOSTILE', 10),
	('MINOR_CIV_QUEST_KILL_CITY_STATE_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_CONTEST_CULTURE_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_CONTEST_CULTURE_COPIES_CULTURED', 10),
	('MINOR_CIV_QUEST_CONTEST_CULTURE_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_CONTEST_CULTURE_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_CONTEST_CULTURE_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_CONTEST_CULTURE_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_CONTEST_CULTURE_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_CONTEST_CULTURE_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_CONTEST_CULTURE_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_CONTEST_CULTURE_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_CONTEST_CULTURE_COPIES_HYPERLINK', 0), -- Cultured + Neutral

	('MINOR_CIV_QUEST_CONTEST_FAITH_COPIES_BASE', 5),
	('MINOR_CIV_QUEST_CONTEST_FAITH_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_CONTEST_FAITH_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_CONTEST_FAITH_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_CONTEST_FAITH_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_CONTEST_FAITH_COPIES_RELIGIOUS', 15),
	('MINOR_CIV_QUEST_CONTEST_FAITH_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_CONTEST_FAITH_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_CONTEST_FAITH_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_CONTEST_FAITH_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_CONTEST_FAITH_COPIES_HYPERLINK', 0), -- Religious + Neutral

	('MINOR_CIV_QUEST_CONTEST_TECHS_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_CONTEST_TECHS_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_CONTEST_TECHS_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_CONTEST_TECHS_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_CONTEST_TECHS_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_CONTEST_TECHS_COPIES_RELIGIOUS', -5),
	('MINOR_CIV_QUEST_CONTEST_TECHS_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_CONTEST_TECHS_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_CONTEST_TECHS_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_CONTEST_TECHS_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_INVEST_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_INVEST_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_INVEST_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_INVEST_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_INVEST_COPIES_MERCANTILE', 5),
	('MINOR_CIV_QUEST_INVEST_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_INVEST_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_INVEST_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_INVEST_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_INVEST_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_INFLUENCE_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_INFLUENCE_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_INFLUENCE_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_INFLUENCE_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_INFLUENCE_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_INFLUENCE_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_INFLUENCE_COPIES_FRIENDLY', 10),
	('MINOR_CIV_QUEST_INFLUENCE_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_INFLUENCE_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_INFLUENCE_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_CONTEST_TOURISM_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_CONTEST_TOURISM_COPIES_CULTURED', 10),
	('MINOR_CIV_QUEST_CONTEST_TOURISM_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_CONTEST_TOURISM_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_CONTEST_TOURISM_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_CONTEST_TOURISM_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_CONTEST_TOURISM_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_CONTEST_TOURISM_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_CONTEST_TOURISM_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_CONTEST_TOURISM_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_ARCHAEOLOGY_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_ARCHAEOLOGY_COPIES_CULTURED', 10),
	('MINOR_CIV_QUEST_ARCHAEOLOGY_COPIES_MILITARISTIC', 10),
	('MINOR_CIV_QUEST_ARCHAEOLOGY_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_ARCHAEOLOGY_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_ARCHAEOLOGY_COPIES_RELIGIOUS', 10),
	('MINOR_CIV_QUEST_ARCHAEOLOGY_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_ARCHAEOLOGY_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_ARCHAEOLOGY_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_ARCHAEOLOGY_COPIES_IRRATIONAL', 0),

	('MINOR_CIV_QUEST_CIRCUMNAVIGATION_COPIES_BASE', 10),
	('MINOR_CIV_QUEST_CIRCUMNAVIGATION_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_CIRCUMNAVIGATION_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_CIRCUMNAVIGATION_COPIES_MARITIME', 10),
	('MINOR_CIV_QUEST_CIRCUMNAVIGATION_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_CIRCUMNAVIGATION_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_CIRCUMNAVIGATION_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_CIRCUMNAVIGATION_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_CIRCUMNAVIGATION_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_CIRCUMNAVIGATION_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_CIRCUMNAVIGATION_COPIES_HYPERLINK', 45), -- Maritime + Friendly / Maritime + Neutral

	('MINOR_CIV_QUEST_HORDE_COPIES_BASE', 30),
	('MINOR_CIV_QUEST_HORDE_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_HORDE_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_HORDE_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_HORDE_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_HORDE_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_HORDE_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_HORDE_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_HORDE_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_HORDE_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_HORDE_COPIES_HYPERLINK', 60), -- Maritime + Hostile

	('MINOR_CIV_QUEST_REBELLION_COPIES_BASE', 50),
	('MINOR_CIV_QUEST_REBELLION_COPIES_CULTURED', 0),
	('MINOR_CIV_QUEST_REBELLION_COPIES_MILITARISTIC', 0),
	('MINOR_CIV_QUEST_REBELLION_COPIES_MARITIME', 0),
	('MINOR_CIV_QUEST_REBELLION_COPIES_MERCANTILE', 0),
	('MINOR_CIV_QUEST_REBELLION_COPIES_RELIGIOUS', 0),
	('MINOR_CIV_QUEST_REBELLION_COPIES_FRIENDLY', 0),
	('MINOR_CIV_QUEST_REBELLION_COPIES_NEUTRAL', 0),
	('MINOR_CIV_QUEST_REBELLION_COPIES_HOSTILE', 0),
	('MINOR_CIV_QUEST_REBELLION_COPIES_IRRATIONAL', 0),
	('MINOR_CIV_QUEST_REBELLION_COPIES_HYPERLINK', 80), -- Maritime + Hostile

---------------------------------------
-- Espionage
---------------------------------------

	('BALANCE_SPY_RESPAWN_TIMER', 5),

-- Calculation of the number of spies per era, if BALANCE_CORE_SPIES is activated:
-- Each era, gain 100 spy points. To get a spy, you need (iThreshold) Spy Points, with iThreshold = 100 * BALANCE_SPY_TO_PLAYER_RATIO / ((Num Minor Civs ever alive) + BALANCE_SPY_POINT_MAJOR_PLAYER_MULTIPLIER * (Num Major Civs ever alive))
-- Excessive Spy Points are stored, so if for example iThreshold = 66, you get 3 spies every 2 eras
-- iThreshold is bounded between BALANCE_SPY_POINT_THRESHOLD_MIN and BALANCE_SPY_POINT_THRESHOLD_MAX
	('BALANCE_SPY_TO_PLAYER_RATIO', 20),
	('BALANCE_SPY_POINT_MAJOR_PLAYER_MULTIPLIER', 2),
	('BALANCE_SPY_POINT_THRESHOLD_MIN', 33),
	('BALANCE_SPY_POINT_THRESHOLD_MAX', 100),

-- Influence modifier for each consecutive successfully rigged election (VP Espionage System)
	('ESPIONAGE_CONSECUTIVE_RIGGING_INFLUENCE_MODIFIER', 40),

-- Calculation of Network Points (VP Espionage System)
	('ESPIONAGE_NP_BASE', 30), -- Base Network Points generated per Turn
	('ESPIONAGE_NP_PER_SPY_RANK', 0), -- Additional Network Points per Spy Level
	('ESPIONAGE_NP_CULTURAL_INFLUENCE', 10), -- Additional Network Points for Cultural Influence
	('ESPIONAGE_NP_PER_TECHNOLOGY_BEHIND', 2), -- Additional Network Points per Technology the Spy Owner does not have
	('ESPIONAGE_NP_MAX_NUM_TECH', 10), -- Max Number of Techs taken into account (see previous line)

-- Security (VP Espionage System)
	('ESPIONAGE_NP_REDUCTION_PER_SECURITY_POINT', 160), -- divided by 100: Percentage Reduction of Network Points per Security Point
	('ESPIONAGE_MAX_NUM_SECURITY_POINTS', 50), -- Max Number of Security Points
	('ESPIONAGE_SECURITY_BASE', 10), -- Base Security
	('ESPIONAGE_SECURITY_NOT_ALL_HAVE_SPIES', 1000), -- Security if not all players have a Spy
	('ESPIONAGE_SECURITY_PREVIOUS_CITY_MISSIONS', 2), -- Security for each previous Spy Mission completed in the City
	('ESPIONAGE_SECURITY_PER_POPULATION', -2), -- Security per Population in City
	('ESPIONAGE_SECURITY_PER_POPULATION_BUILDING_SCALER', 360), -- Adds +1 Security every time X reaches this value, where X = (total SpySecurityModifierPerXPop in city) * (city population)
	('ESPIONAGE_SECURITY_PER_TRADE_ROUTE', -1), -- Security per Trade Route to/from City
	('ESPIONAGE_SECURITY_PER_EXCESS_UNHAPPINESS', -4), -- Security per Excess Unhappiness in City

-- Spy XP (VP Espionage System)
	('ESPIONAGE_SPY_EXPERIENCE_DENOMINATOR', 100), -- XP needed to get to the next Level (scales with game speed)
	('ESPIONAGE_XP_PER_TURN_COUNTERSPY', 0), -- XP gained per Turn when active as Counterspy
	('ESPIONAGE_XP_PER_TURN_DIPLOMAT', 0), -- XP gained per Turn when active as Diplomat
	('ESPIONAGE_XP_PER_TURN_OFFENSIVE', 0), -- XP gained per Turn when active against another Major Civ
	('ESPIONAGE_XP_PER_TURN_CITYSTATE', 0), -- XP gained per Turn when active in a City-State
	('ESPIONAGE_XP_RIGGING_SUCCESS', 0), -- XP gained when successfully rigging an Election
	('ESPIONAGE_XP_UNCOVER_INTRIGUE', 0), -- XP gained when uncovering an Intrigue
	('ESPIONAGE_SPY_XP_MISSION_SUCCESS_PERCENT', 0), -- When successfully completing a Spy Mission, gain (NP Points needed for Mission) * ESPIONAGE_XP_MISSION_SUCESS_PERCENT / 100 XP

	('ESPIONAGE_COUNTERSPY_CHANGE_FOCUS_COOLDOWN', 5), -- Cooldown between switching Counterspy Missions
	('ESPIONAGE_SPY_POINT_UNIT', 100), -- Number of spy points a value of '1' in database columns like Eras.SpiesGrantedForPlayer or Buildings.ExtraSpies corresponds to

---------------------------------------
-- VP happiness system
---------------------------------------
	('UNHAPPY_THRESHOLD', 50), -- Below this approval rating threshold, the empire is unhappy

-- Bonus/Penalty to Growth based on Local Happiness
	('LOCAL_HAPPINESS_FOOD_MODIFIER', 2), -- % bonus to Growth per point of Local Happiness above Local Unhappiness
	('LOCAL_UNHAPPINESS_FOOD_MODIFIER', 10), -- % penalty to Growth per point of Local Unhappiness above Local Happiness

-- Penalty to Growth if empire is super unhappy
	('GLOBAL_GROWTH_PENALTY_PER_UNHAPPY', 2.5), -- Global % penalty to Growth when the empire is unhappy, per approval rating % below 50

-- Production penalties if unhappy
	('LOCAL_UNHAPPY_SETTLER_PRODUCTION_PENALTY', -10), -- Local % penalty to Settler production for each point of Local Unhappiness above Local Happiness
	('LOCAL_UNHAPPY_COMBAT_UNIT_PRODUCTION_PENALTY', -10), -- Local % penalty to combat unit production for each point of Local Unhappiness above Local Happiness
	('GLOBAL_SETTLER_PRODUCTION_PENALTY_PER_UNHAPPY', 2.5), -- Global % penalty to Settler production when the empire is unhappy, per approval rating % below 50
	('UNHAPPY_MAX_UNIT_PRODUCTION_PENALTY', -75), -- Maximum penalty to any kind of unit production from happiness

-- Unhappiness from Needs
	('YIELD_MEDIAN_PERCENTILE', 50), -- 50 = true median. Values below 50 will try to pick a city below the true median, values above 50 will try to pick a city above it. Capped between 1 and 100.
	('YIELD_MEDIAN_MIN_POP_REQUIREMENT', 3), -- The required population for a city to be counted in the global median for Needs. Prevents an early game unhappiness spike due to the high initial rate per citizen.
	('TECH_COUNT_MEDIAN_PERCENTILE', 50), -- 50 = true median. See YIELD_MEDIAN_PERCENTILE above. Only used if TECH_NEED_MODIFIER_PER_TECH_ABOVE_MEDIAN or TECH_NEED_MODIFIER_PER_TECH_BELOW_MEDIAN are enabled below.

	('DISTRESS_MEDIAN_BASE_MODIFIER', 100), -- The median Food/Production need for a city (after modifiers) is multiplied by this value and then divided by 100. Higher values = more Unhappiness.
	('DISTRESS_MEDIAN_RATE_CHANGE', 0.65), -- The rate at which the global median for Distress changes. Valid values are between 0.01 and 1.00. Higher values cause the median to shift more quickly.

	('POVERTY_MEDIAN_BASE_MODIFIER', 100), -- The median Gold need for a city (after modifiers) is multiplied by this value and then divided by 100. Higher values = more Unhappiness.
	('POVERTY_MEDIAN_RATE_CHANGE', 0.65), -- The rate at which the global median for Poverty changes. Valid values are between 0.01 and 1.00. Higher values cause the median to shift more quickly.

	('ILLITERACY_MEDIAN_BASE_MODIFIER', 100), -- The median Science need for a city (after modifiers) is multiplied by this value and then divided by 100. Higher values = more Unhappiness.
	('ILLITERACY_MEDIAN_RATE_CHANGE', 0.65), -- The rate at which the global median for Illiteracy changes. Valid values are between 0.01 and 1.00. Higher values cause the median to shift more quickly.

	('BOREDOM_MEDIAN_BASE_MODIFIER', 100), -- The median Culture need for a city (after modifiers) is multiplied by this value and then divided by 100. Higher values = more Unhappiness.
	('BOREDOM_MEDIAN_RATE_CHANGE', 0.65), -- The rate at which the global median for Boredom changes. Valid values are between 0.01 and 1.00. Higher values cause the median to shift more quickly.

	('UNHAPPINESS_PER_RELIGIOUS_MINORITY_POP', 0.5), -- Base Unhappiness per religious minority citizen. Modified by need modifiers. (rounded up)

-- Unhappiness Need Modifiers (modify the median value)
	('CAPITAL_NEED_MODIFIER', 25), -- +x% Needs in the capital. Offsets boost from Palace, helps make Capital a source of Unhappiness early on.
	('TECH_NEED_MODIFIER_PERCENT_RESEARCHED', 0), -- Modifier to needs equal to % of techs researched, multiplied by this value and then divided by 100. Disabled by default.
	('TECH_NEED_MODIFIER_PER_TECH_ABOVE_MEDIAN', 0), -- Modifier to needs for each tech ahead of the median # of techs researched you are. Disabled by default. 100 = 1%.
	('TECH_NEED_MODIFIER_PER_TECH_BELOW_MEDIAN', 0), -- Modifier to needs for each tech behind the median # of techs researched you are. Disabled by default. -100 = -1%.
	('CITY_SIZE_NEED_MODIFIER', 0), -- Modifier to needs per citizen in the city. Disabled by default. -100 = -1%.
	('EMPIRE_SIZE_NEED_MODIFIER_CITIES', 500), -- Modifier to needs per non-puppet city in the empire, excluding the capital. Scales with map size. Default is 500 (+5%). Does not support negative values.
	('EMPIRE_SIZE_NEED_MODIFIER_POP', 125), --  Modifier to needs per citizen in the empire, excluding those in puppet cities. Scales with map size. Default is 125 (+1% per 8 citizens). Does not support negative values.
	('EMPIRE_SIZE_NEED_MODIFIER_CAP', 100000), -- Cap to total Empire Size Modifier for Needs. (1 = 1%)

-- Unhappiness from Other Sources
	('UNHAPPINESS_PER_STARVING_POP', 1.0), -- Unhappiness point per starving citizen. (rounded down)
	('UNHAPPINESS_PER_PILLAGED_TILE', 0.5), -- Unhappiness point per pillaged plot owned by city. (rounded down)
	('UNHAPPINESS_PER_ISOLATED_POP', 0.34), -- Unhappiness point per pop if unconnected or blockaded. (rounded down)
	('UNHAPPINESS_PER_SPECIALIST', 100), -- 100 = 1 unhappiness per specialist.
	('UNHAPPINESS_PER_X_PUPPET_CITIZENS', 4), -- Puppets produce flat unhappiness based on # of citizens in the city. This is the divisor.
	('WAR_WEARINESS_POPULATION_PERCENT_CAP', 34), -- x% of the War Weariness % (which ranges from 0 to 100) is multiplied by total population and divided by 100 to calculate Unhappiness from War Weariness.

---------------------------------------
-- Tourism influence levels
-- Probably should be converted into a table as well?
---------------------------------------

-- These 5 values change the amount of gold earned from trade routes with influenced civs. Higher influence = more gold (trade-off for higher influence).
	('BALANCE_GOLD_INFLUENCE_LEVEL_EXOTIC', 200),
	('BALANCE_GOLD_INFLUENCE_LEVEL_FAMILIAR', 400),
	('BALANCE_GOLD_INFLUENCE_LEVEL_POPULAR', 600),
	('BALANCE_GOLD_INFLUENCE_LEVEL_INFLUENTIAL', 800),
	('BALANCE_GOLD_INFLUENCE_LEVEL_DOMINANT', 1000),

-- These 5 values change the amount of growth% earned from trade routes with influenced civs. Higher influence = more growth% (trade-off for higher influence). 
	('BALANCE_GROWTH_INFLUENCE_LEVEL_EXOTIC', 5),
	('BALANCE_GROWTH_INFLUENCE_LEVEL_FAMILIAR', 10),
	('BALANCE_GROWTH_INFLUENCE_LEVEL_POPULAR', 15),
	('BALANCE_GROWTH_INFLUENCE_LEVEL_INFLUENTIAL', 20),
	('BALANCE_GROWTH_INFLUENCE_LEVEL_DOMINANT', 25),

--- These 5 values change the amount of science earned from trade routes with influence civs. Each is adding to an incremental value (so Familiar is already 1, Popular already 2, etc.)
	('BALANCE_SCIENCE_INFLUENCE_LEVEL_EXOTIC', 0),
	('BALANCE_SCIENCE_INFLUENCE_LEVEL_FAMILIAR', 1),
	('BALANCE_SCIENCE_INFLUENCE_LEVEL_POPULAR', 2),
	('BALANCE_SCIENCE_INFLUENCE_LEVEL_INFLUENTIAL', 3),
	('BALANCE_SCIENCE_INFLUENCE_LEVEL_DOMINANT', 4);

---------------------------------------
-- Barbarians
---------------------------------------
REPLACE INTO Defines
	(Name, Value)
VALUES
	('BALANCE_BARBARIAN_HEAL_RATE', 0), -- The rate at which Barbarian units heal.

-- Camp Spawning
	('BARBARIAN_CAMP_FIRST_TURN_PERCENT_PER_ERA', 0), -- VP Only: increase to target % of camps to spawn (for the initial spawning) per era. 10 = 1%.
	('BARBARIAN_CAMP_ODDS_OF_NEW_CAMP_SPAWNING', 50), -- Community Patch Only: % chance of a new encampment spawning each turn
	('BARBARIAN_CAMP_MINIMUM_ISLAND_SIZE', 2), -- # of tiles required in a landmass for a camp to spawn.
	('BARBARIAN_CAMP_MINIMUM_DISTANCE_ANOTHER_CAMP', 4), -- Camps can't spawn within X tiles of another camp OR city.
	('BARBARIAN_CAMP_MINIMUM_DISTANCE_RECENTLY_CLEARED_CAMP', 2), -- Min. distance between new camps and a recently cleared camp OR city.
	('BARBARIAN_CAMP_CLEARED_MIN_TURNS_TO_RESPAWN', 15), -- Number of turns before a camp OR city is no longer considered recently cleared. Does not scale with game speed.
	('BARBARIAN_CAMP_COASTAL_SPAWN_ROLL', 33), -- target % of Barbarian camps to create on the coast
	('BARBARIAN_INITIAL_SPAWN_TURN', 0), -- After X turns have elapsed, Barbarians will spawn for the first time. Minimum 0.
	('BARBARIAN_CAMP_SPAWN_RATE', 2), -- Vox Populi only: A camp will spawn every X turns after the initial spawn.
	('BARBARIAN_CAMP_SPAWN_RATE_RAGING', -1), -- Vox Populi only: Spawn rate change if Raging Barbarians is enabled.
	('BARBARIAN_CAMP_SPAWN_RATE_CHILL', 1), -- Vox Populi only: Spawn rate change if Chill Barbarians is enabled.
	('BARBARIAN_CAMP_NUM_AFTER_INITIAL', 1), -- The number of camps to spawn each turn if the random roll succeeds (Community Patch) or next spawn turn occurs (Vox Populi).
	('BARBARIAN_CAMP_NUM_AFTER_INITIAL_CHILL', 0), -- Change if Chill Barbarians is enabled.
	('BARBARIAN_CAMP_NUM_AFTER_INITIAL_RAGING', 0), -- Change if Raging Barbarians is enabled.

-- Unit Spawn Timers
	('BARBARIAN_INITIAL_SPAWN_TURN_FROM_SPAWNER', 10), -- Barbarians can start spawning from camps and cities after this many turns have passed.
	('BARBARIAN_INITIAL_SPAWN_SPAWNER_DELAY', 0), -- Camps and cities created on the initial spawn turn have X turns added to their next spawn delay.
	('BARBARIAN_MIN_SPAWN_DELAY', 2), -- Min. number of turns between spawns
-- Encampments
	('BARBARIAN_SPAWN_DELAY_FROM_ENCAMPMENT', 12), -- Base spawn delay from encampment.
	('BARBARIAN_SPAWN_DELAY_FROM_ENCAMPMENT_RAND', 9), -- Additional random spawn delay from encampment.
	('BARBARIAN_SPAWN_DELAY_FROM_ENCAMPMENT_CHILL_MULTIPLIER', 200), -- 2x spawn delay for encampments with Chill Barbarians enabled
	('BARBARIAN_SPAWN_DELAY_FROM_ENCAMPMENT_RAGING_MULTIPLIER', 50), -- 0.5x spawn delay for encampments with Raging Barbarians enabled
	('BARBARIAN_ENCAMPMENT_SPAWN_DELAY_REDUCTION_PER_SPAWN', -1), -- Reduction to spawn timer per spawned unit (not counting any initially spawned second unit)
	('BARBARIAN_ENCAMPMENT_MAX_SPAWN_DELAY_REDUCTION', -3), -- Max. reduction to spawn timer from spawned units
	('BARBARIAN_ENCAMPMENT_ATTACKED_DELAY_MULTIPLIER', 50), -- 0.5x current spawn time if a camp is attacked
-- Cities
	('BARBARIAN_SPAWN_DELAY_FROM_CITY', 6), -- Base spawn delay from city.
	('BARBARIAN_SPAWN_DELAY_FROM_CITY_RAND', 4), -- Additional random spawn delay from city.
	('BARBARIAN_SPAWN_DELAY_FROM_CITY_CHILL_MULTIPLIER', 150), -- 1.5x spawn delay for cities with Chill Barbarians enabled
	('BARBARIAN_SPAWN_DELAY_FROM_CITY_RAGING_MULTIPLIER', 50), -- 0.5x spawn delay for cities with Raging Barbarians enabled
	('BARBARIAN_CITY_SPAWN_DELAY_REDUCTION_PER_SPAWN', -1), -- Reduction to spawn timer per spawned unit
	('BARBARIAN_CITY_MAX_SPAWN_DELAY_REDUCTION', -3), -- Max. reduction to spawn timer from spawned units
	('BARBARIAN_CITY_ATTACKED_DELAY_MULTIPLIER', 50), -- 0.5x current spawn time if a city is attacked

-- Number of Units Spawned
-- Encampment Creation
	('BARBARIAN_NUM_UNITS_INITIAL_ENCAMPMENT_CREATION_SPAWN', 1), -- The number of units an encampment spawns when created (first spawning turn only).
	('BARBARIAN_NUM_UNITS_INITIAL_ENCAMPMENT_CREATION_SPAWN_CHILL', -1), -- Change if Chill Barbarians is enabled.
	('BARBARIAN_NUM_UNITS_INITIAL_ENCAMPMENT_CREATION_SPAWN_RAGING', 0), -- Change if Raging Barbarians is enabled.
	('BARBARIAN_NUM_UNITS_INITIAL_ENCAMPMENT_CREATION_SPAWN_PER_ERA', 0), -- Extra units added per era (first spawning turn only). Number of extra units = this value * (era #) / 100, rounded down.
	('BARBARIAN_NUM_UNITS_ENCAMPMENT_CREATION_SPAWN', 1), -- The number of units an encampment spawns when created.
	('BARBARIAN_NUM_UNITS_ENCAMPMENT_CREATION_SPAWN_CHILL', 0), -- Change if Chill Barbarians is enabled.
	('BARBARIAN_NUM_UNITS_ENCAMPMENT_CREATION_SPAWN_RAGING', 0), -- Change if Raging Barbarians is enabled.
	('BARBARIAN_NUM_UNITS_ENCAMPMENT_CREATION_SPAWN_PER_ERA', 0), -- Extra units added per era. Number of extra units = this value * (era #) / 100, rounded down.
-- City Capture
	('BARBARIAN_NUM_UNITS_CITY_CAPTURE_SPAWN', 0), -- The number of units spawned when a city is captured. In VP when a Barbarian Horde/Rebellion quest is failed, one unit (which captures the city) is created first, then this number is added.
	('BARBARIAN_NUM_UNITS_CITY_CAPTURE_SPAWN_CHILL', 0), -- Change if Chill Barbarians is enabled.
	('BARBARIAN_NUM_UNITS_CITY_CAPTURE_SPAWN_RAGING', 0), -- Change if Raging Barbarians is enabled.
	('BARBARIAN_NUM_UNITS_CITY_CAPTURE_SPAWN_PER_ERA', 0), -- Extra units added per era. Number of extra units = this value * (era #) / 100, rounded down.
-- Encampment Spawn
	('BARBARIAN_NUM_UNITS_PER_ENCAMPMENT_SPAWN', 1), -- The number of units an encampment spawns AFTER the encampment is initially created.
	('BARBARIAN_NUM_UNITS_PER_ENCAMPMENT_SPAWN_CHILL', 0), -- Change if Chill Barbarians is enabled.
	('BARBARIAN_NUM_UNITS_PER_ENCAMPMENT_SPAWN_RAGING', 0), -- Change if Raging Barbarians is enabled.
	('BARBARIAN_NUM_UNITS_PER_ENCAMPMENT_SPAWN_PER_ERA', 0), -- Extra units added per era. Number of extra units = this value * (era #) / 100, rounded down.
-- City Spawn
	('BARBARIAN_NUM_UNITS_PER_CITY_SPAWN', 1), -- The number of units a city spawns.
	('BARBARIAN_NUM_UNITS_PER_CITY_SPAWN_CHILL', 0), -- Change if Chill Barbarians is enabled.
	('BARBARIAN_NUM_UNITS_PER_CITY_SPAWN_RAGING', 0), -- Change if Raging Barbarians is enabled.
	('BARBARIAN_NUM_UNITS_PER_CITY_SPAWN_PER_ERA', 0), -- Extra units added per era. Number of extra units = this value * (era #) / 100, rounded down.
	('MAX_BARBARIANS_FROM_CITY_NEARBY', 4), -- Max. # of Barbarians within MAX_BARBARIANS_FROM_CITY_NEARBY_RANGE tiles of the city.
	('MAX_BARBARIANS_FROM_CITY_NEARBY_RANGE', 4), -- Range for MAX_BARBARIANS_FROM_CITY_NEARBY.
-- Trade Route Plunder
	('BARBARIAN_NUM_UNITS_PLUNDER_TRADE_ROUTE_SPAWN', 1), -- # of units the Barbarians spawn when they plunder a Trade Route.
	('BARBARIAN_NUM_UNITS_PLUNDER_TRADE_ROUTE_SPAWN_CHILL', 0), -- Change if Chill Barbarians is enabled.
	('BARBARIAN_NUM_UNITS_PLUNDER_TRADE_ROUTE_SPAWN_RAGING', 0), -- Change if Raging Barbarians is enabled.
	('BARBARIAN_NUM_UNITS_PLUNDER_TRADE_ROUTE_SPAWN_PER_ERA', 0), -- Extra units added per era. Number of extra units = this value * (era #) / 100, rounded down.

-- Unit Spawn Selection
	('BARBARIAN_UNIT_SPAWN_NUM_CANDIDATES', 5), -- randomly choose from the top X candidates
	('BARBARIAN_UNIT_SPAWN_NO_RESOURCE_MULTIPLIER', 150), -- 50% extra score to units without resource requirements
	('BARBARIAN_UNIT_SPAWN_UU_MULTIPLIER', 150), -- 50% extra score to Unique Units, if permitted
	('BARBARIAN_UNIT_SPAWN_PREFERRED_TYPE', 200), -- 100% extra score for the specific type of unit (UNIT_AI) the Barbs are looking for

-- Horde Quest
	('MINOR_QUEST_REBELLION_BARB_SPAWN_INTERVAL', 4), -- Spawn barbs every X turns, including the initial turn. No Barbs will be spawned on the final turn.
	('MINOR_QUEST_REBELLION_BARBS_PER_CS_UNIT', 60), -- # of Barbs per CS military unit. 100 = 1.
	('MINOR_QUEST_REBELLION_BARBS_PER_ERA_BASE', 0), -- # of Barbs per era past Ancient. 100 = 1.
	('MINOR_QUEST_REBELLION_BARBS_PER_ERA_RAND', 200), -- Maximum random extra Barbs per era past Ancient. 100 = 1.
	('MINOR_QUEST_REBELLION_BARBS_MIN', 2), -- Minimum # of Barbs

---------------------------------------
-- Warmonger penalty
---------------------------------------
	('WARMONGER_THREAT_PER_TURN_DECAY_INCREASED', 200),
	('WARMONGER_THREAT_PER_TURN_DECAY_DECREASED', 50),
	('WARMONGER_THREAT_ATTACKED_WEIGHT_WORLD_WAR', 50),
	('WARMONGER_THREAT_ATTACKED_WEIGHT_WORLD_PEACE', 200),
	('WARMONGER_THREAT_ATTACKED_SANCTIONED_PLAYER', 50),
	('WARMONGER_THREAT_PER_TURN_DECAY', -2),

-- Multiplicative modifiers which increase or decrease warmonger penalty per turn decay rate
	('WARMONGER_THREAT_STRENGTH_DECAY_IMMENSE', 50),
	('WARMONGER_THREAT_STRENGTH_DECAY_POWERFUL', 75),
	('WARMONGER_THREAT_STRENGTH_DECAY_STRONG', 100),
	('WARMONGER_THREAT_STRENGTH_DECAY_AVERAGE', 150),
	('WARMONGER_THREAT_STRENGTH_DECAY_POOR', 200),
	('WARMONGER_THREAT_STRENGTH_DECAY_WEAK', 250),
	('WARMONGER_THREAT_STRENGTH_DECAY_PATHETIC', 300),

-- Weight of warmonger triggers
	('WARMONGER_THREAT_MINOR_ATTACKED_WEIGHT', 5),
	('WARMONGER_THREAT_MAJOR_ATTACKED_WEIGHT', 10),
	('WARMONGER_THREAT_USED_NUKE_WEIGHT', 20),

	('WARMONGER_THREAT_CITY_VALUE_MULTIPLIER', 100), -- % multiplier
	('WARMONGER_THREAT_CAPITAL_CITY_PERCENT', 150), -- how much more the capital is worth (multiplicative)

-- Multiplicative modifier for when the bystander is on the same team as the defender, has a coop war with the defender against the attacker, or has a Defensive Pact with the defender
	('WARMONGER_THREAT_SHARED_FATE_PERCENT', 200),

-- Multiplicative modifier to the bonus for liberating a city owned by this player's team (added on top of SHARED_FATE_PERCENT)
	('WARMONGER_THREAT_LIBERATED_TEAM_BONUS_PERCENT', 200),

-- Multiplicative modifier for when the bystander is in a coop war with the attacker against the defender (huge reduction!)
	('WARMONGER_THREAT_COOP_WAR_PERCENT', 10),

-- Additive modifiers which increase or decrease warmonger penalty based on how strong the attacker and defender are, compared to the bystander
-- Not applied if SHARED_FATE_PERCENT is applicable; values are inverted when liberating a city
	('WARMONGER_THREAT_ATTACKER_STRENGTH_IMMENSE', 100),
	('WARMONGER_THREAT_ATTACKER_STRENGTH_POWERFUL', 75),
	('WARMONGER_THREAT_ATTACKER_STRENGTH_STRONG', 50),
	('WARMONGER_THREAT_ATTACKER_STRENGTH_AVERAGE', 33),
	('WARMONGER_THREAT_ATTACKER_STRENGTH_POOR', 0),
	('WARMONGER_THREAT_ATTACKER_STRENGTH_WEAK', -25),
	('WARMONGER_THREAT_ATTACKER_STRENGTH_PATHETIC', -50),
	('WARMONGER_THREAT_DEFENDER_STRENGTH_IMMENSE', -75),
	('WARMONGER_THREAT_DEFENDER_STRENGTH_POWERFUL', -50),
	('WARMONGER_THREAT_DEFENDER_STRENGTH_STRONG', -25),
	('WARMONGER_THREAT_DEFENDER_STRENGTH_AVERAGE', 0),

-- Additive modifiers for warmonger penalty based on various other conditions
	('WARMONGER_THREAT_MODIFIER_LARGE', 75),
	('WARMONGER_THREAT_MODIFIER_MEDIUM', 50),
	('WARMONGER_THREAT_MODIFIER_SMALL', 25),
	('WARMONGER_THREAT_MODIFIER_NEGATIVE_SMALL', -25),
	('WARMONGER_THREAT_MODIFIER_NEGATIVE_MEDIUM', -50),

-- Thresholds for warmonger threat levels (must have this much opinion penalty)
	('WARMONGER_THREAT_MINOR_THRESHOLD', 20),
	('WARMONGER_THREAT_MAJOR_THRESHOLD', 80),
	('WARMONGER_THREAT_SEVERE_THRESHOLD', 140),
	('WARMONGER_THREAT_CRITICAL_THRESHOLD', 200),
	('WARMONGER_THREAT_SEVERE_PERCENT_THRESHOLD', 25), -- If you have conquered (killed, vassalized or captured capital) this % of major civs, threat is set to severe regardless of score. CS counts as half a major.
	('WARMONGER_THREAT_CRITICAL_PERCENT_THRESHOLD', 33), -- If you have conquered (killed, vassalized or captured capital) this % of major civs, threat is set to critical regardless of score. CS counts as half a major.

---------------------------------------
-- War progress
-- Used as an AI sanity check to prevent wars of excessive attrition in the opponent's favor.
---------------------------------------(
	('WAR_PROGRESS_INITIAL_VALUE', 100),
	('WAR_PROGRESS_DECAY_VS_STRONGER', -5),
	('WAR_PROGRESS_DECAY_VS_EQUAL', -4),
	('WAR_PROGRESS_DECAY_VS_WEAKER', -3),
	('WAR_PROGRESS_CAPTURED_WORKER', 10),
	('WAR_PROGRESS_CAPTURED_SETTLER', 20),
	('WAR_PROGRESS_PLUNDERED_TRADE_ROUTE', 10),
	('WAR_PROGRESS_PILLAGED_IMPROVEMENT', 10),
	('WAR_PROGRESS_STOLE_TILE', 20),
	('WAR_PROGRESS_HIGH_VALUE_PILLAGE_MULTIPLIER', 200),
	('WAR_PROGRESS_KILLED_UNIT', 20),
	('WAR_PROGRESS_CAPTURED_CITY', 100),
	('WAR_PROGRESS_LOST_WORKER', -5),
	('WAR_PROGRESS_LOST_SETTLER', -10),
	('WAR_PROGRESS_LOST_TRADE_ROUTE', -5),
	('WAR_PROGRESS_LOST_IMPROVEMENT', -5),
	('WAR_PROGRESS_LOST_TILE', -10),
	('WAR_PROGRESS_LOST_UNIT', -10),
	('WAR_PROGRESS_LOST_CITY', -50),
	('WAR_PROGRESS_PER_STRATEGIC_DEFICIT', -5),
	('WAR_PROGRESS_PER_UNHAPPY', -4),
	('WAR_PROGRESS_CAPITAL_MULTIPLIER', 200),
	('WAR_PROGRESS_HOLY_CITY_MULTIPLIER', 150),

---------------------------------------
-- Diplomacy AI
---------------------------------------

-- War Damage values
	('WAR_DAMAGE_LEVEL_CITY_WEIGHT', 175),
	('WAR_DAMAGE_LEVEL_INVOLVED_CITY_POP_MULTIPLIER', 150),
	('WAR_DAMAGE_LEVEL_WORLD_WONDER_MULTIPLIER', 200),
	('PILLAGED_TILE_BASE_WAR_VALUE', 40),
	('STOLEN_TILE_BASE_WAR_VALUE', 80),

-- War Damage thresholds (used in the UI only)
	('WAR_DAMAGE_LEVEL_THRESHOLD_MINOR', 15),
	('WAR_DAMAGE_LEVEL_THRESHOLD_MAJOR', 30),
	('WAR_DAMAGE_LEVEL_THRESHOLD_SERIOUS', 50),
	('WAR_DAMAGE_LEVEL_THRESHOLD_CRIPPLED', 70),

-- Aggressive postures
	('EXPANSION_BICKER_TIMEOUT', 30),
	('EXPANSION_BICKER_RANGE_HIGH', 7),
	('EXPANSION_BICKER_RANGE_MEDIUM', 6),
	('EXPANSION_BICKER_RANGE_LOW', 5),

	('PLOT_BUYING_POSTURE_INCREDIBLE_THRESHOLD', 12),
	('PLOT_BUYING_POSTURE_HIGH_THRESHOLD', 9),
	('PLOT_BUYING_POSTURE_MEDIUM_THRESHOLD', 5),
	('PLOT_BUYING_POSTURE_LOW_THRESHOLD', 3),

	('MILITARY_AGGRESSIVE_POSTURE_THRESHOLD_INCREDIBLE', 12),
	('MILITARY_AGGRESSIVE_POSTURE_THRESHOLD_HIGH', 8),
	('MILITARY_AGGRESSIVE_POSTURE_THRESHOLD_MEDIUM', 6),
	('MILITARY_AGGRESSIVE_POSTURE_THRESHOLD_LOW', 2),

-- Dispute levels
	('LAND_DISPUTE_FIERCE_THRESHOLD', 8),
	('LAND_DISPUTE_STRONG_THRESHOLD', 4),
	('LAND_DISPUTE_WEAK_THRESHOLD', 1),
	('LAND_DISPUTE_CRAMPED_MULTIPLIER', 50),

	('WONDER_DISPUTE_FIERCE_THRESHOLD', 24),
	('WONDER_DISPUTE_STRONG_THRESHOLD', 12),
	('WONDER_DISPUTE_WEAK_THRESHOLD', 1),

	('MINOR_CIV_DISPUTE_FIERCE_THRESHOLD', 1400),
	('MINOR_CIV_DISPUTE_STRONG_THRESHOLD', 1000),
	('MINOR_CIV_DISPUTE_WEAK_THRESHOLD', 700),

	('VICTORY_DISPUTE_GRAND_STRATEGY_MATCH_POSITIVE', 25),
	('VICTORY_DISPUTE_GRAND_STRATEGY_MATCH_LIKELY', 15),
	('VICTORY_DISPUTE_GRAND_STRATEGY_MATCH_UNSURE', 5),

	('VICTORY_BLOCK_FIERCE_THRESHOLD', 40),
	('VICTORY_BLOCK_STRONG_THRESHOLD', 30),
	('VICTORY_BLOCK_WEAK_THRESHOLD', 20),
	('VICTORY_BLOCK_GRAND_STRATEGY_DIFFERENCE_POSITIVE', 20),
	('VICTORY_BLOCK_GRAND_STRATEGY_DIFFERENCE_LIKELY', 15),
	('VICTORY_BLOCK_GRAND_STRATEGY_DIFFERENCE_UNSURE', 5),

	('TECH_BLOCK_FIERCE_THRESHOLD', 30),
	('TECH_BLOCK_STRONG_THRESHOLD', 20),
	('TECH_BLOCK_WEAK_THRESHOLD', 10),

	('POLICY_BLOCK_FIERCE_THRESHOLD', 24),
	('POLICY_BLOCK_STRONG_THRESHOLD', 16),
	('POLICY_BLOCK_WEAK_THRESHOLD', 8),

-- Skill rating evaluation
	('MILITARY_RATING_STARTING_VALUE', 1000),
	('MILITARY_RATING_PER_ADVANCED_START_ERA', 1000),
	('MILITARY_RATING_MAXIMUM_BONUS', 100),
	('MILITARY_RATING_MAXIMUM_PENALTY', -50),
	('MILITARY_RATING_HUMAN_BUFFER_VALUE_PERCENT', 80),

-- Comparative strength evaluation
	('ECONOMIC_STRENGTH_IMMENSE_THRESHOLD', 300),
	('ECONOMIC_STRENGTH_POWERFUL_THRESHOLD', 200),
	('ECONOMIC_STRENGTH_STRONG_THRESHOLD', 126),
	('ECONOMIC_STRENGTH_AVERAGE_THRESHOLD', 75),
	('ECONOMIC_STRENGTH_POOR_THRESHOLD', 50),
	('ECONOMIC_STRENGTH_WEAK_THRESHOLD', 33),

	('MILITARY_STRENGTH_REDUCTION_PER_BOLDNESS', -3),
	('MILITARY_STRENGTH_IMMENSE_THRESHOLD', 300),
	('MILITARY_STRENGTH_POWERFUL_THRESHOLD', 200),
	('MILITARY_STRENGTH_STRONG_THRESHOLD', 126),
	('MILITARY_STRENGTH_AVERAGE_THRESHOLD', 75),
	('MILITARY_STRENGTH_POOR_THRESHOLD', 50),
	('MILITARY_STRENGTH_WEAK_THRESHOLD', 33),

	('MILITARY_STRENGTH_MINOR_BACKUP_IMMENSE', 50),
	('MILITARY_STRENGTH_MINOR_BACKUP_POWERFUL', 35),
	('MILITARY_STRENGTH_MINOR_BACKUP_STRONG', 25),
	('MILITARY_STRENGTH_MINOR_BACKUP_AVERAGE', 15),
	('MILITARY_STRENGTH_MINOR_BACKUP_POOR', 0),
	('MILITARY_STRENGTH_MINOR_BACKUP_WEAK', 0),
	('MILITARY_STRENGTH_MINOR_BACKUP_PATHETIC', 0),
	('MILITARY_STRENGTH_MINOR_BACKUP_NEIGHBORS', 100),

	('MILITARY_STRENGTH_MAJOR_BACKUP_IMMENSE', 50),
	('MILITARY_STRENGTH_MAJOR_BACKUP_POWERFUL', 35),
	('MILITARY_STRENGTH_MAJOR_BACKUP_STRONG', 25),
	('MILITARY_STRENGTH_MAJOR_BACKUP_AVERAGE', 15),
	('MILITARY_STRENGTH_MAJOR_BACKUP_POOR', 10),
	('MILITARY_STRENGTH_MAJOR_BACKUP_WEAK', 5),
	('MILITARY_STRENGTH_MAJOR_BACKUP_PATHETIC', 0),
	('MILITARY_STRENGTH_MAJOR_BACKUP_NEIGHBORS', 200),
	('MILITARY_STRENGTH_MAJOR_BACKUP_CLOSE', 100),
	('MILITARY_STRENGTH_MAJOR_BACKUP_FAR', 50),
	('MILITARY_STRENGTH_MAJOR_BACKUP_DISTANT', 0),

	('MILITARY_STRENGTH_BACKUP_ALREADY_WAR_EACH_PLAYER', 30),
	('MILITARY_STRENGTH_BACKUP_ALREADY_WAR_MINIMUM', 20),

	('TARGET_MINOR_BACKUP_IMMENSE', 50),
	('TARGET_MINOR_BACKUP_POWERFUL', 35),
	('TARGET_MINOR_BACKUP_STRONG', 25),
	('TARGET_MINOR_BACKUP_AVERAGE', 15),
	('TARGET_MINOR_BACKUP_POOR', 0),
	('TARGET_MINOR_BACKUP_WEAK', 0),
	('TARGET_MINOR_BACKUP_PATHETIC', 0),
	('TARGET_MINOR_BACKUP_NEIGHBORS', 100),

	('TARGET_MAJOR_BACKUP_IMMENSE', 50),
	('TARGET_MAJOR_BACKUP_POWERFUL', 35),
	('TARGET_MAJOR_BACKUP_STRONG', 25),
	('TARGET_MAJOR_BACKUP_AVERAGE', 15),
	('TARGET_MAJOR_BACKUP_POOR', 10),
	('TARGET_MAJOR_BACKUP_WEAK', 5),
	('TARGET_MAJOR_BACKUP_PATHETIC', 0),
	('TARGET_MAJOR_BACKUP_NEIGHBORS', 200),
	('TARGET_MAJOR_BACKUP_CLOSE', 100),
	('TARGET_MAJOR_BACKUP_FAR', 50),
	('TARGET_MAJOR_BACKUP_DISTANT', 0),

	('TARGET_ALREADY_WAR_MINIMUM', 20),
	('TARGET_ECONOMIC_MOD', 100),
	('TARGET_CITY_MOD', 33),

	('TARGET_VALUE_RATIO_MULTIPLIER', 100),
	('TARGET_VALUE_REDUCTION_PER_BOLDNESS', -3),
	('TARGET_NEIGHBORS', 3),
	('TARGET_NEIGHBORS_DIVISOR', 4),
	('TARGET_CLOSE', 1),
	('TARGET_CLOSE_DIVISOR', 1),
	('TARGET_FAR', 3),
	('TARGET_FAR_DIVISOR', 2),
	('TARGET_DISTANT', 2),
	('TARGET_DISTANT_DIVISOR', 1),

	('TARGET_IMPOSSIBLE_THRESHOLD', 300),
	('TARGET_BAD_THRESHOLD', 200),
	('TARGET_DIFFICULT_THRESHOLD', 126),
	('TARGET_AVERAGE_THRESHOLD', 75),
	('TARGET_FAVORABLE_THRESHOLD', 50),
	('TARGET_SOFT_THRESHOLD', 33),

-- Diplo agreements
	('COOP_WAR_DESIRE_THRESHOLD', 40), -- min. GetCoopWarDesireScore() value for the AI to agree

-- Peace desire
	('REQUEST_PEACE_TURN_THRESHOLD', 20),
	('REQUEST_PEACE_THRESHOLD_REDUCTION_PER_WAR', 2),
	('REQUEST_PEACE_LEEWAY_THRESHOLD', 17),
	('REQUEST_PEACE_LEEWAY_THRESHOLD_REDUCTION_PER_WAR', 3),

-- Peace values (caps at 100)
	('PEACE_WILLINGNESS_OFFER_THRESHOLD_UN_SURRENDER', 100),
	('PEACE_WILLINGNESS_OFFER_THRESHOLD_CAPITULATION', 90),
	('PEACE_WILLINGNESS_OFFER_THRESHOLD_CESSION', 80),
	('PEACE_WILLINGNESS_OFFER_THRESHOLD_SURRENDER', 70),
	('PEACE_WILLINGNESS_OFFER_THRESHOLD_SUBMISSION', 60),
	('PEACE_WILLINGNESS_OFFER_THRESHOLD_BACKDOWN', 40),
	('PEACE_WILLINGNESS_OFFER_THRESHOLD_SETTLEMENT', 30),
	('PEACE_WILLINGNESS_OFFER_THRESHOLD_ARMISTICE', 15),

	('PEACE_WILLINGNESS_ACCEPT_THRESHOLD_UN_SURRENDER', 100),
	('PEACE_WILLINGNESS_ACCEPT_THRESHOLD_CAPITULATION', 90),
	('PEACE_WILLINGNESS_ACCEPT_THRESHOLD_CESSION', 80),
	('PEACE_WILLINGNESS_ACCEPT_THRESHOLD_SURRENDER', 70),
	('PEACE_WILLINGNESS_ACCEPT_THRESHOLD_SUBMISSION', 60),
	('PEACE_WILLINGNESS_ACCEPT_THRESHOLD_BACKDOWN', 40),
	('PEACE_WILLINGNESS_ACCEPT_THRESHOLD_SETTLEMENT', 30),
	('PEACE_WILLINGNESS_ACCEPT_THRESHOLD_ARMISTICE', 15),

---------------------------------------
-- Mod options
---------------------------------------

-- Trade route related constants (TRADE_ROUTE_SCALING)
	('TRADE_ROUTE_BASE_TARGET_TURNS', 30),
	('TRADE_ROUTE_BASE_LAND_DISTANCE', 10),
	('TRADE_ROUTE_BASE_LAND_MODIFIER', 0),
	('TRADE_ROUTE_BASE_SEA_DISTANCE', 20),
	('TRADE_ROUTE_BASE_SEA_MODIFIER', 100),
	('TRADE_ROUTE_BASE_FOOD_VALUE', 300),
	('TRADE_ROUTE_BASE_PRODUCTION_VALUE', 300),
	('TRADE_ROUTE_SCIENCE_DIVISOR_TIMES100', 200),
	('TRADE_ROUTE_CULTURE_DIVISOR_TIMES100', 200),
	('TRADE_ROUTE_DIFFERENT_RESOURCE_VALUE', 50),
	('TRADE_ROUTE_RIVER_CITY_MODIFIER', 25),
	('TRADE_ROUTE_BASE_PLUNDER_GOLD', 100),
	('TRADE_ROUTE_PLUNDER_TURNS_COUNTER', 30),
	('TRADE_ROUTE_CS_ALLY_SCIENCE_DELTA', 1),
	('TRADE_ROUTE_CS_FRIEND_SCIENCE_DELTA', 0),
	('TRADE_ROUTE_CS_ALLY_CULTURE_DELTA', 1),
	('TRADE_ROUTE_CS_FRIEND_CULTURE_DELTA', 0),
	('TRADE_ROUTE_CS_ALLY_GOLD', 2),
	('TRADE_ROUTE_CS_FRIEND_GOLD', 1),

-- CITY_STATE_SCALE
	('FRIENDSHIP_THRESHOLD_MOD_MEDIEVAL', 6),
	('FRIENDSHIP_THRESHOLD_MOD_INDUSTRIAL', 10),
	('CITY_STATE_SCALE_PER_CITY_MOD', 0),

-- Freebies from City States on first contact (GLOBAL_CS_GIFTS)

-- These are the values for the first team to meet a neutral CS.
-- Multipliers for friendly and hostile city-states are below.
-- Irrational city-states roll to see if they are friendly, neutral or hostile towards the meeting player.
	('MINOR_CIV_FIRST_CONTACT_BONUS_FRIENDSHIP', 5),
	('MINOR_CIV_FIRST_CONTACT_BONUS_CULTURE', 5),
	('MINOR_CIV_FIRST_CONTACT_BONUS_FAITH', 5),
	('MINOR_CIV_FIRST_CONTACT_BONUS_GOLD', 25),
	-- Below are only given to the player who meets the CS instead of the whole team
	('MINOR_CIV_FIRST_CONTACT_BONUS_FOOD', 10),
	-- Chance to get a unit
	('MINOR_CIV_FIRST_CONTACT_BONUS_UNIT', 10),
	('MINOR_CIV_FIRST_CONTACT_XP_PER_ERA', 5),
	('MINOR_CIV_FIRST_CONTACT_XP_RANDOM', 5),

	-- Multiplier and Divisor for the player meeting the CS, we can only store ints so *2 is 2/1
	-- Only Influence uses these
	('MINOR_CIV_FIRST_CONTACT_PLAYER_MULTIPLIER', 2),
	('MINOR_CIV_FIRST_CONTACT_PLAYER_DIVISOR', 1),

	-- Multiplier and Divisor for the subsequent teams meeting the CS, we can only store ints so *0.5 is 1/2
	-- Only Influence uses the multiplier
	('MINOR_CIV_FIRST_CONTACT_SUBSEQUENT_TEAM_MULTIPLIER', 1),
	-- Only Influence, Culture and Faith use the divisor, others are set to 0 instead
	('MINOR_CIV_FIRST_CONTACT_SUBSEQUENT_TEAM_DIVISOR', 2),

	-- Multiplier and Divisor for friendly city states bonuses, we can only store ints so *1.5 is 3/2
	('MINOR_CIV_FIRST_CONTACT_FRIENDLY_BONUS_MULTIPLIER', 3),
	('MINOR_CIV_FIRST_CONTACT_FRIENDLY_BONUS_DIVISOR', 2),

	-- Multiplier and Divisor for friendly city states unit chance, we can only store ints so *2 is 2/1
	('MINOR_CIV_FIRST_CONTACT_FRIENDLY_UNIT_MULTIPLIER', 2),
	('MINOR_CIV_FIRST_CONTACT_FRIENDLY_UNIT_DIVISOR', 1),

	-- Multiplier and Divisor for hostile city states bonuses, we can only store ints so *0.5 is 1/2
	('MINOR_CIV_FIRST_CONTACT_HOSTILE_BONUS_MULTIPLIER', 1),
	('MINOR_CIV_FIRST_CONTACT_HOSTILE_BONUS_DIVISOR', 2),

	-- Multiplier and Divisor for hostile city states unit chance, we can only store ints so *0 is 0/1
	('MINOR_CIV_FIRST_CONTACT_HOSTILE_UNIT_MULTIPLIER', 0),
	('MINOR_CIV_FIRST_CONTACT_HOSTILE_UNIT_DIVISOR', 1),

-- BALANCE_CORE_NEW_GP_ATTRIBUTES
	('RELIGION_MIN_FAITH_SECOND_PROPHET', 600),

-- BALANCE_CORE_WONDER_COST_INCREASE
	('BALANCE_CORE_WORLD_WONDER_SAME_ERA_COST_MODIFIER', 25),
	('BALANCE_CORE_WORLD_WONDER_PREVIOUS_ERA_COST_MODIFIER', 15),
	('BALANCE_CORE_WORLD_WONDER_SECOND_PREVIOUS_ERA_COST_MODIFIER', 10),
	('BALANCE_CORE_WORLD_WONDER_EARLIER_ERA_COST_MODIFIER', 5); -- all previous eras

INSERT INTO PostDefines
	(Name, Key, "Table")
VALUES
	('ANCIENT_ERA', 'ERA_ANCIENT', 'Eras'),
	('CLASSICAL_ERA', 'ERA_CLASSICAL', 'Eras'),
	('MEDIEVAL_ERA', 'ERA_MEDIEVAL', 'Eras'),
	('RENAISSANCE_ERA', 'ERA_RENAISSANCE', 'Eras'),
	('INDUSTRIAL_ERA', 'ERA_INDUSTRIAL', 'Eras'),
	('MODERN_ERA', 'ERA_MODERN', 'Eras'),
	('ATOMIC_ERA', 'ERA_POSTMODERN', 'Eras'),
	('INFORMATION_ERA', 'ERA_FUTURE', 'Eras'),
	('TOURISM_START_TECH', 'TECH_AGRICULTURE', 'Technologies'),
	('TOURISM_START_ERA', 'ERA_ANCIENT', 'Eras'),
	('RELIGION_LAST_FOUND_ERA', 'ERA_RENAISSANCE', 'Eras'),
	('RELIGION_GP_FAITH_PURCHASE_ERA', 'ERA_INDUSTRIAL', 'Eras'),
	('IDEOLOGY_START_ERA', 'ERA_INDUSTRIAL', 'Eras'),
	('IDEOLOGY_PREREQ_ERA', 'ERA_INDUSTRIAL', 'Eras'),
	('MARCH_PROMOTION', 'PROMOTION_MARCH', 'UnitPromotions'),
	('MORALE_PROMOTION', 'PROMOTION_MORALE', 'UnitPromotions'),
	('PROMOTION_DEEPWATER_EMBARKATION', 'PROMOTION_DEEPWATER_EMBARKATION', 'UnitPromotions'),
	('PROMOTION_DEFENSIVE_DEEPWATER_EMBARKATION', 'PROMOTION_DEFENSIVE_DEEPWATER_EMBARKATION', 'UnitPromotions'),
	('PROMOTION_FLAGSHIP', 'PROMOTION_FLAGSHIP', 'UnitPromotions'),
	('NUKE_TRIGGER_PROJECT', 'PROJECT_MANHATTAN_PROJECT', 'Projects');
