on:
  # change to release
  push:

jobs:

  release:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: ./autoinstaller.sh
      - shell: cmd
        run: iscc
