-- Settler stuff

INSERT INTO Defines (
Name, Value)
SELECT 'BALANCE_EMPIRE_BORDERLAND_STRATEGIC_VALUE', '25'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

INSERT INTO Defines (
Name, Value)
SELECT 'BALANCE_COAST_STRATEGIC_VALUE', '3'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

INSERT INTO Defines (
Name, Value)
SELECT 'BALANCE_FRESH_WATER_STRATEGIC_VALUE', '2'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

INSERT INTO Defines (
Name, Value)
SELECT 'BALANCE_CHOKEPOINT_STRATEGIC_VALUE', '50'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

INSERT INTO Defines (
Name, Value)
SELECT 'BALANCE_BAD_TILES_STRATEGIC_VALUE', '-10'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

-- Combat Stuff

INSERT INTO Defines (
Name, Value)
SELECT 'BALANCE_BASIC_ATTACK_ARMY_SIZE', '8'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

INSERT INTO Defines (
Name, Value)
SELECT 'BALANCE_NAVY_START_SIZE', '2'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

INSERT INTO Defines (
Name, Value)
SELECT 'BALANCE_EMBARK_DEFENSE_DIVISOR', '3'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

-- Barbarian Stuff

UPDATE Defines
SET Value = '50'
WHERE Name = 'AI_TACTICAL_BARBARIAN_PRIORITY_CAPTURE_CITY' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE Defines
SET Value = '60'
WHERE Name = 'AI_TACTICAL_BARBARIAN_PRIORITY_CAMP_DEFENSE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

-- Spy Stuff

INSERT INTO Defines (
Name, Value)
SELECT 'BALANCE_SPY_SABOTAGE_RATE', '20'
WHERE EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );
