DELETE FROM HandicapInfo_Goodies
WHERE GoodyType = 'GOODY_REVEAL_NEARBY_BARBS' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE GoodyHuts
SET Experience = '10'
WHERE Type = 'GOODY_EXPERIENCE' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE GoodyHuts
SET MapOffset = '10'
WHERE Type = 'GOODY_MAP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );

UPDATE GoodyHuts
SET MapProb = '110'
WHERE Type = 'GOODY_MAP' AND EXISTS (SELECT * FROM COMMUNITY WHERE Type='COMMUNITY_CORE_BALANCE' AND Value= 1 );